### ISSUE TITLE
Submit package to CRAN

### ISSUE THREAD

**Issue by karthik** [ropensci/plotly#1]
It would be great to get this package to CRAN at some point soon.

- [x] Deal with the license issue. MIT + License file is now required by the CRAN maintainers.
- [x] Write unit tests with testthat
- [x] Write documentation with roxygen2
- [x] Change URL and bugreports URL in the `DESCRIPTION` file.
- [x] Add Travis integration and shield to README
- [ ] Write a vignette
- [ ] Write a blogpost for rOpenSci

Minor nuisances:
- [x] Remove .Rhistory files from repo.

**Comment by TrigonaMinima** [comment]
Is anyone doing this? I'd like to write the vignettes.

**Comment by cpsievert** [comment]
@TrigonaMinima we'll be submitting to CRAN this week (see #296). Feel free to start a pull request with additions/edits to `vignettes/`
