### ISSUE TITLE
4.6.0 Mac check errors on CRAN

### ISSUE THREAD

**Issue by vnijs** [ropensci/plotly#1007]
FYI 4.6.0 binaries are not available on CRAN due to check errors. See links below

https://www.r-project.org/nosvn/R.check/r-release-osx-x86_64/plotly-00check.html
https://www.r-project.org/nosvn/R.check/r-oldrel-osx-x86_64/plotly-00check.html

**Comment by cpsievert** [comment]
Thanks for letting me know! I'll likely be sending a patch for this and other problems tonight

**Comment by vnijs** [comment]
Thanks @cpsievert!

**Comment by vnijs** [comment]
bump ...

**Comment by cpsievert** [comment]
submitting today

**Comment by vnijs** [comment]
Thanks @cpsievert !
