### ISSUE TITLE
An R markdown presentation does not work when`ggplotly` in for-loop

### ISSUE THREAD

**Issue by egpivo** [ropensci/plotly#1017]
Hi there,

The problem is that I want to use a for loop to plot a bunch of interactive ggplotly graphs, which are put into corresponding slides one by one. I've check the issues #273, #425 and #570, but I still can't solve it. 

The fail part of script in my`.Rmd` file is:
```
---
title: "Automated slides"
output: ioslides_presentation
---

```{r, echo = F, message = FALSE,  results='asis'}
### failed
library(plotly)
plt <- htmltools::tagList()
for(j in 1:2) {
  cat(paste("\n\n## Feature: ",j),"\n\n" ) 
  df <- data.frame(x =  1:10, y = (1:10)^2)
  p <- ggplot(df, aes(x = x, y = y)) + geom_line()
  plt[[j]] <-  ggplotly(p)
}

plt
```

This is the expected one without a for loop:
```{r, echo = F, message = FALSE, results='asis'}
### expected
plt <- htmltools::tagList()
for(j in 1:2) {
  p <- ggplot(df, aes(x = x, y = y)) + geom_line()
  plt[[j]] <-  ggplotly(p)
}
cat(paste("\n\n## Feature: ",1),"\n\n" ) 
plt[[1]]
cat(paste("\n\n## Feature: ",2),"\n\n" ) 
plt[[2]]
```

Any ideas to solve the failed part? Thanks.

**Comment by cpsievert** [comment]
Remove the `results='asis'` bit?

**Comment by egpivo** [comment]
It doesn't work. Any other suggestions? Thanks.

**Comment by cpsievert** [comment]
This is what I get. Perhaps your plots are running off the slide?
<img width="639" alt="screen shot 2017-05-20 at 11 20 37 am" src="https://cloud.githubusercontent.com/assets/1365941/26277493/677eef92-3d4e-11e7-9c8f-33de2e80c415.png">

**Comment by egpivo** [comment]
I think you are perhaps misunderstood my example. I tried to generate every single plot into a singe slide, not all plots in a one slide. In this sense, is there any possible way to solve it? Thanks!
