### ISSUE TITLE
Hover text from ggplot differs after publishing

### ISSUE THREAD

**Issue by asayat** [ropensci/plotly#1018]
In the last develop version the hover text of ggplot differs in plots after publishing on server.

Example (create a plot grouped by car class, filled by manufacturer, hover text shows each car's year, model and class):
```
library(ggplot2)
library(plotly)
mpg$order<-seq(1,nrow(mpg))
mpg$Size<-1
ggpl<-mpg%>%
  group_by(class)%>%
  arrange(class, desc(order))%>%
  mutate(cum_size = cumsum(Size) - Size / 2)%>%
  ggplot(aes(x=class, y=cum_size, fill = manufacturer))+
  geom_tile(color="white", size = 1, aes(height = Size))

pp<-ggplotly(ggpl)
pp<-plotly_build(ggpl)
mpg<-mpg[with(mpg, order(manufacturer,class,order)), ]
#Update hover text in each $data list element
pp$x$data[1:nrow(mpg)]<-
  Map(modifyList, pp$x$data[1:nrow(mpg)],
      lapply(paste("Class:",mpg$class,"<br> Year:",mpg$year,
                   "<br> Model:",mpg$model,  sep=" "), 
             function(x) list(text=x)))
pp
```
Runs on RStudio perfectly, but hover text gets wrong in the published version:
https://plot.ly/~azharka/48

Same code published in version 4.5.6 works perfectly:
https://plot.ly/~azharka/51

**Comment by cpsievert** [comment]
This is probably due to the platform using an out-dated version of plotly.js.

It will eventually be fixed, but if you want/need more help from the "internal" team, a support plan is an option -- https://support.plot.ly/plans
