### ISSUE TITLE
plotly: Can’t get polar scatter working in a subplot

### ISSUE THREAD

**Issue by mike-wise** [ropensci/plotly#1020]
Also described in this StackOverflow post with a nice compact MCVE: [link](http://stackoverflow.com/questions/44043317/plotly-can-t-get-polar-scatter-working-in-a-subplot) 

Sorry for two of these in one day, but today was my "plotly" day :). Seems like Plotly should have picked up on the `r` and `t` keys in the trace to figure out it was a polar plot, right?

**Comment by cpsievert** [comment]
Issues for the python package should be posted here https://github.com/plotly/plotly.py
