### ISSUE TITLE
Marker size in 3dscatter plot relative to graph coordinates?

### ISSUE THREAD

**Issue by ajpil** [ropensci/plotly#1025]
I'd like for the markers to grow/shrink as the user zooms in/out on the plot, rather than remaining constant in size relative to the screen. 

In the example below, the size is defined by df$r but it does not change with zoom.

p %>%   add_trace(data = df, x = ~x, y =  ~y, z = ~z
                  , type = 'scatter3d', mode = 'markers', frame = ~frame
                  , marker = list(color = ~col
                                  , size = ~r
                                  ))

Is this possible?

**Comment by cpsievert** [comment]
Thanks!

As per our [contributing guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), github issues are reserved for bug reports and feature requests only. So I'll have to close your ticket.

Please use our community forums at [community.plot.ly](http://community.plot.ly/) for posts of the likes.
