### ISSUE TITLE
Disable zoom in 3d plots (in R)

### ISSUE THREAD

**Issue by ajpil** [ropensci/plotly#1027]
Is it possible to prevent the user from zooming in 3d plots?
I know this can be done in 2d plots using the 'fixedrange' attribute.

**Comment by cpsievert** [comment]
Thanks!

As per our [contributing guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), github issues are reserved for bug reports and feature requests only. So I'll have to close your ticket.

Please use our community forums at [community.plot.ly](http://community.plot.ly/) for posts of the likes.
