### ISSUE TITLE
Treemaps in Plotly

### ISSUE THREAD

**Issue by phidesigner** [ropensci/plotly#1031]
Would be nice to see Plotly support for Treemaps e.g. Treemapify.

Warning messages:

2: In geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
  **geom_GeomTreemap() has yet to be implemented in plotly.**

**Comment by cpsievert** [comment]
Added to #566, but we may be able to treemaps via ggraph plugins cc @thomasp85

**Comment by thomasp85** [comment]
Indeed
