### ISSUE TITLE
'ggplotly' applied to an object of class "NULL"

### ISSUE THREAD

**Issue by devharsh** [ropensci/plotly#1032]
Plotly version: 4.5.2

Error:
Warning: Error in UseMethod: no applicable method for 'ggplotly' applied to an object of class "NULL"
Stack trace (innermost first):
    79: ggplotly
    78: func
    77: origRenderFunc
    76: output$cpumem
     1: runApp

Code:
```r
output$cpumem <- renderPlotly({
    tryCatch({
      input$doAnalysis
      plot_ly(cpudata,
        x =  ~ Timestamp,
        y =  ~ CPU_Usage,
        name = "CPU",
        type = "scatter",
        mode = "lines"
      ) %>% add_trace(
        y = ~Total_Memory_Used,
        name = "Memory"
      ) %>% layout(
        title = "Time vs System Usage",
        xaxis = list(title = "Time"),
        yaxis = list(title = "Usage (%)"))
    },
    error = function(e)
    {
      info(e)
    },
    warning = function(w)
    {
      info(w)
    })
  })
```

**Comment by cpsievert** [comment]
The message is basically saying `renderPlotly()` doesn't know what to do with a value of `NULL`.

You could add an exception to print `plotly_empty()` or similar in that case

**Comment by devharsh** [comment]
i figured out the problem..

my last statement in renderplotly callback was show() and that's why it was generating NULL plots, i assigned plotly value to some variable 'x' and put it after show() and it worked...

sorry for the trouble..
