### ISSUE TITLE
plotlyjs upgrade in v4.7 breaks some plots on shiny-server rendered flex dashboard

### ISSUE THREAD

**Issue by msummersgill** [ropensci/plotly#1033]
*Note: this is unfortunately far from being a reproducible example or a clearly defined issue, but I'm posting what I've got on the off chance it can at least be a starting point towards a solution.*

I've got a flexdashboard report using shiny runtime hosted on a shiny-server instance that has several plotly graphs, and after updating to the current CRAN version of plotly, v4.7, some of the plots no longer displayed, with no R error messages or warnings. The *(redacted of proprietary information)* image below shows what the output looks like when the report is working properly, but after updating to v4.7, the second plot from the left (scatter plot) just appears as an empty panel.

![image](https://cloud.githubusercontent.com/assets/19575728/26599625/de5aed58-453e-11e7-974d-a004c78d65ba.png)

Checking in chrome developer tools there is an error message that I assume is related to the problem, looks like perhaps objects of class `Plotly` are undefined? I have next to no idea what I'm doing when it comes to javascript/html/web applications, but if I had to take a wild guess, it could either be due to an incompatibility between plotly-latest.min.js and shiny.min.js or possibly just the elimination of dependency references in inst/htmlwidgets/plotly.yaml? 

![image](https://cloud.githubusercontent.com/assets/19575728/26594903/2a3e2696-452f-11e7-82d2-bb16e4dbd1af.png)

Ordinarily I would update shiny-server, shiny, and all the other packages in use, but I'm a little short on time this week to go through the server reboot process and risk a more extensive troubleshooting session if other packages introduced unrelated breaking updates on other applications/reports.

Let me know if there's any other information it would be helpful for me to post from the developer tools or the r session or system info. 

I'm having a hard time getting this pared down to a reproducible example without extraneous information. The original dashboard pulls in a handful of pre-processed data sources and generates multiple tabs with multiple panels and plots that use click events and some other bells and whistles. After getting it cut down to a single scatter plot with the mtcars data set everything works fine...

## Functioning workaround:

I forked v4.7 and reverted back the plotlyjs related changes, [(msummersgill/plotlyjs_revert)](https://github.com/msummersgill/plotly/tree/plotlyjs_revert) and with that everything is working again. 

[Comparison between ropensci/master and msummersgill/plotlyjs_revert](https://github.com/ropensci/plotly/compare/master...msummersgill:plotlyjs_revert)

#### Some other anecdotal information:

- When rendering in RStudio server (hosted on the same server running shiny-server), all graphs properly rendered, but it looked like the dependencies were being handled differently due to the different runtime environment.
- Some graphs worked, but others didn't?
- This seems to be specific to plotly graphs rendered in a shiny run time environment within shiny-server

**Comment by cpsievert** [comment]
I have a feeling the problem was introduced in https://github.com/ropensci/plotly/commit/183006c319e37d4eed6b27abc1bdc84e5d5c990e.

Can you revert just that commit and see if it helps?

**Comment by cpsievert** [comment]
Ahh, yea, ok, I think it was just the remove of the yaml file

**Comment by msummersgill** [comment]
Reverting only changes in commit 183006c still results in a similar error.

[Partial revert branch](https://github.com/msummersgill/plotly/tree/partial_revert)

![image](https://cloud.githubusercontent.com/assets/19575728/26602847/6f3a269e-454a-11e7-81fa-ee48cfed1159.png)

**Comment by cpsievert** [comment]
ok, interesting, do you mind trying to *just* changing the plotly.js version to 1.27.0 (and not adding the yaml file as you have done in the plotlyjs_revert branch)?

**Comment by msummersgill** [comment]
Empty yaml file,  but using plotly.js v1.27.0 (see [no_yaml_1.27.0](https://github.com/msummersgill/plotly/tree/no_yaml_1.27.0)) yields similar results.

![image](https://cloud.githubusercontent.com/assets/19575728/26603837/daeb8dc6-454d-11e7-9b52-18512527587f.png)

**Comment by cpsievert** [comment]
ok, does `devtools::install_github("ropensci/plotly#1035")` work? If it does, it definitely has something to do with the removal of the yaml file

**Comment by msummersgill** [comment]
**Success: `devtools::install_github("ropensci/plotly#1035")` does work, and uses plotlyjs v1.27.1**

### ropensci/plotly#1035 results
![image](https://cloud.githubusercontent.com/assets/19575728/26604525/43b8e78e-4550-11e7-8511-1b31fee50ec6.png)

**Comment by iron0012** [comment]
Came to report the same problem, albeit in a "normal" Shiny fluidPage layout (not flex dashboard). Thanks for your quick response, Carson.

**Comment by iron0012** [comment]
Unfortunately, although the symptoms I'm experiencing appear to be identical to msummergill's, devtools::install_github("ropensci/plotly#1035") did not work for me.

**Comment by cpsievert** [comment]
@msummersgill could you please re-install via `devtools::install_github("ropensci/plotly#1035")` and let me know if it works? Thanks!

**Comment by msummersgill** [comment]
`devtools::install_github("ropensci/plotly#1035")` appears to be rendering the plots properly. However, I am now getting an error message that may or may not be related to any of these changes-- I tried reinstalling the fork I'd made that reverted back to plotlyjs v1.27.0 and the error was still present.

The shiny application in question is written and maintained by one of my coworkers, so I need to sit down with them and review all the server logs/find the underlying issue on Monday. After that, I'll let you know if the current error message is related to plotly or not.

*(Moral of the story: for production shiny applications, use packrat and set up a single purpose user account to run each one)*

**Comment by cpsievert** [comment]
I think this is fixed now. Feel free to open another issue if you are running into other problems.
