### ISSUE TITLE
plotlyOutput width argument no longer works in 4.7.0

### ISSUE THREAD

**Issue by vnijs** [ropensci/plotly#1036]
Same install with 4.6.0 the width arguments works fine. After upgrading to 4.7.0 the default width is very narrow and changing the width setting has no effect in the browser. After reinstalling 4.6.0 the width argument works fine again. Any ideas?

```r
library(shiny)
library(plotly)

## Define UI for application 
ui <- fluidPage(
  titlePanel("My Shiny app with plotly"),
  sidebarLayout(
    sidebarPanel(
      sliderInput("my_slider", label = "Number of data points", 
                  min = 100, max = 500, value = 200)
    ),
    mainPanel(
      plotlyOutput("show_scatter", width = "100%")
    )
  )
)

# Define server logic 
server <- function(input, output) {
  output$show_scatter <- renderPlotly({
    y <- rnorm(input$my_slider)
    x <- y  + rnorm(input$my_slider)
    df <- data.frame(x = x, y = y)
    p <- ggplot(df, aes(x = x, y = y)) + 
      geom_point()
    ggplotly(p)
  })
}

# Run the application with plotly
shinyApp(ui = ui, server = server)
```

**Comment by vnijs** [comment]
Adding screenshots for 4.6 and 4.7. 

In 4.6.0:

<img width="720" alt="4 6" src="https://cloud.githubusercontent.com/assets/2998956/26611852/e6a28666-4565-11e7-9ed6-800b8d4c37ac.png">

In 4.7.0:

<img width="720" alt="4 7" src="https://cloud.githubusercontent.com/assets/2998956/26611864/f6c561d0-4565-11e7-9ace-27655903c89a.png">

**Comment by vnijs** [comment]
Just noticed something interesting ... as I change the size of the viewer panel in Rstudio, the size of the plot changes in the browser (after refresh).

**Comment by cpsievert** [comment]
I'm not sure `height`/`width` has ever really worked the way you'd expect it to in all contexts. 

For now, you can specify height/width in `ggplotly()` or `plot_ly()`, but I'll think about a better long-term solution

**Comment by vnijs** [comment]
OK. But autosizing worked when no width was set in 4.6.0 and no longer does that at all in 4.7.0. In fact, the size of the image in a Shiny app shown in Chrome seems to be determined by the size of the Viewer panel in Rstudio. Adding another set of screenshots below as illustration.

4.7.0

<img width="1675" alt="screen shot 2017-05-31 at 4 16 31 pm" src="https://cloud.githubusercontent.com/assets/2998956/26658047/8f18747a-461c-11e7-87b1-ee58f7a9667f.png">

4.6.0

<img width="1665" alt="screen shot 2017-05-31 at 4 19 27 pm" src="https://cloud.githubusercontent.com/assets/2998956/26658137/02d00978-461d-11e7-815d-a64821fdec90.png">

**Comment by cpsievert** [comment]
Ok, yea, that's definitely a problem. Does the same thing happen if you launch the app outside of RStudio?

**Comment by cpsievert** [comment]
Also, BTW, an official fix for this may take a bit, but for now, if you want the old behavior back:

```r
l <- ggplotly(qplot(1:10))
l$x$layout$width <- NULL
l$x$layout$height <- NULL
l$width <- NULL
l$height <- NULL
l
```

**Comment by vnijs** [comment]
The issue doesn't seems to occur outside of Rstudio. The fix does seems to work from Rstudio.

**Comment by vnijs** [comment]
Works! Thanks @cpsievert

**Comment by peranti** [comment]
@cpsievert The fix works for dynamically adjusting the plotly output wrt width. However, the height of the plot is not dynamically adjusting to the browser window.

**Comment by daattali** [comment]
It seems width+height in `plotlyOutput()` still don't work (in a browser), but setting it in `ggplotly()` does. If they aren't intended to work in plotlyOutput(), would it be a good idea to remove them from the signature, or at least mention in the documentation that they don't work?

**Comment by cpsievert** [comment]
Could you be more specific by "doesn't work"?  Both height/width seem to work for me.

**Comment by daattali** [comment]
the height and width arguments seem to be completely ignored when used in plotlyOutput in a shiny app

```
> packageVersion("shiny")
[1] ‘1.0.5’
> packageVersion("htmlwidgets")
[1] ‘0.9’
> packageVersion("plotly")
[1] ‘4.7.0’
```

Actually, after doing a specific small code example I think that the container is set to the proper dimensions, but the plot isn't. Example:

```
library(shiny)
library(plotly)
library(ggplot2)

ui <- fluidPage(
  plotlyOutput("p1", height=100, width=100),
  plotlyOutput("p2")
)

server <- function(input, output, session) {
  output$p1 <- renderPlotly({
    ggplotly(ggplot(mtcars, aes(mpg,wt))+geom_point())
  })
  output$p2 <- renderPlotly({
    ggplotly(ggplot(mtcars, aes(mpg,wt))+geom_point(), width=100,height=100)
  })
}

shinyApp(ui, server)
```

Result:

![image](https://user-images.githubusercontent.com/952340/30285676-cafa6bd0-96ec-11e7-8524-8de9b5ea3dff.png)

Notice that the small plot (which is p2) looks like it's starting 100px down, meaning the p1 actually does think it's only 100px tall, but the plot itself is regular sized. Hope that makes sense

**Comment by cpsievert** [comment]
Changes have been made here since 4.7.0 -- https://github.com/ropensci/plotly/commit/7a8ee9ce79e6e8913f6db990a05866380e7b10ae

Can you please try with a more recent version?

**Comment by daattali** [comment]
Ah yes the dev version works! The bug report title is for v 4.7.0 so I thought that was the latest

**Comment by dfrail24** [comment]
I was seeing this issue with the newest dev version - reverting back to 4.7.1 version on CRAN did fix the issue though.

**Comment by tenshis** [comment]
Still seeing this issue in 4.9.0 when using plotlyOutput inside renderUI. 

Setting the plotlyOutput width to "auto" results in a plot that is too small width-wise, and setting the width to NULL removes the height style attribute alltogether. Setting the width to 100% doesn't work at all, the app just crashes.
