### ISSUE TITLE
[Feature request] Drill-down capabilities 

### ISSUE THREAD

**Issue by gbisschoff** [ropensci/plotly#1041]
It would be nice if some drill-down capabilities are available in plotly. I know highcharts have these capabilities, but I like plotly much more. 

See [drilldown](http://rpubs.com/jbkunst/highcarter-drilldown) for an example. I am sure it is not to difficult and would add a whole new world to user experiences.

Similar capabilities can be developed on pie charts as well.

**Comment by cpsievert** [comment]
Drill-down is a very general term, but in most cases people are referring to what I call a *filter* operation. See some filter examples via `demo(package = "plotly")`

Also, see https://cpsievert.github.io/plotcon17/workshop/day2/#37

If you have questions, please use http://community.plot.ly

If you have more specific requests, please open another issue
