### ISSUE TITLE
javascript onclick event not triggering when clicking on plotly marker

### ISSUE THREAD

**Issue by shosaco** [ropensci/plotly#1043]
The issue is described [here](https://github.com/daattali/shinyjs/issues/129) and on [Stackoverflow](https://stackoverflow.com/questions/44412382/clicking-same-plotly-marker-twice-does-not-trigger-events-twice).

The initial issue is that we cannot fire an event after clicking on the *same* plotly marker *again* (because `event_data("plotly_click")` naturally doesn't change. We are trying to work around this by firing javascript `onclick` events, but Plotly is blocking those when clicking on a plotly marker. Is there a way to overcome this?

Thanks in advance and best regards!

**Comment by shosaco** [comment]
In the meantime I found a workaround by hard resetting the source of `event_data("plotly_click")` with `shinyjs` (described in the answer (here)[https://stackoverflow.com/questions/44412382/]). Would be nice to have this functionality built-in though, if possible.

**Comment by cpsievert** [comment]
This is now possible with `event_data("plotly_click", priority = "event")`

**Comment by shosaco** [comment]
Thanks a lot!!
