### ISSUE TITLE
Plotly object path dependencies are absolute paths and hard coded

### ISSUE THREAD

**Issue by mjmg** [ropensci/plotly#1044]
---

To make rendering of my Rmarkdown html presentations faster, I'm saving plotly objects as Rda files for loading into the presentations later.

However, when rendering the Rmarkdown files on another computer or OS or just a different user for that matter, the render fails due to plotly objects referencing hardcoded source files absolute paths from the computer it was saved.

Is there a way for plotly objects to determine the library path prefix as a relative path for dependencies from the current R session and not from the absolute path of the current session?

This way plotly objects saved as Rda files will be portable for different computers/OS's /sessions.

----

If the ggp plotly object below was saved as Rda file, the path for the src files would be saved as absolute paths when loaded at a different system. 

Perhaps the relative library paths can be dynamically generated from the ".libPaths()" primitive whenever a plotly object is generated/loaded from file?

```r
ggiris <- qplot(Petal.Width, Sepal.Length, data = iris, color = Species)
ggp <- ggplotly(ggiris)
ggp$dependencies[[1]]$src
ggp$dependencies[[2]]$src
ggp$dependencies[[3]]$src
```

**Comment by cpsievert** [comment]
Thanks!

As per our [contributing guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), github issues are reserved for bug reports and feature requests only. So I'll have to close your ticket.

Please use our community forums at [community.plot.ly](http://community.plot.ly/) for posts of the likes.

**Comment by mjmg** [comment]
Please clarify how this does not qualify as a bug report or feature request?

The expected behavior in my issue is plotly objects should not have dependencies with source file absolute paths that are hard-coded to the current running session where the plotly object is saved. 

If such plotly objects are loaded from Rda files on a different system with different OS or system user on Rstudio, the plotly graph will load on the viewer pane but if the Rmarkdown document containing the object is rendered as html, the render fails since the plotly object is referencing a file dependency that cannot be located due to hard-coded paths.

To reproduce:
```
ggiris <- qplot(Petal.Width, Sepal.Length, data = iris, color = Species)
ggp <- ggplotly(ggiris)
ggp$dependencies[[1]]$src
ggp$dependencies[[2]]$src
ggp$dependencies[[3]]$src

save(ggp, file="ggp.Rda")
```

On another computer with different OS/system user:


    ---
    title: "Untitled"
    output: html_document
    ---

    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = TRUE)
    load ("ggp.Rda")
    ```
    ```{r showggp, echo=FALSE}
    ggp
    ```

Rendering the above markdown document fails since the dependency path is hardcoded for the system where the plotly object was originally saved.

```
"Error: path for html_dependency not found: C:/Users/MyOtherUserName/Documents/R/win-library/3.4/crosstalk/www
Execution halted"
```

**Comment by cpsievert** [comment]
This is an issue/problem that would have to resolved at the htmltools/htmlwidgets level.

I'd recommend either using `htmlwidgets::saveWidget()` or a custom hack to override the file location via `system.file()` in the meantime

**Comment by mjmg** [comment]
OK noted. Thanks for the htmlwidgets::saveWidget() workaround for the meantime.
