### ISSUE TITLE
new_id is not reproducible

### ISSUE THREAD

**Issue by saurfang** [ropensci/plotly#1048]
`new_id` is not reproducible by setting random seeds in R because underlying `tempfile` uses C `rand()` function to generate file name.
https://github.com/ropensci/plotly/blob/15cd04927b8ee53b562601644e7ac66521c2b965/R/utils.R#L90

```r
set.seed(0)
basename(tempfile())
#> [1] "file5202337aaabd"
set.seed(0)
basename(tempfile())
#> [1] "file52023a5f78b2"

library(Rcpp)
cppFunction('void setCSeed(const unsigned int seed) { srand(seed); }')
setCSeed(0)
basename(tempfile())
#> [1] "file52021f0cce42"
setCSeed(0)
basename(tempfile())
#> [1] "file52021f0cce42"
```

Even with the Rcpp trick, this is still unreproducible because `tempfile()` also include pid, which cannot be easily spoofed.
https://github.com/wch/r-source/blob/318e389ca6376cf8193c29150743ce977fd4bc8d/src/main/sysutils.c#L1652

This causes the output HTML unreproducible and because htmlwidget collapse everything into a single line, this causes massive diff even though the data and graph are exactly the same.

You can do some nasty trick to get this to work
``` r
library(plotly)
#> Loading required package: ggplot2
#> 
#> Attaching package: 'plotly'
#> The following object is masked from 'package:ggplot2':
#> 
#>     last_plot
#> The following object is masked from 'package:stats':
#> 
#>     filter
#> The following object is masked from 'package:graphics':
#> 
#>     layout
library(htmlwidgets)

knit_print_plotly <- function(p) {
  knitr::knit_print(p, options = list(screenshot.force = FALSE))
}

set_plotly_id <- function(p, id) {
  p$elementId <- "p"
  names(p$x$attrs) <- "p"
  p$x$cur_data <- "p"
  names(p$x$visdat) <- "p"
  p
}

p1 <- plot_ly(economics, x = ~pop)
p2 <- plot_ly(economics, x = ~pop)
identical(
  knit_print_plotly(p1),
  knit_print_plotly(p2)
)
#> No trace type specified:
#>   Based on info supplied, a 'histogram' trace seems appropriate.
#>   Read more about this trace type -> https://plot.ly/r/reference/#histogram
#> No trace type specified:
#>   Based on info supplied, a 'histogram' trace seems appropriate.
#>   Read more about this trace type -> https://plot.ly/r/reference/#histogram
#> [1] FALSE

p1 <- plot_ly(economics, x = ~pop) %>% set_plotly_id("p")
p2 <- plot_ly(economics, x = ~pop) %>% set_plotly_id("p")
identical(
  knit_print_plotly(p1),
  knit_print_plotly(p2)
)
#> No trace type specified:
#>   Based on info supplied, a 'histogram' trace seems appropriate.
#>   Read more about this trace type -> https://plot.ly/r/reference/#histogram
#> No trace type specified:
#>   Based on info supplied, a 'histogram' trace seems appropriate.
#>   Read more about this trace type -> https://plot.ly/r/reference/#histogram
#> [1] TRUE

ggiris <- qplot(Petal.Width, Sepal.Length, data = head(iris))
p1 <- ggplotly(ggiris) %>% set_plotly_id("p")
p2 <- ggplotly(ggiris) %>% set_plotly_id("p")
identical(
  knit_print_plotly(p1),
  knit_print_plotly(p2)
)
#> [1] TRUE
```
but it becomes a bit of a mess as soon as you have more than one data series in the plot.

Would you be open to duplicate the logic from htmlwidget?
https://github.com/ramnathv/htmlwidgets/blob/7454758379d8b8ecc7e5a3e23ff21df0ebb9eca3/R/widgetid.R

**Comment by cpsievert** [comment]
Interesting, thanks for the detailed report. 

> This is troublesome especially for ggplotly because the id is not only generated for htmlwidget but also data series name as well.

Could you provide an example of why its troublesome?

**Comment by saurfang** [comment]
I stand corrected. It looks like `plot_ly` and `ggplotly` both require overriding internal attributes in addition to the htmlwidget id.

**Comment by mtoto** [comment]
One situation where this behaviour becomes problematic, is testing shiny apps that contain plotly graphs. Because of the ids cannot be reproduced, the tests fail.

**Comment by cpsievert** [comment]
I don't think this is an issue any longer now that the `elementId` field is no longer populated #985
