### ISSUE TITLE
Bug: add_trace and text labels --> Error: Variables must be length...

### ISSUE THREAD

**Issue by buggythepirate** [ropensci/plotly#1054]
I am trying to create a scatter plot which has ablines (via add_trace) and additional labels. Each code snippets works on its own. But combining them makes trouble...

```r
# First code. WORKS!
plot_ly(mtcars, x = ~mpg, y = ~disp, type="scatter",mode = "markers") %>%
add_trace(x = c(20, 20), y= c(min(mtcars$disp), max(mtcars$disp)), mode = "lines")

#second code. WORKS!
plot_ly(mtcars, x = ~mpg, y = ~disp, type="scatter",mode = "markers", text=~paste("Test:", wt ))

#third code HOUSTON WE HAVE A PROBLEM!
plot_ly(mtcars, x = ~mpg, y = ~disp, type="scatter",mode = "markers", text=~paste("Test:", wt )) %>%
add_trace(x = c(20, 20), y= c(min(mtcars$disp), max(mtcars$disp)), mode = "lines")
```
The last plot generates an error:

`Error: Variables must be length 1 or 32.
Problem variables: 'x', 'y'`

This is based on the current CRAN version of plotly.

**Comment by cpsievert** [comment]
Do `add_trace(x = c(20, 20), y= c(min(mtcars$disp), max(mtcars$disp)), mode = "lines", inherit = FALSE)`

**Comment by buggythepirate** [comment]
Thanks! User problem ;D
