### ISSUE TITLE
Examples in event_data documentation not running

### ISSUE THREAD

**Issue by GregorDeCillia** [ropensci/plotly#1057]
I just found that in the examples in the `event_data` docs still reference to the folder `inst/plotlyEvents` which does not exist anymore due to the new example structure since 46373a19186ec315d50605768d749826cef43f58. Here is the code from the docs

```r
shiny::runApp(system.file("examples", "plotlyEvents", package = "plotly"))
```

**Comment by cpsievert** [comment]
Thanks, fixed in df10188
