### ISSUE TITLE
Rsymphony package failed to be installed OSX

### ISSUE THREAD

**Issue by ANONIMUS2JI** [ropensci/plotly#1058]
Hello, 

Please help me guys, 

Trying to install Rsymphony package on MAC OSX I have got: 

Macbook PRO 13 with touchbar 
R Studio 1.0.143
R - 3.3.4
Installed Xcode, checked the Toolbar - installed 
Installed XQuartz 
Tried Homebrew - installed than still can't install Rsypmhony with the following error 

install.packages("Rsymphony")
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/PACKAGES.rds': HTTP status was '404 Not Found'
Package which is only available in source form, and may need compilation
  of C/C++/Fortran: ‘Rsymphony’
Do you want to attempt to install these from sources?
y/n: y
installing the source package ‘Rsymphony’

trying URL 'https://cran.rstudio.com/src/contrib/Rsymphony_0.1-26.tar.gz'
Content type 'application/x-gzip' length 8368 bytes
==================================================
downloaded 8368 bytes

* installing *source* package ‘Rsymphony’ ...
** package ‘Rsymphony’ successfully unpacked and MD5 sums checked
Cannot find SYMPHONY libraries and headers.
See <https://projects.coin-or.org/SYMPHONY>.
ERROR: configuration failed for package ‘Rsymphony’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rsymphony’
Warning in install.packages :
  installation of package ‘Rsymphony’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/sl/w8f3jfp501xfsx9c2k7n0q180000gn/T/RtmpzGZRZV/downloaded_packages’

What is wrong ?

**Comment by cpsievert** [comment]
Thanks!

As per our [contributing guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), github issues are reserved for bug reports and feature requests only. So I'll have to close your ticket.

Please use our community forums at [community.plot.ly](http://community.plot.ly/) for posts of the likes.
