### ISSUE TITLE
geom_label_repel not working in plolty

### ISSUE THREAD

**Issue by rajan5660** [ropensci/plotly#1061]
when geom_label_repel or geom_text_repel used with plotly it gives error saying.....................geom_label_repel is not still implemented with plotly

**Comment by duttashi** [comment]
@rajan5660 a minimum reproducible example for the error will be great. See this [SO community wiki](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example), on how to create one.
