### ISSUE TITLE
add_trace issue when x-axis values are POSIXct

### ISSUE THREAD

**Issue by jiayi9** [ropensci/plotly#1063]
Disclaimer: the `reprex` keeps giving me errors but I will make my code reproducible.

---
I want to plot a line chart. X values are time stamps and Y are typical numerical values.

I also want to add a reference line like `geom_hline` in `ggplot`. But the `add_trace` function is not working correctly.

```r
library(plotly)
library(lubridate)

D = data.frame(
  y = round(rnorm(10),1),
  x = structure(c(1498640394, 1498641854, 1498642201, 1498642515, 1498642749, 
                  1498643011, 1498643247, 1498643499, 1498643735, 1498643992), 
                tzone = "UTC", class = c("POSIXct", "POSIXt"))
)

D$DATE_TIME = lubridate::ymd_hms(D$x)

MIN = min(D$x)

MAX = max(D$x)

H = 0


plot_ly(D, x = ~x, y = ~ y, type = "scatter", mode ="lines+markers") %>% 
  add_trace(x = c(MIN, MAX), y = c(H, H), name = "Reference", mode = "lines", line=list(color="red",dash="dash"))

```
https://stackoverflow.com/questions/44878091/r-plotlly-add-trace-issue-when-x-axis-values-are-posixct

**Comment by jiayi9** [comment]
A workaround for this question:

    MIN = min(D$x) - 28800

    MAX = max(D$x) - 28800

Then the chart is correct for now.

28800 seconds are 8 hours by the way.

**Comment by cpsievert** [comment]
This will fix your problem:

```r
plot_ly(D, x = ~x, y = ~ y, type = "scatter", mode ="lines+markers") %>% 
  add_trace(x = ~range(x), y = rep(0, 2), name = "Reference", mode = "lines", line=list(color="red",dash="dash")) 
```

It looks like `c()` *may* use a different timezone (the system default tz), which is the cause of your problem:

```r
> c(MIN, MAX)
[1] "2017-06-28 03:59:54 CDT" "2017-06-28 04:59:52 CDT"
```
