### ISSUE TITLE
wrong position of legend in subplot()

### ISSUE THREAD

**Issue by ziyadsaeed** [ropensci/plotly#1069]
Code below generates a simple subplot with two legends. The legends don't accompany their respective charts. Instead they stack on top of each other on the right most side of the plots.
Using Plotly ‘4.7.0.9000’
```r
p <- plot_ly(mpg, x = ~cty, y = ~hwy, alpha = 0.5)
subplot(
  add_markers(p, color = ~cyl, showlegend = FALSE) %>% 
    colorbar(title = "Viridis"),
  add_markers(p, color = ~factor(cyl))
)
```
The result of this code is as below

![2017-07-08](https://user-images.githubusercontent.com/12503225/27979232-c2f12d26-638d-11e7-8551-da2ab5d1a15a.png)

**Comment by cpsievert** [comment]
> Instead they stack on top of each other on the right most side of the plots.

That is the intended behavior. If you want a different positioning, feel free to use `layout()`

```r
p <- plot_ly(mpg, x = ~cty, y = ~hwy, alpha = 0.5)
subplot(
  add_markers(p, color = ~cyl, showlegend = FALSE) %>% 
    colorbar(title = "Viridis"),
  add_markers(p, color = ~factor(cyl))
) %>% layout(legend = list(x = 0.5))
```
