### ISSUE TITLE
Speed of plotly rendering in R Shiny

### ISSUE THREAD

**Issue by madmark81** [ropensci/plotly#1070]
My code for generating the data frames and variables to render the plotly scatter 3d plot etc literally take less than 3 seconds to make. I have used the tic() tac() functions to clock the processes. To render plotly inside the Shiny App I'm building takes 10-20 seconds however every single time. I've seen other people post about this in some forums, but I have yet to discover any news about the cause and solutions for it. 

cheers, Mark

**Comment by cpsievert** [comment]
Thanks!

As per our [contributing guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), github issues are reserved for bug reports and feature requests only. So I'll have to close your ticket.

Please use our community forums at [community.plot.ly](http://community.plot.ly/) for posts of the likes.
