### ISSUE TITLE
Shiny -> Plotly-> Contour -> event_data()

### ISSUE THREAD

**Issue by milesmiles902** [ropensci/plotly#1072]
Hello Github!

I think this would be valuable for contours....or maybe I am just doing it wrong, so I thought I would ask.

Below represents something I am working on. The bottom and right line plots represent projections of the main plot along their respective axis. 
![image](https://user-images.githubusercontent.com/10928123/28254695-2e92d8fa-6b03-11e7-89b2-aca98575283d.png)

When I zoom in on the main plot, I want the projections to zoom according to the xmin, xmax, ymin and ymax and further project only what the main plot is showing, rather than always projecting the main plot entirely.

Is this possible? I tried using event_data("plot_hover") and event_data("plot_selected"), but neither seemed to work. They both came up with null.

There is a lot of documentation for the simpler graphs, but not as much for contours, so I thought I would ask about this one.

Thanks again,
Miles

**Comment by milesmiles902** [comment]
I thought it would be good to post a crude example of what I am doing.
ui.r
`shinyUI(dashboardPage(
  dashboardHeader(title = "Oscillations in Spectroscopy"),
  dashboardSidebar(sidebarMenu(
    id = "mytabs",
    menuItem(
      "Data Input",
      tabName = "input",
      icon = icon("dashboard")
    )
  )),
  dashboardBody(tabItems(tabItem(
    "input",
    box(
      title = "Data Input",
      status = "warning",
      solidHeader = TRUE,
      width = "100%",
      height = "100%",
      fluidPage(fluidRow(
        column(7,
               plotlyOutput("raw"),
               plotlyOutput("raw.x")),
        column(2, width = 5,
               plotlyOutput("raw.y"))
      ))
    )
  )))
))`
Server.r
`shinyServer(function(input, output, session) {
  process.data <- reactive({
    #Do some back - end stuff
    return(df)
  })

  output$raw <- renderPlotly({
    print(.mainplot())
  })

  output$raw.x <- renderPlotly({
    .xplot()
  })

  output$raw.y <- renderPlotly({
    .yplot()
  })

  .mainplot <- function() {
    df <- data.frame(process.data())
    p <-
      plot_ly(
        df,
        x = ~ series,
        y = ~ time,
        z = ~ value,
        type = "contour",
        source = "A"
      ) %>% hide_colorbar()

    return (df)
  }

  .xplot <- function() {
    df <- data.frame(process.data())
    p <-
      plot_ly(
        df,
        x = ~ series,
        y = ~ value,
        type = 'scatter',
        mode = 'lines'
      ) %>%
      layout(xaxis = list(title = ""),
             yaxis = list(title = "", showticklabels = F))
    return(p)
  }
  .yplot <- function() {
    df <- data.frame(process.data())
    p <-
      plot_ly(
        df,
        x = ~ x,
        y = ~ y,
        type = 'scatter',
        mode = 'lines'
      ) %>%
      layout(xaxis = list(title = ""),
             yaxis = list(title = "", showticklabels = F))
    return (p)
  }

})`

**Comment by milesmiles902** [comment]
Solved:

```
p <-
      plot_ly(x = df[,2], y = df[,4]) %>%
        add_contour(x = dat@wavelength, y = dat@data$x, z = dat@data$spc, visible = TRUE) %>%
        add_markers(x = df[,2], y = df[,4], opacity = 0.01, hoverinfo="x+y") %>%
        layout(dragmode = "select")
```

**Comment by cpsievert** [comment]
Thanks!

As per our [contributing guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), github issues are reserved for bug reports and feature requests only. So I'll have to close your ticket.

Please use our community forums at [community.plot.ly](http://community.plot.ly/) for posts of the likes.
