### ISSUE TITLE
Plot a plotly heatmap in full size

### ISSUE THREAD

**Issue by ndrubins** [ropensci/plotly#1077]
Hi,

I have gene expression data matrix (`mat`) (13,000 genes from 12 samples):
```

set.seed(1)
mat <- matrix(cbind(rnorm(13000,-0.82,0.8),rnorm(13000,-0.78,0.88),rnorm(13000,-0.76,0.8),
             rnorm(13000,0.045,0.85),rnorm(13000,0.1,0.69),rnorm(13000,0.15,0.73),
             rnorm(13000,0.38,0.75),rnorm(13000,0.46,0.78),rnorm(13000,0.43,0.8),
             rnorm(13000,0.2,1),rnorm(13000,0.32,0.99),rnorm(13000,0.27,0.91)),
             nrow=13000,ncol=12,
             dimnames=list(paste("MyGeneName",1:13000,sep="."),paste("MySampleName",1:12,sep=".")))


```

When I plot a `heatmap` using this code:
```
heatmap.plot <- plot_ly() %>% add_heatmap(z=~mat,x=factor(colnames(mat),lev=colnames(mat)),y=factor(rownames(mat),lev=rownames(mat)),colors=colorRamp(c("darkblue","white","darkred")),
                                          colorbar=list(title="lnTPM",len=0.4)) %>% layout(margin=list(l=50*log(y.axis.nchar))) %>% layout(yaxis=list(title="Gene"),xaxis=list(title="Sample"),
         margin=list(l=100*log(max(nchar(rownames(mat)))+1000)/log2(ncol(mat)+1),r=10*nchar("ln.TPM"),
                     b=50*log(max(nchar(colnames(mat)))+10),t=50,pad=2))

```

The plot (couldn't find a way to upload it) doesn't show all the genes but rather defaults to some subset of them, and in this case this default display picks on the most differentially expressed genes and slightly distorts the reality, making it seem more dramatic than it is - compared to what this density plot shows:

```
mat.df <- reshape2::melt(mat) %>% dplyr::rename(gene=Var1,sample=Var2,ln.TPM=value)
mat.df$sample <- factor(mat.df$sample,levels=colnames(mat))
ggplot(mat.df,aes(x=ln.TPM,color=sample))+geom_density(adjust=1)+theme_minimal()

```
So my question is if there's a way to force plotly to plot the heatmap in it's full dimensions? 

Thanks

**Comment by cpsievert** [comment]
> The plot (couldn't find a way to upload it) doesn't show all the genes but rather defaults to some subset of them

It likely seems this way because you are trying to plot more cells than you have pixels on your screen. You probably want to use something like heatmaply to order the rows/columns sensibly
