### ISSUE TITLE
Line breaks in y-tick labels on horizontal bar chart

### ISSUE THREAD

**Issue by e-mitchell** [ropensci/plotly#1079]
On a horizontal barplot, trying to shorten y-tick labels using `<br>` line breaks leaves too much room for the label.

Here's an example of a long label (no line breaks):
```r
library(plotly)

long_label = "Dinner (or, super long label to check out some line breaks in plotly)"

dat1 <- data.frame(
  sex = factor(c("Female","Female","Male","Male")),
  time = factor(c("Lunch",long_label,"Lunch",long_label), levels=c("Lunch",long_label)),
  total_bill = c(13.53, 16.81, 16.24, 17.42)
)

p <- ggplot(data=dat1, aes(x=time, y=total_bill, fill=sex)) +
  geom_bar(stat="identity", position=position_dodge()) + 
  coord_flip() + theme_bw()

p <- ggplotly(p)
ggplotly(p)
```
![image](https://user-images.githubusercontent.com/5256203/28475654-313ed5ac-6e1b-11e7-85c9-b65257487c58.png)

After adding line breaks in the labels, the plot stays squished to the right:
```r
library(plotly)

long_label = "Dinner (or, super long label<br>to check out some<br>line breaks in plotly)"

dat1 <- data.frame(
  sex = factor(c("Female","Female","Male","Male")),
  time = factor(c("Lunch",long_label,"Lunch",long_label), levels=c("Lunch",long_label)),
  total_bill = c(13.53, 16.81, 16.24, 17.42)
)

p <- ggplot(data=dat1, aes(x=time, y=total_bill, fill=sex)) +
  geom_bar(stat="identity", position=position_dodge()) + 
  coord_flip() + theme_bw()

p <- ggplotly(p)
ggplotly(p)
```
![image](https://user-images.githubusercontent.com/5256203/28475706-58047aa2-6e1b-11e7-959b-6a633b7eb574.png)

When it should look more like this (but with the rest of the label):

![image](https://user-images.githubusercontent.com/5256203/28475809-c3d5bd36-6e1b-11e7-95c0-f0522747b983.png)

I think the issue might have something to do with the way that 'nchar' in the ggplotly function is counting characters of each tick label, without splitting by `<br>` first.

Thanks for looking into this!

**Comment by cpsievert** [comment]
Not ideal, but you can use `layout(ggplotly(p), list(l = 50))` to control the left-margin

**Comment by e-mitchell** [comment]
Thanks for the suggestion. I couldn't get the layout to work directly on the ggplotly object, but I was able to tweak it using theme(plot.margin) applied to the ggplot object instead:

```r
p <- ggplot(data=dat1, aes(x=time, y=total_bill, fill=sex)) +
  geom_bar(stat="identity", position=position_dodge()) + 
  coord_flip() + theme_bw() +
  theme(plot.margin = margin(l = -200))

ggplotly(p) 
```

I'm embedding this graphic in a Shiny app, so it would be nice if the adjustment were automatic. For now, I'll play around with the numbers and see if I can make a pseudo-automated margin adjustment based on the plot label length.

**Comment by cpsievert** [comment]
Whoops, it's actually `layout(ggplotly(p), list(margin = list(l = 50)))`
