### ISSUE TITLE
Not able to color lines of histograms

### ISSUE THREAD

**Issue by vikram-rawat** [ropensci/plotly#1085]
I am unable to find a command that shows complete functionality of a layer. I was trying to color lines of histograms. I was not able to understand the documentation.

Its all mixed up. Kindly create a seperate document for every layer

Like

add_marker
And
Add_boxplot should have their own usage guides.

Please it will be a huge help. Newbies also need to learn this package. And i don't know why but is slower than ggplot2 even though its new

**Comment by cpsievert** [comment]
I don't understand the question.

As per our [contributing guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), github issues are reserved for bug reports and feature requests only. So I'll have to close your ticket.

Please use our community forums at [community.plot.ly](http://community.plot.ly/) for posts of the likes.
