### ISSUE TITLE
geom_GeomRoc() has yet to be implemented in plotly.

### ISSUE THREAD

**Issue by pietervosnl** [ropensci/plotly#1092]
I would like to be able to plot an ROC with the package https://github.com/sachsmc/plotROC/
This is working with Shiny:

library(plotROC)
set.seed(2529)
D.ex <- rbinom(200, size = 1, prob = .5)
M1 <- rnorm(200, mean = D.ex, sd = .65)
M2 <- rnorm(200, mean = D.ex, sd = 1.5)

test <- data.frame(D = D.ex, D.str = c("Healthy", "Ill")[D.ex + 1], 
                   M1 = M1, M2 = M2, stringsAsFactors = FALSE)

basicplot <- ggplot(test, aes(d = D, m = M1)) + geom_roc()
basicplot

**Comment by cpsievert** [comment]
Thanks, added to #566
