### ISSUE TITLE
Reopening wrapping of long titles in ggplotly

### ISSUE THREAD

**Issue by mexindian** [ropensci/plotly#1097]
So this issue was already mentioned and closed in #851, but it seems the issue wasn't resolved. This especially doesn't work if the wrapping required is in the y-axis... for example:

```r
library(plotly)
library(stringr)

df_x <- data.frame(
  y = "this is very loooooooooooooooooooooooooooooooooooooooooooooooong text to illustrate",
  x = 100
)

p <- ggplot(aes(x = x, y = y), data = df_x) +
  geom_bar(stat = "identity") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10))
p
ggplotly(p)
```

![image](https://user-images.githubusercontent.com/8094091/29082791-914b7dd2-7c5e-11e7-9237-3ac9da2f4c89.png)

If this issue won't be fixed, then I don't think I'll be able to use ggplotly in a dashboard setting.

**Comment by cpsievert** [comment]
I closed the issue since lineabreaks are now translated.

Closing this since it wont be wise to spend the effort on an auto-margin routine just for the R package. There are several plotly.js issues asking for better auto-margins which hopefully someday we can leverage

**Comment by mexindian** [comment]
Sorry, I hadn't installed the last version of plotly. You are correct.
