### ISSUE TITLE
Reversing Y Axis for Scatter Plot causes scale to disappear

### ISSUE THREAD

**Issue by mayankX** [ropensci/plotly#1102]
<img width="1044" alt="screen shot 2017-08-18 at 1 17 38 pm" src="https://user-images.githubusercontent.com/3822550/29449313-d6b5798e-8417-11e7-8dd2-8af395b556ad.png">

```
data_set %>% plot_ly(x = ~win_vi1_data.gx, y = ~win_vi1_data.gy, type="scattergl", mode = "markers",
                                          symbol= ~description, source = source_name
    ) %>% layout(
      # title = "Dye Error Code Heat Map",
      autosize = T,
      xaxis = list(
        title = "X axis"
      ),
      yaxis = list(
        title = "Y axis",
        autorange = "reversed"
      ),
      showlegend = TRUE
    )
```

Marking autorange = "reversed" causes y axis scale to disappear completely as shown in above screenshot. without **reversed** it appears like this

For Testing this code can be used as well

```
plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length, type="scattergl", mode = "markers")%>% layout(
      # title = "Dye Error Code Heat Map",
      autosize = T,
      xaxis = list(
        title = "X axis"
      ),
      yaxis = list(
        title = "Y axis",
        autorange = "reversed"
      ),
      showlegend = TRUE
    )
```

<img width="985" alt="screen shot 2017-08-18 at 1 18 08 pm" src="https://user-images.githubusercontent.com/3822550/29449369-0a003324-8418-11e7-83c6-ed985cc2d944.png">

<img width="1103" alt="screen shot 2017-08-18 at 1 36 31 pm" src="https://user-images.githubusercontent.com/3822550/29449917-44fd0450-841a-11e7-8f8a-96e440be91fd.png">

**Comment by cpsievert** [comment]
I believe this is now fixed
