### ISSUE TITLE
Plotting large data sets

### ISSUE THREAD

**Issue by Nikolai-Hlubek** [ropensci/plotly#1104]
Basically this is another go at bug number #822. 

R Plotly is not very good in handling large numbers of data. I'm using R in Jupyter and when I plot a line >1e5 points, which I do not consider to be much, I get a pandoc conversion error. 

Python Plotly can easily handle a line with 1e6 points.

Ok, so this might be an issue with pandoc, so I played around a bit and removed the pandoc dependency by doing the html handling manually. 
See the attached zip. This works and I get plots with 2e5 points in a reasonable amount of time. 
I'm actually convinced the way I'm doing it with the precompiled header which is just inserted into the html, instead of using Pandoc to create the header is the way to go.

However at 3e5 points the routine slows down significantly. The reason is the long time spent in plotly_built. So I'm stopping here and asking for help: Help! 
Is there anything that can be done to speed this routine up? A million points is really not a lot nowadays and should be possible with R plotly.

[embed_R_without_PANDOC.zip](https://github.com/ropensci/plotly/files/1236694/embed_R_without_PANDOC.zip)

PS: 
With a bigger box I is possible to plot larger datasets. Therefore for a fair comparison I'm using vagrant to create a virtual machine with python, R, plotly and jupyter:

https://github.com/Nikolai-Hlubek/vagrant-centos7-jupyter

**Comment by msummersgill** [comment]
What version of plotly are you using? When I try to reproduce, I'm seeing several other bottlenecks as the primary constraint, not the `plotly_build()` function.

I took a subset of your function to render using pre-compiled headers and reduced it down to only saving the html as below.

```r
plotly_save_html <- function(x, width = NULL, height = NULL, file = NULL) {
  
  precompiled_html_header <- readRDS("precompiled_html_header.rds")
  p <- plotly_build(x)
  html <- htmlwidgets:::toHTML(p)
  rendered <- htmltools::renderTags(html)
  
  id <- substr(rendered$html, 10, 20)
  linebreak <- regexpr('\n', rendered$html)
  rendered$htmlwidget <- paste0("  ", substr(rendered$html, 1, linebreak))
  
  rendered$htmlwidget_sizing <- paste0(
    "<script type=\"application/htmlwidget-sizing\" data-for=\"",
    id,
    "\">{\"viewer\":{\"width\":\"100%\",\"height\":400,\"padding\":15,\"fill\":true},\"browser\":{\"width\":\"100%\",\"height\":400,\"padding\":40,\"fill\":true}}</script>")
  
  html <- c(
    precompiled_html_header,
    "<body style=\"background-color:white;\">",
    "<div id=\"htmlwidget_container\">",
    rendered$htmlwidget,
    "</div>",
    substr(rendered$html, linebreak+1, nchar(rendered$html)),
    rendered$htmlwidget_sizing,
    "</body>",
    "</html>"
  )
  
  writeLines(html, file)
}
```

*Note: I had issues getting the .rda format to read for some reason so I just rewrote it as a .rds formatted file*

```r
header <- load("precompiled_html_header.rda",envir=.GlobalEnv)
saveRDS(precompiled_html_header,"precompiled_html_header.rds",compress = FALSE)

```

I then ran it through profvis. For 1e6 points, it took about 4.5 seconds to render and save.

```r
library(plotly)
library(profvis)

## Create Data
N <- 1e6
df <- data.frame(x_vals = seq_len(N),
                 y_vals = sin(seq_len(N))*10 + 10)

## Create Plot
df %>% 
  plot_ly() %>% 
  add_lines(x = ~x_vals, y = ~y_vals) -> p

## Save
plotly_save_html(p, file = "plotly_precompiled_test.html")
```

From what I'm seeing, the bottleneck appears to be on the htmlwidgets/jsonlite side, not in `plotly_build()`.

![image](https://user-images.githubusercontent.com/19575728/32104268-4b949be2-bae9-11e7-8bb2-58e9056d0ae8.png)

![image](https://user-images.githubusercontent.com/19575728/32103996-4beae1ce-bae8-11e7-98e2-7469072866b5.png)

[plotly_save_html_profvis.zip](https://github.com/ropensci/plotly/files/1422058/plotly_save_html_profvis.zip)


I am running a somewhat out of date fork of the plotly package for this example, perhaps that could be related to the discrepancy on what we are seeing respectively as the bottleneck).

`devtools::session_info()` output:

```
 package     * version    date       source                              
 assertthat    0.2.0      2017-04-11 cran (@0.2.0)                       
 bindr         0.1        2016-11-13 CRAN (R 3.4.0)                      
 bindrcpp    * 0.2        2017-06-17 CRAN (R 3.4.0)                      
 colorspace    1.3-2      2016-12-14 cran (@1.3-2)                       
 crosstalk     1.0.0      2016-12-21 CRAN (R 3.4.0)                      
 data.table  * 1.10.4     2017-02-01 CRAN (R 3.4.0)                      
 devtools    * 1.12.0     2016-12-05 CRAN (R 3.4.0)                      
 digest        0.6.12     2017-01-27 cran (@0.6.12)                      
 dplyr         0.7.4      2017-09-28 cran (@0.7.4)                       
 ggplot2     * 2.2.1.9000 2017-09-30 Github (tidyverse/ggplot2@c592e32)  
 glue          1.1.1      2017-06-21 cran (@1.1.1)                       
 gtable        0.2.0      2016-02-26 CRAN (R 3.4.0)                      
 htmltools     0.3.6      2017-04-28 CRAN (R 3.4.0)                      
 htmlwidgets * 0.9        2017-07-10 cran (@0.9)                         
 httpuv        1.3.3      2015-08-04 CRAN (R 3.3.0)                      
 httr          1.3.1      2017-08-20 cran (@1.3.1)                       
 jsonlite      1.5        2017-06-01 cran (@1.5)                         
 lazyeval      0.2.0      2016-06-12 CRAN (R 3.3.0)                      
 magrittr      1.5        2014-11-22 CRAN (R 3.4.0)                      
 memoise       1.1.0      2017-04-21 CRAN (R 3.4.0)                      
 mime          0.5        2016-07-07 CRAN (R 3.3.0)                      
 munsell       0.4.3      2016-02-13 CRAN (R 3.3.0)                      
 pkgconfig     2.0.1      2017-03-21 CRAN (R 3.4.0)                      
 plotly      * 4.6.0.9000 2017-09-30 Github (msummersgill/plotly@24d327d)
 plyr          1.8.4      2016-06-08 CRAN (R 3.3.0)                      
 profvis     * 0.3.3      2017-01-14 CRAN (R 3.4.0)                      
 purrr         0.2.3      2017-08-02 cran (@0.2.3)                       
 R6            2.2.2      2017-06-17 cran (@2.2.2)                       
 Rcpp          0.12.13    2017-09-28 cran (@0.12.13)                     
 rlang         0.1.2      2017-08-09 cran (@0.1.2)                       
 scales        0.5.0.9000 2017-09-30 Github (hadley/scales@d767915)      
 shiny         1.0.3      2017-04-26 CRAN (R 3.4.0)                      
 stringi       1.1.5      2017-04-07 CRAN (R 3.4.0)                      
 stringr       1.2.0      2017-02-18 CRAN (R 3.4.0)                      
 tibble        1.3.4      2017-08-22 cran (@1.3.4)                       
 tidyr         0.7.1      2017-09-01 cran (@0.7.1)                       
 viridisLite   0.2.0      2017-03-24 CRAN (R 3.4.0)                      
 withr         2.0.0      2017-09-30 Github (jimhester/withr@d1f0957)    
 xtable        1.8-2      2016-02-05 CRAN (R 3.3.0)                      
 yaml          2.1.14     2016-11-12 CRAN (R 3.3.2)       
```

**Comment by Nikolai-Hlubek** [comment]
Hi Matt

You did some pretty impressive profiling work. Thank you. 
I used the latest version from github master for my changes and the post above.

At work I have been running a version with pre-compiled headers since August and we didn't have memory issues anymore. Actually I made a few other changes along the line since the version above has an issue with scaling. 

I didn't have time preparing a proper git push request until now, but I think I will be able to do so next week, because in my opinion pre-compiled headers are the correct way and the dependency on Pandoc is unnecessary.
Maybe this version will reveal the next memory or slow-down culprit.

Best wishes, 
Nikolai

**Comment by msummersgill** [comment]
Look forward to any improvements you might be able to implement, I use frequently use plotly for visualizing large time series type sensor data, and the capability to plot more points, more traces, and faster is always appreciated!

For what it's worth, when it comes to generating the html, it the majority amount of processing time is spent deep within the call stack on the jsonlite function [num_to_char.c](https://github.com/cran/jsonlite/blob/master/src/num_to_char.c) (for a plot like this with a numeric x axis) and garbage collection. 

I'm in somewhat over my head to try and do tuning at that level, but I do wonder if there might be a way to eliminate some of the exception handling at that level (potentially at the calculated risk of generating corrupted html file outputs if the performance improvement was great enough) or an optimization of the buffer size.

Perhaps a step change improvement might come from a major rewrite of `jsonlite::toJSON` borrowing heavily from some of the multi-threading and performance optimizations used in data.table's [fwrite.c](https://github.com/Rdatatable/data.table/blob/master/src/fwrite.c) function. (See [blog from Matt Dowle: Fast CSV Writing for R](https://blog.h2o.ai/2016/04/fast-csv-writing-for-r/) for some of the steps that they used. If JSON could be generated even at half the throughput rate of ~0.4 GB/second he benchmarked on a 4 core laptop, then the only real constraint would be browser rendering capabilities.

Unfortunately,my understanding of `c`, and the internals of the plotly.js engine are so limited I don't think I can realistically take on such an endeavor, really just throwing the idea out there if someone with such a skill set happens to come along.

**Comment by Nikolai-Hlubek** [comment]
I have been running a custom version of plotly for several months at my company now and we did not experience any issues. 

Changes
- I use precompiled headers containing the plotly javascript code.
- I do not use htmlwidgets and thus pandoc but xml2. This gets rid of pandoc as external dependency and drastically increases the number of points a figure can contain. 

You can find the version at my repository:
https://github.com/Nikolai-Hlubek/plotly

**Comment by cpsievert** [comment]
Recent additions to https://github.com/IRkernel/repr should fix most, if not all, of these issues. I just tried it on 1 million points and it seems fairly responsive (takes about 5-10 seconds). Please try it out:

```r
remotes::install_github("IRkernel/repr")
```

**Comment by onurcanbektas** [comment]
@cpsievert How is it going to help? I've a big data (I don't know the size) and it takes around ~10mins to open the .html file that plotly produces.

Are we supposed to just install "IRkernel/repr" and was that supposed to solve these problems?
