### ISSUE TITLE
plotly object "dependencies" path is absolute rather than relative

### ISSUE THREAD

**Issue by coolbutuseless** [ropensci/plotly#1117]
The list of dependencies in a plotly object are absolute file paths rather than relative file paths. e.g. 

```r
myplotly$dependencies[[1]]$src$file
> [1] "/Library/Frameworks/R.framework/Versions/3.3/Resources/library/plotly/htmlwidgets/lib/typedarray"
```

This means that it is difficult to generate a plotly object on one machine and use it on another machine.

My current use case involves generating interactive charts on my local machine and then uploading those charts to my shiny app.  Since my local machine and my shiny server are different architectures, the dependency locations no longer resolve. My current workaround is to create a softlink on the server to mimic the path on my local machine.

One possible solution might be to make the dependency paths relative to package locations.

**Comment by cpsievert** [comment]
This sort of thing would be best resolved on the htmlwidgets level https://github.com/ramnathv/htmlwidgets
