### ISSUE TITLE
Paired brewer palette does not behave as expected

### ISSUE THREAD

**Issue by Shians** [ropensci/plotly#1120]
When using the "Paired" palette the colours do not appear as they do in ggplot2. It also does not appear to respect the paired colours property of the palette regarding successive factor levels.

```r
data(iris)
plotly::plot_ly(data = iris,
    x = ~Sepal.Length, y = ~Petal.Length, color = ~Species, colors = "Paired")

ggplot(iris, aes(x = Sepal.Length, y = Petal.Length, col = Species)) +
    geom_point() +
    scale_color_brewer("Paired")
```

It can be made to work with

```r
plotly::plot_ly(data = iris,
    x = ~Sepal.Length, y = ~Petal.Length, color = ~Species,
    colors = RColorBrewer::brewer.pal(3, "Paired"))
```

**Comment by cpsievert** [comment]
> It also does not appear to respect the paired colours property of the palette regarding successive factor levels.

I don't quite follow -- can you make an argument that the ggplot2 behavior is objectively better?

**Comment by Shians** [comment]
This is specifically regarding the "Paired" palette

![qual-500x127](https://user-images.githubusercontent.com/6036662/51719148-6f8cdb80-209c-11e9-94ba-cb5571a1f1ed.jpg)

Based on the name I assume the colours are for presenting data in pairs, therefore having similar pairs of colours shown above. This can be useful for data as presented [here](https://moderndata.plot.ly/create-colorful-graphs-in-r-with-rcolorbrewer-and-plotly/).

![screen shot 2019-01-25 at 12 25 49 pm](https://user-images.githubusercontent.com/6036662/51719291-ffcb2080-209c-11e9-9785-adbfaa0e3f9a.png)
 
with the effect that meals have similar colours and the numbering has similar intensity. In ggplot2 this is achieved by ordering your paired levels to be adjacent to each other. In plot_ly it requires going around the canonical interface for accessing "Paired". Obviously the choice is totally arbitrary for the palettes with no structure.

**Comment by cpsievert** [comment]
Both of those `plot_ly()` code blocks produce the same result for me, is this not what you'd expect?

<img width="625" alt="screen shot 2019-01-24 at 7 51 27 pm" src="https://user-images.githubusercontent.com/1365941/51720028-74f11400-2011-11e9-9526-4d6c23eff920.png">

**Comment by Shians** [comment]
On my MacOS 10.13.6 system with Plotly 4.8.0, running

```
plotly::plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length, color = ~Species, colors = "Paired")
```

shows

![screen shot 2019-01-25 at 1 47 30 pm](https://user-images.githubusercontent.com/6036662/51722023-1c208a80-20a8-11e9-9521-9af23aa12644.png)

I think back when I submitted the issue the behaviour with 3 levels was to pick colours from the two ends and centre of a palette.

**Comment by cpsievert** [comment]
Ohhh, this is actually due to a change in `scales::col_factor()` -- if you install the Github version you'll get the result in https://github.com/ropensci/plotly/issues/1120#issuecomment-457426736

**Comment by cpsievert** [comment]
Closing since the new scales gives you the behavior you'd expect, right?
