### ISSUE TITLE
Hover text showing only first letter

### ISSUE THREAD

**Issue by tuomastik** [ropensci/plotly#1125]
Hover tooltip shows only first letter when `color` and `colors` parameters are provided. Without `color` and `colors` parameters, the text is shown correctly.

```r
library(plotly)

plot_ly(mtcars, x = ~wt, y = ~hp, z = ~qsec,
        color = as.factor(rownames(mtcars)),
        colors = grDevices::heat.colors(nrow(mtcars)),
        hoverinfo = "text",
        text = rownames(mtcars)) %>% add_markers()
```

The code above produces the following figure:
![image](https://user-images.githubusercontent.com/5929459/30741590-11692f84-9f9e-11e7-8652-02e15ecda463.png)

The following figure is produced without `color` and `colors` parameters:
![image](https://user-images.githubusercontent.com/5929459/30741607-22e04b58-9f9e-11e7-90e2-4be52494a4ef.png)

**Comment by tuomastik** [comment]
Managed to solve the issue by wrapping the value of `text` parameter into a `list()`.

**Comment by drowsygoat** [comment]
Hi Tuomastik, did you have any other insight into this problem? I have exactly the same problem, but listing the attributes only made it worse.

**Comment by tuomastik** [comment]
@drowsygoat Unfortunately no. I can only suggest comparing your implementation to the code snippet (and its solution) provided in my first comment.

**Comment by madmark81** [comment]
I have run into the same problem. Instead of my custom hover text some points show "<" instead of the message. Putting the code inside a list() results in correct hover texts for the points that showed "<" before, but NO hover text for all other points. 
This is how I code it 
   hoverinfo = 'text' ,
                  text =    ~paste ('<br>', 'Cluster ID: ', Idf[[paste('sub.flow.', groupID, sep = '')]], 
                                    '<br>', 'Particle ID:', Idf[['newid' ]],
                                    '<br>', paste(input[[paste('x_axis', plotID, sep = '_')]],': ', sep =''), format(round(Idf[[input[[paste('x_axis', plotID, sep = '_')]] ]], digits=2), nsmall =2),
                                    '<br>', paste(input[[paste('y_axis', plotID, sep = '_')]],': ', sep =''), format(round(Idf[[input[[paste('y_axis', plotID, sep = '_')]] ]], digits=2), nsmall =2),
                                    '<br>', paste(input[[paste('z_axis', plotID, sep = '_')]],': ', sep =''), format(round(Idf[[input[[paste('z_axis', plotID, sep = '_')]] ]], digits=2), nsmall =2)), 

![image](https://user-images.githubusercontent.com/29946999/33877187-ebdd7b52-df27-11e7-9c1f-36153a610ff2.png)

**Comment by madmark81** [comment]
Additional info on this bug: If I run the plot on my full 100.000 data set, NO PROBLEM, as soon as I do any form of subsetting, varying from dfx[1:1000, ], dfx[listofrandomrownumbers, ] or grabbing 10% per category in a for loop, or running a dplyr arrange solution to subset, they all result in the same bug. 

I also noticed that if i just plot 1 point, and it has the buggy hover, that rotating the camera view fixes it, 
but if there are multiple points, this trick does nothing for the issue.

**Comment by MartinsRodrigo** [comment]
Same issue here, but the list() solution doesnt work

**Comment by cpsievert** [comment]
I believe `I()` (instead of `list()`) would be a more general work-around:

```r
plot_ly(mtcars, x = ~wt, y = ~hp, z = ~qsec,
        color = as.factor(rownames(mtcars)),
        colors = grDevices::heat.colors(nrow(mtcars)),
        hoverinfo = "text",
        text = I(rownames(mtcars))) %>% add_markers()
```

**Comment by cpsievert** [comment]
A proper fix for this will likely have to come from plotly.js -- I've started an issue here -- https://github.com/plotly/plotly.js/issues/2693

**Comment by abautistah** [comment]
list worked for me, =D 

hoverinfo = "text", text = list(size_cluster$sizesc)

**Comment by cpsievert** [comment]
This issue appears to be fixed now.
