### ISSUE TITLE
need some interactive with shiny R plotly gantt chart

### ISSUE THREAD

**Issue by sachinbanugariya** [ropensci/plotly#1130]
hello,

we implemented shiny R plotly gantt chart.
as per our project we need to interactive for gantt chart, which listed below.

is it possible to hover method for task name's display when hover anywhere inside task bar, instead of just only start and end point of bar only?
is it possible to see(print) output values at every bar end side ?

the most important:
how can i link or focus my plotly gantt chart bars based on my table view rows,
that means suppose when i select or clicked on second row of table view then the focus of plotly shiny gantt is on that data of gantt bar.

we kindly want to know how we can do this things.
please let us know ASAP.
thanks

**Comment by cpsievert** [comment]
Thanks!

As per our [contributing guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), github issues are reserved for bug reports and feature requests only. So I'll have to close your ticket.

Please use our community forums at [community.plot.ly](http://community.plot.ly/) for posts of the likes.
