### ISSUE TITLE
embed_notebook() no longer working

### ISSUE THREAD

**Issue by knowitallism** [ropensci/plotly#1138]
I have been using the embed_notebook() function to embed plotly graphs into my Jupyter notebooks. Today I noticed that the embed_notebook function only returns white space. However, I can still graph the plotly object outside of the embed_notebook function.

If anyone could either help me fix this problem or give me an alternative for embedding plotly objects in Jupyter notebooks, I would greatly appreciate it.

**Comment by bcdunbar** [comment]
Specifically, `embed_notebook` currently doesn't work in Chrome and Edge/IE browsers but works in Firefox. Additionally, it still functions as expected in nteract.

**Comment by bcdunbar** [comment]
looks like version `4.6.0` stopped working in the browsers mentioned, @knowitallism you should be able to still use version `4.5.6` for now.

```
require(devtools)
install_version("plotly", version = "4.5.6", repos = "http://cran.us.r-project.org")
```

**Comment by cpsievert** [comment]
Does it work if you just print the plotly object instead of using `embed_notebook()` (e.g., do `plot_ly()` instead of `embed_notebook(plot_ly())`)? That works in Chrome with the latest version of plotly

```shell
docker run -p 8888:8888 cpsievert/r-notebook-plotly ipython notebook
```

**Comment by bcdunbar** [comment]
Yeah, I think there is some confusion about when/where to use `embed_notebook`. Oddly, it still works in FF.

Currently, `plot_ly()` only works in Chrome, it freezes or produces nothing in FF and IE/Edge.

**Comment by knowitallism** [comment]
Hi, sorry, I meant to reply back to this thread earlier. Yes, the problem is specific to Edge/IE and Chrome. With Edge, the problem seems to be that Edge/IE simply don't support data URIs for security reasons. Unfortunately, I'm unclear why this stopped working in Chrome recently. It still works with Firefox and Safari, though. 

cpsievert, printing a plotly object still works in Chrome. Unfortunately, having plotly objects outside of an iframe creates problems when converting a jupyter notebook to html. So far, I have been saving plotly objects as separate html files, then embedding them inside of iframes. This is probably what I should have been doing anyway, since most browsers put limits on data URIs. 

I realize that my problem is very niche, since not many people use jupyter to blog. However, the plotly documentation could be more detailed with respect to plotly and jupyter. 

bcdunbar, thank you for your help. I will try downgrading my version of plotly later today, and report if your solution works.

**Comment by cpsievert** [comment]
@knowitallism @dchen71 could you report your version of pandoc (if you upgrade to pandoc >2.0 it may fix your issues)?

**Comment by cpsievert** [comment]
I think these issues have been mostly resolved in recent versions of Jupyter. And note  that using `embed_notebook()` is not necessarily in Jupyter, just other notebook environments that don't have a dedicated print method for htmlwidgets
