### ISSUE TITLE
[Feature Request] Export data capability

### ISSUE THREAD

**Issue by happyshows** [ropensci/plotly#1140]
Hi,

It would be helpful to be able to export raw data in csv/json format for all types of plotly graph and export exact data for type=table plotly graph.

Thanks.

**Comment by cpsievert** [comment]
You know about `api_create()` and `api_download_grid()`? See `?api`

**Comment by cpsievert** [comment]
If you want to do this without plotly account, you can always get the json with:

```r
p <- plot_ly()
json <- plotly_json(p, jsonedit = FALSE, pretty = TRUE)
cat(json, file = "basic-plot.json")
```

And, if you want to extract specific elements in R:

```r
jsonlite::fromJSON(json)$data
```

**Comment by happyshows** [comment]
will try, thanks.
