### ISSUE TITLE
Allow to set width and height in export using RSelenium [feature request]

### ISSUE THREAD

**Issue by salim-b** [ropensci/plotly#1142]
Since it's now possible to export Plotly charts as SVG using RSelenium it would be _extremely_ useful having a parameter to set the width and height of the exported image. The `width` and `height` set via `layout()` do affect the size of the plot in the browser window openened by RSelenium but are ignored for the downloaded SVG.

I've also tried setting the window size in `RSelenium::rsDriver()` using

```
plotly::export(p = some_plot,
               file = some_file,
               selenium = RSelenium::rsDriver(browser = "chrome",
                                              extraCapabilities = list(
                                                chromeOptions = list(
                                                  args = c("--window-size=1920,1080",
                                                           "--disable-gpu")
                                                )
                                              ),
                                              verbose = FALSE))
```

but this doesn't affect the size of the downloaded plot either. It seems somehow hardcoded to 800x600 pixels. Would be awesome if we could change this!

JFTR:  
~~My current workaround~~ _(wrote a function to use RSelenium instead, see update below)_ to adjust the SVG size consists of calling the JS function `Plotly.downloadImage` after rendering using `htmlwidgets::onRender()` as suggested under the examples in the help of Plotly's `export()`.

Major drawbacks of that method:
1. It tends to freeze RStudio (when using the built-in viewer),
2. it needs manual interaction and
3. it needs to be run from console (otherwise the downloaded SVG is corrupted).

**Update:**  
Meanwhile I figured out how Plotly's `export()` function is currently doing the SVG export using RSelenium and wrote my own function as workaround for the time being. Strangely I couldn't find the relevant execution of the `Plotly.downloadImage()` JS function in the [`export.R`](https://github.com/ropensci/plotly/blob/master/R/export.R) source file, only navigating Selenium to the plot's URL is there:
https://github.com/ropensci/plotly/blob/612264f146432f69776ed41e3b9287e1d3ce02fe/R/export.R#L93

After that, Selenium needs to execute the `Plotly.downloadImage()` function similar to this:
```R
selenium$client$executeScript(
    script = paste0("Plotly.downloadImage(document.getElementById('", htmlwidget_id, "'), ",
                    "{format: 'svg', width: ", width, ", height: ", height, ", filename: '",
                    tools::file_path_sans_ext(x = filename), "'});"),
    args = list(NULL)
  )
```

Now what I'm requesting in this issue is a way to directly set the variables `width` and `height` (and ideally `filename`, too) in Plotly's `export()` function.

Anyway, if someone struggles with this too, I've put my custom SVG export function into this Gist: https://gist.github.com/salim-b/32c4370cee4ac0a3fbfef13a9ce98458 (allows a lot more than just setting the width and height, though.)

**Comment by cpsievert** [comment]
Use the new `orca()` function instead
