### ISSUE TITLE
export to pdf needs control over page size

### ISSUE THREAD

**Issue by talgalili** [ropensci/plotly#1143]
When using `plotly::export` into a pdf file, the output is always an A4 page, leaving most of the output blank. It is important to make sure to clip the PDF into the viewable area so to be able to produce usable vectorized screenshot of a plotly object.

Example:

```
library(plotly)
p <- plot_ly(economics, x = ~pop)
export(p, file = "plotly_export_A4.pdf")
 
```

**Comment by talgalili** [comment]
Update: I see this is due to a problem in webshot ( https://github.com/wch/webshot/issues/28 )
I hope it could get resolved there.

**Comment by cpsievert** [comment]
Closing since this should be resolved in webshot. I should also point out that you can do 'png' export with the plotly.js lib (pdf requires a pro plan):

```r
library(plotly)
library(htmlwidgets)

plot_ly(width = 800, height = 600) %>%
  onRender("function(el, x) {
      var gd = document.getElementById(el.id);
      Plotly.downloadImage(gd, {format: 'png', width: 800, height: 600, filename: 'newplot'});
    }")
```
