### ISSUE TITLE
ggplotly based gantt chart plot takes nearly 1 min

### ISSUE THREAD

**Issue by sachinbanugariya** [ropensci/plotly#1151]
hello,
we implement gantt chart based on ggplotly,
but the issue is its take too much time for give output for plot, takes nearly min 1 min for plot chart.
can anyone suggest how can we improve the responce time of ggplotly gantt chart.
thanks.

**Comment by cpsievert** [comment]
Thanks!

As per our [contributing guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), github issues are reserved for bug reports and feature requests only. So I'll have to close your ticket.

Please use our community forums at [community.plot.ly](http://community.plot.ly/) for posts of the likes.
