### ISSUE TITLE
Fill blob based on x y coordinate in plotly.r e.g. circle. 

### ISSUE THREAD

**Issue by dahalkcc** [ropensci/plotly#1158]
I prepared xy coordinate of the inner ring and outer ring of a tree trunk at a different height where I want to fill the circle with a different color at a different height. 
``p <- plot_ly(x = df$xt, y = df$yt, z = df$zt, colors = colors)%>% 
            add_markers() %>%
                       layout(title = 'vine#27', 
                       scene = list(xaxis = list(title = 'wd1'),
                       yaxis = list(title = 'wd2'),
                       zaxis = list(title = 'height')))
p <- add_trace(p, x = df$a, y = df$b, z = df$c , mode = 'markers', marker = list( size = 1) )
#add number of traces
p
```r
# ![test tree trunk](https://user-images.githubusercontent.com/10645433/33811860-8be5d344-de63-11e7-9444-2ab5a364e543.png) 
```
Anyone can help to fill the inner and outer cirlce with color in plotly r.

**Comment by cpsievert** [comment]
Thanks!

As per our [contributing guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), github issues are reserved for bug reports and feature requests only. So I'll have to close your ticket.

Please use our community forums at [community.plot.ly](http://community.plot.ly/) for posts of the likes.
