### ISSUE TITLE
R Plotly not working with a ggplot chart

### ISSUE THREAD

**Issue by lucasborges210** [ropensci/plotly#1161]
I have made a ggplot graph that almost satisfies my client in 100%. However, an interactive tooltip is necessary and when trying to use plotly, I had not suceeded. I've been trying lot of things but as I'm new in R, things are getting more confusing each try. 

GGPLOT created:
``` r
    install.packages("tidyverse")
    #install.packages("ggplot2")
    install.packages("scales")

    lucas <- expand.grid('cat' = LETTERS[1:5], 'cond'= c(F,T), 'year' = 2016:2017)
    lucas$value <- floor((rnorm(nrow(lucas)))*100)
    lucas$value[lucas$value < 0] <- 0

    library("ggplot2")
    library(scales)

    ggplot() +
    geom_bar(data=lucas, aes(y = value, x = year, fill = cond), stat="identity", position='fill') +
    scale_y_continuous(labels = percent_format()) +
    scale_x_continuous(breaks=c(seq(2016,2017))) +
    facet_grid(cat ~ . , shrink = TRUE, margins = TRUE, switch = "y", scales = "free") +
    theme(strip.text.x = element_text(size = 8, colour = "red", angle = 90)) +
    coord_flip()
```

![rplot](https://user-images.githubusercontent.com/34544334/34002781-b618fa64-e0da-11e7-8c6d-f077abdb9344.png)

Trying to use plotly:
  ``` r
    install.packages("plotly")
    library(plotly)

    p <-   ggplot() +
           geom_bar(data=lucas, aes(y = value, x = year, fill = cond), stat="identity", position='fill') +
           scale_y_continuous(labels = percent_format()) +
           scale_x_continuous(breaks=c(seq(2016,2017))) +
           facet_grid(cat ~ . , shrink = TRUE, margins = TRUE, switch = "y", scales = "free") +
           theme(strip.text.x = element_text(size = 8, colour = "red", angle = 90)) +
           coord_flip()

    ggplotly(p)
```
![plotly](https://user-images.githubusercontent.com/34544334/34002805-c6d9e214-e0da-11e7-9248-b92fbcb43f6a.png)

Packages that I tried to use:

1 -> 
``` r
install.packages("plotly")
```

2 -> 
``` r
if (!require("devtools")) install.packages("devtools")
devtools::install_github('hadley/ggplot2')
```
3 -> 
``` r
devtools::install_github("ropensci/plotly")
```
When I use any of the github's version the first ggplot stops to work. Because it says it can't find scales() anymore.

Not using the coord_flip() makes the plotly shows data however the tooltip doesn't work properly.
 
What do I have to do to plotly works with ggplot in this case?

**Comment by cpsievert** [comment]
This seems to work with the dev version (3). Perhaps you need to load scales `library(scales)`

**Comment by lucasborges210** [comment]
@cpsievert Thanks for helping. I'm new in R. Do i have to remove the plotly previous package before installing the dev version (3)?
And what code do I have to use to install this specific version?
"devtools::install_github("ropensci/plotly")" didnt work the last time I used it.
