### ISSUE TITLE
Continuous scale reset when using toWebGL() with more than ~300+ points

### ISSUE THREAD

**Issue by mmsee** [ropensci/plotly#1163]
I've run into a slightly strange behaviour when using the `toWebGL()` function in plotly. I've made a minimal-ish example using ggplot (and `ggplotly()`).

When using webGL, applying a continuous colour scale to graphs with more than 300+ points, the scale seems to "reset" itself. I've found that I can work around this by applying multiple ggplot layers and then converting to a plotly plot using `ggplotly()` and then passing it to `toWebGL()`.

This seems to also be an issue if calling `plot_ly()` directly. 

```r
library(ggplot2)
library(plotly)

n_pt <- 1000
df <- data.frame("c1"=1:n_pt, "c2"=1:n_pt, "c3"=scale(jitter(1:n_pt, factor = 1, amount = 0.5), center = T, scale = F))

g <- ggplot() +
    geom_point(data=df, aes(x=c1, y=c2, colour=c3)) +
    scale_color_gradient2("", low = "blue", mid = "white", high = "red", na.value="grey")

ggplotly(g) %>%
    toWebGL() %>%
    layout(dragmode="lasso")
```
```r
plot_ly(data = df, x=~c1, y=~c2, color=~c3, mode="markers", type="scatter") %>%
    toWebGL()
```
![image](https://user-images.githubusercontent.com/13144756/34027999-774e52b8-e1b4-11e7-8178-2f3e6fef9d13.png)

**Comment by cpsievert** [comment]
Pretty sure this is fixed now
