### ISSUE TITLE
How to embed in Markdown&html outside Rmd and shiny

### ISSUE THREAD

**Issue by huyingjie** [ropensci/plotly#1165]
My blog uses hexo, which is a static website generator. Each blog post is a Markdown file. `blogdown` developed by Yihui Xie has a lot of errors and I do not have the knowledge to fix them. I do not use shiny. 

How to embed the animation plot generated in a Markdown file? Do you have javascript link similar to bootstrap`<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>`? 

How to get the javascript code containing data which generates the animation plot?

Thank you.

**Comment by cpsievert** [comment]
Thanks!

As per our [contributing guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), github issues are reserved for bug reports and feature requests only. So I'll have to close your ticket.

Please use our community forums at [community.plot.ly](http://community.plot.ly/) for posts of the likes.

**Comment by huyingjie** [comment]
@cpsievert Where is the place to seek for help?
