### ISSUE TITLE
Problem about skipping missing date in candlestick

### ISSUE THREAD

**Issue by haodong** [ropensci/plotly#1166]
Candlestick is often used for trading data. In reality, trading not happened every day. We always get some missing date in our data and that is what we do not want them to show on the plot. Some of them may last for several months.

For example:

![image](https://user-images.githubusercontent.com/8103074/34106760-6734c362-e434-11e7-8c37-2b34d3676589.png)

![image](https://user-images.githubusercontent.com/8103074/34106847-cd3fbb8a-e434-11e7-90ab-4f0b901f58ec.png)

Can you consider to not display those missing date with no data for at least candlestick?

Thanks

**Comment by cpsievert** [comment]
Thanks!

As per our [contributing guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), github issues are reserved for bug reports and feature requests only. So I'll have to close your ticket.

Please use our community forums at [community.plot.ly](http://community.plot.ly/) for posts of the likes.

**Comment by haodong** [comment]
@cpsievert This is indeed a bug. Empty data should not be illustrated.
