### ISSUE TITLE
color coding in a plotly scatter plot interferes with error bars

### ISSUE THREAD

**Issue by ndrubins** [ropensci/plotly#1169]
I also posted this on stackoverflow, but I think this is more appropriate to be posted here.

I have xy data I'd like to plot using R's plotly. The y points have an associated error, of which I'd like to plot the error bars. These points are also associated with a group that has two levels.

Here are the data:
```
set.seed(1)
df <- data.frame(x=rnorm(20),y=rnorm(20),y.err=runif(20,0,0.1))
```

Here, I define the group levels:
```
df$optimal <- F
df$optimal[1] <- T
df$optimal <- factor(df$optimal,levels=c(F,T))
```

And, here's my plotting code:
```
library(dplyr)
library(plotly)
scatter.plot <- plot_ly(type='scatter',mode="markers",color=~df$optimal,x=~df$x,y=~df$y,data=df) %>%
  layout(title="TITLE",xaxis=list(title="X",zeroline=F),yaxis=list(title="Y",zeroline=F))
scatter.plot <- scatter.plot %>% add_trace(scatter.plot,error_y=list(value=df$y.err),data=df,showlegend=F)
```

This results with the error bar of the optimal point being missing. (I tried increasing the error of that point and it doesn't change anything).

This problem does not occur when I do not color by `df$optimal`:
```
scatter.plot <- plot_ly(type='scatter',mode="markers",x=~df$x,y=~df$y,data=df) %>%
  layout(title="TITLE",xaxis=list(title="X",zeroline=F),yaxis=list(title="Y",zeroline=F))
scatter.plot <- scatter.plot %>% add_trace(scatter.plot,error_y=list(value=df$y.err),data=df,showlegend=F)
```

**Comment by cpsievert** [comment]
It seems as though you want to use [array](https://plot.ly/r/reference/#scatter-error_y-array), not [value](https://plot.ly/r/reference/#scatter-error_y-value). This seems to give you what you want

```r
library(plotly)
plot_ly(df, x = ~x, y = ~y) %>% 
  add_markers(color = ~optimal, error_y = ~list(array = y.err))
```

(please link to this comment on the SO post)
