### ISSUE TITLE
Feature Request: Draggable Points

### ISSUE THREAD

**Issue by hherrada** [ropensci/plotly#1170]
Draggable points seem to be possible in plotly (Please refer to [this example](http://bl.ocks.org/niclasmattsson/7bceb05fba6c71c78d507adae3d29417)). The feature would be awesome for Shiny apps. Would you consider adding something like this in the package? Thank you!

**Comment by cpsievert** [comment]
This would have to be implemented on the plotly.js level, and [it seems they have other priorities](https://github.com/plotly/plotly.js/issues/1537). 

Please get in touch if you'd like to support/influence development -- https://plot.ly/products/consulting-and-oem/
