### ISSUE TITLE
access chunk fig.height when knitting in shiny app

### ISSUE THREAD

**Issue by vnijs** [ropensci/plotly#1171]
I'm using knitr in a shiny app (small example below). Unfortunately, ggplotly is not picking up the size of the ggplot object determined by the knitr chunk. Is there a way to access that information and get ggplotly to use it? 

    library(shiny)
    library(plotly)
    
    getdeps <- function() {
      htmltools::attachDependencies(
        htmltools::tagList(),
        c(htmlwidgets:::getDependency("plotly", "plotly"))
      )
    }
    
    chunk <- "
    ```{r fig.width = 4, fig.height = 6, echo = FALSE}
    p <- ggplot(mtcars, aes(cyl, mpg)) + geom_point()
    my_render(ggplotly(p))
    ````
    "
    
    scrub <- function(x) {
      gsub("&lt;!&ndash;html_preserve&ndash;&gt;", "", x) %>%
      gsub("&lt;!&ndash;/html_preserve&ndash;&gt;", "", .)
    }
    
    my_render <- function(object, ...) {
      object$elementId <- NULL
      plotly::renderPlotly(object)
    }
    
    ui = fluidPage(
      htmlOutput("knitted"),
      getdeps()
    )
    
    server = function(input, output, session) {
      output$knitted <- renderUI({
        knitr::knit2html(text = chunk, fragment.only = TRUE, stylesheet = "") %>%
          scrub() %>%
          HTML()
      })
    }
    
    shinyApp(ui = ui, server = server)
    
Screenshot:

![image](https://user-images.githubusercontent.com/2998956/34450823-46b54ed4-ecc9-11e7-8d41-eaa8a5e0da34.png)

**Comment by cpsievert** [comment]
I believe you want `knitr::opts_chunk$get("fig.width")`, but make sure you specify in pixels!

Note there is now a way to specify height/width in shiny https://github.com/ropensci/plotly/blob/master/inst/examples/shiny/ggplotly_sizing/app.R

**Comment by vnijs** [comment]
Thanks for the pointer to `knitr::opts_chunk$get("fig.width")` @cpsievert ! That was very close to what I was looking for (`knitr::opts_current$get('fig.height')`). When I use this approach the plot height is indeed changed, however, as you notice in the screen shot below, the 2nd chunk cuts-off the plot in the 1st chunk. Any idea how to address that?
  
![image](https://user-images.githubusercontent.com/2998956/41134569-e67d6812-6a81-11e8-9456-206b8ebd5bbd.png)

    library(shiny)
    library(plotly)
    
    getdeps <- function() {
      htmltools::attachDependencies(
        htmltools::tagList(),
        c(htmlwidgets:::getDependency("plotly", "plotly"))
      )
    }
    
    chunk <- "
    ```{r fig.width = 4, fig.height = 7, echo = FALSE}
    height <- knitr::opts_current$get('fig.height') * 96
    p <- ggplot(mtcars, aes(cyl, mpg)) + geom_point()
    my_render(ggplotly(p, height = height))
    ````
    
    ```{r fig.width = 4, fig.height = 3, echo = FALSE}
    height <- knitr::opts_current$get('fig.height') * 96
    p <- ggplot(mtcars, aes(cyl, mpg)) + geom_point()
    my_render(ggplotly(p, height = height))
    ````
    "
    
    scrub <- function(x) {
      gsub("&lt;!&ndash;html_preserve&ndash;&gt;", "", x) %>%
        gsub("&lt;!&ndash;/html_preserve&ndash;&gt;", "", .)
    }
    
    my_render <- function(object, ...) {
      object$elementId <- NULL
      plotly::renderPlotly(object)
    }
    
    ui = fluidPage(
      htmlOutput("knitted"),
      getdeps()
    )
    
    server = function(input, output, session) {
      output$knitted <- renderUI({
        knitr::knit2html(text = chunk, fragment.only = TRUE, stylesheet = "") %>%
          scrub() %>%
          HTML()
      })
    }
    
    shinyApp(ui = ui, server = server)

**Comment by cpsievert** [comment]
@vnijs you can set the height/width by using those arguments for the first plot I believe, although that might be a nice community contribution!
