### ISSUE TITLE
Not to lose interactivity in heatmap subplot when height is small

### ISSUE THREAD

**Issue by danielcanueto** [ropensci/plotly#1173]
I'm trying to make a subplot where there are line plots above and a heat map below which gives information about the relationship between these line plots. Unfortunately, the interactivity of the heatmap is lost when scaling it to under 0.22. 

![2018-01-04_09-49-32](https://user-images.githubusercontent.com/21126465/34556197-b1df5a04-f135-11e7-9eba-7552decf210a.png)

Interactivity is not lost when trying other examples with different subplot scaling like the one here: https://plotly-book.cpsievert.me/arranging-htmlwidgets.html

This heatmap interactivity is very important, as regions below 0.05 are of special interest for potential users of this figure. 

I hope to have explained well the problem. If necessary, I can provide reproducible code.

Thanks!

**Comment by cpsievert** [comment]
Without a reproducible example, the best I can say is that you should checkout the newish `layout.hoverdistance` attribute

![screen shot 2018-02-07 at 4 23 59 pm](https://user-images.githubusercontent.com/1365941/35944806-6f2328fe-0c23-11e8-8e1c-1ab153df1753.png)
