### ISSUE TITLE
Filling under the lines for 3D-Plots in R 

### ISSUE THREAD

**Issue by turgutrcaglar** [ropensci/plotly#1179]
I would like to plot a 3D-Line Plot with Plotly in R for time-series and fill the areas under the every lines. I have an example code here.

```r
library(plotly)

dens <- with(diamonds, tapply(price, INDEX = cut, density))
data <- data.frame(
  x = unlist(lapply(dens, "[[", "x")),
  y = unlist(lapply(dens, "[[", "y")),
  cut = rep(names(dens), each = length(dens[[1]]$x)))

p <- plot_ly(data, x = ~cut, y = ~x, z = ~y, type = 'scatter3d', mode = 'lines', color = ~cut)
p
```
with this code I can produce this plot

<img width="1280" alt="bildschirmfoto 2017-12-16 um 19 01 58" src="https://user-images.githubusercontent.com/29779996/34908909-30cb7fa0-f898-11e7-97bd-ba7fe4a332d8.png">

To fill the areas I have already tried setting surfaceaxis=0, 1, or 2 and they produced wrong fillings.

Here is the 3D-Plotly with wrong filling
<img width="1280" alt="bildschirmfoto 2017-12-16 um 19 11 09" src="https://user-images.githubusercontent.com/29779996/34908920-6d661a6a-f898-11e7-803c-b4c8c6f1f40f.png">

To make an area plot with interior filling for 2D  man can set "fill" to "tonexty". But it does not work for 3D-Plots

Is it a bug for 3D-Plots or am I missing something? Thanks in advance

**Comment by cpsievert** [comment]
'scatter3d' doesn't yet support fill attributes...this would have to be added at the plotly.js level. Moving the issue here https://github.com/plotly/plotly.js/issues/2352

**Comment by cpsievert** [comment]
By the way, you can achieve something similar with 3d surfaces https://plot.ly/python/3d-filled-line-plots/

**Comment by turgutrcaglar** [comment]
I have already seen and tried that.  I think, it does not  fill under the lines. If you look at the plot carefully for the lines "China" and "India", you can notice it. If the lines are linear during the x-axis, they can be filled  with "tonexty" in R without problem. By the way, thank you for your interest.

**Comment by ak868308** [comment]
Anyone found solution please update here :( for plotly.js

**Comment by R-Lionheart** [comment]
Solution would be appreciated!
