### ISSUE TITLE
auto scaling bar charts in plotly

### ISSUE THREAD

**Issue by Awais-Hassan-DS** [ropensci/plotly#1180]
Hi,

I have to visualize a plotly bar chart in main panel which varies in width and height depending upon input selected for x-axis and y-axis. I want to resize chart depending upon selected input i.e. x-axis and y-axis should re-scale automatically.

Thanks

**Comment by cpsievert** [comment]
Thanks!

As per our [contributing guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), github issues are reserved for bug reports and feature requests only. So I'll have to close your ticket.

Please use our community forums at [community.plot.ly](http://community.plot.ly/) for posts of the likes.
