### ISSUE TITLE
How to use Rscript to open plotly object at Mac terminal?

### ISSUE THREAD

**Issue by yichunsung** [ropensci/plotly#1183]
hi, I have a question. I want to use Mac termial to run a R file to show my plotly object.
However, I can't show my plotly object.

can anyone give me some hint?

**Comment by shrektan** [comment]
Try `Rscript -e "source('file.R')"`

This is a general question and stackoverflow will be a better place to ask.

**Comment by shrektan** [comment]
Or you can simple type `R` and run whatever commands you want interactively.

**Comment by cpsievert** [comment]
Thanks!

As per our [contributing guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), github issues are reserved for bug reports and feature requests only. So I'll have to close your ticket.

Please use our community forums at [community.plot.ly](http://community.plot.ly/) for posts of the likes.
