### ISSUE TITLE
jitter does not place outlier correctly in boxplot when just one outlier

### ISSUE THREAD

**Issue by bklingen** [ropensci/plotly#1189]
If there is just one outlier in your data and you are drawing a boxplot using jitter, the outlier is printed in the upper left corner (barely visible), not at all where it should be. If there are two outliers, everything works fine.

```{r}
## plots oulier of 20 half visible in upper left corner
plot_ly(y = ~c(1:10, 20), type="box", jitter=0.1)
## works fine with no jittering
plot_ly(y = ~c(1:10, 20), type="box")
## Jittering works fine with two outliers
## plots outliers 20 and 21 right where they should be, with a little jitter
plot_ly(y = ~c(1:10, 20, 21), type="box", jitter=0.1)
```
The x coordinate ofthe outlier seems to be wrong when using jitter with a single outlier.

Thanks,
Bernhard

**Comment by cpsievert** [comment]
Thanks! Moving to https://github.com/plotly/plotly.js/issues/2061
