### ISSUE TITLE
X-Axis Disappears in api_create() 

### ISSUE THREAD

**Issue by m-champion** [ropensci/plotly#1197]
Greetings. 
 
I have been having an issue  recently where the x-axis labels have been disappearing from graphs I've created in R once uploaded using api_create(). I've repeated this numerous times, and it seems entirely reproducible. I've supplied the short R code that highlights the issue. This x-axis disappearance occurs whether or not the ggplotly() function is called before api_create(). 

I've attempted to specify x-axis markers in ggplotly() as well before uploading, but these are stripped during upload. I've also removed all theme values, and the x-axis is still removed.  I've changed the geom between bar() and col() to the same effect. 

Here is the graph as intended: 
https://drive.google.com/file/d/1lQDq98FwYMhS0zxttrrZnOpU3T8JeHar/view?usp=sharing

Here is the graph after upload: 
https://plot.ly/~m_champion/102/ 

---

Code Example

```r
example <- ggplot(mtcars, aes(x = rownames(mtcars), y = mpg)) + 
  geom_col() + 
  #geom_bar(stat = "identity") +  #X-Axis disappears in both geom_col() and geom_bar()
  ggtitle("Cars by MPG") + 
  ylab("Miles per Gallon") + 
  xlab("Car Make and Model") 

example.plotly <- ggplotly(example)
api_create(example.plotly, "Example/example")
```

**Comment by cpsievert** [comment]
Seems to be working if you upgrade to the dev version https://plot.ly/~cpsievert/22934/

```r
devtools::install_github('ropensci/plotly')
```

**Comment by cpsievert** [comment]
Huh, it seems "data array" attributes in the layout  are not being rendered properly on our cloud service, here's a more minimal example:

```r
library(plotly)

p <- plot_ly(x = c("a", "b"), y = c(1, 2)) %>%
  add_bars() %>%
  layout(
    xaxis = list(
      ticktext = c("AAA", "BBB"), tickvals = c(0, 1)
    )
  )

api_create(p)
```

Looking into it...

**Comment by m-champion** [comment]
Thanks for taking a look! And apologies on the gruff language - I should not comment before coffee...

**Comment by cpsievert** [comment]
https://github.com/plotly/streambed/issues/10654

**Comment by cpsievert** [comment]
I've done everything I can do here. It's now up to plotly's backend team to fix this issue.

**Comment by michaelbabyn** [comment]
@cpsievert , I saw the above issue when working on plotly documentation and the above example works if I use `list` instead of `c` for ticktext and tickvals. Then I found [this issue on streambed](https://github.com/plotly/streambed/issues/8028) which decided that they wouldn't support *src references for layout attributes.

So the issue is that plotly.R shouldn't src-ify layout attributes.
