### ISSUE TITLE
On WindowsOS env, when specific Japanese being, nothing is output

### ISSUE THREAD

**Issue by cuttlefish44** [ropensci/plotly#1199]
Thank you for your work.

On Windows OS environment, I think some Japanese word prevent output.  

I researched into the problem and found "能" is one of them.
It is a major Japanese word and I feel plotly R can't support Japanese completely.

```r
d1 <- dplyr::mutate(iris, Species = forcats::fct_collapse(Species, 日本語 = "setosa", 環境 = "versicolor", 確認 = "virginica"))
d2 <- dplyr::mutate(iris, Species = forcats::fct_collapse(Species, 日本語 = "setosa", 環境 = "versicolor", 能 = "virginica"))

# no problem
plotly::plot_ly(data = d1, x = ~Sepal.Length, y = ~Petal.Length, color = ~Species)

# nothing is output
plotly::plot_ly(data = d2, x = ~Sepal.Length, y = ~Petal.Length, color = ~Species)
```

**Comment by cpsievert** [comment]
Hmm, I can't replicate on my mac, so it'd be great if someone could help me identify the source of the issue

**Comment by dchen71** [comment]
I'm on Windows 7 and I can see the character just fine. I am using plotly version 4.7.1.

**Comment by cuttlefish44** [comment]
Thanks for your response.

This problem still remains to be solved on my two machines, windows 7 and vista , but maybe it depends on my execution environments.

Thank you for your time.
