### ISSUE TITLE
add_trace + add_text shows text for main points

### ISSUE THREAD

**Issue by dchen71** [ropensci/plotly#1201]
I am trying to make a scatterplot with text besides the points. When I add in traces for other points in the same plot, the text is only around the original plotly plot. If I were to use add_text, wouldn't I expect all of the traces to also show the text by the points?

    data(iris)
    plot_ly(iris, x = ~Sepal.Length, y = ~Sepal.Width, color = ~Species, text = ~row.names(iris)) %>%
        add_trace(x = ~Petal.Length, y = ~Petal.Width, color = ~Species, text = ~Species) %>%
        add_text(textposition = 'top right')

**Comment by cpsievert** [comment]
You'r x/y mapping is different in each layer:

```r
data(iris)
plot_ly(iris, x = ~Sepal.Length, y = ~Sepal.Width, color = ~Species, text = ~row.names(iris)) %>%
    add_trace(text = ~Species) %>%
    add_text(textposition = 'top right')
```

Please route future questions to http://community.plot.ly/ or SO
