### ISSUE TITLE
[Feature request] Supporting treemaps in ggplotly

### ISSUE THREAD

**Issue by pierreroudier** [ropensci/plotly#1208]
Just a feature request, as opposed to a bug report: the support of `geom_tree` from [the `treemapify` package](https://github.com/wilkox/treemapify) in `ggplotly` would be neat.

Example below:

```
library(ggplot2)
library(treemapify)
library(plotly)

p <- ggplot(G20, aes(area = gdp_mil_usd, fill = hdi)) +
  geom_treemap()

# Print static plot
print(p)

ggplotly(p)
```

Cheers,

**Comment by cpsievert** [comment]
Added to #566
