### ISSUE TITLE
Regression bugs in plotly since updating to 1.32.0

### ISSUE THREAD

**Issue by daattali** [ropensci/plotly#1211]
2/3 of these issues are already mentioned in https://github.com/ropensci/plotly/pull/1178 but since that PR is merged, it would get lost there.

1. When the initial dragmode is zoom and I manually click on lasso selection, the plot stretches horizontally a bit (see GIF below)
  ![](https://user-images.githubusercontent.com/952340/35179284-8cab405e-fd65-11e7-8b57-65320a53d878.gif)

2. Something in selecting/adding points is broken. Here is a GIF of what selecting some points and trying to add the same points back as a different colour looks like:
  ![plotlybugs](https://user-images.githubusercontent.com/952340/35415469-b62c9db4-01f3-11e8-9091-04c090a51d02.gif)
  This does not happen with the current CRAN version of plotly. I assume this doesn't always happen, otherwise it would be noticed and fixed by now. I cannot provide reproducible code in this issue, but @cpsievert has access to code that has this problem. The repo at https://github.com/daattali/sievert-oil is an example of this issue

3. Points aren't showing in RStudio. Using the same app from the private repo https://github.com/daattali/sievert-oil using the CRAN version the plot works absolutely fine within RStudio, but with the current github version, nothing shows up in the plot within RStudio Viewer.

**Comment by cpsievert** [comment]
For (3), can you please report the console errors you are seeing?

**Comment by daattali** [comment]
There are no console errors. The axes and the grid and the legend show up,
only the points do not.

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

Want to improve your Shiny skills? Try my new interactive, online video
course *Shiny Case Studies*
<https://www.datacamp.com/courses/building-web-applications-in-r-with-shiny-case-studies>

**Comment by cpsievert** [comment]
Renders in RStudio on my mac. I assume you're on Windows? Does it render on in IE/Edge? Do these points render in IE/Edge? https://codepen.io/cpsievert/pen/oqvjXa

**Comment by daattali** [comment]
You're correct - this is on Windows. You're also right that the points
don't show up in IE11 (but they also had problems using CRAN version). I do
not have Edge to test on.

The link you sent me does render in IE11.

I would consider issues 1+2 more serious than 3 because lots of things
don't work in the rstudio browser and IE, it's sort of expected for
anything non standard



---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

Want to improve your Shiny skills? Try my new interactive, online video
course *Shiny Case Studies*
<https://www.datacamp.com/courses/building-web-applications-in-r-with-shiny-case-studies>

**Comment by cpsievert** [comment]
Ok, unfortunately I haven't been able to replicate (1) or (2). Do these problems happen universally (e.g. different browsers and states)?

**Comment by nicolaskruchten** [comment]
I wonder if some of this stuff won't have been fixed by https://github.com/plotly/plotly.js/pull/2437 ...

**Comment by daattali** [comment]
1+2 happen on chrome as well. Strange you can't replicate

**Comment by cpsievert** [comment]
@daattali just upgraded to plotly.js 1.35.0 -- let me know if that helps/hurts anything

**Comment by daattali** [comment]
@cpsievert latest version does fix the first issue with the plot dimensions getting slightly resized.

But the other issues are still appearing, LASSOing points causes points to jump around while the mouse is dragging, and new points are appearing in a place they shouldn't be when done. Using the same repo that you have (sorry for anyone else here, only Carson and I can access that code) I get this now (Chrome on Win7)
![plotlybugs](https://user-images.githubusercontent.com/952340/37124146-123eed44-2235-11e8-8f6c-2425fd66f545.gif)

**Comment by daattali** [comment]
I'm closing this as I opened individual issues with short reproducible code samples.

**Comment by cpsievert** [comment]
> after another couple hours of debugging, it seems that when I don't use `toWebGL()` things look and work much better

yea, plotly.js devs recently completely rewrote the webgl logic, which is why we're running into headaches -- you can always use `scatter` (SVG) over `scattergl` (canvas) and things should be less buggy, but it won't be as performant

> seems like these issues are happening even for the most basic plots when converted to webgl.

Huh, I can't replicate either of these issues. If you get the same behavior on this codepen, could you please post a [plotly.js issue](https://github.com/plotly/plotly.js) with a screen-recording (and tag me)?

https://codepen.io/cpsievert/pen/oqvjXa
