### ISSUE TITLE
Regression bug: LASSOing has become significantly slower

### ISSUE THREAD

**Issue by daattali** [ropensci/plotly#1216]
This was introduced some time between 2018-01-26 to 2018-03-07

Here's a plot of 10,000 points:

```
df <- data.frame(x = runif(10000, min = 0, max = 20000), y = runif(10000, min = 0, max = 20000))
plot_ly(df, x = ~x, y= ~y) %>% add_markers()
```

Running this 2 months ago, I was able to LASSO points with no problem. Now it's essentially unusable.

Converting it to `toWebGL()` helps, but is still much slower than it was before.

See video below for comparisons

![calculatingkindgar-max-14mb](https://user-images.githubusercontent.com/952340/37134557-115afb2a-2267-11e8-99b8-5c6bec06ca9d.gif)

(related to #1211)

**Comment by cpsievert** [comment]
Strange. Again, this might be Windows-specific weirdness.

To help isolate the issue, it would be great if you could (try to) replicate these issues with pure plotly.js. I have a codepen here where you can switch `scatter` to `scattergl` to switch from SVG to WebGL. Also, feel free to play with different versions (version 1.33.0 was when the scattergl rewrite happened)  https://codepen.io/cpsievert/pen/WzNvVN

PS. I'm fairly sure lasso selection in scatter has always been sluggish with this many points. Here is a minimal example with plotly.js 1.30.0 (Aug 21, 2017). When I compare that to 1.35.0 (current version), there isn't much of a noticeable difference -- https://codepen.io/cpsievert/pen/wmvaeQ

**Comment by daattali** [comment]
Thanks for providing the biolerplate js code, even though it's that simple it would have taken me a long time to come up with it as I'm not familiar at all with plotly.js

**Comment by cpsievert** [comment]
Closing as this seems fixed https://github.com/plotly/plotly.js/issues/2459#issuecomment-392272363

**Comment by daattali** [comment]
Yep it's better in a browser! Within RStudio it's agonizingly slow, but in a browser it's all good now
