### ISSUE TITLE
static Hover box position 

### ISSUE THREAD

**Issue by haohua** [ropensci/plotly#1222]
Hi, 

is it possible to make the hover box at the top-right corner of the plot, instead of right next to the data point i click? 
A static hover box position is very helpful for me to read hover information in a stacked bar plot. 
It will be even greater if i can combine all the hover info from all stacked components into one box. 

Thank you

**Comment by cpsievert** [comment]
@haohua this kind of feature would be best implemented on the plotly.js level...feel free to open an issue there -- https://github.com/plotly/plotly.js/issues/new
