### ISSUE TITLE
Adding ggplotly() to the end of a pipe operation

### ISSUE THREAD

**Issue by ratnanil** [ropensci/plotly#1229]
I'm very used to the `ggplot ` syntax and generate most plots with that library. Now and again, I'd like to turn my `ggplot `into a `plotly `plot. `ggplotly ()`works great for this.
```r
data("diamonds")

library(ggplot2)
library(plotly)

data("cars")

p <- ggplot(diamonds,aes(carat,price)) +
  geom_point()

p %>%
  ggplotly()
```

It would be really elegant if one could add ggplotly() at the very end via piping. It nearly works, as shown in the code above. The following code however produces an error:

```
ggplot(diamonds,aes(carat,price)) +
  geom_point() %>%
  ggplotly()

#> Error in UseMethod("ggplotly", p) : 
#> no applicable method for 'ggplotly' applied to an object of class "c('LayerInstance', 'Layer', 'ggproto', 'gg')"
```

**Comment by mschilli87** [comment]
How about something like this (untested)? 

```r
ggplot(diamonds,aes(carat,price)) %>%
  + geom_point() %>%
  ggplotly()
```

**Comment by cpsievert** [comment]
If it were possible to make `%>%` into a generic function, this might be doable, but I don't think infix operators are allowed to be generic. If that is in fact true, I don't think this will be possibility

**Comment by BenoitFayolle** [comment]
My workaround, adding parentheses around the expression before piping to `ggplotly()`:
( ggplot(diamonds,aes(carat,price)) +
   geom_point() ) %>%
   ggplotly()

**Comment by gdmcdonald** [comment]
You can but it needs to have curly braces {} around the ggplot, like this:

```r
diamonds %>%
{ggplot(.,aes(carat,price)) +
  geom_point()} %>%
  ggplotly()
```
