### ISSUE TITLE
Issue supplying rgba() codes to color arg

### ISSUE THREAD

**Issue by viniciusvgp** [ropensci/plotly#1233]
When using `hoveron='fills'` the custom hover text is not drawn. The hover shows only the split/fill variable.

Code example:
```r
library(plotly)
data.frame(AA=c(2,3,3,2,NA, 6,7,7,6,NA),
           BB=c(2,2,3,2,NA, 6,6,7,6,NA),
           CC=c(rep('abc', 5), rep('xyz', 5)),
           LL=c(rep('A', 5), rep('B', 5))) %>%
    plot_ly() %>%
             add_trace(x=~AA,
                       y=~BB,
                       text=~paste('<br> <b>Example</b> of <em>custom</em> hover text <br>', LL, '<br>', CC, '<br>.'),
                       split=~LL, 
                       mode="lines", 
                       fill="toself", 
                       hoveron='fills',
                       type="scatter", 
                       color = I(c(rep(toRGB("black", 1), 5),
                                   rep(toRGB("red", 1), 5)))
                       )
```

Result: 
[![wrong hover][1]][1]

[1]: https://i.stack.imgur.com/jQOGJ.png

**Comment by cpsievert** [comment]
I believe you want `fill`, not `fills`?

**Comment by cpsievert** [comment]
Interestingly enough this example is currently broken in the development version, so I will keep this open

**Comment by viniciusvgp** [comment]
It is 'fills' with 's'. From the code, it seems correct:

     R/layers2traces.R:29:    if (identical("fills", hover_on(x))) {
     R/layers2traces.R:915:  if (identical(hover_on(dat), "fills")) {

**Comment by cpsievert** [comment]
Should work as you'd expect now, thanks!
