### ISSUE TITLE
plotly was broken by ggplot2 update

### ISSUE THREAD

**Issue by dorayin12** [ropensci/plotly#1247]
Hello. This morning I updated ggplot2 as suggested by R and reinstalled plotly after that. But plotly didn't work but gave me an error message:
```
Error: package or namespace load failed for ‘plotly’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘data.table’
```
I tried to reinstall data.table but neither the install.packages command nor installation from resource worked. The error was:
```
Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘data.table’
  These will not be installed
```
I'm using Windows 10 and R Studio 1.1.423. Thanks!

**Comment by cpsievert** [comment]
Unfortunately this isn't a problem that I can fix in plotly. Sounds like you need the windows requirements  for installing packages from source -- https://support.rstudio.com/hc/en-us/articles/200486498-Package-Development-Prerequisites
