### ISSUE TITLE
Hide x-axis label in a violin plot with a single variable

### ISSUE THREAD

**Issue by ndrubins** [ropensci/plotly#1249]
Hi,

I just installed the latest plotly R package (`devtools::install_github("ropensci/plotly")`).

I trying to generate a violin plot for a single variable and I would like to suppress the x-axis label.

I tried:
```
library(dplyr)
library(plotly)

df <- read.csv("https://raw.githubusercontent.com/plotly/datasets/master/violin_data.csv")
plot_ly(y =~ df$total_bill,type = 'violin',
        box = list(visible = T),
        meanline = list(visible = T)) %>% 
  layout(xaxis = list(title = ""),yaxis = list(title = "Total Bill",zeroline = F))

```

But I'm getting `"trace 0"` as the x-axis label.

I tried playing around with the `x0` parameter but couldn't get a violin with no x-axis label.

Any idea?

**Comment by mschilli87** [comment]
@ndrubins: I think this would be better suited as a stackoverflow question than as a github issue.
