### ISSUE TITLE
scatter plot matrix trace

### ISSUE THREAD

**Issue by bcdunbar** [ropensci/plotly#1261]
`type = 'splom'` added in _Plotly.js v1.36.0_. https://codepen.io/bcd/pen/gzqXbm

Currently, (assuming the syntax is right) R gives a different output than expected.

```r
plot_ly(
  type = 'splom',
  dimensions = list(
    list(values=c(1,2,3), label="A"),
    list(values=c(2,5,6), label="B")
  )
)
```
![splom-r](https://user-images.githubusercontent.com/8393928/40414096-bdeb30e6-5eba-11e8-82d6-df12cf0f1477.PNG)

**Comment by cpsievert** [comment]
@bcdunbar I'll add a fix so that you don't have to clear the axes, but it will have to be next week
