### ISSUE TITLE
Radio buttons

### ISSUE THREAD

**Issue by RB000** [ropensci/plotly#1267]
Hello 
is there any way to add some cotrols using radio buttons to plotly charts in R !

**Comment by cpsievert** [comment]
Thanks!

As per our [contributing guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), github issues are reserved for bug reports and feature requests only. So I'll have to close your ticket.

Please use our community forums at [community.plot.ly](http://community.plot.ly/) for posts of the likes.
