### ISSUE TITLE
Shiny: axis limits not updated in `event_data` after plot is redrawn automatically

### ISSUE THREAD

**Issue by dmhv** [ropensci/plotly#1284]
Hey everybody,

I have a plotly graph with an additional line, representing a threshold that can be set by the user, and more processing/plotting logic that depends on Shiny receiving the X axis limits if the user zooms into the plotly graph. Found what appears to be a small glitch, unless it's me who's doing something wrong :)

Current behavior and steps to reproduce:

1. select a region in the plotly graph; observe the x-limits shown in the bottom output have changed;
2. adjust the slider value; observe that the graph is back to its original x-limits, but the values seen by Shiny are still those after step (1).

Expected behavior: when the limits of the plot change, the values in `event_data` should reflect that.

Reproducible example (sorry, it's not really a tiny one):
```r
library(shiny)
library(plotly)

hline <- function(y = 0, color = "red") {
  list(
    type = "line", x0 = 0, x1 = 1, xref = "paper",
    y0 = y, y1 = y, line = list(color = color)
  )
}

df <- data.frame(x = runif(100), y = runif(100))

ui <- fluidPage(
   plotlyOutput('plt'),
   sliderInput('val', "Value", 0, 1, 0.5, 0.1),
   textOutput('xlim_txt')
)

server <- function(input, output) {
   
   output$plt <- renderPlotly({
      p <- plot_ly(df, x = ~x, y = ~y, type = 'scatter', mode = 'markers', source = "foo") %>% 
        layout(shapes = list(hline(input$val)))
      p$elementId <- NULL
      p
   })
   
   xlim <- reactive({
     zoom <- event_data("plotly_relayout", "foo")
     if(is.null(zoom) || names(zoom[1]) %in% c("xaxis.autorange", "width")) {
       'NONE'
     } else {
       c(zoom$`xaxis.range[0]`, zoom$`xaxis.range[1]`)
     }
   })

   output$xlim_txt <- renderText(paste('X axis limits:', xlim()))
}

shinyApp(ui = ui, server = server)
```
Thanks in advance for looking into this!

Kind regards,
Dmitrij

**Comment by cpsievert** [comment]
I don't think I'd classify this as a bug, but I can certainly see how it's unclear why it's "expected" behavior. I'd consider this as "motivation" for https://github.com/ropensci/plotly/issues/1390 and https://github.com/ropensci/plotly/issues/1282 (expose a plotly_redraw event?)

Anyway, when you change the slider value, plotly does a full redraw of the plot, which is different from a relayout event. Since there are two different events that can have an impact on the range, you could keep track of the range's state through a `reactiveValue`:

```r
library(shiny)
library(plotly)

hline <- function(y = 0, color = "red") {
  list(
    type = "line", x0 = 0, x1 = 1, xref = "paper",
    y0 = y, y1 = y, line = list(color = color)
  )
}

df <- data.frame(x = runif(100), y = runif(100))

ui <- fluidPage(
  plotlyOutput('plt'),
  sliderInput('val', "Value", 0, 1, 0.5, 0.1),
  textOutput('xlim_txt')
)

server <- function(input, output) {
  
  output$plt <- renderPlotly({
    plot_ly(df, x = ~x, y = ~y, type = 'scatter', mode = 'markers', source = "foo") %>% 
      layout(shapes = list(hline(input$val)))
  })
  
  xlim <- reactiveVal("NONE")
  
  observeEvent(event_data("plotly_relayout", "foo"), {
    zoom <- event_data("plotly_relayout", "foo")
    print(zoom)
    if (all(c("xaxis.range[0]", "xaxis.range[1]") %in% names(zoom))) {
      xlim(c(zoom$`xaxis.range[0]`, zoom$`xaxis.range[1]`))
    } else {
      xlim("NONE")
    }
  })
  
  observeEvent(input$val, {
    xlim("NONE")
  })
  
  output$xlim_txt <- renderText(paste('X axis limits:', xlim()))
}

shinyApp(ui = ui, server = server)
```

You could also replace `"NONE"` with the default range, if you know it ahead of time
