### ISSUE TITLE
geom_GeomLabel() not yet implemented in plotly

### ISSUE THREAD

**Issue by mcercone77** [ropensci/plotly#1291]
---

Thanks for all the work you do on this awesome package. I'm trying to add edge labels on a network graph. I'm expecting to see something like this (created solely using ggplot2):

![image](https://user-images.githubusercontent.com/38894378/41377157-7641e2ee-6f18-11e8-834f-6289b5795f2e.png)
 
This isn't a _huge_ deal, but this visualization looks more slick in ggplotly.

```r
ggplotly(ggplot(my_network, aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_edges(color = "black", aes(size = frequency)) +
  geom_nodes(color = "gold", size = 15) +
  geom_nodetext(aes(label = vertex.names),
                fontface = "bold") +
  geom_edgetext(aes(label = frequency), color = "white", fill = "grey25",
                      box.padding = unit(1, "lines")) +
  theme(axis.text = element_blank(),
        axis.title = element_blank(),
        panel.background = element_rect(fill = "grey25"),
        panel.grid = element_blank()))
```

**Comment by cpsievert** [comment]
Thanks! We already have a note of this here #348, but this would be a great community contribution! http://plotly-book.cpsievert.me/translating-custom-ggplot2-geoms.html
