### ISSUE TITLE
boxplot: specification color bounding box 

### ISSUE THREAD

**Issue by lcougnaud** [ropensci/plotly#1292]
I would like to set the color of the line bounding the box of a boxplot.
It is mentioned in the documentation that the 'color' parameter via the 'line' parameter is available for this purpose.
However, it seems that this color overwrites the filling color of the boxplot when used in combination with the 'color' parameter:
```r
data <- data.frame(x = rep(c("A", "B"), each = 5), y = rnorm(10))
plot_ly(data) %>% 
add_boxplot(x = ~x, y = ~y, color = ~x, colors = c('A' = "blue", 'B' = "red")

```
![newplot](https://user-images.githubusercontent.com/15339154/41852785-63b40864-788c-11e8-9dc0-c59d2cff8f8b.png)
```r
data <- data.frame(x = rep(c("A", "B"), each = 5), y = rnorm(10))
plot_ly(data) %>% 
add_boxplot(x = ~x, y = ~y, color = ~x, colors = c('A' = "blue", 'B' = "red"), line = list(color = "black"))
```
![newplot 1](https://user-images.githubusercontent.com/15339154/41852801-6eb1d78c-788c-11e8-8771-846f6296e160.png)
Is there an alternative specification to obtain colored boxplot based on a variable, with line set to a fixed color?
Thanks in advance

**Comment by cpsievert** [comment]
Yea, this is related to a bug in `plot_ly()`. You should be able to do this with

```r
plot_ly(data) %>% 
    add_boxplot(x = ~x, y = ~y, color = ~x, colors = c('A' = "blue", 'B' = "red"), stroke = I("black"))
```

Follow #1388 for progress
