### ISSUE TITLE
geom_path cannot be coloured

### ISSUE THREAD

**Issue by devktpx** [ropensci/plotly#1294]
I have a shiny app with server.R and ui.R.

This is the code in server.R:

```
library(shiny)
library(ggplot2)
library(plotly)

server <- shinyServer(function(input, output, session) {

dat=data.frame(mycolA=c(1,2,3,4), mycolB=c(12,13,16,10), mycolC=c(330,510,290,530))

    p=ggplot(dat,aes(x=mycolB, y=mycolC)) +
    geom_path(aes(colour=mycolA)) # <----------------------------------
    #geom_path() 

    output$myggplotwithplotly=renderPlotly({
    p
    })

    output$myggplotonly=renderPlot({
        p
    })

})
```

This is the code in ui.R:

```
library(shiny)
library(ggplot2)
library(plotly)

ui <- shinyUI(fillPage(
fillRow(
plotlyOutput("myggplotwithplotly", height="100%"), plotOutput("myggplotonly", height="100%")
  )

))
```

It returns:

![plotly](https://user-images.githubusercontent.com/40054269/41958313-f2ff4bec-79e9-11e8-9108-500411ef1b70.PNG)

As you see, there is no line at all in plotly.

(See also [stackoverflow](https://stackoverflow.com/questions/51047022/why-can-geom-path-not-be-coloured-when-used-together-with-plotly-in-shiny))

By the way: Arrows are not shown either. The following code works for shiny (only) but not for plotly:
`geom_path(size=1,aes(colour=mycolA), arrow = arrow(type="closed", length = unit(0.1, "inches"))) `

**Comment by cpsievert** [comment]
Duplicate https://github.com/plotly/plotly.js/issues/147 #469
