### ISSUE TITLE
ggmap to plotly?

### ISSUE THREAD

**Issue by sckott** [ropensci/plotly#13]
A user asked (http://ropensci.org/blog/2014/04/17/plotly/#comment-1350050604) about going from ggmap to plotly. Any chance this is possible? Will ask plotly folks about this.

**Comment by rosemm** [comment]
i would also be very interested in this! i was disappointed to see that plotly can't use the ggplot object produced by ggmap.

**Comment by cpsievert** [comment]
Not sure if this will be high up on the TODO list given that you can now use plotly's native support for maps -> https://plot.ly/r/#maps

**Comment by sckott** [comment]
cool, looks great

**Comment by jackparmer** [comment]
It's also now possible to create MapboxGL plots with Plotly's R library:
https://plot.ly/r/scattermapbox/
![image](https://cloud.githubusercontent.com/assets/1865834/24682761/6fad01c6-1969-11e7-95f2-603afeb397ad.png)

**Comment by cpsievert** [comment]
`GeomRasterAnn` [was recently implemented](e43b1b306344de92b01c7c7417db49485ae37658) which means most of ggmap should work, except for fixed/map coordinates, which will be tracked in #878
