### ISSUE TITLE
Plotly JS filesize

### ISSUE THREAD

**Issue by jakelever** [ropensci/plotly#1302]
Hey, apologies if this is discussed elsewhere but I haven't found it anywhere else.

I've got a Shiny app deployed using Plotly. The file size of the Plotly JS library is substantial (2.2M) and takes the majority of time for loading the page. I've found discussions about modularization (https://plot.ly/javascript/modularizing-monolithic-javascript-projects/) for using the JS library directly. My app only uses barcharts and piecharts. I was wondering if there were any plans to try to do some kind of modularization with the R Plotly library to reduce the file overhead.

Thanks for this great library!

**Comment by cpsievert** [comment]
The dev version has `partial_bundle()` which is designed to help take advantage of plotly.js' partial bundles.
