### ISSUE TITLE
Value of hoverinfo attribute is replicated as many times as number of points in trace

### ISSUE THREAD

**Issue by kmatveev** [ropensci/plotly#1306]
Attribute "hoverinfo" should have a single value in JSON sent to plotly.js. However, after plotly_build() it will be turned into vector with as many values as number of points in trace. I'm not sure, but I suspect that this happens because in plotly::schema() this attribute is describes as arrayOk: true for all trace types.

**Comment by cpsievert** [comment]
Your intuition is mostly correct, but I'll need a reproducible example to be of any help.
