### ISSUE TITLE
Blank rectangles with ggplot+geom_rect using toWebGL

### ISSUE THREAD

**Issue by llnns** [ropensci/plotly#1307]
Converting a plot with a `ggplot` `geom_rect` element with `toWebGL()` results in blank rectangles (no fill). Still the original plot from `ggplotly` is correct. The follow code illustrate this:

```r
library(plotly)
library(ggplot2)
data <- data.frame(x_start = c(0, 2, 4, 6),
               x_end = c(1, 3, 5, 7),
               y_start = c(0, 0, 2, 2),
               y_end = c(1, 1, 3, 3),
               info = c("x", "y", "x", "y"))

p <- ggplot(data ,aes(xmin=x_start, xmax=x_end, ymin=y_start, ymax=y_end, fill=info)) + geom_rect()
p_ply <- ggplotly(p)
p_ply_gl <- toWebGL(p_ply)
p_ply
p_ply_gl
```

My `p_ply` output:
![ply](https://user-images.githubusercontent.com/11335099/42854654-4ab82816-8a13-11e8-9e2e-15951e5de4a2.png)

My `p_ply_gl` output:
![ply_gl](https://user-images.githubusercontent.com/11335099/42854660-51ff65bc-8a13-11e8-961f-1ded0a9de755.png)

Also, if I add the color parameter in the `aes`, the Webgl version shows it (the border) correctly, but doesn't fill it. Changing `p` for:

```r
p <- ggplot(data ,aes(xmin=x_start, xmax=x_end, ymin=y_start, ymax=y_end, fill=info, color=info)) + geom_rect()
```

Makes my `p_ply_gl` output: 

![ply_gl_colour](https://user-images.githubusercontent.com/11335099/42854661-56fc3ab8-8a13-11e8-9cad-3542e31010a1.png)

I got the same problem on the versions installed with:

     install.packages("plotly")

and the with the `plotly_4.7.1`, installed with:

     install.packages("plotly", type = "source")

**Comment by cpsievert** [comment]
Have you tried the dev version? `devtools::install_github('ropensci/plotly')`

If you still have problems, let me know if you're windows/Rstudio

**Comment by llnns** [comment]
Hey, It worked. Sorry for the inconvenience.
