### ISSUE TITLE
Bubble chart based on geom_polygon not rendering in RStudio

### ISSUE THREAD

**Issue by mmgledhill** [ropensci/plotly#1312]
Plotly bubble chart via ggplotly and geom_polygon no longer rendering in Rstudio Viewer or Flexdashboard app in latest CRAN version of plotly (4.8.0). Confirmed it renders fine in old CRAN Version 4.7.1. I am working with fresh install of all packages from CRAN, latest install of Rtools, and R.Version 3.5.1.

Expected output is packed circles/bubble chart with hover functionality.

```r
library(ggplot2)
library(packcircles)
library(plotly)
library(data.table)

temp<-data.table(id=LETTERS,value=1:26)

temp[,text:=paste(id,"<BR>Value:",value)]
packing <- circleProgressiveLayout(x=temp[,.(value)],sizecol="value")
dat <- circleLayoutVertices(packing)

g<-ggplot(data = dat) +
  scale_y_reverse() + 
  coord_equal()+
  geom_polygon(aes(x, y, fill = id,group = id, text=rep(temp$text,each=26)), 
               colour = NA,
               show.legend = FALSE)+
  geom_polygon(aes(x, y, fill = rep(temp[,value],each=26),group = id, text=rep(temp$text,each=26)), 
            colour = NA,
            show.legend = TRUE) +
  scale_fill_gradient2(name="Letters",
                       low="#cb003d",
                       mid="white",
                       high="#006db7",
                       midpoint = 0,
                       space = "Lab",
                       na.value = "#006db7", 
                       guide = "colourbar"
                       )

ggplotly(g,tooltip = c("text")) %>% 
  layout(showlegend=TRUE, hovermode="x")
```

**Comment by cpsievert** [comment]
Does it render if you open in web browser (e.g., Chrome or Firefox)?

**Comment by mmgledhill** [comment]
Yes, it looks it renders in Chrome ok.

**Comment by peeter-t2** [comment]
Same issue for `sf` maps. Renders in Firefox in 4.8, but not in preview. Any chance this has an easy fix? Checking the plots in Rstudio can be pretty important for data analysis.

**Comment by cpsievert** [comment]
> Any chance this has an easy fix?

I don't think so because I'm pretty sure this is a Windows specific issue that must be fixed on the plotly.js level

**Comment by peeter-t2** [comment]
Ok, too bad. Just to say, I was working on Ubuntu 16.04 not Windows for this. I could give you some system details, if you want and tell me which ones. :)
Good luck in any case :)

**Comment by cpsievert** [comment]
Could you please right-click in RStudio, choose "Inspect Element", navigate to console tab, and report any errors that appears when attempting to render this example?

**Comment by mmgledhill** [comment]
Errors on Inspect for Letters Bubble chart example above:
![inspect_letters_bubble_chart_plotly](https://user-images.githubusercontent.com/11818724/45370141-1afa2f80-b5d7-11e8-97e3-5234351dfb5e.PNG)

**Comment by cpsievert** [comment]
I'm fairly sure using the preview release of RStudio fixes this problem. The preview should become stable in the coming months. Please report if you have any issues (with recent versions of RStudio).
