### ISSUE TITLE
Issue in Sankey Plot: Error in proposed[["hoveron"]] 

### ISSUE THREAD

**Issue by cpsievert** [ropensci/plotly#1315]
From @KoningD

Example https://plot.ly/r/sankey-diagram/#basic-sankey-diagram under Add Links gives the error:

Error in proposed[["hoveron"]] : subscript out of bounds

I tried it with the following versions:
r version 3.5.1, plotly_4.8.0
r version 3.4.2, plotly_4.8.0

**Comment by cpsievert** [comment]
I didn't say it was fixed, I just moved the issue's location

**Comment by cpsievert** [comment]
As it turns out, the example itself has a bug...the `domain` should be a list of two atomic vectors (both of length 2):

```r
domain = list(
    x =  c(0,1),
    y =  c(0,1)
 )
```

Not an atomic vector with four elements:

```r
domain = c(
    x =  c(0,1),
    y =  c(0,1)
 )
```

If anyone sees this error due to a different problem please let me know.

**Comment by aarora79** [comment]
Verified, works with 
domain = list(
    x =  c(0,1),
    y =  c(0,1)
 )
