### ISSUE TITLE
Pre-defined colorscales has no effect on heatmaps

### ISSUE THREAD

**Issue by priyatharsan** [ropensci/plotly#1319]
The heatmap/heatmapgl plots has no effect from the predefined color-scales such as "Greys",  "Picnic", "Rainbow", "Red", etc..

However, when specifying the RGB matrix manually to the color-scale changes the color.

```
p <- plot_ly(z = zdata, colorscale = "Greys", type = "heatmap")
```

![1](https://user-images.githubusercontent.com/25846124/43722685-d7294f50-9963-11e8-8945-ad631030b70a.PNG)

![2](https://user-images.githubusercontent.com/25846124/43722704-e3b57c58-9963-11e8-840a-0a6c78aedf16.PNG)

**Comment by sergiballestar** [comment]
I can confirm this issue has been fixed
