### ISSUE TITLE
points-changing-size for R-plotly and ggplotly

### ISSUE THREAD

**Issue by stemangiola** [ropensci/plotly#1320]
I was not able to find an analogue of https://plot.ly/python/animations/#points-changing-size for R. I need to animate with frame aes the size of a goem_point() rather than their position.

Thanks

**Comment by cpsievert** [comment]
As per our [contributing guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), github issues are reserved for bug reports and feature requests only. So I'll have to close your ticket.

Please use our community forums at [community.plot.ly](http://community.plot.ly/) for posts of the likes.

Thanks!
