### ISSUE TITLE
Getting an error of "Evaluation error: Incorrect number of arguments (5), expecting 4 for 'rlang_tilde_eval'." when wrapping ggplotly around my ggplot2 function

### ISSUE THREAD

**Issue by benjaminrobinson** [ropensci/plotly#1327]
Never mind.  Was an issue with `rlang` and `tidyselect` not `plotly`.  My apologies!

**Comment by cpsievert** [comment]
Thanks, could u let me know which package `usac_colors()` belongs to and/or remove it from the example?

**Comment by benjaminrobinson** [comment]
That's a color palette from my own personal library.  But my apologies.  I edited the comment to reflect the fact that this isn't a `plotly` problem but a `rlang`/`tidyselect` issue on my end that I needed to update `rlang` and `tidyselect` inside of a fresh R session in order for things to jive.
