### ISSUE TITLE
ggplotly in nested loop, rmarkdown

### ISSUE THREAD

**Issue by tacormier** [ropensci/plotly#1329]
I have a question related to #273 . I am trying to use ggplotly in a nested loop. The solution from #273  works fine in a single loop, but when I nest it within another loop (necessary for output html document structure) it doesn't print the plots. I need the plots from the while loop to be under the heading established in the for loop. Simplified example below. I'm hoping I'm just missing something re: html format/tags etc.

If I just run the while loop and comment out the outer for-loop, it works and prints the graphs. Once I add in that outer loop, I have problems. Any thoughts on a work-around. Perhaps the widget solution in 273 would work, but I wanted to post the question in case there's an easier, more straightforward answer.

My expected output here is 

## This is a heading for A
plots 1-3 from while loop printed here.

## This is a heading for B
plots 1-3 from while loop printed here.  
 </br>  

Many thanks!

```r
library(plotly)
library(ggplot2)

#+ results='asis', echo = FALSE
for (i in c('A','B')) {
  cat("## This is a heading for ", i, "\n")

  v <- 1
  l <- htmltools::tagList()

  while (v <= 3) {
    print(noquote(v))
    df <- data.frame(x=v, y=10)
    p <- ggplot(df, aes(x=x, y=y)) + geom_point()
    ggp <- ggplotly(p)
    l[[v]] <- ggp

    v=v+1
    cat('\n')
  
  }

  l
}

**Comment by cpsievert** [comment]
Try using `unlist()` to "flatten" your nested list of plotly objects

**Comment by tacormier** [comment]
Thanks for your response. Using unlist on 'l' did not work - I saw no change in the behavior of the code - still did not plot the graphs. If you were able to get the plots to display, I'd love to know what we did differently. Thank you!

**Comment by cpsievert** [comment]
Using your example, `l` displays in knitr/rmarkdown (you don't need  `results='asis'`) and `htmltools::browsable(l)` displays correctly in other contexts
