### ISSUE TITLE
Mapbox plot - map not appearing in the plot

### ISSUE THREAD

**Issue by priyatharsan** [ropensci/plotly#1330]
Map disappears when plotting offline, and getting a  `(400) Bad Request` when using `api_create` 
Sample code:
```
dat <- map_data("world", "canada") %>% group_by(group)

p <- plot_mapbox(dat, x = ~long, y = ~lat) %>%
  add_paths(size = I(2)) %>%
  add_segments(x = -100, xend = -50, y = 50, 75) %>%
  layout(mapbox = list(zoom = 0,
                       center = list(lat = ~median(lat),
                                     lon = ~median(long))
  ))
p
```
Output
![image](https://user-images.githubusercontent.com/25846124/44731466-421e1080-aab1-11e8-8e1f-f5f2f678ea94.png)

When using `api_create`:
```
chart_link = api_create(p, filename="mapbox-basic")
chart_link
```
Error:
```
Error: Client error: (400) Bad Request
	Figure field is invalid. Reason: Raw data arrays are not allowed at this endpoint. Use grid references instead. Raw data found at the following paths in the figure [('data', 0, u'marker', u'size')]
```

**Comment by nhieu0602** [comment]
It doesn't work for me too even in Python. I suspect plotly can't work well with Mapbox API. Here is my session Info
![image](https://user-images.githubusercontent.com/42833995/44843635-e4d1bd00-ac72-11e8-8c21-37d5912ff1f3.png)

**Comment by cpsievert** [comment]
Closing since the `api_create()` issue needs to be fixed in plotly's chart editor (likely by upgrading plotly.js).
