### ISSUE TITLE
Plotly graphs are not displayed in knitr output if produced inside a loop

### ISSUE THREAD

**Issue by Stan125** [ropensci/plotly#1341]
If plotly graphs are printed inside a loop and not with `subgroup`, which is necessary if you have a lot of plots, then it just doesn't work.

**Input**

Consider this minimal working example:
![screen shot 2018-09-20 at 16 37 42](https://user-images.githubusercontent.com/17404160/45825902-948acf80-bcf3-11e8-9551-051edeacb0d2.png)

The code for this is [here](https://gist.githubusercontent.com/Stan125/1b0b870a2b2679835becb0dafba04f51/raw/1a68e208dc53ffc87357482f6d3f12aeb29f2f59/Problem.Rmd). Sorry, there is no way to to syntax highlighting for `.Rmd` files so I cannot display it in this issue with the correct code.

**Output**

Only the second code chunk can yield outputs. The first plots just don't show up in the resulting .pdf file. Here is the resulting .pdf file:
[Untitled.pdf](https://github.com/ropensci/plotly/files/2401758/Untitled.pdf)

Essentially, if I make a list of plotly objects and print them, knitr does not catch them, even with `htmltools` and all that. If I ust print them without looping, everything works.

**Comment by cpsievert** [comment]
Try wrapping the list in `htmltools::tagList()` https://github.com/ropensci/plotly/issues/273#issuecomment-195611009
