### ISSUE TITLE
scattergl breaks hiDPI display for markers

### ISSUE THREAD

**Issue by uncle-m** [ropensci/plotly#1344]
New version of plotly.r 4.8.0 breaks hi resolution display on hiDPI (retina) displays. Simple example in the plotly.r polar webGL scatter plot example here:
https://plot.ly/r/polar-chart/#webgl-polar-charts

Axis lines and tick labels are correctly displayed. Markers are displayed in low resolution.

**Comment by cpsievert** [comment]
Related to https://github.com/plotly/plotly.js/issues/2780, please post a screenshot and details of your system there
