### ISSUE TITLE
demo(crosstalk-highlight-leaflet) contains unknown function crosstalk_unit

### ISSUE THREAD

**Issue by dshkol** [ropensci/plotly#1347]
The demo for linking plotly to leaflet using crosstalk is currently broken when run on current CRAN release versions of the plotly, leaflet, and crosstalk packages. The demo runs correctly until the execution of `sd <- crosstalk_unit(quakes)` which throws an error that it is unable to find function `crosstalk_unit`.

A search of [github code](https://github.com/search?q=crosstalk_unit&type=Code) shows that the only references to `crosstalk_unit` are from this demo, and do not exist in any of these three packages. 

```r
# fresh install of CRAN packages
install.packages("plotly")
install.packages("leaflet")
install.packages("crosstalk")

# load demo
demo("crosstalk-highlight-leaflet", package = "plotly")
```
> Error in crosstalk_unit(quakes) : 
  could not find function "crosstalk_unit"

**Comment by cpsievert** [comment]
Ahh, yes, thanks, that should be `highlight_key()`, not `crosstalk_unit()`
