### ISSUE TITLE
Mapbox on Binder not showing the tiles

### ISSUE THREAD

**Issue by alexetnunes** [ropensci/plotly#1348]
I have some notebooks set up to run in a Binder, but when I run them on Binder no tiles show up. I can run them locally and in a local docker instance and I can see the map. For some reason, it is only in a Binder instance that the tiles will not show, but the tooltips will.

```r
library(plotly)

dat <- map_data("world", "canada") %>% group_by(group)

p <- plot_mapbox(dat, x = ~long, y = ~lat) %>%
  add_paths(size = I(2)) %>%
  add_segments(x = -100, xend = -50, y = 50, 75) %>%
  layout(mapbox = list(zoom = 0,
                       center = list(lat = ~median(lat),
                                     lon = ~median(long))
  ))

embed_notebook(p)


```

<img width="1026" alt="screen shot 2018-09-24 at 3 36 43 pm" src="https://user-images.githubusercontent.com/6401210/45971788-5aca0980-c010-11e8-97e3-328ec00da0b9.png">

**Comment by cpsievert** [comment]
Can you get other plotly charts rendering in binder?

**Comment by alexetnunes** [comment]
Yes, and in the mean time I've managed to figure out it's the exact combination of Binder+Safari when this happens. It works fine in Chrome.

**Comment by cpsievert** [comment]
Huh, strange, in that case, it's likely something that needs to be fixed by plotly.js. Please try to copy/paste [one of these JavaScript examples](https://plot.ly/javascript/scattermapbox/) into Binder+Safari to reproduce the problem. If you can, please report it to https://github.com/plotly/plotly.js
