### ISSUE TITLE
Can not add the Package Plotly: Unsatisfiable requirements

### ISSUE THREAD

**Issue by carlitosborja** [ropensci/plotly#1350]
Hello everyone. I have a problem when I execute this cell:

`Pkg.add("Plotly")`

the output says as follows:

> Resolving package versions...
> Unsatisfiable requirements detected for package PlotRecipes [0e44f1d2]:
>  PlotRecipes [0e44f1d2] log:
>  ├─possible versions are: [0.0.1-0.0.6, 0.1.0, 0.2.0, 0.3.0] or uninstalled
>  ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1-0.0.6, 0.1.0, 0.2.0, 0.3.0]
>  └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

> Stacktrace:
>  [1] #propagate_constraints!#61(::Bool, ::Function, ::Pkg.GraphType.Graph, ::Set{Int64})
> ...
> ...
> ...
> [14] add(::String) at .\none:0
> [15] top-level scope at In[8]:1
> 

I am using julia 1.0.0 on jupyter notebook.
Thanks. Hope you can help me with this.

**Comment by cpsievert** [comment]
This repo is for the plotly R package, not the Julia package
