### ISSUE TITLE
orca crash on linux cinamon

### ISSUE THREAD

**Issue by abrionne** [ropensci/plotly#1353]
Hello,
My linux cinnamon crash when I want to  print static image with orca, and I don't know why?
And now the export function works but the returned picture contain white columns strip that come from webshot.

 R version 3.5.1 (2018-07-02) , linux 17.3

**Comment by cpsievert** [comment]
I can't do much in the R package about this, especially without a reproducible example. 

Regarding your `orca()` problems -- setting up linux can be tricky -- these sort of issues will be better handled in the plotly/orca repo

https://github.com/plotly/orca#linux
https://github.com/plotly/orca/issues/131
https://github.com/plotly/orca/issues/127
