### ISSUE TITLE
event_data("plotly_selected") is not working with type="scatter" and mode="lines"

### ISSUE THREAD

**Issue by saurabhbhatt** [ropensci/plotly#1358]
---

In my shiny app, I am trying to see a list of data points on a line plot after the selecting a specific region on the chart but getting the `list()` output. I used `event_data("plotly_selected", source = "A")` to get the selected field data.

Below is my plotly code:

```r
nms = row.names(mtcars)

plot_ly(mtcars, source = "A") %>%
add_trace(x = ~mpg, y = ~wt, key = nms, type="scatter", mode = "lines")
```

**Comment by cpsievert** [comment]
The `plotly_selected` event won't fire when `mode="lines"`, but you could use this 'trick':

```r
plot_ly(mtcars, source = "A") %>%
add_trace(x = ~mpg, y = ~wt, key = nms, type="scatter", mode = "lines+markers", marker = list(size = 0.1))
```
