### ISSUE TITLE
Annotate not converting using ggplotly

### ISSUE THREAD

**Issue by marco-vene** [ropensci/plotly#1368]
---
Hi,
I noticed that annotate does not work when converting plot with ggplotly.

```r
ggplotly(
ggplot(mtcars, aes(cyl,mpg))  +
  geom_point() +
  annotate("label", 
           x = 7, 
           y = 30,
           label = "Test"))
```

Will this feature be developed? Any workaround?

**Comment by cpsievert** [comment]
Maybe someday, but you'll always be able to use the underlying plotly.js library to modifying the `ggplotly()` conversion

https://plotly-book.cpsievert.me/extending-ggplotly.html
https://blog.cpsievert.me/2018/01/30/learning-improving-ggplotly-geom-sf/

```r
p <- ggplot(mtcars, aes(cyl,mpg)) + geom_point()
ggplotly(p) %>%
  layout(
    annotations = list(
      text = "Test",
      x = 7, 
      y = 30,
      showarrow = FALSE
    )
  )
```
