### ISSUE TITLE
Custom text doesn't replace default hover in Candlestick charts

### ISSUE THREAD

**Issue by senthilthyagarajan** [ropensci/plotly#1370]
Candlestick charts by default come with hover high,open,close,low. So when you try to replace it with custom hover text it still shows the default hover text.

``` r
library(plotly)
getSymbols("AAPL",src='yahoo')
# basic example of ohlc charts
df <- data.frame(Date=index(AAPL),coredata(AAPL))
df <- tail(df, 30)

p <- df %>%
  plot_ly(x = ~Date, type="candlestick",
          open = ~AAPL.Open, close = ~AAPL.Close,
          high = ~AAPL.High, low = ~AAPL.Low,
          text = ~paste("TEXT1:", ~AAPL.High,"<br>TEXT2: ", AAPL.Low)) %>%
  layout(title = "Basic Candlestick Chart")
p
```

![](https://i.imgur.com/4T9ygQh.png)

<sup>Created on 2018-10-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by cpsievert** [comment]
I have a hunch this is related to a plotly.js bug, follow along here -- https://github.com/plotly/plotly.js/issues/3201

**Comment by cpsievert** [comment]
This appears to be fixed now
