### ISSUE TITLE
Plotly captures environments on save

### ISSUE THREAD

**Issue by nolanp2** [ropensci/plotly#1372]
The issue comes up when saving a plotly object in an RDS file. If the plot has been generated within a function, the plotly plot seems to capture the entire environment of that function. This can result in a ~100kb plot taking up Gbs of disk space (and taking hours to save) if any large objects are being calculated in within the function. 

The below code will create a simple plot which is ~33kb according to object.size. However on saving, the object will be of order ~4Gb. 
`
library(plotly)
library(magrittr)

simple_plot = function() {
  
  big = 1:1e9
  
  small = sample(big,100)
  
  small_df <- data.frame(small_x = small, small_y = small)
  
  small_x <- small_df$small_x
  small_y <- small_df$small_y

  out <- small_df %>%
    plot_ly() %>%
    add_lines(x = ~small_x,y= ~small_y)
  
  return(out)
}

out <- simple_plot()

object.size(out)

saveRDS(out,"D:/RandomData/simple_plot.RDS")
`

Once the object is created, I can't find where in the plotly object the 'big' object is being captured. Any thoughts on how to detach the environment before saving? 

Update: The environment seems to get captured via the ~ calls. If the x/y definitions are replaced with x = small_df$small_x, y= small_df$small_y  the issue no longer arrises. This at least gives a simple workaround, but it's a shame to have to actively avoid calls with ~.

**Comment by cpsievert** [comment]
Before I offer my hack, may I ask why you need to serialize the R object? Keep in mind you can save the resulting HTML/JS/CSS via `htmlwidgets::saveWidget()` and `htmltools::save_html()`.

The hack you could do would be to build the plot, then get rid of the closure(s) that plotly uses to track references to the data. 

```r
out <- plotly_build(simple_plot())
out$x$visdat <- NULL
out$x$cur_data <- NULL
out$x$attrs <- NULL
saveRDS(out, "out.rds")
```

Fair warning though, these are 'internal' attributes that could change, and weird things might happen if you `readRDS()` and modify the result.

**Comment by nolanp2** [comment]
The reason for the save as an R object, is I'm saving a list of plots, reloading them in a shiny app, and displaying different plots on click by indexing the list element. It seemed like the more natural way to do that. 

As for your hack, it works great, but can you explain how applying plotly_build changes the object? I'm still baffled as to what's going on!

**Comment by cpsievert** [comment]
`plotly_build()` evaluates the formula mappings and builds a valid JSON spec. Generally speaking, as long as you're not post-processing the result of `plotly_build()` with other R code, I don't see a real problem with using this hack
