### ISSUE TITLE
Can anyone help with the problem about error information when installing packages 

### ISSUE THREAD

**Issue by Ericq1998** [ropensci/plotly#1374]
I am puzzled about the following description:

_ERROR: dependency 'SuppDists' is not available for package 'kSamples'
* removing 'F:/R-3.5.1/library/kSamples'
In R CMD INSTALL_

Is my edition too old?For I have downloaded one package successfully called"crank" with the option"install package from the local files"
And then the others all failed.

And what about the package which are not released on CRAN Package?
Thanks for answering!

**Comment by cpsievert** [comment]
I am puzzled too. This likely has nothing to do with plotly

**Comment by Ericq1998** [comment]
> I am puzzled too. This likely has nothing to do with plotly

Thanks,I decided to use to code to install instead of from the local files
