### ISSUE TITLE
Color not set properly when plotly aggregates data for pie chart

### ISSUE THREAD

**Issue by shosaco** [ropensci/plotly#1375]
hi Carson,

thanks for your wonderful work. Today we discovered an issue with Plotly's pie chart coloring. Colors can be set using the `marker` argument:

```r
library(plotly)
plot_ly(mtcars[c(1,3,5), c("cyl", "drat")], labels = ~cyl, values = ~drat, type = 'pie', 
        marker = list(colors = c("yellow", "green", "red"))) %>%
    layout(xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
           yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
```
![2018-10-24 18_10_56-](https://user-images.githubusercontent.com/20717764/47445052-3b153500-d7b8-11e8-9819-5e1b540d9329.png)

Provided with an un-aggregated dataframe, Plotly conducts the aggregation into bins and displays the resulting pie chart. Unfortunately, coloring the slices is then not working properly:

```r 
library(plotly)
plot_ly(mtcars[, c("cyl", "drat")], labels = ~cyl, values = ~drat, type = 'pie', 
         marker = list(colors = c("yellow", "green", "red"))) %>%
     layout(xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
            yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
```
![2018-10-24 18_11_45-](https://user-images.githubusercontent.com/20717764/47445079-4bc5ab00-d7b8-11e8-9d44-ea4cda4f65a2.png)

Thanks and best regards,
sandro

**Comment by cpsievert** [comment]
Huh, weird, this doesn't seem to be a problem using the master branch on GitHub -- would you mind trying `devtools::install_github("ropensci/plotly")`  and/or report your `devtools::session_info()`?

**Comment by shosaco** [comment]
That's true, it is working properly with the devleopment version. Thank you!
