### ISSUE TITLE
stacked (relative) bar chart: silly stacking order

### ISSUE THREAD

**Issue by salim-b** [ropensci/plotly#1395]
If I want to plot a stacked bar chart of mixed positive and negative values, say to recreate a likert plot, the order given in the relevant factor fed to `plot_ly`'s `name` parameter is not displayed in the chart as one would expect!

Below you find a reprex which does

1. create some sample data

2. plot a bar chart without stacking -> order is fine

3. plot a bar chart with stacking (`barmode = "relative"`) -> category `very good` comes before `not so good` while I would expect the opposite (same order as in `barmode = "normal")`!

As a workaround I could reorder the factor levels before plotting, but then the legend entry order is messed up. Since there's no way to fully customize order of legend entries I don't even have see a proper workaround for this...

Now this problem might not be specifically R-related, but present in the underlying plotly.js library, I can't tell. Therefore I thought it'd make most sense to report it here and maybe you can bring it up upstream if necessary :)

---

Brief description of the problem

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

# create example dataset
data_example <- data_frame(question = c("q1", "q1", "q1", "q1",
                                        "q2", "q2", "q2", "q2",
                                        "q3", "q3", "q3", "q3",
                                        "q4", "q4", "q4", "q4"),
                           category = factor(x = c(0, 1, 2, 3,
                                                   0, 1, 2, 3,
                                                   0, 1, 2, 3,
                                                   0, 1, 2, 3),
                                             labels = c("very bad",
                                                        "not so bad",
                                                        "not so good",
                                                        "very good"),
                                             ordered = TRUE),
                           percentage = c(-12, -22, 45, 21,
                                          -33, -7, 41, 19,
                                          -50, -27, 13, 10,
                                          -1, -11, 56, 32))

# print example dataset
data_example
#> # A tibble: 16 x 3
#>    question category    percentage
#>    <chr>    <ord>            <dbl>
#>  1 q1       very bad           -12
#>  2 q1       not so bad         -22
#>  3 q1       not so good         45
#>  4 q1       very good           21
#>  5 q2       very bad           -33
#>  6 q2       not so bad          -7
#>  7 q2       not so good         41
#>  8 q2       very good           19
#>  9 q3       very bad           -50
#> 10 q3       not so bad         -27
#> 11 q3       not so good         13
#> 12 q3       very good           10
#> 13 q4       very bad            -1
#> 14 q4       not so bad         -11
#> 15 q4       not so good         56
#> 16 q4       very good           32

# plot bar chart without stacking
data_example %>%
    plotly::plot_ly(type = "bar",
                    orientation = "h",
                    name = ~category,
                    x = ~percentage,
                    y = ~question) %>%
    plotly::layout(barmode = "normal",
                   xaxis = list(title = NA,
                                ticksuffix = " %"),
                   yaxis = list(title = NA))
```

![](https://i.imgur.com/yDYiZcZ.png)

``` r

# plot bar chart with stacking (relative mode)
data_example %>%
    plotly::plot_ly(type = "bar",
                    orientation = "h",
                    name = ~category,
                    x = ~percentage,
                    y = ~question) %>%
    plotly::layout(barmode = "relative",
                   xaxis = list(title = NA,
                                ticksuffix = " %"),
                   yaxis = list(title = NA))
```

![](https://i.imgur.com/lM0Paos.png)

<sup>Created on 2018-11-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by cpsievert** [comment]
I think `layout(., legend = list(traceorder = "reversed"))` does what you want? If not, please be more specific about what ordering you expect.

**Comment by salim-b** [comment]
> I think `layout(., legend = list(traceorder = "reversed"))` does what you want?

Nope, not at all. The order in the legend is fine (as long as I don't reorder the factor levels) but at the same time the order in the stacked bar chart is not!

> If not, please be more specific about what ordering you expect.

On the right side of the zero line the blue area (`very good`) comes before the orange area (`not so good`) while I would expect it the other way round (as per factor level ordering). I have to admit that in the end, the whole plot is a bit of a hack (negative values) to recreate a likert plot like [this one](http://rnotr.com/likert/ggplot/barometer/likert-plots/). Maybe I should have labelled the different levels `very good` > `rather good` > `rather bad` > `very bad`, so that the ordering would be more intuitive – sorry for that.

But do you agree that the order changes from `barmode = normal` (orange comes **before** blue) to `barmode = stacked` (orange comes **after** blue)? That's my main point: This shouldn't be the case!

**Comment by cpsievert** [comment]
> But do you agree that the order changes from barmode = normal (orange comes before blue) to barmode = stacked (orange comes after blue)?

No, not if you take the approach that "low" levels should start from the origin, which I believe the way most visualization tools interpret it.

**Comment by salim-b** [comment]
> No, not if you take the approach that the first levels should start from the origin (...)

What do you mean by "origin"? The zero line? Then I have to disagree because `very good` is a  "pole" level (the highest one) and is placed right next to the zero line while the other "pole" level `very bad` (the lowest one) is _not_ placed right next to the zero line... I can't see any sense in that.

**Comment by YsoSirius** [comment]
The ordering is correct if you include `type="category"` to the xaxis options, but then the layout changes.

**Comment by salim-b** [comment]
> The ordering is correct if you include `type="category"` to the xaxis options, but then the layout changes.

Well...
![bildschirmfoto vom 2018-11-14 16-47-54](https://user-images.githubusercontent.com/20040931/48494162-2ced8e00-e825-11e8-81e8-2f31003434f5.png)

The order of the categories is fine indeed, but everything else isn't much more than "modern art" :rofl:
