### ISSUE TITLE
Contour plot - color bar not displaying the proper range as based on the z-data

### ISSUE THREAD

**Issue by priyatharsan** [ropensci/plotly#1397]
In this example: https://plot.ly/r/contour-plots/#set-x-and-y-coordinates

```
p <- plot_ly(
  x = c(-9, -6, -5, -3, -1), 
  y = c(0, 1, 4, 5, 7), 
  z = c(10, 10.625, 12.5, 15.625, 20, 5.625, 6.25, 8.125, 11.25, 15.625, 2.5, 3.125, 5, 8.125, 12.5, 0.625, 1.25, 3.125,
        6.25, 10.625, 0, 0.625, 2.5, 5.625, 10), 
  type = "contour" 
)
```
The z is assigned with values ranging from 0 to 20, but the resulting color bar displays the ticks ranging from 10 to 20 :
![1](https://user-images.githubusercontent.com/25846124/48275226-01c50200-e413-11e8-8c38-2852485b9975.PNG)

Also, from the plot, the `len` of the colorbar looks like `0.5`, but the default seems to be `1`: https://plot.ly/r/reference/#contour-colorbar-len
and manually setting to 1, still did not resolve with the range of the colorbar ticks: 
![2](https://user-images.githubusercontent.com/25846124/48275511-a9dacb00-e413-11e8-947f-88d512903fe4.PNG)

**Comment by michaelbabyn** [comment]
This is a documentation error where a vector was used when a matrix was needed. The Documentation has been fixed in https://github.com/plotly/documentation/pull/1171

**Comment by priyatharsan** [comment]
Thanks @michaelbabyn for figuring that out. Closing the issue.
