### ISSUE TITLE
Retrieving axis tick information from a plotly figure object

### ISSUE THREAD

**Issue by ndrubins** [ropensci/plotly#1402]
Hi,

It's probably not an `issue` proper but I doubt [my stackoverflow post](https://stackoverflow.com/questions/53287801/retrieve-axis-tick-information-from-a-plotly-figure) will be answered. 

The question is whether it is possible to retrieve the axis tick labels from the plotly object?

So for example, I'm plotting a heatmap:
```
set.seed(1)
df <- reshape2::melt(matrix(rnorm(100*20),100,20,dimnames = list(paste0("G",1:100),paste0("S",1:20))))

library(plotly)
library(dplyr)
plotly.obj <- plot_ly(z=c(df$value),x=df$Var2,y=df$Var1,colors=grDevices::colorRamp(c("darkblue","gray","darkred")),type="heatmap",colorbar=list(title="Scaled Value",len=0.4)) %>%
  layout(yaxis=list(title=NULL),xaxis=list(tickangle=90,tickvals=10,ticktext="X-Label"))
```

And I want to be able to get the y-axis tick labels that were selected for the plot.

I looked around the saved object but couldn't find that information:

```
> plotly.obj$x$layoutAttrs
$`102ce55fd393e`
$`102ce55fd393e`$yaxis
$`102ce55fd393e`$yaxis$title
NULL


$`102ce55fd393e`$xaxis
$`102ce55fd393e`$xaxis$tickangle
[1] 90

$`102ce55fd393e`$xaxis$tickvals
[1] 10

$`102ce55fd393e`$xaxis$ticktext
[1] "X-Label"
```

Can you offer any help?

Thanks a lot

**Comment by MattDnv** [comment]
Thank you so much for opening this ticket ndrubins, I was right now intending to open the same ticket here on github. I have opened two tickets on this problem in stackoverflow. Nobody gave me a working answer

https://stackoverflow.com/questions/53266457/r-plotly-plot-ly-function-axis-titles-dont-appear-when-i-call-plotly-inside-a/53266633#53266633

https://stackoverflow.com/questions/53284719/same-code-for-function-plot-ly-in-r-gives-different-results-in-a-project-and-in

I have also opened a ticket on plotly, with still no working answer

https://community.plot.ly/t/axis-titles-not-displayed-when-im-in-a-project-plot-ly-function/15592/2

What is really strange, is that these command lines are working when you write them as command lines in RGui, but they don't work when you write them inside a package. For my part, I have the impression it is a bug from plotly

**Comment by cpsievert** [comment]
> get the y-axis tick labels that were selected for the plot.

I assume you mean the tick labels supplied by plotly.js? Although not entirely foolproof, the best way to do this will be to leverage `htmlwidgets::onRender()` to spit out the labels via JavasScript (after the graph has been rendered in your browser). Here is how you can log the "full layout" to your browser's developer tools:

```r
plot_ly() %>% 
  htmlwidgets::onRender(
    "function(el, x) {
       console.log(el._fullLayout);
    }"
  )
```

Note that the `_fullLayout` name means "this is an internal API", so use caution when relying on it. That being said, `_fullLayout` should be fairly stable, but to answer your question, we need to reach into another internal attribute:


```r
plot_ly() %>% 
  htmlwidgets::onRender(
    "function(el, x) {
       alert(el._fullLayout.xaxis._vals.map(function(i) { return i.text; }));
    }"
  )
```

**Comment by ndrubins** [comment]
Thanks a lot @cpsievert . 

So per my example, running:
```
set.seed(1)
df <- reshape2::melt(matrix(rnorm(100*20),100,20,dimnames = list(paste0("G",1:100),paste0("S",1:20))))
library(plotly)
library(dplyr)
plot_ly(z=c(df$value),x=df$Var2,y=df$Var1,colors=grDevices::colorRamp(c("darkblue","gray","darkred")),type="heatmap",colorbar=list(title="Scaled Value",len=0.4)) %>%
  layout(yaxis=list(title=NULL),xaxis=list(tickangle=90,tickvals=10,ticktext="X-Label")) %>%
  htmlwidgets::onRender("function(el, x) {alert(el._fullLayout.yaxis._vals.map(function(i) { return i.text; }));}")
```
Pops up a window which shows the tick values.

Is there a way to save this to an R variable or even write this to file?

Thanks again
