### ISSUE TITLE
FR: renderCachedPlotly

### ISSUE THREAD

**Issue by fabiangehring** [ropensci/plotly#1403]
In it's newest release 1.2 shiny introduced the possibility to cache "standard" plots out of the box (renderCachedPlot).

It would be nice to have a plotly equivalent (renderCachedPlotly).

**Comment by cpsievert** [comment]
As the release post mentioned, future versions of shiny will likely have a way cache outputs generically,  and plotly will likely be able to leverage that -- https://blog.rstudio.com/2018/11/13/shiny-1-2-0/

**Comment by AlexanderWanitschke** [comment]
Any progress on this ?

**Comment by turqoisehat** [comment]
I would love this.

**Comment by cpsievert** [comment]
Dev versions of shiny and plotly now have support for this via `shiny::bindCache()`
