### ISSUE TITLE
Implement geom_GeomConfint() from ggsurvplot in plotly for plotting survival curves with confidence intervals

### ISSUE THREAD

**Issue by rvenghat** [ropensci/plotly#1404]
I'm currently working on converting survival curves plotted by ggsurvplot to a plotly chart. However it does not plot the confidence intervals provided by ggsurv.  The following warning was generated when i tried to plot it.
Warning in geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
  geom_GeomConfint() has yet to be implemented in plotly.
  If you'd like to see this geom implemented,
  Please open an issue with your example code at
  https://github.com/ropensci/plotly/issues

# This is the code to generate the plot using ggsurvplot

p<-ggsurvplot(
  survfit(res),
  xlab = "Chargeoff Time (Months)",
  palette = "#2E9FDF",
  data = final_data,
  ggtheme = theme_minimal(),
  ylab = "Loan Survival Probablity",
)
# This is to generate the same plot using plotly
plotly::ggplotly(p$plot)

Can this be implemented?

**Comment by cpsievert** [comment]
Added to #566, but quite frankly, there are other extension packages that will likely take priority. 

If you like to take a stab at providing a ggplotly plug-in yourself, see https://plotly-book.cpsievert.me/translating-custom-ggplot2-geoms.html
