### ISSUE TITLE
Plotly generates artificial data point when using with crosstalk

### ISSUE THREAD

**Issue by linhai86** [ropensci/plotly#1406]
When using with crosstalk, plotly generates "new" data point on the scatter plot after selecting and deselecting.

First plot a scatter plot with plotly and crosstalk.
![image](https://user-images.githubusercontent.com/5193356/48574309-bd7aab80-e8c3-11e8-8227-c5c970a7dea7.png)

Then highlight some points by selecting them.
![image](https://user-images.githubusercontent.com/5193356/48574384-e438e200-e8c3-11e8-83d3-34d73f689e2a.png)

Double click anywhere to deselect. Then these's a "new" data point shows at the lower left corner.
![image](https://user-images.githubusercontent.com/5193356/48574413-f450c180-e8c3-11e8-9aff-3a13caf56696.png)

If I set `color = I("black")`, everything works fine.

R 3.4.1, plotly 4.8.0, crosstalk 1.0.0, macOS High Sierra 10.13.6.

```r
library(plotly)
library(crosstalk)
library(tidyverse)

m <- mtcars %>% tibble::rownames_to_column()
d <- SharedData$new(m, ~rowname)

plot_ly(d, x = ~mpg, y = ~disp, color = ~cyl, type="scatter", mode = "markers") %>%
    highlight(on="plotly_selected", off="plotly_deselect")
```

**Comment by cpsievert** [comment]
Thanks for the report!
