### ISSUE TITLE
Crosstalk highlighting also redraws manual colorbar

### ISSUE THREAD

**Issue by brooksambrose** [ropensci/plotly#1412]
Sometimes it is necessary to create a manual colorbar (like if you want [two colorscales for the same trace type](https://stackoverflow.com/questions/49231083/r-plotly-different-colorscales-for-two-scatter-on-the-same-plots/53348254#53348254)). Crosstalk highlighting has the interesting effect of redrawing the colorbar scale for the highlighted selection, which could be a feature, but happens to redraw it on top of the initial colorscale, which looks like a bug. When specifying color outside of the marker list, everything works fine.

``` r
library(plotly)
d<-data.frame(x=rnorm(10),y=rnorm(10),z=rnorm(10),grp=sample(1:2,10,T),clr=rnorm(10)) %>%
    highlight_key(~grp)
plot_ly(d) %>%
    add_markers(x=~x,y=~y,z=~z,text=~grp,hoverinfo='text'
        ,marker=list(color=~clr,showscale=T)) %>%
    highlight(on='plotly_hover')
```

![reprex mov](https://user-images.githubusercontent.com/1271481/48667516-80154a00-ea8c-11e8-9a54-e523b0765a5f.gif)

**Comment by cpsievert** [comment]
This will work better if you use the R specific `color` argument, which ensures there is always one color scale:

```r
library(plotly)
d<-data.frame(x=rnorm(10),y=rnorm(10),z=rnorm(10),grp=sample(1:2,10,T),clr=rnorm(10)) %>%
    highlight_key(~grp)
plot_ly(d) %>%
    add_markers(x=~x,y=~y,z=~z,text=~grp,hoverinfo='text', color = ~clr) %>%
    highlight(on='plotly_hover')
```

Alternatively, you could also leverage the `selected` argument in `highlight()` to control the attributes of the trace that is added on hover. For example, you could hide the colorscale of the additional trace:

```r
plot_ly(d) %>%
    add_markers(x=~x,y=~y,z=~z,text=~grp,hoverinfo='text'
                ,marker=list(color=~clr,showscale=T)) %>%
    highlight(on='plotly_hover', selected = attrs_selected(marker = list(showscale = FALSE)))
```

**Comment by brooksambrose** [comment]
That works, thanks. I didn't realize the crosstalk implementation adds a new trace. In the new trace, the color of the subset data is rescaled so that the minimum in the subset gets the head of the color scale and the max gets the tail, rather than keeping their color assignments from the original data. Is there a way for the new selected trace to inherit the colors of the original?
