### ISSUE TITLE
ggploly not working with ggdendro

### ISSUE THREAD

**Issue by slfan2013** [ropensci/plotly#1419]
`ggdendro` is a ggplot package. `ggdendrogram` returns `gg ggplot` class object. So plotly should be able to convert `ggdendro` to plotly plots. However, following code generates error of `Error in nchar(axisObj$ticktext) : 'nchar()' requires a character vector`. 

Code is

```
  library(ggplot2);library(plotly)
  hc <- hclust(dist(USArrests), "ave")
  p <- ggdendrogram(hc, rotate=FALSE)
  o = ggplotly(p)
```

**Comment by mschilli87** [comment]
@slfan2013: I know it's not a solution for the `ggplotly` usecase, but maybe [`iheatmapr`](https://github.com/ropensci/iheatmapr) already has what you need.

**Comment by slfan2013** [comment]
Thank you! Is iheatmap dependent on plotly?

**Comment by mschilli87** [comment]
@slfan2013: [`ropensci/iheatmapr` (R package)](https://github.com/ropensci/iheatmapr) [does not depend](https://github.com/ropensci/iheatmapr/blob/master/DESCRIPTION#L48-L62) on [`ropensci/plotly` (R package)](https://github.com/ropensci/plotly), but bundles [`plotly/plotly.js` (JavaScript library)](https://github.com/plotly/plotly.js`) which is also the basis of [`ropensci/plotly` (R package)](https://github.com/ropensci/plotly).

**Comment by slfan2013** [comment]
Thank you for the info. It helps.

**Comment by cpsievert** [comment]
I vaguely remember looking at `ggdendrogram()` a while back and decided it would be better to roll my own version to make [`demo("animation-tour-USArrests", package = "plotly")` possible](https://vimeo.com/239695664)

```r
plot_dendro(as.dendrogram(hc))
```
