### ISSUE TITLE
Specifying a plot title

### ISSUE THREAD

**Issue by region-spotteR** [ropensci/plotly#1451]
There is inconsistency in the documentation how to customize the plot title. In [the R complete reference documentation] it tells you specify a title by using list object with elements called `text`,`color` etc. 
However the documentation on the [project website](https://plot.ly/r/text-and-annotations/#text-mode) still uses `title="some string"`. 

I am using R 3.5.2. and plotly 4.8. from CRAN. The way from the R reference documentation does not work for me...

```r
plot_ly()%>%
  layout(
    title = list(text = 'sample plot', color = 'rgb(217,83,79)')
    ) %>%
  add_trace(x=1:7,y=round(runif(7)*7),type="scatter",mode="lines+marker")
```
...the `title="some string"` works though:

```r
plot_ly()%>%
  layout(
    title = 'sample plot'
    ) %>%
  add_trace(x=1:7,y=round(runif(7)*7),type="scatter",mode="lines+marker")
```

I discovered the issue through by answering a [question on stackoverflow](https://stackoverflow.com/questions/54131048/position-title-above-plot-area-in-r-plotly/54136444#54136444)

**Comment by cpsievert** [comment]
You won't be able to use title.text until the R package upgrades to plotly.js 1.43 or higher

https://github.com/plotly/plotly.js/releases/tag/v1.43.0

https://github.com/ropensci/plotly/pull/1450

**Comment by cpsievert** [comment]
Fixed now, although I think you want:

```r
plot_ly()%>%
  layout(
    title = list(text = 'sample plot', font = list(color = 'rgb(217,83,79)'))
    ) %>%
  add_trace(x=1:7,y=round(runif(7)*7),type="scatter",mode="lines+marker")
```
