### ISSUE TITLE
Add support for geoms from the naniar package

### ISSUE THREAD

**Issue by dandermotj** [ropensci/plotly#1453]
The [naniar package](https://github.com/njtierney/naniar) has some nice geoms for visualising missing data alongside complete data. There are 9 geoms in the package:

geom | Description
-- | --
geom_miss_point() | geom_miss_point
gg_miss_case() | Plot the number of missings per case (row)
gg_miss_case_cumsum() | Plot of cumulative sum of missing for cases
gg_miss_fct() | Plot the number of missings for each variable, broken down by a factor
gg_miss_span() | Plot the number of missings in a given repeating span
gg_miss_upset() | Plot the pattern of missingness using an upset plot.
gg_miss_var() | Plot the number of missings for each variable
gg_miss_var_cumsum() | Plot of cumulative sum of missing value for each variable
gg_miss_which() | Plot which variables contain a missing value

On the off chance that somehow plotly could automatically convert them into a plotly object I tried but no luck. The error message suggested I open an issue if I'd like to see these geoms implemented. It would be very cool if they were. Also, just a quick thanks for plotly, it's one of my favourite packages and use it for everything.

Thanks,
Dan

**Comment by njtierney** [comment]
Just wanted to chime in to confirm that on the current master branch of naniar `geom_miss_point` works, and all the other `gg_miss_` work except for `gg_miss_upset`

**Comment by dandermotj** [comment]
Thanks a million lads, that was swift! Looking forward to trying it out in the next few days.
