### ISSUE TITLE
subplot: problems with stacked histograms bins and legends when few datapoints

### ISSUE THREAD

**Issue by jumanbar** [ropensci/plotly#1456]
# What I want to do

Hello! I'm currently creating a shiny app using `plotly` to show histograms of my data. My intention is to emulate the `ggplot2` function `facet_grid` with stacked histograms. With enough data, the code seems to work correctly, but when the data is scarce, some strange things start to happen. Specifically, the **size of the bins** gets distorted and the **legend has fewer categories than what it should**.

Here's a quick comparison of 3 outputs:

- Left and middle: made with `ggplot` and `plotly` respectively, using the same 50 rows of data in both cases. The latter has the aforementioned problems.  
- Right: made with `plotly` (using the same code as the middle figure), using 1000 rows of data. This one seems OK.

![Left: ggplot2 with 50 datapoints; middle: plotly with 50 datapoints ; right: plotly with 1000 datapoints](https://user-images.githubusercontent.com/1039904/51402395-1f59ca80-1b2c-11e9-8940-9580b121c83c.png)

[Full-res image here.](https://raw.githubusercontent.com/jumanbar/misc/master/R/issue.png)

# Reprex

(not made with reprex package)

The following code sets up the R session and the data, including the amount of datapoints needed to recreate the figures (change to size = 1000 to get the one on the right):

```r
library(ggplot2)
library(dplyr)
library(magrittr)
library(plotly)
library(scales)
library(grDevices)

set.seed(0)
di <- diamonds %>%
  sample_n(size = 50)
```

My goal is to reproduce plot on the left (created with the code below), w/o using the `ggplotly` function (mainly because of [this](https://stackoverflow.com/questions/54120239/plotly-r-ggplot2-when-clicking-the-legend-in-a-plot-made-via-ggplotly-it-fai)).

```r
p <- ggplot(di) +
  aes(price, fill = cut) +
  facet_grid(color ~ .) +
  geom_histogram() +
  scale_x_log10() +
  ggtitle("Made with ggplot2") +
  xlab("Price (US dollars)")
print(p)
```

![ggplot figure](https://user-images.githubusercontent.com/1039904/51402968-cdb23f80-1b2d-11e9-8ea7-9f50656081c3.png)

## Manipulating the data for `plot_ly`

First I need to manually set the breaks and counts for the histogram bins (the `type = "log"` option for the xaxis [has some problems](https://github.com/plotly/plotly.js/issues/1844)). To do this I use the `hist` and `cut` functions:

```r
# With hist I set the breaks and midpoints of said breaks:
h <- hist(di$price %>% log10, breaks = 30, plot = FALSE)

# Using cut I get a factor with all the bins:
intervals <- cut(log10(di$price), breaks = h$breaks)
midpoints <- intervals
levels(midpoints) <- h$mids

# This are the x values used in the final plots:
midpoints <- midpoints %>%
  as.character %>%
  as.numeric
```

Finally I calculate de counts for all the bins, using all combinations of the columns cut, color and midpoints (note that I group by `intervals` too, which coincide with the grouping made with `midpoints`; the goal is to have the `intervals` for hovermode info):

```r
plot_data <- di %>%
  mutate(mids = midpoints,
         ints = intervals) %>%
  count(cut, color, mids, ints)
```

## Setting up the plotting parameters

Here I set up the `plot_ly` parameters. First I set a common range for the y axis (`yrange`):

```r
maxCount <- plot_data %>%
  group_by(color, mids) %>%
  summarise(N = sum(n, na.rm=TRUE)) %>%
  (function(x) max(x$N))
yrange <- c(0, maxCount) # The range for all the y axis
```

Then I set up both axis, which are lists. The first part involves calculating the breaks for x axis, using functions from the `scales` package (`log10_trans` and `number`):

```r
plot_breaks <- log10_trans()$breaks(di$price)

xaxis <- list(
  title = "Price (US dollars)",
  tickvals = log10(plot_breaks),
  ticktext = number(plot_breaks, accuracy = min(plot_breaks)),
  range = range(log10(di$price))
  )
yaxis <- list(
  fixedrange = FALSE,
  range = yrange
  )
```

## Creating the plot objects

In this part I split the data by the column `color` and then I create a list to store the plots. I also made the `plotFun` as a wrapper for the `plotly` commands for the sake of cleanlyness.

```r
pdata_split <- split(plot_data, plot_data[["color"]])
plots <- vector("list", length(pdata_split))

plotFun <- function(i, showlegend = TRUE) {
  yaxis$title <- names(pdata_split)[i]
  pdata_split[[i]] %>%
    plot_ly(
      x = ~mids, y = ~n, color = ~cut,
      legendgroup = ~cut,
      showlegend = showlegend,
      text = ~paste0("Rango: ", ints, "\n",
                     "Conteo: ", n),
      hoverinfo = "text+name") %>%
    add_bars() %>%
    layout(
      hovermode = "compare",
      barmode = "stack",
      bargap = 0,
      xaxis = xaxis,
      yaxis = yaxis
    )
}
```

Finally I excecute the `plot_ly` commands using a loop, with an iteration for each "color" category in the dataset:

```r
plots[[1]] <- plotFun(1, TRUE)
for (i in 2:length(pdata_split))
  plots[[i]] <- plotFun(i, FALSE)

sp <- subplot(plots, nrows = i, shareX = TRUE,
              shareY = TRUE, titleY = TRUE)
```

## The (sub)plot:

```r
print(sp)
```

![Plotly made with subplot](https://user-images.githubusercontent.com/1039904/51402932-a52a4580-1b2d-11e9-8d9c-4eb2571b4abb.png)

# **UPDATE**

Found a hacky solution to this, check my following comment.

**Comment by jumanbar** [comment]
Found a solution! It works even though it's a bit of a hack. I found out that I can use the function `tidyr::complete` to fill in the missing combination of cases into the `plot_data` table. Here's the new code for when I create `plot_data`:

```r
plot_data <- di %>%
  mutate(mids = midpoints,
         ints = intervals) %>%
  count(cut, color, mids, ints) %>% 
  complete(cut, color, mids, ints, fill = list(n = 0))
```

(This only adds one line to my code.)

The thing is, even though it works, it's much slower since `plot_data` now has 32340 rows instead of 48 (for example, when clicking one of the groups in the legend it has a noticeable lag before hidding the elements on the histograms).

Here's the plot generated with the modified code:

![Now it looks ok](https://user-images.githubusercontent.com/1039904/51406617-6e0d6180-1b38-11e9-9bde-da46350a7bba.png)

**Comment by cpsievert** [comment]
Interesting, thanks for the thorough report!

I think this could be considered a plotly.js bug, but the problem can be fixed by explicitly setting https://plot.ly/r/reference/#bar-width to 1/2 the bin width you desire. 

In other words, change

```r
add_bars() %>%
```

to 

```r
add_bars(width = 0.025) %>%
```

and believe the problem goes away, and you don't need the `tidyr::complete()` hack, right?

**Comment by jumanbar** [comment]
Hi! I've tried your suggestion and it works for the anomalous bin width, but it messes up the legend:

![result](https://user-images.githubusercontent.com/1039904/51497705-b039db80-1da2-11e9-8982-16f6c4e85fe3.png)

Seems like it has to do with the data split that I made to do the multiple plots: it just uses the legend for the first plot/chunk of data, which has only a sample of the whole set of categories.

**Comment by cpsievert** [comment]
Closing since the legend ordering is a separate issue
