### ISSUE TITLE
ggplotly give error when used with sf

### ISSUE THREAD

**Issue by Ammar-K** [ropensci/plotly#1457]
first of all, i love your work.

 this:-
```r
nc <- sf::st_read(system.file("shape/nc.shp", package = "sf"), quiet = TRUE)

p <-  ggplot(nc) +  geom_sf(aes(fill = AREA))

ggplotly(p)
```

return this:-
`Error: stat_sf requires the following missing aesthetics: geometry`

`R version 3.5.1 (2018-07-02)`
`Platform: x86_64-w64-mingw32/x64 (64-bit)`
`Running under: Windows >= 8 x64 (build 9200)`

`Matrix products: default`

`locale:`
`[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   `
`[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C    `                      
`[5] LC_TIME=English_United States.1252    `

`attached base packages:`
`[1] stats     graphics  grDevices utils     datasets  methods   base     `

`other attached packages:`
`[1] bindrcpp_0.2.2     plotly_4.8.0.9000  ggplot2_3.1.0.9000`

`loaded via a namespace (and not attached):`
` [1] Rcpp_1.0.0        later_0.7.5       pillar_1.3.1      compiler_3.5.1    bindr_0.1.1       class_7.3-14     `
` [7] tools_3.5.1       digest_0.6.18     jsonlite_1.6      tibble_1.4.2      gtable_0.2.0      viridisLite_0.3.0`
`[13] pkgconfig_2.0.2   rlang_0.3.0.1     shiny_1.2.0       DBI_1.0.0         rstudioapi_0.8    crosstalk_1.0.0`  
`[19] yaml_2.2.0        e1071_1.7-0.1     withr_2.1.2       dplyr_0.7.8       httr_1.3.1        htmlwidgets_1.3`  
`[25] classInt_0.3-1    grid_3.5.1        tidyselect_0.2.5  glue_1.3.0        data.table_1.11.8 sf_0.7-3        ` 
`[31] R6_2.3.0          purrr_0.2.5       tidyr_0.8.2       magrittr_1.5      promises_1.0.1    units_0.6-2      `
`[37] scales_1.0.0      htmltools_0.3.6   assertthat_0.2.0  xtable_1.8-3      mime_0.6          colorspace_1.3-2 `
`[43] httpuv_1.4.5.1    lazyeval_0.2.1    munsell_0.5.0     crayon_1.3.4   `

Many thanks

**Comment by cpsievert** [comment]
Interesting, thanks, FWIW this example works with the CRAN version of ggplot2 (3.1.0).

**Comment by Ammar-K** [comment]
Confirm, CRAN version of ggplot2 do not throw the error.
Thanks, I really needed that.

**Comment by MattCowgill** [comment]
I'm getting this problem with github ggplot2 as well
