### ISSUE TITLE
Violin plots with extremely sparse data

### ISSUE THREAD

**Issue by dchen71** [ropensci/plotly#1465]
I am trying to create violin plots but when I create a violin plot with all 0s, I unexpected get back an actual violin plot bounded around the 0s. In other plotting libraries including ggplot, I get back a straight line instead.

```r
testing = data.frame(x = rep(0,100))
plot_ly(testing, x = ~x, y = ~x, type = 'violin')
```

Additionally, when I change the spanmode to only consider the min and max, I still get a similar type of shape for the violin plot.

```r
testing = data.frame(x = rep(0,100))
plot_ly(testing, x = ~x, y = ~x, type = 'violin', spanmode = 'hard')
```

Is this expected behavior or is there a way to hide it as I typically plot very sparse data with actual data.

**Comment by cpsievert** [comment]
Hmm, I get the following:

<img width="710" alt="screen shot 2019-02-15 at 6 12 18 pm" src="https://user-images.githubusercontent.com/1365941/52890963-43212800-314d-11e9-894b-7a1a093cc1ec.png">

Perhaps try with the current github version?
