### ISSUE TITLE
Exporting a heatmap with dendrograms using orca does not show all row labels 

### ISSUE THREAD

**Issue by ndrubins** [ropensci/plotly#1470]
Hi,

I'm creating a heatmap to which I'm adding row and column dendrograms and then I'm trying to export the combined figure to a pdf using `orca`.

Here's an example:

```
library(plotly)
library(dplyr)
library(dendextend)
library(ggplot2)
library(ggdendro)

#create matrix
set.seed(1)
mat <- matrix(rnorm(25*5), nrow = 25, ncol = 5, dimnames = list(paste0("Row:",1:25), paste0("Long Col Name:",1:5)))

#create dendrograms
row.dend <- as.ggdend(as.dendrogram(hclust(dist(mat))))
col.dend <- as.ggdend(as.dendrogram(hclust(dist(t(mat)))))
row.dend$labels$label <- ""
row.dend$labels$col <- "black"
row.dend$segments$lwd <- 0.5
col.dend$labels$label <- ""
col.dend$labels$col <- "black"
col.dend$segments$lwd <- 0.5
col.ggdend <- ggplot()+geom_segment(data=col.dend$segments,aes(x=x,y=y,xend=xend,yend=yend))+annotate("text",size=4,hjust=1,x=col.dend$label$x,y=col.dend$label$y,label=col.dend$label$label,colour=col.dend$label$col)+labs(x="",y="")+
  theme_minimal()+theme(axis.text=element_blank(),axis.ticks=element_blank(),panel.grid=element_blank())
row.ggdend <- ggplot()+geom_segment(data=row.dend$segments,aes(x=x,y=y,xend=xend,yend=yend))+coord_flip()+annotate("text",size=4,hjust=1,x=row.dend$label$x,y=row.dend$label$y,label=row.dend$label$label,colour=row.dend$label$col)+labs(x="",y="")+
  labs(x="",y="")+theme_minimal()+theme(axis.text=element_blank(),axis.ticks=element_blank(),panel.grid=element_blank())

#create the heatmap
df <- reshape2::melt(mat)

#add dendrograms to the heatmap
heatmap.plot <- plot_ly(z=c(df$value),x=df$Var2,y=df$Var1,colors=grDevices::colorRamp(c("darkblue","lightgray","darkred")),type="heatmap")
heatmap.plot <- subplot(col.ggdend,plotly_empty(),heatmap.plot %>% layout(showlegend = F),row.ggdend,nrows=2,margin=c(0,0,0,0),widths=c(0.8,0.2),heights=c(0.2,0.8))

```

In the `RStudio`'s viewer the combined figure looks fine, meaning that all row labels are visible. However, when I export it using:

`orca(heatmap.plot, file = "heatmap.plot.pdf")
`
The resulting figure in the pdf downsamples the row labels (keeping only odd row labels).

I tried playing around with the `plotly` `layout` function's `t` an `b` argument values, as well as with the `width` and `height` argument values of `orca`. The former didn't help and as for the latter using values that are too small (e.g., `width = 0.8` and `height = 1`) got `orca` hanging.

On the other hand, if I use `plotly::export`, the sparse row labels issue does not occur, but the content of the color bar is missing.

Hope you can help me out

**Comment by cpsievert** [comment]
`height`/`width` are measured in pixels -- if you are thinking in inches, you can likely multiply by 96 to convert pixels to inches. You can also use `dev.size("px")` to get the current size of your graphics device (if you want to replicate what you see)
