### ISSUE TITLE
Is it possible to add a text aesthetic to geom_smooth to customize tooltips?

### ISSUE THREAD

**Issue by benjaminrobinson** [ropensci/plotly#1471]
---
Thanks so much again for your work, Carson!  I use your library a ton in my personal and professional work to create interactive graphics.  The code below works fine to produce a ggplotly chart with points and a fitted Loess regression line but I find the tool-tip on the geom_smooth to be lacking.  I would love to be able to customize the tool-tip for it like I have been able to do with the text aesthetic in geom_point like below.  Is it possible to do or am I thinking about this the wrong way?
```r
library(plotly)
library(ggplot2)

ggplotly(
    iris %>%
        ggplot(aes(x = Sepal.Length, y = Sepal.Width, color = Species, text = paste("Species:", Species, "<br>", "Sepal Length:", Sepal.Length, "<br>", "Sepal Width:", Sepal.Width), group = 1)) +
        geom_point() +
        geom_smooth(),
    tooltip = 'text'
)
```
I was thinking it would look similar to this...but I get a `Warning: Ignoring unknown aesthetics: text` message, which usually doesn't mean much and I can still get the tool-tips to work:
```r
library(plotly)
library(ggplot2)

ggplotly(
    iris %>%
        ggplot(aes(x = Sepal.Length, y = Sepal.Width, color = Species, text = paste("Species:", Species, "<br>", "Sepal Length:", Sepal.Length, "<br>", "Sepal Width:", Sepal.Width), group = 1)) +
        geom_point() +
        geom_smooth(aes(x = Sepal.Length, y = Sepal.Width, text = paste("<b>", "Sepal Length:", "</b>", Sepal.Length, "<br>", "<b>", "Sepal Width:", "</b>", Sepal.Length), group = 1), method = 'loess'),
    tooltip = 'text'
)
```

**Comment by cpsievert** [comment]
Providing `text` will only generally work if the **ggplot2** isn't aggregating the supplied data in some way. I will have a section on what you can do in these cases in the new edition of the [plotly book](https://plotly-book.cpsievert.me/) (remind me to point you there in the coming weeks)

**Comment by benjaminrobinson** [comment]
Thanks, Carson!  That would be great.

**Comment by cpsievert** [comment]
Actually, here is a preview https://5c75db4c3ace1e00093973d3--plotly-book.netlify.com/controlling-tooltips.html#tooltip-text-ggplotly

See the figure towards the bottom

**Comment by 666666888** [comment]
I get the information that Warning: Ignoring unknown aesthetics: text,but it can work in the picture,have any question?
