### ISSUE TITLE
Error when selecting points that are labeled by discrete colors

### ISSUE THREAD

**Issue by hzc363** [ropensci/plotly#1475]
---

When creating a shiny app, I encountered an error with plotly. I created a scatter plot and used the lasso selection tool to isolate a subset of points. The selection tool works when the point are labeled with continuous color scale. However, when they are labeled with discrete colors, the lasso selection tool does not return the correct ID of the points. 

I have created a minimalism shiny app as an example using IRIS dataset. If I choose the continuous variable "Patel.Length" as color label, the selection tool works as expected. However, if I choose the categorical variable "Species" as color label, the selection tool will return a wrong set of points. 

``` r
library(shiny)
library(plotly)

##### ui of shiny app ####
ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      
      # select color label of the points
      selectInput("color", label = "Color label",
                  choices = c("Petal.Length","Species"),
                  multiple=FALSE, selectize=TRUE)
    ),
    mainPanel(plotlyOutput("plot"),
              verbatimTextOutput("print"))))

##### server of the siny app #####
server <- function(input, output, session) {
    d = iris
    
    # display the selected data 
    output$plot <- renderPlotly({
      s1<- event_data("plotly_selected")
      if(!is.null(s1)){d_plot =  d[s1$pointNumber+1,]}else{d_plot=d}

      p <- ggplot(d_plot, aes_string(x = "Sepal.Length", y = "Sepal.Width")) +
        geom_point(aes_string(color = input$color))
      ggplotly(p)%>% layout(dragmode = "lasso")
    })
    
    # print the id of selected points
    output$print <- renderPrint({
      s1 <- event_data("plotly_selected")
      if(!is.null(s1)){
        cat("The IDs of selected points are : ", (s1$pointNumber+1))
      }
    })

}

##### run the app #####
shinyApp(ui, server)
```

**Comment by cpsievert** [comment]
The `pointNumber` column returned by `event_data()` is not what you think it is -- it's the index *within* the plotly.js trace. I don't recommend using `pointNumber`, and if I could turn back time, I wouldn't have exposed it at all in `event_data()`. 

Instead, if you want to know how a row in `s1` (the event data) maps to `d` (the original data), consider passing the row index through the `customdata` attribute:

```r

server <- function(input, output, session) {
  d <- iris
  d$.id <- seq_len(nrow(d))
  
  output$plot <- renderPlotly({
    gg <- ggplot(d, aes_string(x = "Sepal.Length", y = "Sepal.Width")) +
      geom_point(aes_string(color = input$color, customdata = ".id"))
    ggplotly(gg) %>% 
      layout(dragmode = "lasso") %>%
      event_register("plotly_selecting")
  })
  
  # the brushed observations
  output$print <- renderPrint({
    s1 <- event_data("plotly_selecting")
    d[d$.id %in% s1$customdata, ]
  })
  
}

shinyApp(ui, server)
```

**Comment by hzc363** [comment]
Thank you very much! The solution works! plotly_selected works better for me, since I do not want the plot to change while I am still drawing lasso.
