### ISSUE TITLE
Force plotly violin plot not to display a violin on zero values

### ISSUE THREAD

**Issue by ndrubins** [ropensci/plotly#1476]
Hi,

I have measurements from several groups which I would like to plot as violin plots:

 ```
   set.seed(1)
    df <- data.frame(val = c(runif(100,1,5),runif(100,1,5),rep(0,100)),
                     group = c(rep("A",100),rep("B",100),rep("C",100)))


```
When I use `R`'s `ggplot2`:

```
    library(ggplot2)
    ggplot(data = df, aes(x = group, y = val, color = group)) + geom_violin()

```
I get [this plot](https://imgur.com/bWxLRRc)

But when I try to get the equivalent with `R`'s `plotly` using:

```
    library(plotly)
    plot_ly(x = df$group, y = df$val, split = df$group, type = 'violin', box = list(visible = F), points = F, showlegend = T, color = df$group)

```
I get [this plot](https://imgur.com/8HnhspU) in which group "C" gets an inflated/artificial violin.

Can I tell `plot_ly` not to create violin for groups such as "C"?

**Comment by cpsievert** [comment]
This is something that should be fixed at the plotly.js level, see https://github.com/plotly/plotly.js/issues/2779
