### ISSUE TITLE
Invalid Error Message when adding Text

### ISSUE THREAD

**Issue by BenBilbro** [ropensci/plotly#1478]
I discovered this error when trying to add text to a Plotly graph in R. Shown below is code that compiles without any warnings or errors:
`p <- plot_ly(newCoords, x = ~Dim.1, y = ~Y, mode = 'markers', marker = list(size = 8), height = 600) %>%
  add_markers() %>%
  layout(
    xaxis = list(title = 'PC1'), 
    yaxis = list(title = 'Y')
  )`

When trying to annotate I changed the code to look like this:

`p <- plot_ly(newCoords, x = ~Dim.1, y = ~Y, text = rownames(newCoords), mode = 'markers', marker = list(size = 8), height = 600) %>%
  add_markers() %>%
  add_text(textposition = "top left") %>%
  layout(
    xaxis = list(title = 'PC1', range = c(-100, 120)), 
    yaxis = list(title = 'Y', range = c(-.1,.1))
  )`

This produces the plot I wanted, but it also prints out the error message:

`A marker object has been specified, but markers is not in the mode
Adding markers to the mode...`

Sorry for the awful formatting, just wondering if this a bug.

**Comment by cpsievert** [comment]
Do this instead:

```r
plot_ly(newCoords, x = ~Dim.1, y = ~Y, text = rownames(newCoords), height = 600) %>% add_markers(marker = list(size = 8)) %>% add_text(textposition = "top left")
```

**Comment by BenBilbro** [comment]
Thank you.
