### ISSUE TITLE
Visualization violin plot

### ISSUE THREAD

**Issue by workah0lic** [ropensci/plotly#1488]
Hi, I came across a problem regarding plotly violin plots in R - it can be seen in the first one of the examples on <https://plot.ly/r/violin/> (“Basic Violin Plot”).

```r
library(plotly)

df <- read.csv("https://raw.githubusercontent.com/plotly/datasets/master/violin_data.csv")

p <- df %>%
  plot_ly(
    y = ~total_bill,
    type = 'violin',
    box = list(
      visible = T
    ),
    meanline = list(
      visible = T
    ),
    x0 = 'Total Bill'
  ) %>% 
  layout(
    yaxis = list(
      title = "",
      zeroline = F
    )
  )

# Create a shareable link to your chart
# Set up API credentials: https://plot.ly/r/getting-started
chart_link <- api_create(p, filename = "violin-basic")
chart_link
```

If I investigate the dataset, the lowest value for “total_bill” is 3.07:
`min(df$total_bill) # 3.07
`

However, the lower end of the violin plot even reaches below zero (y-axis). Is this result a bug or expected - and (how) can it be “fixed”?

![example1_violin](https://user-images.githubusercontent.com/19282100/54263815-03920400-4572-11e9-95fc-368369d89288.PNG)

I found another user who identified this as a problem: <https://stackoverflow.com/questions/55011840/force-plotly-violin-plot-not-to-display-a-violin-on-zero-values>

Unfortunately, I can’t use the solution of hiding a certain group, as I do want to show the existing values within this very same group (I have this problem in the upper as well as in the lower area of my plots, but I do want to plot the existing values in the middle).

I’d appreciate any help and/or clarification!

Best regards,
david

**Comment by cpsievert** [comment]
If you want to stop the violin at the min/max, you can set `spanmode = "hard"`. Please route future questions to https://community.rstudio.com/
