### ISSUE TITLE
Synchronizing multiple timeseries plots with range selectors

### ISSUE THREAD

**Issue by vagifaliyev** [ropensci/plotly#1490]
Hello, 

I really enjoy the library which I am using in JavaScript for my uni project, unfortunately I have run into synchronization issues between multiple timeseries graphs on the page, this is basically the same thing as issue #298 which was opened several years ago, but unfortunately I did not find the solution to it:

I have two graphs on the same page which display different column from a CSV file but they both correspond to the same time data set by the 3rd column, the range selectors work fine but I was wondering if its possible to change the range on both graphs by only dragging one of them. 

This is behavior I am after: https://rstudio.github.io/dygraphs/gallery-synchronization.html

Thanks again for such a great library!

**Comment by cpsievert** [comment]
> Please briefly describe your problem and what output you expect. If you have a question, please don't use this form, but instead ask on the community forum <http://community.plot.ly/c/api/r> or stackoverflow <http://stackoverflow.com>.

BTW, I think you're looking for `shareX` in `subplot()`?  https://plotly-r.com/merging-plotly-objects.html#fig:economics
