### ISSUE TITLE
installing from github doesnt seem to be complete

### ISSUE THREAD

**Issue by ldfreight** [ropensci/plotly#1492]
Hello, 

I am on Windows 10

This was my installation folder after installing from CRAN plotly version 4.8.0:
![image](https://user-images.githubusercontent.com/23113465/54520027-b0b9b180-49a2-11e9-86bb-2bfeb1e7b498.png)

I tried to install from github using

```r
devtools::install_github("ropensci/plotly")
```

However now any simple plotly graph will fail when displaying it, even the ones from  [https://plot.ly/r/line-charts/](https://plot.ly/r/line-charts/ )

The error doesnt  happens when computing the graph and saving it to a variable, but when printing the variable to a Viewer

`Error in dirname(to) : a character vector argument expected`

Looking at the installion folder, I now see much less files:
![image](https://user-images.githubusercontent.com/23113465/54519825-62a4ae00-49a2-11e9-98a7-3d2008f3fc5e.png)

Note that I tried several times to install from github, and do not get any error.

Then I tried a crazy thing: I copied the missing file from previous installation folder to the new one (skipping files which are now there), and everything seems to work now.

Is this a bug?

**Comment by cpsievert** [comment]
Hmm, perhaps try restarting R after installing? If that doesn't work, please report the output of `devtools::session_info()`

**Comment by cpsievert** [comment]
Feel free to reopen if you're still having problems and have more information for me.
