### ISSUE TITLE
Combining plotly plots by subplot  doesn't seem to be compatible with event_data() source 

### ISSUE THREAD

**Issue by niekverw** [ropensci/plotly#1504]
I would like to be able to use `event_data()` in plots that are combined and be able to process clicks on a sub plot. As I understand, combining plotly plots is solely possible with subplot. However, it seems that the source command isn't supported by subplot, which is needed to direct event_data(). 

````
source: a character string of length 1. Match the value of this string with the source argument in event_data() to retrieve the event data corresponding to a specific plot (shiny apps can have multiple plots).
````

e.g. this doesn't work 

`subplot(ggplotly(p1, source="source_rp"), p2 , nrows = 2, margin = 0.09, heights = c(0.8, 0.2))`

this also doesn't work

`subplot(p1, p2 , nrows = 2, margin = 0.09, heights = c(0.8, 0.2), source="source_rp")`

Is there a way around this? or is this not yet implemented?

the error that I am getting is: `Warning: Can only have one: source`

**Comment by cpsievert** [comment]
One way to do this would be to set the source ID to the same plot object going into `subplot()`, like this:

```r
s <- subplot(ggplotly(qplot(1:10), source="myID"), ggplotly(qplot(1:10), source="myID"), plot_ly(x = 1:10, y = 1:10, source = "myID"))
```

You can check it did the right thing like this

```r
s$x$source
#> [1] "myID"
```

Is that's too much of a hassle you could also set the source ID after-the-fact:

```r
s$x$source <- "otherID"
```

**Comment by cpsievert** [comment]
Also, `Warning: Can only have one: source` is a warning, not an error
