### ISSUE TITLE
plotly package installation

### ISSUE THREAD

**Issue by ghatfan99** [ropensci/plotly#152]
i want to install plotly package in R, from github

library(devtools)
install_github("ropensci/plotly")
and i have an error message:

Downloading github repo ropensci/plotly@master
Error in function (type, msg, asError = TRUE)  : couldn't connect to host
i have searched on the internet and i found that it's a problem of proxy, i tried:

set_config(
use_proxy(url="https://github.com/ropensci/plotly", port=8080, username="***",password="***")
)
but still have the same problem, i don't know what to put in url and port values, i have two accounts on Githup and plotly

thank you for your help

**Comment by mkcor** [comment]
I'm not familiar with the `httr` package, but looking up `use_proxy()`, I gather that the `url` argument should be your proxy IP (not the "plotly" repo).

**Comment by ghatfan99** [comment]
@mkcor thank's for your answer, 
Does anyone knows how to install the packages from Github manually, i tried downloading the zip file from https://github.com/ropensci/plotly and after that in my Rstudio i installed the package from zip file, but when i tape : 
library(plotly)
Error in library(plotly) : there is no package called ‘plotly’

thanks

**Comment by mkcor** [comment]
@ghatfan99 How did you install the package from the zip file, please? Can you share the command plus its output, please?

**Comment by ghatfan99** [comment]
Hello mkcor,
after you have downloaded the zip file of any package in R to your hard disk, you have two choices to install the package:
1. in console: install.packages("C:/Users/.../plotly_master.zip", repos = NULL)
here i have no error message:
"Installing package into ‘C:/Users/.../Documents/R/win-library/3.1’
(as ‘lib’ is unspecified)"
now when i do:
library(plotly_master)
i have the error: Error in library(plotly_master) : 
  there is no package called ‘plotly_master’

Regards

**Comment by mkcor** [comment]
Okay -- although the zip file you download should be named `plotly-master.zip`, not `plotly_master.zip`...

Then you should load "plotly":
```r
library(plotly)
```
not "plotly_master".

**Comment by ghatfan99** [comment]
Hello mkcor
i tried the instructions as you mentioned but still have the same problem:

> install.packages("C:/Users/.../Downloads/plotly-master.zip", repos = NULL)
Installing package into ‘C:/Users/.../Documents/R/win-library/3.1’
(as ‘lib’ is unspecified)
> library(plotly)
Error in library(plotly) : ‘plotly’ is not a valid installed package
i don't understand where is the problem?

**Comment by mkcor** [comment]
After running the `install.packages()` command, can you check that you actually have a `plotly` directory at `C:/Users/.../Documents/R/win-library/3.1/`? You should see your other R packages there as well.
Once you have made sure where the `plotly` package got installed, please load it with
```r
require(plotly, lib.loc="C:/Users/.../Documents/R/win-library/3.1")
```
where argument `lib.loc` is the location of R library trees to search through (see official docs).

Let me Cc @msund who may have assisted Windows users with their install issues.

**Comment by cpsievert** [comment]
Closing this since it's not a problem with the R package itself...

Assuming you have the source files locally, you can also install with `R CMD INSTALL` or `devtools::install()`:

```
git clone https://github.com/ropensci/plotly.git
Rscript -e "devtools::install('plotly')"
```

**Comment by vishy730** [comment]
Hi, have downloaded zip file from this location, https://github.com/ropensci/plotly/releases/tag/0.3
and tried teh above steps.. with type=source.. neither it gave error nor installed..
I am using windows server 2012 and latest R and Rstudio versions

**Comment by mkcor** [comment]
@vishy730 That version is super outdated... Please refer to https://plot.ly/r/getting-started/ for up-to-date information on how to install and load the "plotly" R package.

**Comment by vishy730** [comment]
Thanks mkcor, I could solve the issue...

**Comment by mkcor** [comment]
@vishy730 Great, I'm glad!

**Comment by h3ncabo** [comment]
I have the same issue, tried mkcor's suggestions but instead of seeing a plotly directory, i see plotly-master....

**Comment by h3ncabo** [comment]
I have the same issue, tried mkcor's suggestions but instead of seeing a plotly directory, i see plotly-master....I get this mesasage when

>Loading required package: plotly
>Warning message:
>In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
>there is no package called ‘plotly’

**Comment by 13bzhang** [comment]
@h3ncabo Sorry you're experiencing this problem. Can you provide us with the exact code you used and what type of operation system you're using?

**Comment by h3ncabo** [comment]
@13bzhang 
I'm using Windows 8.1. I tried installing by ```install_github("ropensci/plotly")```
but did not work since my college uses a proxy and is not inclined to provide me details/access
so I tried local installation
```install.packages("C:/Users/.../Downloads/plotly-master.zip", repos = NULL, type="source")```
then I got that error above

**Comment by 13bzhang** [comment]
Hi! Have you talked to your system administrator about this issue? At my university, sometimes you need permission to install certain things.

**Comment by h3ncabo** [comment]
@13bzhang yes. its not possible. any comment on the exact code I use? Is there an alternative?
