### ISSUE TITLE
how to reshape dataframe for sunburst?   

### ISSUE THREAD

**Issue by liygzting** [ropensci/plotly#1529]
Hi   
when i RUN this example:
library(plotly)

d1 <- read.csv('https://raw.githubusercontent.com/plotly/datasets/master/coffee-flavors.csv')
d2 <- read.csv('https://raw.githubusercontent.com/plotly/datasets/718417069ead87650b90472464c7565dc8c2cb1c/sunburst-coffee-flavors-complete.csv')
p <- plot_ly() %>%
  add_trace(
    ids = d1$ids,
    labels = d1$labels,
    parents = d1$parents,
    type = 'sunburst',
    maxdepth = 2,
    domain = list(column = 0)
    ) %>%
  add_trace(
    ids = d2$ids,
    labels = d2$labels,
    parents = d2$parents,
    type = 'sunburst',
    maxdepth = 3,
    domain = list(column = 1)
  ) %>%
    layout(
      grid = list(columns =2, rows = 1),
      margin = list(l = 0, r = 0, b = 0, t = 0),
      sunburstcolorway = c(
        "#636efa","#EF553B","#00cc96","#ab63fa","#19d3f3",
        "#e763fa", "#FECB52","#FFA15A","#FF6692","#B6E880"
      ),
      extendsunburstcolors = TRUE)

it work well 

how can i change dataframe to the data like d2?

**Comment by liygzting** [comment]
> head(tmp)
                 vin iswk crkpdnm hh crkpdnm_stop cnt
1: L6T792423JN451621 周末    公司  0         其他   1
2: L6T792423JN451621 周末    公司  1         其他   1
3: L6T792423JN451621 周末    公司  2           家   1
4: L6T792423JN451621 周末    公司  5           家   1
5: L6T792423JN451621 周末    公司  6           家   2
6: L6T792423JN451621 周末    公司  7         公司   1
 
There are four columns like that，or more
Is there any way to convert quickly?

**Comment by ismirsehregal** [comment]
Please see [this](https://stackoverflow.com/questions/57395424/how-to-format-data-for-plotly-sunburst-diagram) related SO question.
