### ISSUE TITLE
Forecast using ggplotly() not working anymore

### ISSUE THREAD

**Issue by Gui-go** [ropensci/plotly#1535]
After making a forecat, using an ARIMA model, It is only possible to check the results in autoplot(). Although, what really matters to me is the interactivity of ggplotly(), but this function is not working properly for forecasts anymore, It was a few months ago :/

```{r}
library(forecast)
TTAF <- forecast(auto.arima(WWWusage), h = 60)
ggplotly(autoplot(TTAF))

```

Please help

**Comment by cpsievert** [comment]
forecast now uses a custom ggplot2 geom, which is why it no longer works. I have a note to implement in #566
