### ISSUE TITLE
WebGL in RStudio viewer panel

### ISSUE THREAD

**Issue by mladencucak** [ropensci/plotly#1537]
I have a problem with 3D plotting in RStudio.  
the error message:  
![image](https://user-images.githubusercontent.com/11738104/58216835-e3d73480-7cb4-11e9-8a47-fdd0d171235d.png)

When I click the link :  
![image](https://user-images.githubusercontent.com/11738104/58216785-bdb19480-7cb4-11e9-9611-8e97f20bda8b.png)

My session info: 
` Session info ------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.0 (2019-04-26)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/Los_Angeles         
 date     2019-05-22                  

- Packages ----------------------------------------------------------------------------------------------------------
 package          * version    date       lib source                            
 abind              1.4-5      2016-07-21 [1] CRAN (R 3.5.0)                    
 assertthat         0.2.1      2019-03-21 [1] CRAN (R 3.5.3)                    
 backports          1.1.4      2019-04-10 [1] CRAN (R 3.5.3)                    
 boot               1.3-20     2017-08-06 [1] CRAN (R 3.5.1)                    
 broom              0.5.2      2019-04-07 [1] CRAN (R 3.5.3)                    
 callr              3.2.0      2019-03-15 [1] CRAN (R 3.5.3)                    
 car              * 3.0-2      2018-08-23 [1] CRAN (R 3.5.2)                    
 carData          * 3.0-2      2018-09-30 [1] CRAN (R 3.5.2)                    
 cellranger         1.1.0      2016-07-27 [1] CRAN (R 3.5.1)                    
 checkmate          1.9.3      2019-05-03 [1] CRAN (R 3.5.3)                    
 cli                1.1.0      2019-03-19 [1] CRAN (R 3.5.3)                    
 codetools          0.2-15     2016-10-05 [1] CRAN (R 3.5.1)                    
 coin               1.3-0      2019-03-08 [1] CRAN (R 3.5.3)                    
 colorspace         1.4-1      2019-03-18 [1] CRAN (R 3.5.3)                    
 commonmark         1.7        2018-12-01 [1] CRAN (R 3.5.2)                    
 crayon             1.3.4      2017-09-16 [1] CRAN (R 3.5.1)                    
 crosstalk          1.0.0      2016-12-21 [1] CRAN (R 3.5.1)                    
 curl               3.3        2019-01-10 [1] CRAN (R 3.5.3)                    
 data.table       * 1.12.2     2019-04-07 [1] CRAN (R 3.5.3)                    
 desc               1.2.0      2018-05-01 [1] CRAN (R 3.5.1)                    
 DescTools          0.99.28    2019-03-17 [1] CRAN (R 3.5.3)                    
 devtools           2.0.2      2019-04-08 [1] CRAN (R 3.5.3)                    
 digest             0.6.18     2018-10-10 [1] CRAN (R 3.5.1)                    
 dplyr            * 0.8.0.1    2019-02-15 [1] CRAN (R 3.5.3)                    
 EMT                1.1        2013-01-29 [1] CRAN (R 3.5.2)                    
 evaluate           0.13       2019-02-12 [1] CRAN (R 3.5.3)                    
 expm               0.999-4    2019-03-21 [1] CRAN (R 3.5.3)                    
 fansi              0.4.0      2018-10-05 [1] CRAN (R 3.5.2)                    
 forcats          * 0.4.0      2019-02-17 [1] CRAN (R 3.5.3)                    
 forecast           8.7        2019-04-29 [1] CRAN (R 3.5.3)                    
 foreign            0.8-70     2017-11-28 [1] CRAN (R 3.5.1)                    
 fracdiff           1.4-2      2012-12-02 [1] CRAN (R 3.5.1)                    
 fs                 1.3.0      2019-05-02 [1] CRAN (R 3.5.3)                    
 generics           0.0.2      2018-11-29 [1] CRAN (R 3.5.2)                    
 ggplot2          * 3.1.1      2019-04-07 [1] CRAN (R 3.5.3)                    
 ggridges         * 0.5.1      2018-09-27 [1] CRAN (R 3.5.2)                    
 ggthemes         * 4.1.1      2019-04-09 [1] CRAN (R 3.5.3)                    
 glue               1.3.1      2019-03-12 [1] CRAN (R 3.5.3)                    
 gridExtra          2.3        2017-09-09 [1] CRAN (R 3.5.1)                    
 gt               * 0.1.0      2018-12-28 [1] Github (rstudio/gt@e8bc46e)       
 gtable             0.3.0      2019-03-25 [1] CRAN (R 3.5.3)                    
 haven              2.1.0      2019-02-19 [1] CRAN (R 3.5.3)                    
 here             * 0.1        2017-05-28 [1] CRAN (R 3.5.2)                    
 hms                0.4.2      2018-03-10 [1] CRAN (R 3.5.1)                    
 htmltools          0.3.6      2017-04-28 [1] CRAN (R 3.5.1)                    
 htmlwidgets        1.3        2018-09-30 [1] CRAN (R 3.5.2)                    
 httpuv             1.5.1      2019-04-05 [1] CRAN (R 3.5.3)                    
 httr               1.4.0      2018-12-11 [1] CRAN (R 3.5.2)                    
 imputeTS         * 2.7        2018-06-20 [1] CRAN (R 3.5.1)                    
 inline             0.3.15     2018-05-18 [1] CRAN (R 3.5.1)                    
 jsonlite           1.6        2018-12-07 [1] CRAN (R 3.5.2)                    
 knitr            * 1.22       2019-03-08 [1] CRAN (R 3.5.3)                    
 labeling           0.3        2014-08-23 [1] CRAN (R 3.5.0)                    
 later              0.8.0      2019-02-11 [1] CRAN (R 3.5.3)                    
 lattice            0.20-35    2017-03-25 [1] CRAN (R 3.5.1)                    
 lazyeval           0.2.2      2019-03-15 [1] CRAN (R 3.5.3)                    
 leaflet          * 2.0.2      2018-08-27 [1] CRAN (R 3.5.2)                    
 libcoin            1.0-4      2019-02-28 [1] CRAN (R 3.5.3)                    
 lmtest             0.9-37     2019-04-30 [1] CRAN (R 3.5.3)                    
 loo                2.1.0      2019-03-13 [1] CRAN (R 3.5.3)                    
 lubridate        * 1.7.4      2018-04-11 [1] CRAN (R 3.5.1)                    
 magrittr           1.5        2014-11-22 [1] CRAN (R 3.5.1)                    
 manipulate         1.0.1      2014-12-24 [1] CRAN (R 3.5.0)                    
 manipulateWidget   0.10.0     2018-06-11 [1] CRAN (R 3.5.1)                    
 MASS               7.3-50     2018-04-30 [1] CRAN (R 3.5.1)                    
 Matrix             1.2-14     2018-04-13 [1] CRAN (R 3.5.1)                    
 matrixStats        0.54.0     2018-07-23 [1] CRAN (R 3.5.1)                    
 memoise            1.1.0      2017-04-21 [1] CRAN (R 3.5.1)                    
 mgcv               1.8-24     2018-06-23 [1] CRAN (R 3.5.1)                    
 mgsub            * 1.7.1      2019-03-13 [1] CRAN (R 3.5.3)                    
 mime               0.6        2018-10-05 [1] CRAN (R 3.5.1)                    
 miniUI             0.1.1.1    2018-05-18 [1] CRAN (R 3.5.1)                    
 modelr             0.1.4      2019-02-18 [1] CRAN (R 3.5.3)                    
 modeltools         0.2-22     2018-07-16 [1] CRAN (R 3.5.2)                    
 multcomp           1.4-10     2019-03-05 [1] CRAN (R 3.5.3)                    
 multcompView       0.1-7      2015-07-31 [1] CRAN (R 3.5.1)                    
 munsell            0.5.0      2018-06-12 [1] CRAN (R 3.5.1)                    
 mvtnorm            1.0-10     2019-03-05 [1] CRAN (R 3.5.2)                    
 nlme               3.1-137    2018-04-07 [1] CRAN (R 3.5.1)                    
 nnet               7.3-12     2016-02-02 [1] CRAN (R 3.5.1)                    
 nortest            1.0-4      2015-07-30 [1] CRAN (R 3.5.2)                    
 openxlsx           4.1.0      2018-05-26 [1] CRAN (R 3.5.1)                    
 packrat            0.5.0      2018-11-14 [1] CRAN (R 3.5.2)                    
 pander           * 0.6.3      2018-11-06 [1] CRAN (R 3.5.2)                    
 pillar             1.3.1      2018-12-15 [1] CRAN (R 3.5.2)                    
 pkgbuild           1.0.3      2019-03-20 [1] CRAN (R 3.5.3)                    
 pkgconfig          2.0.2      2018-08-16 [1] CRAN (R 3.5.2)                    
 pkgload            1.0.2      2018-10-29 [1] CRAN (R 3.5.2)                    
 plotly           * 4.9.0      2019-04-10 [1] CRAN (R 3.5.3)                    
 plyr               1.8.4      2016-06-08 [1] CRAN (R 3.5.1)                    
 prettyunits        1.0.2      2015-07-13 [1] CRAN (R 3.5.1)                    
 processx           3.3.0      2019-03-10 [1] CRAN (R 3.5.3)                    
 promises           1.0.1      2018-04-13 [1] CRAN (R 3.5.1)                    
 ps                 1.3.0      2018-12-21 [1] CRAN (R 3.5.2)                    
 purrr            * 0.3.2      2019-03-15 [1] CRAN (R 3.5.3)                    
 quadprog           1.5-5      2013-04-17 [1] CRAN (R 3.5.0)                    
 quantmod           0.4-14     2019-03-24 [1] CRAN (R 3.5.3)                    
 R.methodsS3      * 1.7.1      2016-02-16 [1] CRAN (R 3.5.0)                    
 R.oo             * 1.22.0     2018-04-22 [1] CRAN (R 3.5.0)                    
 R.utils          * 2.8.0      2019-02-14 [1] CRAN (R 3.5.3)                    
 R6                 2.4.0      2019-02-14 [1] CRAN (R 3.5.3)                    
 RColorBrewer     * 1.1-2      2014-12-07 [1] CRAN (R 3.5.0)                    
 rcompanion       * 2.1.7      2019-04-09 [1] CRAN (R 3.5.3)                    
 Rcpp               1.0.1      2019-03-17 [1] CRAN (R 3.6.0)                    
 readr            * 1.3.1      2018-12-21 [1] CRAN (R 3.5.2)                    
 readxl           * 1.3.1      2019-03-13 [1] CRAN (R 3.5.3)                    
 remotes            2.0.4      2019-04-10 [1] CRAN (R 3.5.3)                    
 rgl              * 0.100.19   2019-03-12 [1] CRAN (R 3.5.3)                    
 rio                0.5.16     2018-11-26 [1] CRAN (R 3.5.2)                    
 rlang              0.3.4      2019-04-07 [1] CRAN (R 3.5.3)                    
 rmarkdown          1.12.6     2019-04-20 [1] Github (rstudio/rmarkdown@9923811)
 rprojroot          1.3-2      2018-01-03 [1] CRAN (R 3.5.1)                    
 rstan              2.18.2     2018-11-07 [1] CRAN (R 3.5.2)                    
 rstudioapi         0.10       2019-03-19 [1] CRAN (R 3.5.3)                    
 rvest              0.3.3      2019-04-11 [1] CRAN (R 3.5.3)                    
 sandwich           2.5-1      2019-04-06 [1] CRAN (R 3.5.3)                    
 sass               0.1.0.9000 2018-12-28 [1] Github (rstudio/sass@c73867d)     
 scales             1.0.0      2018-08-09 [1] CRAN (R 3.5.2)                    
 scatterplot3d      0.3-41     2018-03-14 [1] CRAN (R 3.5.2)                    
 sessioninfo        1.1.1      2018-11-05 [1] CRAN (R 3.5.2)                    
 shiny              1.3.2      2019-04-22 [1] CRAN (R 3.5.3)                    
 StanHeaders        2.18.1     2019-01-28 [1] CRAN (R 3.5.3)                    
 stinepack          1.4        2018-07-30 [1] CRAN (R 3.5.2)                    
 stringi            1.4.3      2019-03-12 [1] CRAN (R 3.5.3)                    
 stringr          * 1.4.0      2019-02-10 [1] CRAN (R 3.5.3)                    
 survival           2.42-3     2018-04-16 [1] CRAN (R 3.5.1)                    
 testthat           2.1.1      2019-04-23 [1] CRAN (R 3.5.3)                    
 TH.data            1.0-10     2019-01-21 [1] CRAN (R 3.5.3)                    
 tibble           * 2.1.1      2019-03-16 [1] CRAN (R 3.5.3)                    
 tidyr            * 0.8.3      2019-03-01 [1] CRAN (R 3.5.3)                    
 tidyselect         0.2.5      2018-10-11 [1] CRAN (R 3.5.2)                    
 tidyverse        * 1.2.1      2017-11-14 [1] CRAN (R 3.5.2)                    
 timeDate           3043.102   2018-02-21 [1] CRAN (R 3.5.0)                    
 tseries            0.10-46    2018-11-19 [1] CRAN (R 3.5.2)                    
 TTR                0.23-4     2018-09-20 [1] CRAN (R 3.5.2)                    
 urca               1.3-0      2016-09-06 [1] CRAN (R 3.5.1)                    
 usethis            1.5.0      2019-04-07 [1] CRAN (R 3.5.3)                    
 utf8               1.1.4      2018-05-24 [1] CRAN (R 3.5.1)                    
 viridisLite        0.3.0      2018-02-01 [1] CRAN (R 3.5.1)                    
 webshot            0.5.1      2018-09-28 [1] CRAN (R 3.5.1)                    
 withr              2.1.2      2018-03-15 [1] CRAN (R 3.5.1)                    
 xfun               0.6        2019-04-02 [1] CRAN (R 3.5.3)                    
 xml2               1.2.0      2018-01-24 [1] CRAN (R 3.5.1)                    
 xtable             1.8-4      2019-04-21 [1] CRAN (R 3.5.3)                    
 xts                0.11-2     2018-11-05 [1] CRAN (R 3.5.2)                    
 yaml               2.2.0      2018-07-25 [1] CRAN (R 3.5.1)                    
 zip                2.0.1      2019-03-11 [1] CRAN (R 3.5.3)                    
 zoo              * 1.8-5      2019-03-21 [1] CRAN (R 3.5.3)                    

[1] C:/Users/mlade/Documents/R/library
[2] C:/Program Files/R/R-3.6.0/library
> `

**Comment by cpsievert** [comment]
What version of RStudio are you using? If you update RStudio to the latest stable release, I believe this problem will go away, feel free to reopen if it doesn't

**Comment by mladencucak** [comment]
I have updated Rstudio last week (RStudio Desktop 1.2.1335)

**Comment by cpsievert** [comment]
Unfortunately there are a lot of different factors that can contribute to this problem that are not related to the plotly package (it has to do with your system setup and RStudio). I'd recommend trying the workarounds in [this post](https://community.rstudio.com/t/webgl-is-not-supported-by-your-browser-plotly/13962/20) and trying the [preview](https://www.rstudio.com/products/rstudio/download/preview/) release as well as the [daily builds](https://dailies.rstudio.com/) of RStudio.

If you open the plotly graphs outside of RStudio, do they render?
