### ISSUE TITLE
Time Series Graph Issue In Plotly

### ISSUE THREAD

**Issue by cyruslentin** [ropensci/plotly#154]
Refer to URL https://cyruslentin.shinyapps.io/kiei-proj/
Giving below code for ggplot2 & plotly via ggplot2 both using Shiny Apps

In the above URL, please refer to IIP > SpecificIndex > Mode = QuickGraph //normal ggplot graph
**Code**
```
fileData <- read.csv("xsiFileData.csv") #csv file is attached herewith
par(mfrow=c(1,1), pin=c(6,4))
xsiDataPlot <- ggplot(data=fileData, aes(x=FiscalMonth, y=CurrentMonth, label=CurrentMonth, group=1, color="ThisYear")) +
   geom_line(lwd=1.3) +
   geom_point(aes(y=CurrentMonth), size=2, color="black") +
   geom_line(mapping=aes(x=FiscalMonth, y=PreviousYear, label=PreviousMonth, group=1, color="PrevYear"),lwd=1.1) +
   geom_point(aes(y=PreviousYear), size=2, color="black") +
   xlab("Month") + ylab("IIP Data") +
   theme(axis.text.x=element_text(angle=80, hjust=1, vjust=1)) +
   theme(legend.title=element_blank())
```
*Note*
This works as required. Note that in this graph "geom_points" are used.

In the above URL, please refer to IIP > SpecificIndex > Mode = QuickGraph //normal ggplot graph
**Code**
```
fileData <- read.csv("xsiFileData.csv") #csv file is attached herewith ... same as above
par(mfrow=c(1,1), pin=c(6,4))
xsiDataPlot <- ggplot(data=fileData, aes(x=FiscalMonth, y=CurrentMonth, label=CurrentMonth, group=1, color="ThisYear")) +
   geom_line(lwd=1.3) +
   #geom_point(aes(y=CurrentMonth), size=2, color="black") +
   geom_line(mapping=aes(x=FiscalMonth, y=PreviousYear, label=PreviousMonth, group=1, color="PrevYear"),lwd=1.1) +
   #geom_point(aes(y=PreviousYear), size=2, color="black") +
   xlab("Month") + ylab("IIP Data") +
   theme(axis.text.x=element_text(angle=80, hjust=1, vjust=1)) +
   theme(legend.title=element_blank())
```
*Note*
For plotly to generate the graph, the geom_point line has to be commented. 
The error message given is "undefined columns selected"
Even after commenting, the required graph in plotly is not proper. 
Shows "null" in x-axis.

**Query**
Surely I am missing something ... is there something required to be done in plotly.
Is there a work around?

PS - how does one upload a csv file here?

**Comment by cyruslentin** [comment]
Please treat this as resolved.

I removed the "label=CurrentMonth" from the ggplot line and the graph appeared properly.

Though I still had to comment the goem_point for it to work.

**Comment by mkcor** [comment]
Thanks, @cyruslentin.

Could you try and pass an `x` aesthetic under `geom_point()`, in addition to the `y` aesthetic?

I would happily troubleshoot the issue, but where can I find the CSV (or a sample thereof)?
