### ISSUE TITLE
Add support for changing orientation of hover label

### ISSUE THREAD

**Issue by hmhensen** [ropensci/plotly#1541]
I would like to create a column chart with hover labels that hover above the bars instead of to the left or right side. This does not appear possible to do in the `R` implementation of `plotly`. Here's a sample `d3` chart I found online that does what I would like to do: bl.ocks.org/Caged/6476579.

Below is sample code of a simple column chart with a hover label.

```r
library(dplyr)
library(plotly)
data.frame(x = 1:10, y = 1:10*10) %>% 
  plotly::plot_ly(data = .) %>%
  plotly::add_trace(x = ~x, 
                    y = ~y, 
                    type = 'bar', 
                    hoverinfo = "text", 
                    text = ~y)
```

**Comment by cpsievert** [comment]
I don't think there is an easy option for this, but you can always implement your own hover functionality in JS https://plotly-r.com/supplying-custom-data.html#fig:tooltip-image

**Comment by cpsievert** [comment]
By the way, I closed this since this, if implemented should be done at the plotly.js level, so please file an issue here if you'd like to see that happen https://github.com/plotly/plotly.js/issues/new
