### ISSUE TITLE
Hover info broken on 3d scatter plot

### ISSUE THREAD

**Issue by deliciouslytyped** [ropensci/plotly#1547]
I'm running into something that looks like https://github.com/plotly/plotly.js/issues/3258 and https://github.com/plotly/plotly.py/issues/952 on 4.8.0 and I don't know what to do.

My code is just a simple `plot_ly(data, x= ~a,y=~b,z=~c)`.

**Comment by deliciouslytyped** [comment]
An example of a temporary workaround is `plot_ly(data, x= ~a,y=~b,z=~c, opacity=0.99)`.

**Comment by cpsievert** [comment]
Please provide a reproducible example and your `devtools::session_info()`

**Comment by deliciouslytyped** [comment]
I failed to realize 4.8.0 is almost a year old now. The fixes to my problem were incorporated in a plotly.js version that is newer, so this will likely be fixed by updating. I'll give it a shot tomorrow.

**Comment by cpsievert** [comment]
Please reopen if it isn't

**Comment by deliciouslytyped** [comment]
In a moment of motivation, I did the update, several things work better now. :ok_hand:
