### ISSUE TITLE
%V in tickformat is not formated as described in docs

### ISSUE THREAD

**Issue by nbbn** [ropensci/plotly#1549]
Dear Maintainers,
I wanted to use isoweek (%V) according to [documentation](https://github.com/d3/d3-time-format/blob/master/README.md#locale_format) in R code:
`
    plot <- plot %>%
      layout(
        xaxis = list(
          title = "Week",
          type = 'date',
          tickformat = "%V"
        ), ...
`

however, I see:
![image](https://user-images.githubusercontent.com/7264317/59520968-72f9f580-8ecb-11e9-9cb6-74259b1e046b.png)

Thanks for any hints how to solve it.

**Comment by cpsievert** [comment]
Thanks, I've ported the issue to https://github.com/plotly/plotly.js/issues/4040, please follow progress there.
