### ISSUE TITLE
Support functions from "scales" package

### ISSUE THREAD

**Issue by mkcor** [ropensci/plotly#155]
For example,
```r
ggplot(iris, aes(x = Sepal.Length, y = Petal.Width/Petal.Length)) + geom_point() +
  scale_y_continuous(labels = percent_format())
```
does not work in plain "ggplot2" (you need to install and load "scales").

At the moment, `ggplotly()` does not convert (ignores) the `labels = percent_format()` part.

/cc @sckott

**Comment by sckott** [comment]
hi @mkcor - did you need help with this?

**Comment by mkcor** [comment]
We're not sure about adding the "scales" dependency...  Do you have an opinion?

Thanks for checking in!

**Comment by sckott** [comment]
@mkcor depends on how you use functions from `scales` i think. 

Do you mean to expose them to users? Or just use functions from `scales` internally?  

`scales` is maintained by Hadley, so I would imagine it's a dependable piece of software, if quality is a concern

**Comment by cpsievert** [comment]
ggplot2 imports scales, so users need scales installed in order to install ggplot2. All users have to do is respect namespaces in the same way as if they were using ggplot2 directly.

```r
library(plotly)
p <- ggplot(iris, aes(x = Sepal.Length, y = Petal.Width/Petal.Length)) + geom_point() +
  scale_y_continuous(labels = scales::percent_format())
ggplotly(p)
```

Depending on scales (that is, attaching the scales namespace when loading the plotly library) is a bad idea IMO
