### ISSUE TITLE
Heatmap displayed coordinates off-by-one

### ISSUE THREAD

**Issue by deliciouslytyped** [ropensci/plotly#1550]
![image](https://user-images.githubusercontent.com/47436522/59554905-bbd4ab80-8faa-11e9-8719-411727ea6c2e.png)
R uses 1 based coordinates, so coordinates displayed by plotly on a heatmap (might be relevant to other plot types as well?) are off-by one. If one is unaware of this it can lead to a lot of head scratching during exploratory data analysis. Would be somewhat alleviated by there being a documented way to use hovertemplate to display additional data on a heatmap, but really I think the coordinates should just be fixed to be 1-based.
A repro example:
```R
library(tidyverse)
library(plotly)
data=matrix(1:4,2,2)
plot_ly(z=data, type="heatmap") %>% layout(yaxis=list(scaleanchor="x"))
data[1,1]
```
results in ```[1] 1```

**Comment by cpsievert** [comment]
You code gives me this, which is what I'd expect

<img width="1192" alt="Screen Shot 2019-06-17 at 9 37 00 AM" src="https://user-images.githubusercontent.com/1365941/59612889-7f589b00-90e3-11e9-8f8e-1971ab250fc5.png">

If you're referencing the x/y positions, supply values to `x` or `y` to control them

**Comment by deliciouslytyped** [comment]
I think this is a UX bug what the axes show and what R shows are two different things. The axes show the value 1 at (0,0).
