### ISSUE TITLE
scatter plot in R: marker size not working

### ISSUE THREAD

**Issue by qchengray** [ropensci/plotly#1554]
I want change the marker size when I try a 3D plot，but it not worked，so I test the parameter with a sample example like this：
> df
    a  b
1   1  1
2   2  2
3   3  3
4   4  4
5   5  5
6   6  6
7   7  7
8   8  8
9   9  9
10 10 10
>plot_ly(df,x=~a,y =~b) %>% add_markers(size = 1)
>plot_ly(df,x=~a,y =~b) %>% add_markers(size = 20)
unfortunately，It have no difference.
```r
> packageVersion('plotly')
[1] ‘4.9.0’
```
installed with Github.

**Comment by cpsievert** [comment]
If you want to specify the value on the visual range (in this case, size in pixels), wrap the value in `I()`

```r
plot_ly(df,x=~a,y =~b) %>% add_markers(size = I(1))
```
