### ISSUE TITLE
[Feature Requested]: Sunburst Plots

### ISSUE THREAD

**Issue by Rothdyt** [ropensci/plotly#1563]
---

1. Add  `rotation` functionality to the sunburst plot.
2. Add texts comments/ ticks on the outer most/ inner most ring(s).

![image](https://user-images.githubusercontent.com/19240875/60683274-77616f00-9ec9-11e9-9e29-6280134c29b5.png)

For example, I would like to rotate the figure such that tick, which the green arrow points to, can point to 12 o'clock position. This can be done in pie chart. (For the nested structure reason, I cannot use the pie chart.)

2. I would like to add ticks and texts on the boundary of each circle, e.g., positions where red arrows point to. (Image a use case, I am creating a clock. So the outer most boundary should be able to show ticks with numbers annotated.)

Thanks!
 
```r

# code to produce the graph above without arrow annotations. 
library('plotly')

df <- data.frame(
  labels = c(
    'test', 
    'A', 'A1', 'A2',
    'B', 'B1', 'B2', 
    'C', 'C1', 'C2'
  ), 
  parents = c (
    '',
    'test', 'A', 'A',
    'test', 'B', 'B',
    'test', 'C', 'C'
  ),
  values = c(
    6,
    2, 1, 1,
    2, 1, 1,
    2, 1, 1
  )
)

plot_ly(df,
        labels = ~labels,
        parents =  ~parents,
        values = ~values,
        type = 'sunburst',
        branchvalues='total')
```

**Comment by cpsievert** [comment]
Requests for new plotly.js attributes should be made here https://github.com/plotly/plotly.js/issues/new
