### ISSUE TITLE
[Feature request]: Let the first sector of a pie chart unfold counterclockwise

### ISSUE THREAD

**Issue by DaniMori** [ropensci/plotly#1564]
When I create a pie chart, and I set argument `direction = "counterclockwise"`, I would like that the first sector can be configured to unfold counterclockwise as well.

Although I could "manually" compute the angular width of the sector and subtract it from the desired value in the `rotation` argument, that would still fix the first edge (in clockwise order) when I turn on/off categories in the legend, and thus the last edge would not be aligned with the desired rotation.  The desired behavior would be that the last edge is fixed so that the `rotation` argument fixes the rotation of the first sector shown, no matter which one it is.

``` r
library(plotly, quietly = TRUE)
library(tibble, quietly = TRUE)
library(magrittr, quietly = TRUE)

foo <- tibble(
  lab = letters[1:5],
  val = c(5, 1, 6, 5, 3)
)

# Sector "a" unfold clockwise, while the categories are plot counterclockwise
#   from the reference direction (12 o'clock)
foo %>% plot_ly(
  type = "pie", labels = ~lab, values = ~val,
  sort = FALSE, direction = "counterclockwise"
)
```
![](https://i.imgur.com/Mk73IOV.png)

``` r
# Workaround: subtract width of first category from the desired value for
#   `rotation`; Ok as long as all traces are active, but not when they are
#   clicked on/off on legend
foo %>% plot_ly(
  type = "pie", labels = ~lab, values = ~val,
  sort = FALSE, direction = "counterclockwise",
  rotation = 0 - foo$val[1] / sum(foo$val) * 360
)
```
![](https://i.imgur.com/pSOz5kE.png)

``` r
# Suggestion: an argument like `revert_fist` could allow the first category to
#   unfold counterclockwise

## Not run:
foo %>% plot_ly(
  type = "pie", labels = ~lab, values = ~val,
  sort = FALSE, direction = "counterclockwise", revert_first = TRUE,
  rotation = 0
)
## End(Not run)
```

<sup>Created on 2019-07-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by cpsievert** [comment]
Requests for new plotly.js attributes should be made here https://github.com/plotly/plotly.js/issues/new
