### ISSUE TITLE
[Feature Requested]: `direction` and `rotation` arguments in sunburst plots

### ISSUE THREAD

**Issue by DaniMori** [ropensci/plotly#1565]
`direction` and `rotation` arguments in sunburst plots, similar to those in pie charts, would be most welcome.

P.S.: no need for a "reprex"... I assume? (I'll provide it if required of course)

**Comment by cpsievert** [comment]
Requests for new plotly.js attributes should be made here https://github.com/plotly/plotly.js/issues/new
