### ISSUE TITLE
[Feature request]: value `branchvalues = "relative"` (or similar) in sunburst plots

### ISSUE THREAD

**Issue by DaniMori** [ropensci/plotly#1566]
A mode for computing branch values that considered each angular width relative to the siblings would be much desired.

Also, having a value of `NA` for a certain branch could automatically compute its value from its children's values sum.

The first result can be attained by using `branchvalues = "remainder"` and values of 0 for the branches, but in that case, the values on the labels are not the desired ones (they would have values of 0, instead of the sum of the children's values as would be intended).

This would allow plotting the sunburst without having to precompute the value of the branches as the sum of its siblings and then using `branchvalues = "total"`, and also to have the proper value in the hover label, without having to use `branchvalues = "remainder"` and values of 0.

``` r
library(plotly, quietly = TRUE)

# `branchvalues = "total"` sets "Seth" width to 12 as supplied in data (OK)
plot_ly(
  labels = c("Eve", "Seth", "Enos", "Noam", "Awan", "Enoch"),
  parents = c("", "Eve", "Seth", "Seth", "Eve", "Awan"),
  values = c(16, 12, 10, 2, 4, 4),
  type = 'sunburst',
  branchvalues = 'total'
)
```

![](https://i.imgur.com/3mGVBKn.png)

``` r

# `branchvalues = "remainder"` sets "Seth" width to "12", by taking the sum
#   of "Enos" and "Noam", and its own value (12).  The value in the label is
#   0 as expected (OK)
plot_ly(
  labels = c("Eve", "Seth", "Enos", "Noam", "Awan", "Enoch"),
  parents = c("", "Eve", "Seth", "Seth", "Eve", "Awan"),
  values = c(0, 0, 10, 2, 0, 4),
  type = 'sunburst',
  branchvalues = 'remainder'
)
```

![](https://i.imgur.com/ROrizWG.png)

``` r

# `branchvalues = "relative"` would ideally compute the value of "Seth" as 12
#    "Awan" as 4, and "Eve" as 16, by summing up their children's values:

## Not run:
plot_ly(
  labels = c("Eve", "Seth", "Enos", "Noam", "Awan", "Enoch"),
  parents = c("", "Eve", "Seth", "Seth", "Eve", "Awan"),
  values = c(NA, NA, 10, 2, NA, 4),
  type = 'sunburst',
  branchvalues = 'relative'
)
## End(Not run)


# `branchvalues = "relative"` in this case would make "Enos" and "Noam" take
#   10/12 and 2/12 of the angular width of "Seth", respectively, but the
#   angular width of Seth would be 180º, as its value is 1 and its level sums
#   up to 2 (with "Seth" and "Awan"'s values)

## Not run:
plot_ly(
  labels = c("Eve", "Seth", "Enos", "Noam", "Awan", "Enoch"),
  parents = c("", "Eve", "Seth", "Seth", "Eve", "Awan"),
  values = c(NA, 1, 10, 2, 1, 4),
  type = 'sunburst',
  branchvalues = 'relative'
)
## End(Not run)
```

<sup>Created on 2019-07-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by cpsievert** [comment]
Requests for new plotly.js attributes should be made here https://github.com/plotly/plotly.js/issues/new

**Comment by batubb** [comment]
@DaniMori did you end up finding a solution to this? Running into the same issue

**Comment by DaniMori** [comment]
The issue is marked as completed, so I guess it must be implemented now. It's been quite a while since I requested this and haven't used it anymore since then.
