### ISSUE TITLE
[feature request] Make ggplotly usable with feast/fable based forecast and autoplot()

### ISSUE THREAD

**Issue by klausr90** [ropensci/plotly#1568]
---
I am forecasting different type of models(ARIMA, ETS and Neural networks) on a tsibble based time series data set **dat()** with the structure Date & Data. The recently released feast/fable packages provide the forecast data that I want to plot. Usually, with ggplot2 i just use the autoplot() function. As i want to convert the obtained plot to a nicer one with plotly, I have added in the last row ggplotly(). The code works totally fine until the penultimate line. 
I get the following message in my console:

> Warning in geom2trace.default(dots[[1L]][[2L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
>   geom_GeomForecast() has yet to be implemented in plotly.
>   If you'd like to see this geom implemented,
>   Please open an issue with your example code at
>   https://github.com/ropensci/plotly/issues

```r
plot <- dat() %>%
        model(ARIMA(Data),
              ETS(Data),
              NNETAR(Data)) %>%
        forecast(h = 10) %>%
        autoplot(dat()) %>%
        ggplotly()

```

**Comment by cpsievert** [comment]
Thanks, I'm maintaining a list of 3rd-party Geoms in #566

**Comment by tanga94** [comment]
Hi @cpsievert , did you ever manage to implement this geom in plotly? I'm also interested rendering some forecasts from the ```fpp3``` package as a ```ggplotly``` like in @klausr90 's example, so I'm just wondering whether its possible now?

**Comment by Justfja** [comment]
@cpsievert @moutikabdessabour When using fable with plotly, I am still getting the error that was reported earlier on 

``
Warning in geom2trace.default(dots[[1L]][[2L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
geom_GeomForecast() has yet to be implemented in plotly.
If you'd like to see this geom implemented,
Please open an issue with your example code at
https://github.com/ropensci/plotly/issues
``

**Comment by Justfja** [comment]
> You currently need the development version `remotes::install_github("ropensci/plotly")`

Thank you for the response, I will try it out

**Comment by tanga94** [comment]
Hi @cpsievert . I have tried using the development version of ```plotly``` however I'm still running into the same issue [https://stackoverflow.com/questions/73485119/forecasts-from-fable-package-dont-appear-in-ggplotly-image?noredirect=1#comment129776180_73485119](url).
