### ISSUE TITLE
plotly R conflict with htmlwidgets on shiny

### ISSUE THREAD

**Issue by dingying85** [ropensci/plotly#1573]
Dear plotly developer,

Recently I encounter an issue when I putting htmlwidgets on my R shiny server code (such as using networkD3 or others like collapsibleTree), my other interactive plots implemented with plotly stop loading and disappeared on the interface.

I am wondering whether anyone else encounter this issue. I really want to incorporate the nice htmlwidgets to shiny apps.

Thanks in advance.

Brief description of the problem

```r
plot_ly(labels = ~sex, values = ~counts,data = sex_df,textposition = 'inside') %>%
              add_pie(hole = 0.6)
```

```r
forceNetwork(Links = networkData, Nodes = NodeData,
                       Source = "src", Target = "target",
                       Value = "value", NodeID = "name",Group="group",opacity = 1,fontSize=20,zoom=TRUE,linkColour = networkData$color,Nodesize="nodesize")
          
```

when I have both, especially when I start specify the forceNetworkOutput in the ui.R, those plot_ly plot starts to disappear on the apps.

**Comment by cpsievert** [comment]
This renders ok for me on Chrome, does it work for you? If it does, please try to make a minimal reproducible example

```r
library(shiny)
library(plotly)
library(networkD3)

ui <- fluidPage(
  plotlyOutput("p"),
  forceNetworkOutput("o")
)

server <- function(input, output, session) {
  
  output$p <- renderPlotly({
    ds <- data.frame(labels = c("A", "B", "C"), values = c(10, 40, 60))
    plot_ly(ds, labels = ~labels, values = ~values) %>%
      add_pie() %>%
      layout(title = "Basic Pie Chart using Plotly")
  })
  
  output$o <- renderForceNetwork({
    forceNetwork(Links = MisLinks, Nodes = MisNodes, Source = "source",
                 Target = "target", Value = "value", NodeID = "name",
                 Group = "group", opacity = 0.4, zoom = TRUE)

  })
  
}

shinyApp(ui, server)
```

**Comment by dingying85** [comment]
Please see the example and please give some advice how to make it work, it does not work on my end
library(shiny)
library(plotly)
library(networkD3)
library(treemap)
library(d3treeR)
ui <- fluidPage(
  plotlyOutput("p"),
  forceNetworkOutput("o"),
  d3treeOutput("a")
)

server <- function(input, output, session) {
  
  output$p <- renderPlotly({
    ds <- data.frame(labels = c("A", "B", "C"), values = c(10, 40, 60))
    plot_ly(ds, labels = ~labels, values = ~values) %>%
      add_pie() %>%
      layout(title = "Basic Pie Chart using Plotly")
  })
  
  output$o <- renderForceNetwork({
    forceNetwork(Links = MisLinks, Nodes = MisNodes, Source = "source",
                 Target = "target", Value = "value", NodeID = "name",
                 Group = "group", opacity = 0.4, zoom = TRUE)
    
  })
  
  output$a <- renderD3tree({
    data(GNI2014)
    
    tm <-  treemap(
      GNI2014,
      index=c("continent", "iso3"),
      vSize="population",
      vColor="GNI",
      type="value"
    )
    
    
    d3tree( tm,rootname = "World" )
  })
    
}
  
  
  
  
  


shinyApp(ui, server)

**Comment by cpsievert** [comment]
Thanks, the JS console errors suggest this is a d3treeR problem.

<img width="826" alt="Screen Shot 2019-07-15 at 10 22 08 AM" src="https://user-images.githubusercontent.com/1365941/61227806-a1493b80-a6ea-11e9-81ad-2d5a682947ad.png">


Indeed, I can replicate the error without plotly (so I'll be closing, please consider posting an issue at https://github.com/d3treeR/d3treeR

```r
library(shiny)
library(networkD3)
library(treemap)
library(d3treeR)

ui <- fluidPage(
  forceNetworkOutput("o"),
  d3treeOutput("a")
)

server <- function(input, output, session) {
  
  output$o <- renderForceNetwork({
    forceNetwork(Links = MisLinks, Nodes = MisNodes, Source = "source",
                 Target = "target", Value = "value", NodeID = "name",
                 Group = "group", opacity = 0.4, zoom = TRUE)
    
  })
  
  output$a <- renderD3tree({
    data(GNI2014)
    
    tm <-  treemap(
      GNI2014,
      index=c("continent", "iso3"),
      vSize="population",
      vColor="GNI",
      type="value"
    )
    
    
    d3tree( tm,rootname = "World" )
  })
  
}

shinyApp(ui, server)
```
