### ISSUE TITLE
x axis problem when using facets with a unique value on the x axis

### ISSUE THREAD

**Issue by paobranco** [ropensci/plotly#1577]
Hi, 
Great package!

I found an issue when using facet_wrap and facet_grid.
The problem is related with the existence of a unique value in the x axis. When this happens, only the first panel shows the x axis correctly.
Here is a reproducible example:

```r
data(iris)
ds <- iris[1:10,]
ds$var <- as.factor(c(rep("A", 5), rep("B",5)))
p <- ggplot(ds, aes(x=Species, y=Petal.Length))+facet_grid(~var)+geom_point()
p
```
This produces this plot:
![Rplot1](https://user-images.githubusercontent.com/3248426/61164115-7902e680-a50a-11e9-803c-cec9feffc499.png)

However, when using ggplotly
```r
ggplotly(p)
```
This happens:
![Rplot2](https://user-images.githubusercontent.com/3248426/61164132-92a42e00-a50a-11e9-9dcd-b5714ae92752.png)

The x axis of the first panel is OK, but all the other panels will show numbers on the x axis.

Thank you!

**Comment by cpsievert** [comment]
Fixed via #1788
