### ISSUE TITLE
rmarkdown without inline JS

### ISSUE THREAD

**Issue by nicolaskruchten** [ropensci/plotly#1586]
When I knit an Rmarkdown file with a `plot_ly` plot, the resulting HTML is pretty big, because it inlines plotly.js. Is there a flag somewhere that I can use to get it to load plotly.js from the CDN instead?

**Comment by cpsievert** [comment]
You can put `self_contained: false` in the yaml of the Rmd to have it import a local file instead (see `?rmarkdown::html_document`).

I think you can use `partial_bundle()` with `local=FALSE` to get an external link instead, but you probably to be careful you're not importing multiple versions.

**Comment by nicolaskruchten** [comment]
So I just tried it with `self_contained: false` and it still seems to output a 3.8MB HTML file with inlined data-uri Javascript. Did I need to do anything else as well or...?

here are the contents of my source file (with extra spaces between the backticks for formatting reasons ;)

```
---
title: "Untitled"
output: html_document
self_contained: false
---

` ` `{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
` ` `

` ` `{r pressure, echo=FALSE, message=FALSE, warning=FALSE}
library(plotly)
plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length)
` ` `
```

**Comment by cpsievert** [comment]
It needs to be this way (`self_contained` is an argument to `html_document`):

```r
---
title: "Untitled"
output: 
  html_document:
    self_contained: false
---
```

**Comment by nicolaskruchten** [comment]
Ah perfect, thanks!

**Comment by nicolaskruchten** [comment]
Following up on this: is there any way to get the resulting HTML to request plotly.js from a CDN?

**Comment by cpsievert** [comment]
I think the only 'official' way to do it is to add `partial_bundle(p, local = FALSE)` to a plot `p`

**Comment by nicolaskruchten** [comment]
OK thanks :)
