### ISSUE TITLE
Plotly does not work with webshot

### ISSUE THREAD

**Issue by kmalone7** [ropensci/plotly#1587]
There is an issue with plotly and using webshot to save images of the figures. I first posted this with webshot, but no progress has been made. Hoping that posting here will yield some results. To see the details of this issue see: wch/webshot#73

**Comment by cpsievert** [comment]
See https://github.com/wch/webshot/issues/73#issuecomment-520473038, also note that you can use `plotly::orca()` for more powerful/flexible export of plotly images (it can be painful to install, though)
