### ISSUE TITLE
Implement ability to use annotations with labels through ggplotly()

### ISSUE THREAD

**Issue by MeganStodel** [ropensci/plotly#1590]
When using `ggplotly()`, it is currently not possible to use `annotate(geom = "label")` to get a label on the plot. It is possible to make other annotations, such as `annotate(geom = "text")`. Trying to use the label option brings up this warning message: 

> Warning message:
In geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
  geom_GeomLabel() has yet to be implemented in plotly.

It also suggests opening an issue so here I am! Could this be implemented?

See below for an example. It uses example data so appreciate it is not the most stunningly useful plot ever!

```r
library(ggplot2)
library(plotly)

# ggplot code using "text" in annotation
diet_changes_text <- ggplot(ChickWeight, aes(x = Time, y = weight, color = Diet, group = Chick)) +
  geom_point() + 
  geom_vline(xintercept = 7, linetype = "dotted", 
             color = "gray", size = 0.5) + 
  annotate(geom = "text", x = 7.2, y = 250, label = "Significant event", size = 3)

# Show ggplotly object - works fine
ggplotly(diet_changes_text) %>% style(textposition = "right")

# ggplot code using "label" instead of "text" in the annotation
diet_changes_label <- ggplot(ChickWeight, aes(x = Time, y = weight, color = Diet, group = Chick)) +
  geom_point() + 
  geom_vline(xintercept = 7, linetype = "dotted", 
             color = "gray", size = 0.5) + 
  annotate(geom = "label", x = 7.2, y = 250, label = "Significant event", size = 3)

# Show ggplotly object - no annotation shown
ggplotly(diet_changes_label) %>% style(textposition = "right")

```

**Comment by cpsievert** [comment]
Thank you! I have a note to implement `GeomLabel` in #348
