### ISSUE TITLE
zoom on this map

### ISSUE THREAD

**Issue by tdhock** [ropensci/plotly#16]
I'm not sure if I'm missing something here, but the zoom on this one is a bit weird, and it doesn't *seem* like there is more data we're fitting for: 

https://plot.ly/~RgraphingAPI/948/ 

So if I make the graph, it looks like the "map" screenshot, but then if I zoom it a bit, it looks like the "zoom" shot. Hypothesis: because it's being drawn from ggplot, maybe there is something coming through as part of the scale? Or is it attaching to zero? 

This is fun stuff. I'll talk to Alex about it. It'd also be sweet to auto-size them to something like 800 x 550 or so if we could.

**Comment by cpsievert** [comment]
The zooming behavior looks fine to me. Feel free to reopen and elaborate @tdhock
