### ISSUE TITLE
Error on guide_colorbar “object 'tickvals' not found”

### ISSUE THREAD

**Issue by petersmp** [ropensci/plotly#1606]
I am trying to use `ggplotly` to make an interactive plot with some `geom_ribbon`s.

The plot looks like (data made using the `tidyverse` packages):

    temp_data <-
       tibble(Group = 1, x = 1) %>%
       complete(Group = 1:3, x = 1:10) %>%
       mutate(y_val = x + Group * 5
              , ymin = y_val - 3/Group
              , ymax = y_val + 3/Group)
    
    temp_plot <-
        ggplot(temp_data
               , aes(x = x
                     , ymin = ymin
                     , ymax = ymax
                     , fill = Group
                     , group = Group)) +
        geom_ribbon()

The plot is then:

[![enter image description here][1]][1]

Which is the plot I want. However, when I go to render it in `plotly` with `ggplot(temp_plot)`, I get the error:

> Error in eval(substitute(expr), data, enclos = parent.frame()) :    
> object 'tickvals' not found

I can track this down to the `geom_ribbon` element, and specifically the legend. If I run `ggplotly(temp_plot + theme(legend.position = "none"))`, the plot renders fine (without the legend).

I am running the latest stable releases of both `ggplot2` (ggplot2_3.2.0.9000) and `plotly` (plotly_4.9.0). Of note, I do **not** get this error on a server that is running an older version of ggplot2 (ggplot2_3.1.1), but is current on `plotly`.

I also posted this at [StackOverflow](https://stackoverflow.com/questions/57661445/ggplotly-error-on-guide-colorbar-object-tickvals-not-found)

  [1]: https://i.stack.imgur.com/LAQGW.png

**Comment by cpsievert** [comment]
Closing since I don't get this error with the current CRAN or dev release of ggplot2
