### ISSUE TITLE
geom_treemap convert to ggplotly

### ISSUE THREAD

**Issue by BMichela** [ropensci/plotly#1607]
Hi! I would like to see my treemap created with ggplot, converted with ggplotly.
Now if I try to use ggplotly on this type of plot I only get a grey box.

Example code:
p <- ggplot(data, aes(area = amount, fill = sector, label = country, subgroup = 
     sector)) +
    geom_treemap() +
    geom_treemap_subgroup_border(colour = "white") +
    geom_treemap_text(fontface = "italic", colour = "white", place = "centre")+
    labs(fill="Sector")

gp <- ggplotly(p)

**Comment by cpsievert** [comment]
Thanks, `geom_treemap()` comes from the ggforce package, right? I have a note to implement here #566

**Comment by BMichela** [comment]
No the package is treemapify
