### ISSUE TITLE
Confusing 'margin' with subplot

### ISSUE THREAD

**Issue by rfenouil** [ropensci/plotly#1612]
When using subplot for grouping panels, it seems that margins values are not applied to sides on figure borders.
It makes it hard to:
 - generate a group of 3 panels with exact same size
 - control spacing between panels

```r
panel = plot_ly( x = 1, y = rnorm(100)) %>% 
          add_trace(type = "violin")

# Here middle plot is significantly smaller than border ones with default margins
subplot( panel, panel, panel)

# Here left margin does not seem to be applied to leftmost panel
subplot( panel, panel, panel, margin = c( 0.3, 0, 0, 0))
```

**Comment by cpsievert** [comment]
> When using subplot for grouping panels, it seems that margins values are not applied to sides on figure borders.

Use [`layout()`'s margin](https://plot.ly/r/reference/#layout-margin) to control this spacing (`subplot()`'s margin is for controlling the spacing between panels, and nothing more).

```r
subplot(panel, panel, panel, margin = 0) %>% 
  layout(margin = list(l = 100, r = 100))
```

**Comment by rfenouil** [comment]
@cpsievert thank you for your answer, I understand better now.

On the same topic, I can't figure how to add some space between panels (using margin argument) and keep their size identical. It seems that separation space is taken subtracted middle panel.
Would you mind providing a working example ?

Thank you for your help and sorry for the dumb questions... :/
