### ISSUE TITLE
parcoords clears lines when filter is used

### ISSUE THREAD

**Issue by hedberg503** [ropensci/plotly#1619]
Hello. I have created a reproducible code snippet to illustrate my issue.
I setup a parallel coordinates plot and it renders beautifully. However, if the user then goes to filter on one of the regions the lines disappear from the plot.
Is this a meaningful error? I don't have a constraintrange setup in the beginning because I want to leave the option of filtering to the user.

```r
library(plotly)
options(viewer=NULL) 
p <- plot_ly(type = 'parcoords', line = list(color = 'blue'),
             dimensions = list(
                 list(range = c(1,5),
                      label = 'A', values = c(1,4)),
                 list(range = c(1,5),
                      tickvals = c(1.5,3,4.5),
                      label = 'B', values = c(3,1.5)),
                 list(range = c(1,5),
                      tickvals = c(1,2,4,5),
                      label = 'C', values = c(2,4),
                      ticktext = c('text 1', 'text 2', 'text 3', 'text 4')),
                 list(range = c(1,5),
                      label = 'D', values = c(4,2))
             )
)
print(p)
```

**Comment by cpsievert** [comment]
I'm not sure I follow. Could you provide a screencast of the behavior you're seeing and explain more specifically what you'd expect to happen instead?

**Comment by cpsievert** [comment]
Closing until the issue can be clarified (I can seem to replicate the lines disappearing)
