### ISSUE TITLE
Rmarkdown Markdown output without webshot

### ISSUE THREAD

**Issue by nicolaskruchten** [ropensci/plotly#1620]
To produce docs like https://plot.ly/r/line-and-scatter/, we knit `.Rmd` files to `.md` and then use Jekyll to convert the `.md` files to HTML. Right now we use `api_create(p)` and render the output, which in the `.md` file shows up as`<iframe ... />` and this is eventually inlined straight into the resulting HTML file.

* `Rmd`: https://raw.githubusercontent.com/plotly/documentation/source-design-merge/_posts/r/basic/2015-07-30-line-and-scatter.Rmd
* `md`: https://raw.githubusercontent.com/plotly/documentation/source-design-merge/_posts/r/basic/2015-07-30-line-and-scatter.md
* Final HTML: https://raw.githubusercontent.com/plotly/documentation/gh-pages/r/line-and-scatter/index.html

This is all fine and good except now we want to stop using `api_create()` and instead inline the plots into the HTML directly. We made this switchover in the Python v4 docs and it's R's turn now.

The challenge is that if I just try to display `p` in the `.Rmd` file, then in the `.md` file I get some error about `webshot` which I imagine means that it's trying to inline a static image of my plot....

My question, finally, after all this context, is: is there a way to get the `.Rmd` to `.md` conversion to result in a `<script>` tag in the `.md` file that would cause the plot to render inline in the resulting HTML page once Jekyll copies it over? (Jekyll would just treat that `<script>` tag as any other HTML-in-Markdown I think)

**Comment by nicolaskruchten** [comment]
We're using `Rscript -e 'knitr::knit("YOUR_FILE.Rmd")'`

**Comment by cpsievert** [comment]
Ahh, this yaml:

```r
output:
  html_document:
    keep_md: true
```

is rmarkdown specific yaml matter, so do `Rscript -e 'rmarkdown::render("YOUR_FILE.Rmd")'` instead

**Comment by nicolaskruchten** [comment]
Ah, perfect, thanks! Almost there, but I think I can get it over the finish line :)

**Comment by nicolaskruchten** [comment]
Just a follow-up on this: your input was really helpful here @cpsievert ! We finally moved our https://plot.ly/r/ docs away from hosting only embedded Chart Studio plots and into direct embedding. We're now basically not talking about Chart Studio at all in these docs, making them much more general-purpose!

The trick was to use `rmarkdown::render()` but then to throw away the resulting HTML and use only the intermediate Markdown, which contained just what Jekyll needed to render things. Our R docs are now stored in Rmd form only in https://github.com/plotly/plotly.r-docs and on every commit all the docs are rebuilt and then thereafter Jekyll picks them up and deploys them.
