### ISSUE TITLE
is there a way to further customize plotly figure when plotting in shiny

### ISSUE THREAD

**Issue by dingying85** [ropensci/plotly#1622]
Dear Plotly developer,

I am exploring the possibility of further customize the plotly chart after the chart is constructed in R or shiny app. Is there a way to do that, such as changing line width, changing line color, dot size?

I see one way is to create api and link to chart studio to modify it further? Are there other ways to do it? Thanks.

Best Regards,
Ying

**Comment by cpsievert** [comment]
GitHub issues are reserved for feature requests and bug reports, please use https://community.rstudio.com/ or https://community.plot.ly/ to ask questions.
