### ISSUE TITLE
Not possible to produce funnel plot

### ISSUE THREAD

**Issue by MeganBeckett** [ropensci/plotly#1623]
I am trying to produce a funnel plot, as described here: https://plot.ly/r/funnel-charts/#basic-funnel-plot

Even the example does not work:

```
p <- plot_ly() %>%
  add_trace(
    type = "funnel",
    y = c("Website visit", "Downloads", "Potential customers", "Requested price", "invoice sent"),
    x = c(39, 27.4, 20.6, 11, 2)) %>%
  layout(yaxis = list(categoryarray = c("Website visit", "Downloads", "Potential customers", "Requested price", "invoice sent")))
p
```

The error given is that type must be one of the ones specified in the list.

I am using plotly version 4.9.0 and R version 3.6.1.

**Comment by cpsievert** [comment]
Currently you need to install plotly from GitHub to get funnel plots: `devtools::install_github("ropensci/plotly")`
