### ISSUE TITLE
Problem with present p_value in plotly

### ISSUE THREAD

**Issue by ehudahan** [ropensci/plotly#1627]
Hi,
I use stat_compare_means in my ggplot - works well. But when I excute it with plotly I get this eror: <geom_GeomSignif() has yet to be implemented in plotly.>.
How I can add automatically the p value to the plotly?

**Comment by cpsievert** [comment]
`ggplotly()` doesn't automatically know how to convert 3rd party geoms like `GeomSignif`.

What package is `stat_compare_means()` from?

**Comment by cpsievert** [comment]
Turns out it's `ggpubr::stat_compare_means()`. Added a note to #566

**Comment by juechenyang** [comment]
Hi,

I also have the same issue on this. Is there any potential solution to add p value in ggplotly @cpsievert
