### ISSUE TITLE
Violin Plot, parameter for density colour

### ISSUE THREAD

**Issue by aalvarezf** [ropensci/plotly#1629]
Hi, 
I'm using  packageVersion("plotly") ‘4.9.0’ to draw violin plots.  
I have an issue defining the colours. It works for the line around the violin, also for the meanline and for the markers, however the density plot inside is keeping the default values. 

At the beginning I thought that the colour density was the same than the line, but maybe is not working in this version?

Even if I copy paste  exactly the example code here:  https://plot.ly/r/violin/
for Advanced Violin Plot or the Grouped Violin Plot, I got the correct line colour but not the density.

Is there any parameter to set that colour?

**Comment by cpsievert** [comment]
The code behind these examples feel wrong to me. For example, the Grouped Violin Plot only sets the `line.color` to blue/pink, but it doesn't set `marker.color` (even though the figure suggests so)

In that example, if you change `line = list(color = "blue")` to `color = I("blue")` you'll get the right result. Note that you can also use `stroke = I("something")` to set the `line.color`

**Comment by aalvarezf** [comment]
Thanks!  It works perfectly

**Comment by pwildenhain** [comment]
Can this issue be re-opened to update the documentation? I just ran into this issue today (thanks @aalvarezf  for filling it out and @cpsievert for providing such a quick answer) and was about to file my own issue until I came across this
