### ISSUE TITLE
Only half bar is highlighted when using highlight_key function

### ISSUE THREAD

**Issue by jiayi9** [ropensci/plotly#1631]
When I use plotly in R to plot a bar chart which has highlighting function by clicking, only half of the bar is highlighted, as can be reproduced by the following script.

```
library(plotly)

D = data.frame(
  NAME = LETTERS[1:5],
  VALUE = rnorm(5)
)

D %>% 
  highlight_key(~NAME) %>%
  plot_ly(x=~VALUE, y = ~NAME, type ="bar", orientation = "h") %>% 
  highlight(on = "plotly_click",off = "plotly_doubleclick")
```

**Comment by cpsievert** [comment]
This happens because the highlighted layer is added as a new trace, and plotly.js by default want to consider that new trace a new 'group'. You can workaround that by adding:

```r
layout(p, barmode = "overlay")
```
