### ISSUE TITLE
marker.color in Scattermapbox does not work as expected

### ISSUE THREAD

**Issue by Mahdis-z** [ropensci/plotly#1632]
```r
plot_ly(
  fill = "toself", 
  lon = c(-74, -70, -70, -74), 
  lat = c(47, 47, 45, 45),
  type = 'scattermapbox',
  marker = list(size = 10, color = "orange")) %>%
layout(
  mapbox = list(
     style = "stamen-terrain", 
     center = list(lon = -73, lat = 46), 
     zoom = 5), 
  showlegend = FALSE)
```
<img width="333" alt="Screen Shot 2019-09-30 at 10 41 48 AM" src="https://user-images.githubusercontent.com/47799189/65889243-ec303200-e36e-11e9-8d14-aefd3709756c.png">

**Comment by cpsievert** [comment]
I'm pretty sure you need to use `fillcolor` to specify the color?

**Comment by Mahdis-z** [comment]
> I'm pretty sure you need to use `fillcolor` to specify the color?

right, my mistake
