### ISSUE TITLE
FR: Upgrade to plotly.js 1.50.0

### ISSUE THREAD

**Issue by fabiangehring** [ropensci/plotly#1633]
Hi, 
A soon upgrade to the  just released plotly.js 1.50.0 would be much appreciated.

Especially this fix could solve some issues we have in our shiny app (other users might experience the same?):
- Fix numerous axis `automargin` bugs [#4165, #4216]

I just tried to upgrde myself by replacing the plotly.min.js but wasn't successful myself.

**Comment by emrichter** [comment]
Would also appreciate an upgrade. Also facing issues due to automargin.

**Comment by cpsievert** [comment]
There's a work-in-progress https://github.com/ropensci/plotly/pull/1634, feel free to test it out

```r
devtools::install_github("ropensci/plotly#1634")
```

**Comment by cpsievert** [comment]
On master now
