### ISSUE TITLE
problem in align of hoverlabel

### ISSUE THREAD

**Issue by zerlia** [ropensci/plotly#1647]
Hi,
when I use plotly in R, set the 【align】 to be 'left' in hoverlabel ,but the output is alway be 'auto', it means that the parameter 【align】 in  【hoverlabel】is useless. Is this a bug ? or how can I set the align to be 'left'? Thanks.

```r
library(plotly)
x <- 1:5
y <- (1:5)^2
z <- c('CCTV<br />花蝴蝶1234567 <br />2006-12-20 14:35:30 <br />涨停了，哈哈！感谢。<br />我是早，你呢2006-12-20 14:45',
       'CCTV<br />花蝴蝶1234567 <br />2006-12-20 14:35:30 <br />涨停了，哈哈！感谢。<br />我是早，你呢2006-12-20 14:45',
       'CCTV<br />花蝴蝶1234567 <br />2006-12-20 14:35:30 <br />涨停了，哈哈！感谢。<br />我是早，你呢2006-12-20 14:45',
       'CCTV<br />花蝴蝶1234567 <br />2006-12-20 14:35:30 <br />涨停了，哈哈！感谢。<br />我是早，你呢2006-12-20 14:45',
       'CCTV<br />花蝴蝶1234567 <br />2006-12-20 14:35:30 <br />涨停了，哈哈！感谢。<br />我是早，你呢2006-12-20 14:45')

mydf <- data.frame(x,y,z)

plot_ly() %>%
 add_trace(data=mydf, x = ~ x, y = ~y, type="scatter", mode = 'markers', 
           marker=list(symbol='triangle-down',size=15,color='yellow'),
		   hoverlabel=list(bgcolor='cyan',align='left'),
		   hoverinfo='text', text=~z)
```

This example code, the last point text is align right, not left.

**Comment by cpsievert** [comment]
This is what I see (seems to work ok)...do you see something different?

<img width="758" alt="Screen Shot 2020-02-05 at 4 43 50 PM" src="https://user-images.githubusercontent.com/1365941/73890091-c17f4a00-4836-11ea-8a3a-d042f5b5bffa.png">

Please reopen if you see something different or if I'm missing something
