### ISSUE TITLE
Treemap

### ISSUE THREAD

**Issue by ttrevisan18** [ropensci/plotly#1654]
I notice that on the plotly website in the treemap section (https://plot.ly/r/reference/#treemap) there are instructions to set up a treemap. However, when I attempt to add a treemap trace, it gets rejected. Is this a bug or have treemaps not yet been built for R plotly?

![image](https://user-images.githubusercontent.com/45466366/68494491-857b1f80-021c-11ea-8754-d3c54f034fb1.png)

**Comment by cpsievert** [comment]
They're not yet available in R but will be in the coming weeks

**Comment by cpsievert** [comment]
This will be coming within the next few days...closing now so I don't forget.

**Comment by msgoussi** [comment]
Hi..
you provide TM with child and parents, what if you want to create TM from wide dataframe in order to use in treemap
