### ISSUE TITLE
y-axis range not set properly when facet_wrap(scales = "free_y")

### ISSUE THREAD

**Issue by cpsievert** [ropensci/plotly#166]
This is related to the scales="free" bullet of #161, but is probably worth noting separately. I'll send a pull request in attempt to fix both. I've uploaded [this plot](https://plot.ly/52/~cpsievert/) to demonstrate a bug in the y-axis limits:

```r
library("plotly")
no_panels <- ggplot(mtcars, aes(mpg, wt)) + geom_point()
no_panels + facet_wrap(~am+vs, scales = "free")
```

On a larger note, the package currently seems a little confused about the conceptual difference between `facet_grid` and `facet_wrap` in terms of free scales. For `facet_grid`, the y-axis/x-axis *has to* be fixed for a given row/column. But for `facet_wrap`, each panel is allowed to have it's own axis. I think this figure from the ggplot2 book helps demonstrate that:

![position-facets](https://cloud.githubusercontent.com/assets/1365941/6234245/e5eb3ed2-b69e-11e4-98c2-a83c90b0e519.png)

@chriddyp @mkcor do you know if the plotly API would support drawing an axis on each panel?

**Comment by chriddyp** [comment]
hey @cpsievert -- I'm not too familiar with `facet_*` but Plotly 'panels' can share axes. in fact, plotly's axes are pretty flexible: you control the length of them and the position of them. there are some good simple docs here: https://plot.ly/r/subplots/. The "Multiple Subplots" example seems like `facet_wrap` and "Subplots with Shared Axes" more similar to `facet_grid`. Here's another good 3x3 `facet_grid` example: 
[![](https://plot.ly/~chris/1638.png)][https://plot.ly/~chris/1638]

**Comment by cpsievert** [comment]
Nice, just what I was looking for, thanks!

**Comment by mkcor** [comment]
@cpsievert You are right, the conversion as is doesn't distinguish between `facet_grid` and `facet_wrap` in terms of free scales or column/row behaviour.
