### ISSUE TITLE
sunburst plot isn't rendered without specifying a (single) root for branchvalues = 'total'

### ISSUE THREAD

**Issue by ismirsehregal** [ropensci/plotly#1664]
The following won't render:

```
library(plotly)

plot_ly(
  labels = c("Seth", "Enos", "Noam", "Awan", "Enoch"),
  parents = c("", "Seth", "Seth", "", "Awan"),
  values = c(12, 10, 2, 4, 4),
  type = "sunburst",
  branchvalues = "total"
)
```

Once we add a "root" the plot renders fine:

```
library(plotly)

plot_ly(
  labels = c("Eve", "Seth", "Enos", "Noam", "Awan", "Enoch"),
  parents = c("", "Eve", "Seth", "Seth", "Eve", "Awan"),
  values = c(16, 12, 10, 2, 4, 4),
  type = "sunburst",
  branchvalues = "total"
)
```
![image](https://user-images.githubusercontent.com/36849480/69706498-26604a80-10f8-11ea-8e43-f11a3b3f3c60.png)

I guess, but I'm not sure if [this pull request](https://github.com/plotly/plotly.js/pull/4253) already adresses the problem.

I saw the problem [here](https://community.plot.ly/t/plotly-sunburst-returning-empty-chart-with-branchvalues-total/26582) first.

**Comment by cpsievert** [comment]
Yes, plotly.js 1.52 will fix this, the R package will be updated in the next couple days
