### ISSUE TITLE
Plotting some factors make RStudio freeze up

### ISSUE THREAD

**Issue by tenshis** [ropensci/plotly#1665]
If I try to run plot_ly on certain factors (like the one in the example), RStudio freezes up for a minute before displaying the result, but only the first time around.

```r
library(plotly)
balance <- factor("91112-102127")
df <- data.frame(balance)
plot_ly(x=~df$balance, type="histogram")
```

Anybody else experiencing this?

**Comment by cpsievert** [comment]
This code runs ok for me both in and outside of RStudio. Try running it outside of RStudio and/or upgrading and report back if you still have issues.
