### ISSUE TITLE
ggarrange: geom_GeomDrawGrob() has yet to be implemented in plotly

### ISSUE THREAD

**Issue by sparky2708** [ropensci/plotly#1668]
I am having a problem calling ggplotly on a plot generated by ggarrange:

```
data(iris)
g1 <- ggplot(iris, aes(x = Sepal.Length, y = Petal.Length, col = Species)) + geom_point()
g2 <- ggplot(iris, aes(x = Sepal.Width, y = Petal.Length, col = Species)) + geom_point()
btw_tick <- 1 # space between 2 ticks
gg <- ggarrange(g1 + scale_y_continuous(breaks = seq(1,8, btw_tick)), 
                 g2 + scale_y_continuous(breaks = seq(1,8, btw_tick * 3)), 
                 ncol = 1, nrow = 2, align = "v", heights = c(3, 1))
ggplotly(gg)
```

Error I get:

> Warning in geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
>   geom_GeomDrawGrob() has yet to be implemented in plotly.
>   If you'd like to see this geom implemented,
>   Please open an issue with your example code at
>   https://github.com/ropensci/plotly/issues
> Warning in geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
>   geom_GeomDrawGrob() has yet to be implemented in plotly.
>   If you'd like to see this geom implemented,
>   Please open an issue with your example code at
>   https://github.com/ropensci/plotly/issues

**Comment by cpsievert** [comment]
`ggplotly()` isn't likely to gain support for 'arrangement' functions like `ggarrange()` anytime soon...use `plotly::subplot()` instead https://plotly-r.com/arranging-views.html
