### ISSUE TITLE
Ability to drag and zoom when using rangeslider

### ISSUE THREAD

**Issue by chuymtz** [ropensci/plotly#1676]
I want to be able to use the drag and zoom capability of plotly whenever I use the nice rangeslider. 

Here's my toy example code:

`make_trend <- function(n=1000){`
`    x <- seq(n)`
`    y <- c(0, cumsum(rnorm(n = length(x) - 1, sd = sqrt(0.01))))`
`    data.frame(x=x,y=y)`
`}`
`make_trend() %>% `
`    plotly::plot_ly(x=~x,y=~y,mode='lines') %>%`
`    plotly::layout(xaxis=list(rangeslider = list(type = "date")))`

**Comment by chuymtz** [comment]
`make_trend <- function(n=1000){
    x <- seq(n)
    y <- c(0, cumsum(rnorm(n = length(x) - 1, sd = sqrt(0.01))))
    data.frame(x=x,y=y)
}
make_trend() %>% 
    plotly::plot_ly(x=~x,y=~y,mode='lines') %>% 
    plotly::layout(xaxis=list(rangeslider = list(type = "date")))`

**Comment by cpsievert** [comment]
Can you be more specific in what you mean by "drag and zoom capability of plotly"? Seems to me you are able to click and drag to zoom+pan on both the rangeslider and the full-size graph?

**Comment by cpsievert** [comment]
Please feel free to reopen if I'm missing something

**Comment by chuymtz** [comment]
Sorry, I meant, once the rangeslider is set to pan left right, i cant seem to be able to restrict in the y direction.
