### ISSUE TITLE
implement geom_GeomCurve

### ISSUE THREAD

**Issue by Courvoisier13** [ropensci/plotly#1684]
I am trying to do the correlation plot from the package `corrr`. When I tested `ggplotly` it said to request `geom_GeomCurve()` and `geom_GeomTextRepel()` to be implemented

```r
mydata <- mtcars[, c('mpg', 'cyl', 'disp', 'hp', 'carb')]
library(corrr)
p = mydata %>% correlate() %>% network_plot(min_cor=0.6)
ggplotly(p)
```

gives a blank canvas with invisible dots and the warnings:

> Warning messages:
> 1: In geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
>   geom_GeomCurve() has yet to be implemented in plotly.
>   If you'd like to see this geom implemented,
>   Please open an issue with your example code at
>   https://github.com/ropensci/plotly/issues
> 2: In geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
>   geom_GeomTextRepel() has yet to be implemented in plotly.
>   If you'd like to see this geom implemented,
>   Please open an issue with your example code at
>   https://github.com/ropensci/plotly/issues

**Comment by vkartha** [comment]
I have the same request, would love to see ggplotly work with geom_curv output (I receive the same warnings, and do not get any curves  drawn on the resulting plots). Just need some hover over functionality to highlight annotations and features for each curve drawn.

**Comment by cpsievert** [comment]
Added to #566
