### ISSUE TITLE
Latex annotation vanishes after static export

### ISSUE THREAD

**Issue by RalfKellner** [ropensci/plotly#1689]
Hi,

I hope I am not dublicating a previous issue. I am exporting plot_ly graphs in R via the orca function. The plot includes mathematical formulas which are defined with the TeX-function. After exporting the plot (no matter which format), the tex-annotation is not shown, instead it shows the tex-formula annotation, e.g., $x$, instead of x.  See the attached graphic. 
[num_Opt_Gerade.pdf](https://github.com/ropensci/plotly/files/4148033/num_Opt_Gerade.pdf)
Can this be fixed somehow?

Greetings, 
Ralf

**Comment by cpsievert** [comment]
You need `config(p, mathjax = TRUE)` and to also point the `PLOTLY_MATHJAX_PATH` environment variable a local version of mathjax. See more on `?config` and https://plotly-r.com/mathjax.html

**Comment by RalfKellner** [comment]
Sorry to bother again, but I did everything as explained and no error or warnings occur, yet, the pdf-file does not include latex type setting. This stays the same when rendering the plot to a png file instead of pdf.

**Comment by RalfKellner** [comment]
ok, when I use an older mathjax version it works, I do not know if this is a general problem or related to my system. So under mathjax version 3.xx it did not work, but under mathjax version 2.7.7 it works.
