### ISSUE TITLE
Improve 'Hovertemplate' instructions on the example page

### ISSUE THREAD

**Issue by nitramwin** [ropensci/plotly#1691]
- I refer to the example posted on this page: https://plot.ly/r/hover-text-and-formatting/#advanced-hovertemplate
- This occurs with Plotly 4.9.1 in RStudio 1.2.5033 on Windows 10.
- If the `text` value for hovertemplate is defined outside of the plotly call, the hovertemplate does not show if the text is not defined again within the hovertemplate.
- This happens to me when (for example), the example code chunk `Customize Tooltip Text with a Hovertemplate` is changed in the following way.

```
library(plotly)

text = c("Text A", "Text B", "Text C", "Text D", "Text E") #instead, define outside of plotly call

p <- plot_ly() %>%
  add_trace(
    type = 'scatter',
    mode = 'lines+markers',
    x = c(1,2,3,4,5),
    y = c(2.02825,1.63728,6.83839,4.8485,4.73463),
    # text = c("Text A", "Text B", "Text C", "Text D", "Text E"), #remove from here
    hovertemplate = paste('<i>Price</i>: $%{y:.2f}',
                        '<br><b>X</b>: %{x}<br>',
                        '<b>%{text}</b>'),
    showlegend = FALSE
  ) %>%
  add_trace(
    type = 'scatter',
    mode = 'lines+markers',
    x = c(1,2,3,4,5),
    y = c(3.02825,2.63728,4.83839,3.8485,1.73463),
    hovertemplate = 'Price: %{y:$.2f}<extra></extra>',
    showlegend = FALSE
  )

p
```

**Result:** The hovertemplate doesnt show at all due to the undefined `%{text}`.

- As such, only redefining the `text` value inside the plotly call allows the hovertemplate to be properly shown. 
- In addition, the `text` value must already be a character value outside of the plotly call.

- I suggest that plotly either get access to the local variables/values or that the instructions on the example page are made more explicity (since I struggled with this for some time!) 

**Suggestion for Plotly Improvement:** 
1. Add information that the `text` value (if defined outside of the call) must be already in character format and,
2. that the `text` value must be called again once inside the plotly call.

In the example below, the hovertemplate works as expected because the rules, described above, are followed. I imagine that this additional info would be very useful for other students of plotly in R. 
```
library(plotly)

text = c("Text A", "Text B", "Text C", "Text D", "Text E") #instead, define outside of plotly call 

p <- plot_ly() %>%
  add_trace(
    type = 'scatter',
    mode = 'lines+markers',
    x = c(1,2,3,4,5),
    y = c(2.02825,1.63728,6.83839,4.8485,4.73463),
    text = text, #redefine the value for plotly
    # text = c("Text A", "Text B", "Text C", "Text D", "Text E"), #remove from here
    hovertemplate = paste('<i>Price</i>: $%{y:.2f}',
                        '<br><b>X</b>: %{x}<br>',
                        '<b>%{text}</b>'),
    showlegend = FALSE
  ) %>%
  add_trace(
    type = 'scatter',
    mode = 'lines+markers',
    x = c(1,2,3,4,5),
    y = c(3.02825,2.63728,4.83839,3.8485,1.73463),
    hovertemplate = 'Price: %{y:$.2f}<extra></extra>',
    showlegend = FALSE
  )

p
```

**Comment by cpsievert** [comment]
See https://github.com/ropensci/plotly/issues/1692#issuecomment-582652325

Also, consider using `glue::glue()` over `paste()` if you want the template to reference local R variables
