### ISSUE TITLE
'Hovertemplate' only accepts 'text' and not a different label

### ISSUE THREAD

**Issue by nitramwin** [ropensci/plotly#1692]
- I refer to the example posted on this page but which has been slightly adapted by me (see comments): https://plot.ly/r/hover-text-and-formatting/#advanced-hovertemplate
- This occurs with Plotly 4.9.1 in RStudio 1.2.5033 on Windows 10.
- In working with the `hovertemplate` (see issue https://github.com/ropensci/plotly/issues/1691#issue-560297313), I have noticed that when the `text` label from the example is changed, the hovertemplate no longer renders in the plot. 
- Is this limitation by design? 

See the example below to test this for yourself. 
```
library(plotly)

text = c("Text A", "Text B", "Text C", "Text D", "Text E") #define outside of plotly call 

p <- plot_ly() %>%
  add_trace(
    type = 'scatter',
    mode = 'lines+markers',
    x = c(1,2,3,4,5),
    y = c(2.02825,1.63728,6.83839,4.8485,4.73463),
    texttext = text, #redefine the value for plotly with a label different from the regular 'text'
    # text = c("Text A", "Text B", "Text C", "Text D", "Text E"), #remove from here
    hovertemplate = paste('<i>Price</i>: $%{y:.2f}',
                        '<br><b>X</b>: %{x}<br>',
                        '<b>%{texttext}</b>'), # add the new label here
    showlegend = FALSE
  ) %>%
  add_trace(
    type = 'scatter',
    mode = 'lines+markers',
    x = c(1,2,3,4,5),
    y = c(3.02825,2.63728,4.83839,3.8485,1.73463),
    hovertemplate = 'Price: %{y:$.2f}<extra></extra>',
    showlegend = FALSE
  )

p
``` 
**Result:** The hovertemplate does not show.
**Suggestion:** Allow multiple custom names to be added into the hovertemplate to increase the functionality of the feature.

**Comment by cpsievert** [comment]
Thanks for the suggestion, but I don't see the value in adding this feature considering you can just use `paste()` to do the same:

```r
hovertemplate = paste(
  '<i>Price</i>: $%{y:.2f}',
  '<br><b>X</b>: %{x}<br>',
  '<b>',  c("Text A", "Text B", "Text C", "Text D", "Text E"),  '</b>'
)
```

**Comment by nitramwin** [comment]
@cpsievert  Thanks for the example. This is incredibly useful to learn about. Perhaps consider adding this to the example page so that beginners like myself don't have to go around bothering busy people like yourself ;-) Cheers!
