### ISSUE TITLE
Incorrect Background Fill when violin plot generated by ggplot is piped into toWebGL()

### ISSUE THREAD

**Issue by wdm0336** [ropensci/plotly#1693]
Generating a series of violin plots with vertical facets. The background color is not filled completely in the entire background when the ggplot object is sent thru toWebGL(). If I generate boxplots instead of violin plots, things seem to work. If I don't use faceting, things appear to be correct.

A picture is worth a 1000 words so check out the "with" and "without" toWebGL().
![plot_with_toWebGL](https://user-images.githubusercontent.com/25665393/73879360-529bf400-482a-11ea-8314-838beef0a9e5.png)
![plot_without_toWebGL](https://user-images.githubusercontent.com/25665393/73879362-529bf400-482a-11ea-8038-bf3b9b1c61cc.png)

```r
# Data set is attached. load into data_frame() called 'dat'

library(ggplot2)
library(dplyr)
gg <- ggplot(dat, aes(x = Axis, y = Value))
gg <- gg + geom_violin(scale = "width", aes(color = group_color))
gg <- gg + geom_jitter(shape = 16, position = position_jitter(0.2), 
    aes(text = hover_text))
gg <- gg + facet_grid(Vert ~ .)
gg <- gg + guides(color = FALSE)
gg <- gg + ylim(0, 1) + ylab("Score")
gg <- gg + xlab("Attributes")
gg <- gg + ggtitle("Violin Plot of Data")
gg <- gg + theme_minimal()
gg <- gg + theme(legend.position = "none",
	plot.title = element_text(size = 20, hjust = 0.5), 
	panel.grid.major = element_blank(),
	panel.background = element_rect(fill = "grey90"),
	axis.text.y = element_text(size = 10),
	axis.title.y = element_text(size = 16),
	panel.grid.major.y = element_line(linetype = "dotted"),
	axis.text.x = element_text(size = 10, angle = 90, hjust = 1),
	axis.title.x = element_text(size = 16),
	strip.text.x = element_text(size = 10),
	strip.text.y = element_text(size = 10),
	plot.margin = margin(0, 2, 0, 2, "cm"))

print(gg)
print(gg) %>% toWebGL()
```

[dat.csv.zip](https://github.com/ropensci/plotly/files/4161871/dat.csv.zip)

**Comment by cpsievert** [comment]
Likely a result of https://github.com/plotly/plotly.js/issues/2291, so unfortunately there's isn't much I can do fix...is there a reason why you need `toWebGL()` over `ggplotly()` (the latter renders ok, right?)

**Comment by wdm0336** [comment]
ggplotly renders correctly (without toWebGL). We are using toWebGL() to reduce the time it takes to generate the plot when there is a lot of data.

**Comment by cpsievert** [comment]
Ok, unfortunately there's isn't anything I can do in the R package to workaround this problem...the fix must come from plotly.js, so I'll be closing this...subscribe to https://github.com/plotly/plotly.js/issues/2291 for updates

PS. thanks for the reprex!

**Comment by wdm0336** [comment]
Thanks for the quick follow up. I understand you cannot do anything about.

Bill
