### ISSUE TITLE
annotate() in ggplot2 is not working in plotly

### ISSUE THREAD

**Issue by sammyds** [ropensci/plotly#170]
Hi,

I have some annotations in my graphs created by ggplot2. When I create plotly graphs, the annotations either disappear or the converter returns an error. Would appreciate any feedback on this. Below is the sample code

Thanks.
Sammy

## This doesn't return any error but the annotation disappears in the plotly graph
library(plotly)
py <- plotly()
TmpDf <- data.frame (Year = c("2012", "2013", "2014"), Count = c(150, 350, 250))
graph <- ggplot(TmpDf, aes(x=Year, y=Count)) +  geom_bar(stat="identity", width=0.5) 
graph = graph + annotate ("text", label = "+28.6%", x = 3, y = 265, size = 3)
py$ggplotly(graph, kwargs=list(fileopt="overwrite", filename="stacked-bars"))

## This  returns an error "Error in eval(expr, envir, enclos) : object 'Period' not found"
TmpDf <- data.frame (Year = c("2012", "2013", "2014", "2012", "2013", "2014"),
                     Count = c(150, 350, 250, 300, 600, 260),
                     Period = c("YTD", "YTD", "YTD", "Rest of year",
                                "Rest of year", "Rest of year"))
graph <- ggplot(TmpDf, aes(x=Year, y=Count, group=Period, fill=Period)) +
         geom_bar(stat="identity", width=0.5) 
graph = graph + annotate ("text", label = "+28.6%", x = 3, y = 540, size = 3)
py$ggplotly(graph, kwargs=list(fileopt="overwrite", filename="stacked-bars"))

**Comment by cpsievert** [comment]
Instead of using ggplot2's `annotate()`, you could achieve the same effect by first converting ggplot2 to plotly and add a plotly annotation.

```r
g <- ggplot(TmpDf, aes(x=Year, y=Count)) + geom_bar(stat="identity", width=0.5) 
ggplotly(g) %>%
  layout(annotations = list(x = "2014", y = 275, text = "+28.6%", showarrow = F))
```
