### ISSUE TITLE
plot_mapbox: example from book not working after updating plotly

### ISSUE THREAD

**Issue by werkstattcodes** [ropensci/plotly#1707]
Many thanks for your invaluable contribution with the plotly package!

I tried to recreate one map from your very helpful book on plotly & co (chapter  4.1.1).
Here the [link](https://plotly-r.com/maps.html#overview-1).

```
library(plotly)
plot_mapbox(maps::canada.cities) %>%
  add_markers(
    x = ~long, 
    y = ~lat, 
    size = ~pop, 
    color = ~country.etc,
    colors = "Accent",
    text = ~paste(name, pop),
    hoverinfo = "text"
  )
```
The map is produced as intended when using your RStudio Cloud version which uses Plotly  4.9.0.9000.  After updating the package to the latest CRAN version (which I use on my local machine, 4.9.2) the code produces only the dots, but no map in the background. Below a screenshot of the graph. I assume that's a bug, no? 

Many thanks again.

<img width="298" alt="Capture" src="https://user-images.githubusercontent.com/9595585/75138384-5fee2500-56ea-11ea-9b16-6e3238464c9b.PNG">

**Comment by cpsievert** [comment]
Introduced by https://github.com/ropensci/plotly/commit/8108b20216732859b98954af6e4749a19f9fcb4a

**Comment by werkstattcodes** [comment]
Great. Can confirm it works as intended after installing the dev version. Many thanks!
