### ISSUE TITLE
Crosstalk + Plotly bar-chart “gaps” for unselected entries

### ISSUE THREAD

**Issue by dgdi** [ropensci/plotly#1709]
First, many thanks for your work. It is amazing how simple it is to do amazing visualizations using it and as a non-CS guy I am really grateful for that. Keep up with the great work!

I have also posted on  [SO](https://stackoverflow.com/questions/60393253/crosstalk-plotly-bar-chart-gaps-for-unselected-entries) about the issue.

I am tring to use Crosstalk and Plotly to create a dashboard and I have come across an unexpected behaviour. When selecting through the Crosstalk fiter, the Plotly bargraph leaves "gaps" for the unselected entries.

As a reproducible example, let's say I want compare cities populations, what I am getting is this (code at the bottom)

![SO_crosstalk_plotly](https://user-images.githubusercontent.com/14221480/75243527-520fd100-57ca-11ea-97df-1da08809b11a.gif)

It might very well be that I am missing something, is there a way to get rid of the gap? any advice on viable ways to do a similar comparison avoiding the issue?

I am using R 3.6.1, crosstalk 1.1.1.9000, plotly 4.9.2

Thanks in advance.

Code

```
---
title: "Crosstalk+Plotly bargraph selection"
---

```{r setup, include=FALSE}
options(stringsAsFactors = FALSE)
library(crosstalk) 
library(dplyr)
library(plotly)  

#data on cities' population
city_pop <- data.frame("City" = c("Florence",  "Milan", "Venice"),
                    "Population" = c(382258, 1352000, 261905))

#setting up Crosstalk shared data
sd <- SharedData$new(city_pop, key = city_pop$city)

#filter for the cities
filt <- filter_select(
  id = "select_name",
  label = "Selected City",
  sharedData = sd,
  group = ~City,
  selected = "")

#barplot of cities' population
bars_pop <- plot_ly(sd, x = ~City, y = ~Population) %>% 
add_bars(width=0.2,
           x =  ~City,
       y =  ~Population,
       color = I("#89CFF0"),
       name = "",
       opacity=.9,
       hoverinfo = 'y',
       hovertemplate = paste('%{x} <br> number of Residents: %{y}<extra></extra>')
       ) 



```

```{r, echo=FALSE}
filt

bars_pop
```

**Comment by rainer-rq-koelle** [comment]
Hi @dgdi, I ran into the very same issue about the same time, my friend :)
It will not help, but the issue seems to be known for quite a while now without any real solution/change, c.f. https://github.com/ropensci/plotly/issues/689. I keep my fingers crossed.

**Comment by dgdi** [comment]
Hi @rainer-rq-koelle, thanks for your feedback. Nice to know I am not the only one who thougt to use the packages that way! 
This issue is definetly a Duplicate of #689 .
I have updated the SO question with the link to your [SO question](https://stackoverflow.com/questions/60464144/how-to-remove-empty-factors-from-xaxis) and to issue #689 .

**Comment by rainer-rq-koelle** [comment]
Good stuff. Let’s keep the fingers crossed that a solution can be found.
All the best,
RQ
