### ISSUE TITLE
X axis tick labels incorrect when plotting dates

### ISSUE THREAD

**Issue by chlorenz** [ropensci/plotly#1725]
The x axis labels in ggplotly() are incorrect when the data consists of dates.

![Capture](https://user-images.githubusercontent.com/9529898/77428356-da849000-6dcf-11ea-83f5-4cfe4f887e09.PNG)

The difference can range from one to several days and seems to depend on the total number of tickmarks/labels. It seems there is some sort of offset applied to all labels.

```r
dat <- data.frame(
  x = as.Date(0:10, origin="1970-01-01"),
  y = 0:10
)

p <- ggplot(data = dat, aes(x=x, y=y)) + geom_point()
p
ggplotly(p)
```

Similar data, different offset:

```r
dat <- data.frame(
  x = as.Date(1:10, origin="1970-01-01"),
  y = 1:10
)

p <- ggplot(data = dat, aes(x=x, y=y)) + geom_point()
p
ggplotly(p)
```

**Comment by janejuenyang** [comment]
I'm seeing this issue in a deployed Shiny app as well, though the graph is displaying correctly locally.

**Comment by dbeley** [comment]
Hi I have the same issue, it seems to be a problem with ggplot 3.3.0.

Downgrading to 3.2.1 with `devtools::install_version("ggplot2", version = "3.2.1", repos = "http://cran.us.r-project.org")` fixes the issue for me.

source : https://stackoverflow.com/questions/60807523/how-to-show-correct-horizontal-axis-in-ggplotly-when-it-is-a-date/60808558#60808558

**Comment by chlorenz** [comment]
Thanks @dbeley 

The Stackoverflow post links to #1721 which indicates that this issue is not necessarily restricted to dates.
