### ISSUE TITLE
Human-readable number formatting in hover tooltip

### ISSUE THREAD

**Issue by stvrd** [ropensci/plotly#1726]
Hello and thank you for this magnificient package!

I am struggling a bit with the number formatting in the hoverinfo.
[Here](https://plotly.com/r/bubble-charts/#styled-buble-chart) is an example of a wonderful plot, but the big numbers in the hoverinfo should be human-readable (with big.mark = `,`).

Is there a way to do this inside the `text` argument ?

Btw, I know how to do this with
` plot_ly(df,..., hovertemplate = 'Big Number: %{marker.size:,} `
but when I need many numbers inside the tooltip, hovertemplate does not work anymore (you can only specify numbers used for the plot).

Thank you in advance!

**Comment by cpsievert** [comment]
> Is there a way to do this inside the `text` argument ?

You're probably looking for `scales::comma_format()` (or similar). See also https://plotly-r.com/controlling-tooltips.html

By the way, please use https://community.rstudio.com/ or SO to ask questions like this
