### ISSUE TITLE
ggplotly is making 1st label of x scale NA on line graph

### ISSUE THREAD

**Issue by davidhodge931** [ropensci/plotly#1729]
ggplotly is making 1st label of x scale NA on line graph.

```r
library(dplyr)
library(ggplot2)

plot_data <- storms %>% 
  group_by(year) %>% 
  summarise(max_wind = max(wind)) 

plot <- ggplot(plot_data) +
  geom_line(aes(year, max_wind))

plot

plotly::ggplotly(plot)
```

**Comment by davidhodge931** [comment]
This appears to be a bug in 4.92, as 4.91 was sweet

**Comment by cpsievert** [comment]
Hmm, I can't seem to replicate. Can you include your `devtools::session_info()` and a screenshot?

**Comment by davidhodge931** [comment]
![ggplotly_bug_image](https://user-images.githubusercontent.com/55065152/78070713-c86ea700-73f8-11ea-843f-82bac5fd2d94.PNG)

**Comment by cpsievert** [comment]
Can u please try again with the dev version of plotly? `remotes::install_github('ropensci/plotly')`

**Comment by davidhodge931** [comment]
Dev version works fine :)
