### ISSUE TITLE
ggplotly call on line plot with time series produces incorrect X-axis labels

### ISSUE THREAD

**Issue by apoorvalal** [ropensci/plotly#1734]
Like everyone else, I've been playing around with COVID19 data [I promise I'm not planning to write a medium post], and came across this weird bug. 

---

When I create a time series plot with ggplot [where the date column is created using `anydate`], the x axis labels are correct [Month - Date]. However, when I pass the plot object to ggplotly, the x-axis labels are inexplicably moved back by 7 days. Here's a minimal example:

```r
library(data.table)
library(tidyverse) 
library(anytime) 
library(plotly)
theme_set(theme_minimal())
# %%
ctracking_url = "http://covidtracking.com/api/states/daily.csv"
state_tests = fread(ctracking_url)
# date column
state_tests[, d := anydate(date)]
# slice to display 10 worst hit states
(most_affected = 
     state_tests[d == max(state_tests$d)][
    order(-positive)][
    1:10])
# %%
t10states = state_tests[positive >= 10 & state %in% most_affected$state]
# ggplot figure with date correct labels
(p = ggplot(t10states, aes(x = d, y = positive, colour = state, group = state)) +
        geom_point() + geom_line() + 
        labs(
            title = "Cumulative Cases by state",
            subtitle = paste(most_affected$state, collapse = ", ")
        ) + scale_y_log10()
)

# ggplotly call that produces figure with incorrect labels
ggplotly(p)
```

+ here's the ggplot figure with the correct labels
![ggp_fig](https://user-images.githubusercontent.com/12086926/78290784-21ae0780-74d9-11ea-81c1-5731af345828.png)

+ and here's the ggplotly figure with the incorrect labels
![plotly_fig](https://user-images.githubusercontent.com/12086926/78290788-22df3480-74d9-11ea-85b8-c0c5b1a56fa1.png)

**Comment by apoorvalal** [comment]
That fixed it. Thanks a lot!

**Comment by TarynLeeMorris** [comment]
I was having this exact problem! (also with my covid app - haha!). Hallelujah!
