### ISSUE TITLE
Adding a simple data table to figure

### ISSUE THREAD

**Issue by asmagen** [ropensci/plotly#1737]
I am using subplot and plot_ly to organize multiple figures in a grid and I want to have a table summarizing the metadata of the select points in the scatter plot.
I found that renderDataTable from DT is generating the table I am interested in but it seems that it can be produced only in a shiny program while I am not using that.
Can it be done in plot_ly without generating a shiny app?

**Comment by cpsievert** [comment]
Sounds like it should, see https://plotly-r.com/client-side-linking.html and also `demo("sf-dt", package = "plotly")`.

In the future, please use https://community.rstudio.com/ or similar to ask such questions...this issue tracker is for bug reports and feature requests only
