### ISSUE TITLE
ggplotly shifts x-axis to the right with ggplot2 version 3.3.0 when plotting dates 

### ISSUE THREAD

**Issue by mbastin19** [ropensci/plotly#1738]
---

Hello, 
When using ggplotly on a ggplot2 object that plots a vector of class "Date" in x, ggplotly shifts the x-axis to the right. This issue happens with ggplot2 version 3.3.0 but does not happen with ggplot2 3.2.1. This issue also happens with ggplot2 3.2.1 if the dplyr package version is older than 0.8.4. 
Please see the example below: 
```r
library(ggplot2)
g = ggplot(data.frame(date=as.Date(sprintf("2020-04-%02i", 1:9)), n=((1:9)-5)^2), aes(date, n)) + geom_line()
print(g) #  displayed x labels: Apr 02, Apr 04, Apr 06, Apr 08 (expected)
plotly::ggplotly(g) # displayed x labels: Mar 31, Apr 02, Apr 04, Apr 06 (shift to the right)
```

**Comment by cpsievert** [comment]
Upgrading plotly should fix this (let me know if it doesn't)
