### ISSUE TITLE
layout yields warning regarding attributes: 'sunburstcolorway', 'extendsunburstcolors'

### ISSUE THREAD

**Issue by ismirsehregal** [ropensci/plotly#1745]
The sunburst example _subplots_ given [here](https://plotly.com/r/sunburst-charts/) yields the follwing warning when executed:

> Warning message:
> 'layout' objects don't have these attributes: 'sunburstcolorway', 'extendsunburstcolors'
> Valid attributes include:
> 'font', 'title', 'uniformtext', 'autosize', [...]

Using plotly version 4.9.2

**Comment by cpsievert** [comment]
Duplicate of https://github.com/ropensci/plotly/issues/1745
