### ISSUE TITLE
plot_ly(mtcars, x = ~mpg, y = NULL) shows two variables

### ISSUE THREAD

**Issue by zac-garland** [ropensci/plotly#1749]
not understanding the behavior here, what y value is this showing?

```r
plot_ly(mtcars, x = ~mpg, y = NULL)
```

**Comment by cpsievert** [comment]
Huh, weird, this should be fixed in the R package, but you can avoid the weird result by being explicit about how you want to the render the `x` values:

```r
plot_ly(mtcars, x = ~mpg, y = NULL, type = "histogram")
```

Or

```r
plot_ly(mtcars, x = ~mpg, y = NULL) %>% add_histogram()
```

**Comment by zac-garland** [comment]
@cpsievert no worries! just thought it was odd and wanted to check what value it was showing.
