### ISSUE TITLE
plot_ly(.) function does not consistently display a plot in R 4.0.0 and RStudio

### ISSUE THREAD

**Issue by QuantDevHacks** [ropensci/plotly#1756]
Since upgrading to R 4.0.0, and to plotly 4.9.2.1, I have been experiencing a problem where `plot_ly(.)` will only display its result about 25%-30% of the time.  The other attempts result in a blank result in the RStudio (v 1.2.5042) Viewer.  I have tried reverting to an earlier version of RStudio (1.2.1335), as well as an earlier version of plotly (4.8.0), but the problem still occurs.  This would seem to indicate the problem is with R 4.0.0, as I had no issues with R 3.6.2 and RStudio 1.2.1335, but of course this is not necessarily conclusive.  Reverting to a an R installation earlier than v 4.0.0, is not an option, due to other requirements for the projects I'm working on.

My OS is Windows 10.

Below is some simple code I've used; there seems to be no pattern which graphs will be displayed or when.

Thanks in advance.

```r
library(plotly)

squareSides <- c(1:10)
circleRadii <- c(1:10)

squareAreas <- c(1, 4, 9, 16, 25, 36, 49, 64, 81, 100)
circleAreas <- c(3.141593,12.566371,28.274334,50.265482,78.539816,113.097336,
153.938040, 201.061930, 254.469005, 314.159265)

dfSq <- matrix(data=c(squareSides, squareAreas), nrow=length(squareSides), ncol=2)
dfSq <- as.data.frame(dfSq)
colnames(dfSq) = c("Side", "Area")
rownames(dfSq) = NULL
plot_ly(dfSq, x = ~Side, y = ~ Area, type = "bar")


dfCirc <- matrix(data=c(circleRadii, circleAreas), nrow=length(squareSides), ncol=2)
dfCirc <- as.data.frame(dfCirc)
colnames(dfCirc) = c("Radius", "Area")
rownames(dfCirc) = NULL
plot_ly(dfCirc, x = ~Radius, y = ~ Area, type = 'scatter', mode = 'lines', color = 'red')
```

**Comment by cpsievert** [comment]
Thanks, could you also right-click -> Inspect Element and report any errors you're seeing?

**Comment by QuantDevHacks** [comment]
Thanks for your reply.  I ran Inspect Element but did not detect any obvious anomalies.  Under the _Elements_ tab, there is HTML code displayed that looks normal, and under _Console_, there are no notifications.  I looked under the other tabs as well, but I didn't see anything obviously wrong; however, this is the 1st time I've used Inspect Element.  

Is there something in particular I should be looking for?  

Just for completeness, I opened Inspect Element for both cases running `plot_ly(.)`, where the plot didn't display, and where it did.  I didn't see any obvious differences between these either.  I also repeated the process about 10 times.

**Comment by jcheng5** [comment]
It's an issue we've discussed here: https://github.com/rstudio/rstudio/issues/6737

RStudio dailies will work around this problem in the next day or two (https://dailies.rstudio.com).

**Comment by jmcphers** [comment]
We have also just updated the preview release with a version that fixes this problem.

https://www.rstudio.com/products/rstudio/download/preview/

**Comment by QuantDevHacks** [comment]
Seems to work just fine now.  Thanks very much!!!
