### ISSUE TITLE
Legends of multiple ggplots with facet_grids are not displayed correctly with subplot

### ISSUE THREAD

**Issue by MarcoPortmann** [ropensci/plotly#1757]
I want to plot several ggplots with facet_grids with plotly. The plots should have a common legend. Unfortunately, I can't get it that the y-axes are not cut off (https://github.com/ropensci/plotly/issues/1224), only one legend is displayed and there are no repetitions in the legend, as in the example:

```r
library(plotly)

mtcars2 <- mtcars
mtcars2$gear <- factor(mtcars$gear)
mtcars2$vs <- factor(mtcars$vs)

pl1 <- ggplot(mtcars2, aes(x = cyl, y = disp, color = gear)) +
  geom_point() + facet_grid(cols = vars(vs)) + ylab("display")

pl2 <- ggplot(mtcars2, aes(x = qsec, y = disp, color = gear)) +
  geom_point() + facet_grid(cols = vars(vs)) + ylab("q sec")

subplot(pl1, pl2, margin = 0.10)
```
![image](https://user-images.githubusercontent.com/7468121/80704544-13a5d380-8ae5-11ea-8c77-136c29f81388.png)

I have found the same question several times on stackoverflow, but unfortunately without a working solution.

Among other things it is suggested to create a ggplot with several facets instead of several ggplots. However, I create a shiny app where the user can customize the plots and maybe has already defined facet rows and columns. Also the plots have different y-axis labels because the units are different (It is not impossible to define different ylabs for each facet, but actually it does not correspond to the ggplot philosophy and needs some tweaking).

I would be grateful for a solution or a workaround to this problem.

**Comment by cpsievert** [comment]
This is a big hack, but I think it does what you want 

```r
p <- subplot(hide_legend(pl1), pl2, margin = 0.03) %>%
  plotly_build()

grps <- vapply(p$x$data, function(trace) trace$legendgroup, character(1))
p$x$data <- Map(function(trace, show) { 
  trace$showlegend <- show
  trace
  }, p$x$data, !duplicated(grps))
p
```
