### ISSUE TITLE
geom_hline, geom_vline as shapes?

### ISSUE THREAD

**Issue by tdhock** [ropensci/plotly#176]
currently these are implemented as traces of mode "lines"

http://ropensci.github.io/plotly-test-table/tables/00a5c8df16e2b19a6629c32ed42ef3a76d6fbac6/vline-multiple.html

but should we implement them as shapes?

https://plot.ly/~etpinard/1647/plotly-shapes/

**Comment by chriddyp** [comment]
yeah, definitely! the nice thing about shapes is that we can use paper coordinates, so that they can span the entire plot

**Comment by tdhock** [comment]
I'm thinking about how to do this and I'm wondering ... can plotly shapes can have legend entries?

If not, then we will run into problems, since geom_hline and geom_vline can generate legends in ggplot2. In this case we should keep these as traces of mode "lines" which will result in plotly legends.

**Comment by tdhock** [comment]
@alexcjohnson can plotly shapes can have legend entries?

**Comment by cpsievert** [comment]
In #269 I've implemented hline/vline/abline as paths
