### ISSUE TITLE
Plotly (R) not Rendered in Jupyter html Output

### ISSUE THREAD

**Issue by LustigePerson** [ropensci/plotly#1763]
## Issue
When using R Plotly in a Jupyter Notebook, the interactive widgets will not appear in the output when using nbconvert to transform it to html.
Console in the browser says: ```Uncaught ReferenceError: Plotly is not defined```.

I am not quite sure if this issue is caused by plotly, jupyterlab, or nbconvert, but for the python version it works, so I guess plotly R is doing something different here.

## Reproduce
You can use the jupyter-stacks R image and install plotly to test:
```bash
docker run -it -p 8888:8888 jupyter/r-notebook bash


conda install -y r-plotly

export NODE_OPTIONS=--max-old-space-size=4096
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
jupyter labextension install jupyterlab-plotly --no-build
jupyter labextension install plotlywidget --no-build
jupyter lab build
unset NODE_OPTIONS

jupyter lab --NotebookApp.token=''
```
Without the labextensions, the widgets are rendered within the notebook but they don't look right (the height of the output field is to low).

When you access the notebook (```localhost:8888```) just try a standard plot, e.g. :
```R
library(plotly)
fig <- plot_ly(y = ~rnorm(50), type = "box")
fig <- fig %>% add_trace(y = ~rnorm(50, 1))

fig
```
This should render fine within the notebook, but saving as html (via jupyter lab interface or via nbconvert from the terminal) is not working, i.e. the output is missing.

For Python this is working fine with the jupyter lab extensions.

## Versions
plotly 4.9.2.1
nbconvert 5.6.1

**Comment by MSeal** [comment]
Linked issue in nbconvert if it helps to have our teams chat about how to approach this. Effectively the html outputs in the cell aren't renderable without the extensions present, which on a plain html file don't exist.

**Comment by MSeal** [comment]
https://github.com/jupyter/nbconvert/issues/1253

**Comment by MSeal** [comment]
Also, somewhat related, the cell output is really really big for a basic plot (5MB). Looking through the file it seemd every script associated has a the png embeded into the html, causing the rendering to be duplicated on every media type including text. You likely want to only render the PNG on the image output and leave the other with the raw data to reproduce to PNG.

**Comment by LustigePerson** [comment]
Sorry @MSeal , I wanted to link the two issues I created, but eventually forgot to do so. Thanks for taking care.

**Comment by cpsievert** [comment]
In the case that something needs to be done on the R level, it'll likely need to happen at the [htmlwidgets](https://github.com/ramnathv/htmlwidgets) level (i.e., the R->HTML bridge) and/or the [repr](https://github.com/IRkernel/repr) level (i.e., the Jupyter R->HTML bridge, which uses htmlwidgets under the hood to generate the HTML). Put another way, if this is a problem for plotly, I bet it's also a problem for other htmlwidgets (e.g., leaflet, networkD3, etc). In that case, I don't think there's anything I can do in the R plotly package to help with this issue, but feel free to reopen if I'm missing something (and/or open a new issue elsewhere)

**Comment by MSeal** [comment]
Alright, I'll repost the issue into those packages and see if someone can address the problem in the R package most responsible for managing outputs. Thanks @cpsievert
