### ISSUE TITLE
Error of plotly_build() function in google Colab using R

### ISSUE THREAD

**Issue by erivandosena** [ropensci/plotly#1769]
Description of the my problem:

Used R in google Colab I can't plot a ggplot2 graph as dynamic using the plotly plotly_build() function, any solution to do this in Google Colab in R?

Example code:
```r
# Load libraries
library(ggplot2)
library(dplyr)

# Dataset
data <- data.frame(
  name=c("north","south","south-east","north-west","south-west","north-east","west","east"),
  val=sample(seq(1,10), 8 )
)

# Load the library
library(forcats)

# ggplot2 chart default
gplot <- data %>%
  mutate(name = fct_reorder(name, val)) %>%
  ggplot( aes(x=name, y=val)) +
    geom_bar(stat="identity", fill="#f68060", alpha=.6, width=.4) +
    coord_flip() +
    xlab("") +
    theme_bw()
 
 # Load the library
 library(plotly)

 # Plot dynamic chart
 plotly_build(gplot) # <= on google Colab it doesn't plot anything :(
```
![plotly_build_error_google_colab_R](https://user-images.githubusercontent.com/23545595/82106908-57f6bd80-96fa-11ea-885c-f2305bf52000.jpg)

**Comment by cpsievert** [comment]
The example in the screenshot is using `geom_text_repel()`, which generally isn't supported by `ggplotly()`...does the example code that you've provided (which doesn't `geom_text_repel()`) not work either?

**Comment by erivandosena** [comment]
Hi! cpsievert

no!
no graph using plotly () natively does not work in Google Colab in R :/

**Comment by cpsievert** [comment]
Interesting, thanks...do other htmlwidgets (e.g. leaflet) work inside google collab?

**Comment by erivandosena** [comment]
hi! **cpsievert**
I used leaflet and it works perfect, just plotly that fails.
