### ISSUE TITLE
ssl certificate problem

### ISSUE THREAD

**Issue by tdhock** [ropensci/plotly#177]
```
SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

There is currently no way for plotly users to override certificate errors such as above. You simply can't use the R-API if the certificate verify fails.

The current code in plotly.R uses RCurl, which actually does support ignoring the certificate errors if you give it the right option.

```
> foo <- getURLContent("https://plot.ly/~TestBot/3422.png")
Error in function (type, msg, asError = TRUE)  : 
  SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
> foo <- getURLContent("https://plot.ly/~TestBot/3422.png", ssl.verifypeer=FALSE)
> foo
    [1] 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 02 bc 00 00 01 f4
   [25] 08 06 00 00 00 df 59 fe df 00 00 00 20 63 48 52 4d 00 00 7a 26 00 00 80
   [49] 84 00 00 fa 00 00 00 80 e8 00 00 75 30 00 00 ea 60 00 00 3a 98 00 00 17
```

It would be nice if we could supply such options as kwargs when using the plotly interface object. For example in my test table code I currently write

```r
kwargs <-
        list(filename=paste0("ggplot2/", SHA1, "/", name),
             fileopt="overwrite",
             auto_open=FALSE)
u <- py$ggplotly(gg, kwargs=kwargs)
```

which today has always given me a certificate error.

But it would be nice if I could instead write

```r
u <- py$ggplotly(gg, kwargs=kwargs, RCurl=list(ssl.verifypeer=FALSE))
```

@chriddyp does this sound OK to you? If so do you want to write that code or should I? We would have to modify the makecall, plotly, and ggplotly methods.

**Comment by chriddyp** [comment]
I actually don't think we should allow people to ignore SSL for security reasons since each API calls contains the API key, which can be used to access all of a user's data. This method is currently failing because Plotly's SSL cert expired, which should've never happened (and is getting fixed right now!)
