### ISSUE TITLE
Remove iris from examples

### ISSUE THREAD

**Issue by cpsievert** [ropensci/plotly#1790]
Instead use https://github.com/allisonhorst/palmerpenguins when it's on CRAN

**Comment by julianstanley** [comment]
This was pushed to CRAN a few days ago now (https://cran.r-project.org/web/packages/palmerpenguins/index.html).

Do you also want to remove iris from the tests? I only see 4 instances of iris in the examples, but quite a few in `test-plotly`, `test-ggplot-legend`, `test-ggplot-theme`,` test-ggplot-symbol`, `test-ggplot-labels`, `test-api`, `test-plotly-color`, `test-plotly-subplot`, and `test-ggplot-size`.

**Comment by cpsievert** [comment]
I'd say the book would be a better change than the tests, but both would be welcome, thanks!

**Comment by superjai** [comment]
Hello! I am an ecologist and an admirer from afar of Ropensci for some time. I thought that I might jump in to actually help with things. Stefanie Butland suggested that I should take a look at open issues, as a way to get started with helping. This particular issue seems like a very easy place to get started. I am happy to work on this issue, but before I get started, I wanted to double check that this was still actually an open issue (the message at the top of the screen indicates that Commit #1830 might have fixed this issue). On the other hand, I still see references to iris in the package. Thanks! Jai

**Comment by cpsievert** [comment]
Hi @jai, yes, #1830 closes this issue (I just merged it)
