### ISSUE TITLE
 plot_mapbox() default style is causing the states borders to be invisible

### ISSUE THREAD

**Issue by fmgithub2017** [ropensci/plotly#1793]
plot_mapbox() default style ('basic') is causing the countries states borders to be invisible, since both have the same color gray. First observe the perfect seeable USA states borders using style 'outdoors': 

```
library(plotly)
library(magrittr)
plot_mapbox() %>% layout(mapbox=list(style = 'outdoors'))
```
![image](https://user-images.githubusercontent.com/26294221/84558855-4f4ed280-ad0c-11ea-9fd8-30faeb4c87b7.png)
(By the way, with this style, there are large portions of the world map with the color white instead of green, what does that represent?)

Then compare to the invisible ones obtained by the 'basic' default style:
```
plot_mapbox() %>% layout(mapbox=list(style = 'basic')) 
```
![image](https://user-images.githubusercontent.com/26294221/84558856-55dd4a00-ad0c-11ea-8c15-a8e0b83adf14.png)

So, is it possible to customize the 'basic' style, changing the borders color for example?

In my ignorance, I found the mapbox site ( https://docs.mapbox.com/mapbox-gl-js/style-spec/ ) completely useless to learn style customizations for R plot_mapbox(). Is there a more clear reference for non-experts?

I would really appreciate if you can shed some light on these issues. 

Plotly is one of the best packages that I ever worked with, so congratulations for the great work.

**Comment by cpsievert** [comment]
> So, is it possible to customize the 'basic' style, changing the borders color for example?

Yes, I think this is the documentation you're looking for -- https://docs.mapbox.com/help/tutorials/create-a-custom-style/

After creating the custom map, you should be able to get a link to it that you can pass along to `...` in:

```r
plot_mapbox() %>% layout(mapbox=list(style = ...)) 
```

**Comment by fmgithub2017** [comment]
Thanks man! I will try and later post here if worked.

**Comment by fmgithub2017** [comment]
Done. Just replace `...` from `plot_mapbox() %>% layout(mapbox=list(style = ...))`  with the Style URL generated for your new custom map.
