### ISSUE TITLE
hovermode = 'x unified' is not showing as expected

### ISSUE THREAD

**Issue by MinhChauVanNguyen** [ropensci/plotly#1794]
I am trying to run the same code obtained from https://plotly.com/r/hover-text-and-formatting/ under **Unififed hovermode**, but the plot didn't come out the same as the example plot. 

**Example plot**

<img width="600" alt="Screen Shot 2020-06-14 at 10 22 08 AM" src="https://user-images.githubusercontent.com/61895317/84580260-646d5380-ae29-11ea-9475-3cc8bb50d3e2.png">

**My plot**

<img width="744" alt="Screen Shot 2020-06-14 at 10 22 59 AM" src="https://user-images.githubusercontent.com/61895317/84580266-6fc07f00-ae29-11ea-91d7-e081a24318f0.png">

As you can see the tool tip is split into separate tool tips for each trace in my version. My question is how do I then get the default/correct tool tip?

**R code**
```
trace_0 <- rnorm(100, mean = 5)
trace_1 <- rnorm(100, mean = 0)
trace_2 <- rnorm(100, mean = -5)
x <- c(1:100)

data <- data.frame(x, trace_0, trace_1, trace_2)

fig <- plot_ly(data, x = ~x, y = ~trace_0, name = 'trace 0', type = 'scatter', mode = 'lines') 
fig <- fig %>% add_trace(y = ~trace_1, name = 'trace 1', mode = 'lines+markers') 
fig <- fig %>% add_trace(y = ~trace_2, name = 'trace 2', mode = 'markers')
fig <- fig %>%
  layout(hovermode = "x unified")
fig
```

I am using **R Studio version 1.2.1335** and **plotly package version 4.9.2**. Also, I don't know if this helps but I am running this on a **Mac**.

**Comment by Ricmuck** [comment]
I have the same issue plotly version 4.9.2

**Comment by trekonom** [comment]
I just checked on the latest development version. Installing via `devtools::install_github("ropensci/plotly")` should give you the tooltip as in the example on [https://plotly.com/r/hover-text-and-formatting/ ](https://plotly.com/r/hover-text-and-formatting/ ).

**Comment by MinhChauVanNguyen** [comment]
It's working now. Thank you!
