### ISSUE TITLE
Master list of supported/unsupported features

### ISSUE THREAD

**Issue by chriddyp** [ropensci/plotly#18]
Hi all --

This great post is keeping track of the unsupported ggplot geoms: [http://aarongonzales.net/plotly_examples.html](http://aarongonzales.net/plotly_examples.html). 

I thought I'd copy that master list over here, just to make y'all aware. Feel free to re-organize the issue (close it, break it out into separate issues, etc!) in anyway that you'd like!

### geoms
- [x] geom_abline
- [x] geom_area
- [x] geom_bar
- [ ] geom_bin2d
- [x] geom_boxplot
- [x] geom_contour
- [ ] geom_crossbar
- [x] geom_density
- [x] geom_density2d
- [ ] geom_dotplot
- [x] geom_errorbar
- [x] geom_errorbarh
- [ ] geom_freqpoly
- geom_hex() (untested)
- [x] geom_histogram
- [x] geom_hline
- [ ] geom_jitter
- [x] geom_line()
- [ ] geom_linerange
- [ ] geom_map
- [x] geom_path()
- [x] geom_point()
- [ ] geom_pointrange
- [x] geom_polygon()
- [ ] geom_quantile
- [ ] geom_raster
- [x] geom_rect
- [x] geom_ribbon
- [ ] geom_rug
- [x] geom_segment()
- [x] geom_smooth
- [x] geom_step
- [x] geom_text
- [x] geom_tile
- [x] geom_violin
- [x] geom_vline

### stats
- [ ] stat_abline
- stat_bin
- stat_bin2d
- stat_bindot
- stat_bindot
- stat_binhex
- stat_contour
- stat_density
- stat_density2d
- stat_ecdf
- stat_function
- stat_hline
- stat_identity
- stat_qq
- [ ] stat_quantile
- stat_smooth
- stat_spoke
- stat_sum
- stat_summary
- stat_summary_hex
- stat_summary2d
- stat_unique
- stat_vline
- stat_ydensity

### other ggplot stuff
- expand_limits
- guide_legend
- guide_colourbar(guide_colorbar)
- scale_alpha(scale_alpha_continuous, scale_alpha_discrete)
- scale_area()
- scale_color_brewer
- scale_color_continuous
- scale_color_discrete
- scale_color_gradient
- scale_color_gradient2
- scale_color_gradientn

- coord_cartesian
- coord_equal
- coord_fixed
- coord_flip
- [ ] coord_map
- coord_polar
- coord_trans
- facet_grid
- facet_null
- facet_wrap
- position_dodge
- position_fill
- position_identity
- position_jitter
- position_stack

**Comment by jackparmer** [comment]
Just curious -- In https://plot.ly/~JodyMcintyre/615/plotly-benchmarks/, does scatter with 300k points have no image server initial load b/c it exceeds 30 seconds? Limit on # of scatter points got brought up on a sales call today and I said 500k... :/
Can't wait until this graph gets crushed with WebGL...

**Comment by cpsievert** [comment]
Closing in favor of #348
