### ISSUE TITLE
API should not use /var/root on OS X

### ISSUE THREAD

**Issue by brianboonstra** [ropensci/plotly#180]
The API attempts to store credentials in `/var/root`, at least on my OS X Yosemite installation via MacPorts.  This (rightly) fails due to permission problems.

Traditionally on OS X this type of thing is stored in something like `$HOME/Library/Preferences/com.plotly.plist`.  Python probably has a good defaults module for it.

**Comment by chriddyp** [comment]
Yikes! Thanks for reporting. We were supposed to install it your home directory, `~`, which used to be something like `/Users/chris`: https://github.com/ropensci/plotly/blob/master/R/tools.R#L4.

Where does `$ cd ~` take you?

**Comment by brianboonstra** [comment]
`cd ~` takes me to `/Users/brian`.   Please note the issue is specific to the R API, and occurs whether I am running normally in RStudio or I am using an [R kernel within iPython/Jupyter](https://github.com/takluyver/IRkernel) v3.0.0.  

Is it perhaps related to the fact that I was running an R session as _root_ when I did the `install_github("ropensci/plotly")` ?

**Comment by brianboonstra** [comment]
> py <- plotly('brianboonstra',  '<deleted>')
    Error in if (file.info(CONFIG_FILE)$size) { : 
      argument is not interpretable as logical
    In addition: Warning message:
    In file.create(abspath) :
      cannot create file '/var/root/.plotly/.config', reason 'Permission denied'
    > file.path(path.expand("~"), ".plotly")
    [1] "/Users/brian/.plotly"

**Comment by bogdanrau** [comment]
Any updates to this? I'm running into the same issue on an Ubuntu 14.04 box, my path is:
```
[1] "Your credentials file:"
Error in if (file.info(CREDENTIALS_FILE)$size) { : 
  argument is not interpretable as logical
In addition: Warning message:
In file.create(abspath) :
  cannot create file '/root/.plotly/.credentials', reason 'Permission denied'
> file.path(path.expand("~"), ".plotly")
[1] "/home/[user]/.plotly"
```
with [user] being a specific username on the system.

**Comment by Varshul** [comment]
Even I installed it as a root user, doesn't seem to work at all.
Warning in file.create(abspath) :
  cannot create file '/root/.plotly/.credentials', reason 'Permission denied'
Error in if (file.info(CREDENTIALS_FILE)$size) { : 
  argument is not interpretable as logical

Even Though the CREDENTIALS_FILE does exist having non logical size, it doesn't seem to work.

Is there any solution to it ?

**Comment by cpsievert** [comment]
Version 1.0 no longer requires credentials to be stored in this location. Instead, you can store credentials with:

```r
Sys.setenv("plotly_username"="your_plotly_username")
Sys.setenv("plotly_api_key"="your_api_key")
```

If you want these credentials to be loaded on startup, put this code in your `~/.Rprofile`
