### ISSUE TITLE
ggplotly converts text axis tick labels to numeric

### ISSUE THREAD

**Issue by samfranks** [ropensci/plotly#1854]
ggplotly converts character text for axis labels (x-axis anyway) to numeric. The text renders correctly in the ggplot. This must be a recent bug, as it correctly rendered as recently as 9 Jun 2020, but became a problem certainly by 27 July 2020 (tested using my own code and dataset, but replicated using the iris dataset below).

Reproducible example provided:

```r
p <- ggplot(data = iris, aes(x = Species, y = Petal.Width)) + geom_boxplot()
ggplotly(p)
```

Screenshots below of ggplot:
![iris_ggplot](https://user-images.githubusercontent.com/8385598/93620930-b4ccf200-f9d2-11ea-85d9-99c3121c7ba5.jpg)

and plotly output:
![iris_ggplotly](https://user-images.githubusercontent.com/8385598/93620926-b4345b80-f9d2-11ea-9238-dfca5a4e1607.jpg)

**Comment by samfranks** [comment]
Apologies, that was on plotly version 4.9.0

**Comment by cpsievert** [comment]
I think this is no longer an issue?
