### ISSUE TITLE
Height and Width Need to Be Explicitly Set After Update to R 4.0

### ISSUE THREAD

**Issue by s-etty** [ropensci/plotly#1860]
I recently updated my computer and had to re-install R and all the libraries. In the process I also updated from R 3.6 to R 4.0. On my old machine (and with R 3.6) I was able to knit the code below without supplying a height and width attribute. The Plotly graphs would fill the container they were set in and everything would work nicely. (Please remove the x's after each code chunk to run the code. Needed them for formatting here).

```r
---
title: "Testing Plotly"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
```x

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

plot_ly(data = mtcars, x = ~mpg, y = ~cyl) %>%
add_trace()

```x
```

Now, on my new machine (and R 4.0), I get the error:
```
Error in validateCssUnit(sizeInfo$width) : 
  CSS units must be a single-element numeric or character vector
Calls: <Anonymous> ... <Anonymous> -> need_screenshot -> toHTML -> validateCssUnit
```
I can get around this by supplying a height and width, but has something changed with the update to R 4.0? I preferred letting Plotly fill the container it was placed in and would like to go back to that if possible. It worked better with screen resizing, etc.

Additionally, I can switch back to running R 3.6 and get the above code to work.

**Comment by cpsievert** [comment]
`install.packages("htmlwidgets")` should fix it (please re-open if it doesn't)

**Comment by s-etty** [comment]
That fixed it! It's a bit strange because I had htmlwidgets installed already, but updating it seemed to fix it. ¯\_(ツ)_/¯
