### ISSUE TITLE
Early warning that **sf** built with forthcoming GEOS breaks **plotly**

### ISSUE THREAD

**Issue by rsbivand** [ropensci/plotly#1862]
Forthcoming GEOS 3.9.0 introduces a new internal overlay-NG engine. The output geometries differ (in order we think) from current and previous GEOS. I'm seeing:

[plotly_00check.log](https://github.com/ropensci/plotly/files/5384880/plotly_00check.log)
[testthat.Rout.fail.zip](https://github.com/ropensci/plotly/files/5384881/testthat.Rout.fail.zip)

My local attempts to debug further were stopped by not finding `expect_doppelganger_built()` - if you can show me how to run the offending test file completely manually - copy & paste - I can check further. Repair will be to change the tests to make them robust to the underlying GEOS engine (things like `st_intersection()` output order).

**Comment by cpsievert** [comment]
Thanks for the heads-up @rsbivand, I can look into it -- do you have a timetable for a CRAN release?

**Comment by cpsievert** [comment]
Ah, ok, in that case it'd be great to get some help. To inspect these test failures, it'd be easiest to just change this line 

https://github.com/ropensci/plotly/blob/9bc585/tests/testthat/test-ggplot-sf.R#L32

to 

```r
l <- ggplotly(p)$x
```

**Comment by rsbivand** [comment]
Briefly:

```
> l$data[[4]]$x
[1] 7.0 6.0 5.5 7.0 7.0 7.0
> l$data[[4]]$y
[1] -0.5 -0.5  0.0  0.0 -0.5 -0.5
```
so that the sequence starts in position 3, and duplicates ring closure in a different place. Hard to test equivalence across GEOS versions. More later.

**Comment by rsbivand** [comment]
On the geos-devel list thread linked above, they suggest normalizing the objects before converting back to R objects. This would, in the case I've tested, mean changing all hard-wired output orderings, but then the normalized output should be the same irrespective of GEOS version. Is that pain less than having to branch on GEOS version?

**Comment by rsbivand** [comment]
@edzer and I feel after consideration that branching tests on the GEOS version < "3.9.0" for legacy behaviour, and >= "3.9.0" for Overlay-NG is least invasive. All alternatives involve changes to examples, tests, etc., in packages using GEOS through **sf**, **rgeos** or others.

**Comment by cpsievert** [comment]
Good to know, thanks, is there an sf or rgeos function I can use to query the version? Or do I have to resort to a `syetem()` command?

**Comment by edzer** [comment]
Yes:
```
sf::sf_extSoftVersion()["GEOS"] >= "3.9.0"
```

**Comment by rsbivand** [comment]
For **rgeos**: `rgeos::version_GEOS()` gives the whole string, `rgeos::version_GEOS0()` the first five characters.
