### ISSUE TITLE
plotlyOutput broken - unused argument (reportTheme = TRUE)

### ISSUE THREAD

**Issue by ismirsehregal** [ropensci/plotly#1868]
Using the latest GitHub version (4.9.2.9000) of plotly, shiny 1.5.0 and htmlwidgets 1.5.2 the provided example gives:

> Error in (function (outputId, name, width, height, package = name, inline = FALSE,  : 
>   unused argument (reportTheme = TRUE)

```
library(shiny)
library(plotly)

ui <- fluidPage(
  plotlyOutput("testPlot")
)

server <- function(input, output, session) {
  plot_ly(y = 1:10, type = "scatter", mode = "lines")
}

shinyApp(ui, server)
```

The problem seems to be [introduced](https://github.com/ropensci/plotly/pull/1802) [here](https://github.com/ropensci/plotly/commit/36e2928904ee92ed48b95c31c01545107a9e728e):

```
  if (is_available("shiny", "1.4.0.9003") && is_available("htmlwidgets", "1.5.1.9001")) {
    args$reportTheme <- reportTheme
  }
```
`reportTheme` is available [since htmlwidgets 1.5.2.9000](https://github.com/ramnathv/htmlwidgets/blob/master/inst/NEWS) not 1.5.1.9001.

**Comment by cpsievert** [comment]
Thanks for letting me know!
