### ISSUE TITLE
Error in misc$trans[sc$aesthetics]  <- sc$trans$name :    replacement has length zero

### ISSUE THREAD

**Issue by radinamatic** [ropensci/plotly#187]
I was trying to finish the task stated at R Google Summer of Code (https://github.com/rstats-gsoc/gsoc2015/wiki/ggplotly) page for Plot.ly, using the dataframe from one of my shiny apps, and I was getting this error (ggplot code works fine in my Shiny App with no errors). Here is my console output:

> ggplot(gmNouAula, aes(y=Promig_p1, x=factor(Grup), fill=factor(CodiA))) +
>+   geom_bar(position="dodge", stat="identity") + 
>+   facet_grid(. ~ CurSem) +
>+   scale_y_continuous(limits=c(0,10)) +
>+   scale_fill_brewer(palette="Spectral", guide = guide_legend(title = "Assig")) +
>+   labs(x = "Valoració grups", y = "Promig ítem")
> 
> py <- plotly()
> py$ggplotly()

>**Error in misc$trans[sc$aesthetics] <- sc$trans$name : 
>  replacement has length zero**

Dataframe has nothing special about it (it's a subset of a much larger dataset):

> str(gmNouAula)
'data.frame':	28 obs. of  4 variables:
 $ CodiA    : int  361478 361478 361478 361478 361478 361482 361482 361488 361488 361512 ...
 $ Grup     : Factor w/ 170 levels "1A","1B","1C",..: 157 157 130 130 157 157 157 157 130 157 ...
 $ Promig_p1: num  8.5 7.71 7.29 7 7.87 8.5 7.87 8.11 6.36 6.14 ...
 $ CurSem   : chr  "2010-111r" "2009-101r" "2010-111r" "2009-101r" ...
> head(gmNouAula)
       CodiA Grup Promig_p1    CurSem
12056 361478   T1      8.50 2010-111r
12058 361478   T1      7.71 2009-101r
12059 361478   M1      7.29 2010-111r
12061 361478   M1      7.00 2009-101r
12062 361478   T1      7.87 2011-121r
12085 361482   T1      8.50 2010-112n

I'm gonna work on another plot for this GSoC taks, but if anyone can shed some light on this error, it might be useful for the future...
Cheers!

**Comment by brianboonstra** [comment]
That error often comes when the user has misspecified a column name

**Comment by TrigonaMinima** [comment]
I didn't get the same error when I tried with recreated data having the same structure as your dataset, but I did get an error.

It resolved once I retyped the ggplot instruction as follows,

```
ggplot(gmNouAula, aes(y=Promig_p1, x=Grup, fill=factor(CodiA))) +
```
that is without ```factor()```. See if this works. (If you had provided the data it might have helped).

**Comment by TrigonaMinima** [comment]
I didn't get the same error when I tried with recreated data having the same structure as your dataset, but I did get an error. It resolved once I retyped the ggplot instruction as follows,
```
ggplot(gmNouAula, aes(y=Promig_p1, x=Grup, fill=factor(CodiA))) +
```
that is without ```factor()``` for Grup variable. See if this works. (If you had provided the data it might have helped).
