### ISSUE TITLE
plotly silently drops groups of size 1 when colouring / grouping variable is non-numeric

### ISSUE THREAD

**Issue by cnowzohour** [ropensci/plotly#1876]
Only group "1" is shown:
```r
plot_ly(type = "scatter", mode = "markers", x = 1:4, y = 1:4, color = c("1", "1", "1", "2"))
```

Making both groups have size >1 makes the bug disappear:
```r
plot_ly(type = "scatter", mode = "markers", x = 1:4, y = 1:4, color = c("1", "1", "2", "2"))
```

Also grouping on a numeric variable makes the bug disappear:
```r
plot_ly(type = "scatter", mode = "markers", x = 1:4, y = 1:4, color = c(1, 1, 1, 2))
```

I suspect this might be related to https://github.com/ropensci/plotly/issues/1133

I am running R 3.6.3 on RHEL 7.6 with plotly 4.9.2.1

**Comment by bklingen** [comment]
I couldn't replicate the error using R 4.0.2 and plotly 4.9.2.1 on Windows. Both groups do show up for me.

>Only group "1" is shown:

```
plot_ly(type = "scatter", mode = "markers", x = 1:4, y = 1:4, color = c("1", "1", "1", "2"))
```

However, I get the following warnings, that I get with other plotly functions, too:
```{
Warning messages:
1: `arrange_()` is deprecated as of dplyr 0.7.0.
Please use `arrange()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
2: In RColorBrewer::brewer.pal(N, "Set2") :
  minimal value for n is 3, returning requested palette with 3 different levels

3: In RColorBrewer::brewer.pal(N, "Set2") :
  minimal value for n is 3, returning requested palette with 3 different levels
```

**Comment by cnowzohour** [comment]
I did some more experimenting and it seems this is only happens on my Linux machine and only in jupyter with the IRKernel. I'm closing this for now.
