### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by msgoussi** [ropensci/plotly#1888]
Is there a way to stop orca to create spaces in console (ie invisible the process) 
```r
for (i in 1 :100){
  p <- plot_ly(z = ~volcano) %>% add_surface()
  orca(p, paste0("surface-plot", i, ".svg"))
}
```
![image](https://user-images.githubusercontent.com/18138496/100184217-112c2080-2ef2-11eb-84c3-8b32983cc9ee.png)

**Comment by cpsievert** [comment]
I don't think so

**Comment by msgoussi** [comment]
Yes you can
function (p, file = "plot.png", format = tools::file_ext(file), 
    scale = NULL, width = NULL, height = NULL, mathjax = FALSE, 
    parallel_limit = NULL, verbose = FALSE, debug = FALSE, safe = FALSE, 
    more_args = NULL, ...) 
{
    orca_available()
    b <- plotly_build(p)
    plotlyjs <- plotlyjsBundle(b)
    plotlyjs_path <- file.path(plotlyjs$src$file, plotlyjs$script)
    if (!is.null(plotlyjs$package)) {
        plotlyjs_path <- system.file(plotlyjs_path, package = plotlyjs$package)
    }
    tmp <- tempfile(fileext = ".json")
    cat(to_JSON(b$x[c("data", "layout")]), file = tmp)
    args <- c("graph", tmp, "-o", file, "--format", 
        format, "--plotlyjs", plotlyjs_path, if (debug) "--debug", 
        if (verbose) "--verbose", if (safe) "--safe-mode", 
        more_args)
    if (!is.null(scale)) 
        args <- c(args, "--scale", scale)
    if (!is.null(width)) 
        args <- c(args, "--width", width)
    if (!is.null(height)) 
        args <- c(args, "--height", height)
    if (!is.null(parallel_limit)) 
        args <- c(args, "--parallel-limit", parallel_limit)
    if (!is.null(tryNULL(mapbox_token()))) 
        args <- c(args, "--mapbox-access-token", mapbox_token())
    if (isTRUE(mathjax)) 
        args <- c(args, "--mathjax", file.path(mathjax_path(), 
            "MathJax.js"))
    try_library("processx", "orca")
    invisible(processx::run("orca", args, **echo = TRUE**, 
        spinner = TRUE, ...))
}
<bytecode: 0x0000026f6b1f4ec0>
<environment: namespace:plotly>

Yes you can

add echo to the function argument, so you use can choose between TRUE or FALSE
