### ISSUE TITLE
Warning, if mapping a discrete column with two levels to color

### ISSUE THREAD

**Issue by DavidBarke** [ropensci/plotly#1889]
Mapping a discrete column with two levels to `color` throws a warning:

```r
library(plotly)

tbl <- mtcars[mtcars$cyl %in% c(4, 6),]
plot_ly(tbl, x = ~disp, y = ~mpg, color = as.character(tbl$cyl), mode = "markers")

#> Warning message:
#> In RColorBrewer::brewer.pal(N, "Set2") :
#>  minimal value for n is 3, returning requested palette with 3 different levels
```

Replacing the following line with `N <- max(length(lvls), 3)` would solve this issue. 

https://github.com/ropensci/plotly/blob/5e5db5938ebc60139cd318a06f2bbedbba6f00c0/R/plotly_build.R#L782

**Comment by cpsievert** [comment]
That warning is there for a reason (the color palette is designed to used with 3 or more levels). If you want to get rid of the warning, I'd suggest using a different `colors` palette:

```r
plot_ly(mtcars, x = ~disp, y = ~mpg, color = ~as.factor(am), mode = "markers", colors = "Dark2")
```

**Comment by DavidBarke** [comment]
Thanks for your answer, specifying the color palette definitely prevents the warning. I still think that this is an issue. 

In the documentation of `brewer.pal` it is written that all palettes are designed to be used with 3 or more levels. Therefore I would either expect your example to throw the same warning as well or expect my example to not throw a warning when `colors` is not specified. Not throwing a warning is in accordance with `scales::brewer_pal(palette = "Set2")(2)`, which is used implicitly via calling `scales::col_factor`.

I see that my initial proposal would probably break the case when `viridis(N)` is called. Therefore I'd propose to change

https://github.com/ropensci/plotly/blob/4a33aea10b0a62f61845bc8406e4be130ee98947/R/plotly_build.R#L783

to

```r
pal <- palette %||% if (isOrdered) viridisLite::viridis(N) else "Set2". 
```
