### ISSUE TITLE
Support mode="text+markers"

### ISSUE THREAD

**Issue by mkcor** [ropensci/plotly#189]
See bullet points at the end of http://stackoverflow.com/questions/29068867/plotly-not-getting-geom-text-in-r-ggplot/29086989#29086989

/cc @chriddyp @tdhock @cpsievert

**Comment by tdhock** [comment]
I recently added some code to support this (along with the error-bars merging code)

https://github.com/ropensci/plotly/blob/master/R/ggplotly.R#L712-L757

There are some tests for merging lines, points, and error bars

https://github.com/ropensci/plotly/blob/master/tests/testthat/test-mean-error-bars.R

but I guess we need to add some tests for the case of just geom_point and geom_line (no error bars).

**Comment by cpsievert** [comment]
FWIW, this is the new approach to merging -- https://github.com/ropensci/plotly/blob/78e4612597a4ba3e3b95ad2747867363613d1448/R/ggplotly.R#L610-L628

I rarely ever see anyone wanting to plot text and points at the same x/y so I don't think this is really worth the effort
