### ISSUE TITLE
problems rendering `plotly` plots in `rmarkdown` with R-devel

### ISSUE THREAD

**Issue by IndrajeetPatil** [ropensci/plotly#1890]
`R-devel` recently bumped its graphics engine version:

![image](https://user-images.githubusercontent.com/11330453/100264167-c68cc180-2f4e-11eb-953b-b1cbfd1564fc.png)

And if I update to `R-devel`, I can no longer knit `Rmarkdown` documents containing `plotly` chunks, since they fail with the following error:

![image](https://user-images.githubusercontent.com/11330453/100264598-53d01600-2f4f-11eb-8882-7a16558aa3db.png)

**Comment by cpsievert** [comment]
Does `install.packages("Cairo")` happen to fix it?

**Comment by IndrajeetPatil** [comment]
That worked! Thanks :)
