### ISSUE TITLE
plotly histogram center and boundary attributes 

### ISSUE THREAD

**Issue by haruna-rgb** [ropensci/plotly#1895]
```
df %>%
  filter(include == "TRUE") %>%
  ggplot(aes(var1,fill=var2))+
  geom_histogram(center = 0.5, binwidth = 0.1)
```

Can i please know the equivalent attributes to center ? 

```
plot= plot_ly(xbins = number_of_bins,autobinx = FALSE)
plot =plot%>%
    add_histogram(x = d$var1,
                  center = 0.5)
```
`
this is my code for histogram in plotly so can you please tell me how I can recreate the center attribute in plotly

**Comment by cpsievert** [comment]
This issue tracker is for bugs and feature requests, http://stackoverflow.com/ or https://community.rstudio.com/ would be a more appropriate venue for this question
