### ISSUE TITLE
marker symbol missing

### ISSUE THREAD

**Issue by sunhuaiyu** [ropensci/plotly#1897]
---

Marker symbols are missing starting from 'arrow-up'. 
Basically all marker symbols with 'arrow' in their names are not available for plot_ly().

**Comment by cpsievert** [comment]
Were these symbols recently added to plotly.js?

**Comment by cpsievert** [comment]
Looks as though these are supported, if you can produce a reprex to show otherwise I reopen the issue:

```r
> grep("arrow", schema(F)$traces$scatter$attributes$marker$symbol$values, value = T)
 [1] "arrow-up"             "arrow-up-open"       
 [3] "arrow-down"           "arrow-down-open"     
 [5] "arrow-left"           "arrow-left-open"     
 [7] "arrow-right"          "arrow-right-open"    
 [9] "arrow-bar-up"         "arrow-bar-up-open"   
[11] "arrow-bar-down"       "arrow-bar-down-open" 
[13] "arrow-bar-left"       "arrow-bar-left-open" 
[15] "arrow-bar-right"      "arrow-bar-right-open"
```

**Comment by sunhuaiyu** [comment]
Sorry I am not familiar with reprex. But this is the code to plot all symbols:

library(plotly)

all_names <- c('circle', 'circle-open', 'circle-dot', 'circle-open-dot', 'square', 'square
-open', 'square-dot', 'square-open-dot', 'diamond', 'diamond-open', 'diamond-dot', 'diamon
d-open-dot', 'cross', 'cross-open', 'cross-dot', 'cross-open-dot', 'x', 'x-open', 'x-dot',
 'x-open-dot', 'triangle-up', 'triangle-up-open', 'triangle-up-dot', 'triangle-up-open-dot
', 'triangle-down', 'triangle-down-open', 'triangle-down-dot', 'triangle-down-open-dot', '
triangle-left', 'triangle-left-open', 'triangle-left-dot', 'triangle-left-open-dot', 'tria
ngle-right', 'triangle-right-open', 'triangle-right-dot', 'triangle-right-open-dot', 'tria
ngle-ne', 'triangle-ne-open', 'triangle-ne-dot', 'triangle-ne-open-dot', 'triangle-se', 't
riangle-se-open', 'triangle-se-dot', 'triangle-se-open-dot', 'triangle-sw', 'triangle-sw-o
pen', 'triangle-sw-dot', 'triangle-sw-open-dot', 'triangle-nw', 'triangle-nw-open', 'trian
gle-nw-dot', 'triangle-nw-open-dot', 'pentagon', 'pentagon-open', 'pentagon-dot', 'pentago
n-open-dot', 'hexagon', 'hexagon-open', 'hexagon-dot', 'hexagon-open-dot', 'hexagon', 'hex
agon-open', 'hexagon-dot', 'hexagon-open-dot', 'octagon', 'octagon-open', 'octagon-dot', '
octagon-open-dot', 'star', 'star-open', 'star-dot', 'star-open-dot', 'hexagram', 'hexagram
-open', 'hexagram-dot', 'hexagram-open-dot', 'star-triangle-up', 'star-triangle-up-open',
'star-triangle-up-dot', 'star-triangle-up-open-dot', 'star-triangle-down', 'star-triangle-
down-open', 'star-triangle-down-dot', 'star-triangle-down-open-dot', 'star-square', 'star-
square-open', 'star-square-dot', 'star-square-open-dot', 'star-diamond', 'star-diamond-ope
n', 'star-diamond-dot', 'star-diamond-open-dot', 'diamond-tall', 'diamond-tall-open', 'dia
mond-tall-dot', 'diamond-tall-open-dot', 'diamond-wide', 'diamond-wide-open', 'diamond-wid
e-dot', 'diamond-wide-open-dot', 'hourglass', 'hourglass-open', 'bowtie', 'bowtie-open', '
circle-cross', 'circle-cross-open', 'circle-x', 'circle-x-open', 'square-cross', 'square-c
ross-open', 'square-x', 'square-x-open', 'diamond-cross', 'diamond-cross-open', 'diamond-x
', 'diamond-x-open', 'cross-thin', 'cross-thin-open', 'x-thin', 'x-thin-open', 'asterisk',
 'asterisk-open', 'hash', 'hash-open', 'hash-dot', 'hash-open-dot', 'y-up', 'y-up-open', '
y-down', 'y-down-open', 'y-left', 'y-left-open', 'y-right', 'y-right-open', 'line-ew', 'li
ne-ew-open', 'line-ns', 'line-ns-open', 'line-ne', 'line-ne-open', 'line-nw', 'line-nw-ope
n', 'arrow-up', 'arrow-up-open', 'arrow-down', 'arrow-down-open', 'arrow-left', 'arrow-lef
t-open', 'arrow-right', 'arrow-right-open', 'arrow-bar-up', 'arrow-bar-up-open', 'arrow-ba
r-down', 'arrow-bar-down-open', 'arrow-bar-left', 'arrow-bar-left-open', 'arrow-bar-right'
, 'arrow-bar-right-open')

plot_ly() %>%
  add_markers(
    x = rep(1:14, each = 12, length.out = length(vals)),
    y = rep(1:12, times = 14, length.out = length(vals)),
    text = all_names,
    hoverinfo = "text",
    marker = list(
      symbol = all_names,
      size = 30,
      line = list(
        color = "black",
        width = 2)))

On Dec 8, 2020, at 3:45 PM, Carson Sievert <notifications@github.com<mailto:notifications@github.com>> wrote:



Looks as though these are supported, if you can produce a reprex to show otherwise I reopen the issue:

> grep("arrow", schema(F)$traces$scatter$attributes$marker$symbol$values, value = T)
 [1] "arrow-up"             "arrow-up-open"
 [3] "arrow-down"           "arrow-down-open"
 [5] "arrow-left"           "arrow-left-open"
 [7] "arrow-right"          "arrow-right-open"
 [9] "arrow-bar-up"         "arrow-bar-up-open"
[11] "arrow-bar-down"       "arrow-bar-down-open"
[13] "arrow-bar-left"       "arrow-bar-left-open"
[15] "arrow-bar-right"      "arrow-bar-right-open"
