### ISSUE TITLE
Ribbons in geom_smooth 

### ISSUE THREAD

**Issue by cpsievert** [ropensci/plotly#190]
A user tried to recreate the following example in plotly. 

```r
p <- (qplot(Date, Score, colour=Program, data=x)
      +stat_smooth(method=lm)+facet_wrap(~Name)
      +scale_x_date(labels=date_format("%b/%y"))
      +scale_color_fivethirtyeight()+theme_fivethirtyeight())
```

![asada vs yuna](https://cloud.githubusercontent.com/assets/1365941/6712007/61cbd258-cd58-11e4-8bad-a1504b0ef455.png)

However, [the plotly result](https://plot.ly/~sungho.hong/45) is:

![](https://plot.ly/~sungho.hong/45.png)

This is clearly a bug, but before I fix it, it'd be nice to have a discussion on how best to implement the ribbon in `geom_smooth()`.

Alex mentioned that each ribbon should should be 2 traces, so that upon hover in compare mode, we can compare the top and bottom. I definitely agree that would be useful. My question however is: [why isn't `geom_ribbon()` implemented this way](https://plot.ly/~cpsievert/245)? 

The current approach is basically to treat `geom_smooth()` as `geom_line() + geom_ribbon()`. So if we re-implement `geom_ribbon()` as 2 traces, that change should propagate to `geom_smooth()`.

Thoughts @tdhock @chriddyp @mkcor?

**Comment by tdhock** [comment]
geom_ribbon has both aes(fill) and aes(color), so if we want to be able to translate both of those to plotly I think we should treat it as a basic polygon (like geom_rect, see #178). To support comparing top and bottom values, I propose that we add an invisible error bar for each ribbon.
