### ISSUE TITLE
Plotly is an 'ORPHANED' package on CRAN

### ISSUE THREAD

**Issue by James-G-Hill** [ropensci/plotly#1906]
Hello,

At the following link you will see that plotly is now an orphaned package on CRAN; I assume that's not correct?

[https://cran.r-project.org/web/packages/plotly/index.html](https://cran.r-project.org/web/packages/plotly/index.html)

**Comment by cpsievert** [comment]
It's a misnomer. CRAN gave me 7 days to fix a cryptic r-devel issue, which I met, but they rejected the submission due to URL redirects which were only discoverable on their internal debian machine, then went on vacation before I could submit again.

Anyway, this should get resolved as soon as CRAN returns on Jan 4th.

**Comment by jamesdalg** [comment]
Hopefully CRAN is appeased soon. My package will be archived if plotly is orphaned much longer. I can't submit a new version for review until this is fixed.

**Comment by cpsievert** [comment]
Sorry @jamesdalg, I submitted plotly over 24 hours ago and still haven't heard anything -- it hopefully shouldn't be too much longer until it's accepted. 


(If your package does happen to get archived, please let me know -- IMO it'd be completely unacceptable for CRAN to allow that in this situation)

**Comment by pat-s** [comment]
You can check the status [here](https://lockedata.github.io/cransays/articles/dashboard.html).

FWIW I was able to update my package even though the plotly note appeared.

**Comment by jamesdalg** [comment]
Which package was that? I wasn't able to update mine and CRAN wouldn't accept it. I even emailed them.

**Comment by pat-s** [comment]
For me {plotly} was only in `Suggests` (which is usually a good practice for plotting-related packages if they are not part of the main functionality).

It might be different if it is listed in `Imports`.
If you also have in in `Suggests` then its just CRAN arbitrariness, which is not unusual.

**Comment by jamesdalg** [comment]
I've tried making it a suggests, but my package still went straight to auto-reject. Is there anything else I can do to work around this plotly ORPHANED maintainer issue?

**Comment by cpsievert** [comment]
plotly 4.9.3 is on CRAN now

**Comment by jamesdalg** [comment]
Thanks so very much for taking care of it and for all your correspondence! CNVScope has been resubmitted to CRAN and thanks to your help, won't be archived. :)
