### ISSUE TITLE
Support horizontal legend

### ISSUE THREAD

**Issue by Huade** [ropensci/plotly#194]
For some reason, the ggplot2 API does not respond to the following commands:
```
scale_colour_hue(…,guide = guide_legend(direction="horizontal”))
```
or
```
theme(legend.direction = "horizontal", legend.position = "bottom")
```

I am not sure whether that is an issue on my end or it is a general issue. It would be great if we have some way to build horizontal legend on ploy.ly.

Thanks!

**Comment by chriddyp** [comment]
Hey @Huade -- Thanks for reaching out! Horizontal legend aren't currently supporting in Plotly's graphing library, so we can't make that conversion. We'll probably have more flexible legends sometime this summer.

**Comment by Huade** [comment]
Hi @chriddyp , thanks for reply! The reason why I would like to have this feature is because the legend and the figure is overlapping. For example, we cannot see Mexico's result in 2010. Do you know whether there are any way to change the position with ggplot2 API? Thanks again!

![screen shot 2015-03-30 at 2 18 40 pm](https://cloud.githubusercontent.com/assets/5031825/6903360/c3bc5684-d6e7-11e4-9d08-604b10834926.png)

**Comment by chriddyp** [comment]
Hey @Huade --
Thanks for providing an example. Our legend positioning is really off there! Until that gets fixed, you can edit the legend position (and any other plotly graph attributes) manually before you send the graph to Plotly.

Here's an example: 

```
dsamp <- diamonds[sample(nrow(diamonds), 1000), ]
gg <- qplot(carat, price, data=dsamp, colour=clarity)

fig <- gg2list(gg) # This converts the ggplot2 graph into Plotly's format, where you can see all of the keys

data <- list()
for(i in 1:(length(fig)-1)){data[[i]]<-fig[[i]]}

layout <- fig$kwargs$layout 
layout$annotations[[1]]$x <- 1.02 # this "annotation" is the legend title, here we change the `x` position
layout$annotations[[1]]$xanchor <- "left" # change the position of the annotation to the left
layout$annotations[[1]]$y <- 0.8 # change the vertical position - move it up a bit
layout$annotations[[1]]$yanchor <- "bottom" # change the vertical position reference

# Similarly, update the position of the legend itself
layout$legend$x <- 1.0 # move it to the right a bit
layout$legend$xanchor <- "left" 
layout$legend$y <- 0.5 # move it to the vertical center
layout$legend$yanchor <- "middle" 

filename='ggplot with legend updates'

# Send it up to plotly
py$plotly(data, kwargs=list(layout=layout, filename=filename, fileopt="overwrite"))
```

Note that you can edit every attribute inside the graph editor. To edit the graph, click "edit"
![image](https://cloud.githubusercontent.com/assets/1280389/6904981/9acde200-d6f2-11e4-9cb9-ae6f112a152c.png)

Then, you can move around the legends and annotations by hand, or modify everything else about the graph, like the colors or the text:
![image](https://cloud.githubusercontent.com/assets/1280389/6904956/69f1c2dc-d6f2-11e4-850d-fcca8025ada1.png)

Let me know if that makes sense, or if you need any more help.

**Comment by Huade** [comment]
Hi @chriddyp thanks for your detailed solution and thanks for creating a new issue. Yes, that do make sense. However, I cannot execute your example script since R returns an error
```r
> py$plotly(data, kwargs=list(layout=layout, filename=filename, fileopt="overwrite"))
Error in function (type, msg, asError = TRUE)  : Could not resolve host: ��[
```

I checked the encoding but it seems correct. Do you have any idea?

Thanks again!

**Comment by cpsievert** [comment]
Closing since horizontal legends are on our list of [unsupported features](https://github.com/ropensci/plotly/wiki/Unsupported-plotly.js-features)

**Comment by abalter** [comment]
Legend orientation is NO LONGER an unsupported feature.

https://plot.ly/python/legend/#changing-orientation-of-legend

**Comment by aaiezza** [comment]
This link is broken.
