### ISSUE TITLE
Support for ggplot stacked bar plots? 

### ISSUE THREAD

**Issue by mvollger** [ropensci/plotly#198]
I am not sure this is an issue as much as a question as to whether this kind of graph is supposed to be supported. I have a stacked bar plot in ggplot and it does not appear the same way online in ploty. Here is the code and the link to the graph on ploty. 

```
library(ggplot2)
library(reshape2)
library(gtools)
library(scales)
library(dplyr)
library(devtools)
library(plotly)
setwd("/home/mitchell/IW/hmm")

load("mutations.data")
head(mutations)
```
output:
```
       chr    pos change ref alt dp ao strain Percentage Mutation                   id
11    chrX 289758    T>G   T   G 49 22  cis--          1  A>C:T>G    chrX289758A>C:T>G
28 chrVIII 204811    A>C   A   C 44 18  cis--          1  A>C:T>G chrVIII204811A>C:T>G
34  chrXII  65829    A>C   A   C 44 19  cis--          1  A>C:T>G   chrXII65829A>C:T>G
40   chrIX 187852    T>G   T   G 37 16  cis--          1  A>C:T>G   chrIX187852A>C:T>G
41    chrV 519341    T>G   T   G 41 17  cis--          1  A>C:T>G    chrV519341A>C:T>G
42   chrVI 113016    T>G   T   G 33 14  cis--          1  A>C:T>G   chrVI113016A>C:T>G
```

```
p <- ggplot(mutations, aes(x = strain, fill=Mutation ))
p <- p + geom_bar(stat="identity", position="fill", aes(y=Percentage ))
p <- p + scale_y_continuous(labels = percent_format())
p
```
Local out put graph:

![image](https://cloud.githubusercontent.com/assets/6935283/7055599/a7c42e52-de12-11e4-8fcc-2ebc4b3077f2.png)
```
py <- plotly(username="mrvollger", key="aboy5gyo0b")
r<-py$ggplotly(p)
r$response$url
```
output url:
https://plot.ly/~mrvollger/59

**Comment by cpsievert** [comment]
Here is a reproducible example of the same problem:

```r
p <- ggplot(mtcars, aes(factor(vs), fill=factor(cyl))) + 
  geom_bar(position = "fill")
```
![rplot](https://cloud.githubusercontent.com/assets/1365941/7056434/2af96b5e-de11-11e4-96e6-6bbed1533502.png)

https://plot.ly/~cpsievert/432/count-vs-factorvs/

I can take a look at fixing this @tdhock @chriddyp @mkcor.

**Comment by tdhock** [comment]
there definitely are some tests for bar graphs like this e.g.

http://ropensci.github.io/plotly-test-table/tables/3105143f285dc2c5cb7194a3bab702539b28746f/bar-stack.html

**Comment by cpsievert** [comment]
The problem here has to do with `position_fill()` -- which essentially normalizes the stacked bar chart. I'm working on a fix for that and I will add some proper tests.
