### ISSUE TITLE
geom_density() as filled area chart

### ISSUE THREAD

**Issue by cpsievert** [ropensci/plotly#199]
To me, `geom_density()` should translate to a [filled area chart](https://plot.ly/javascript-graphing-library/filled-area-plots/). Right now it's translated to a [histogram](https://plot.ly/javascript-graphing-library/histograms/) (with autobinning). As a result, most [arguments to `stat_density()`](http://docs.ggplot2.org/current/stat_density.html) are ignored and `geom_density() + geom_histogram()` doesn't seem to make sense. Consider the following:

```r
p <- ggplot(mtcars, aes(wt)) + geom_density() + geom_histogram(aes(y = ..density..))
```

![rplot](https://cloud.githubusercontent.com/assets/1365941/7061027/480160f4-de51-11e4-8630-777f03402d3f.png)

This actually gives me an error:

```r
ggplotly(p)
Error in if (is.character(new.mode) && !is.na(new.mode)) { : 
  missing value where TRUE/FALSE needed
```

Any thoughts/objections @tdhock @chriddyp @mkcor?

**Comment by tdhock** [comment]
seems fine with me .. are there any tests that would need to be changed?

**Comment by cpsievert** [comment]
Yea, test-ggplot-density.R would have to change.
