### ISSUE TITLE
geom_violin() not supported

### ISSUE THREAD

**Issue by cpsievert** [ropensci/plotly#201]
Maybe we could implement as a special type of polygon?

**Comment by cpsievert** [comment]
In order for this to work, we need to treat the x-scale as continuous, which works great when x is numeric (see [here](https://plot.ly/~cpsievert/513))

```r
ggplot(mtcars, aes(x = 1, y = wt)) + geom_violin()
```
![](https://plot.ly/~cpsievert/513.png)

(and [here](https://plot.ly/~cpsievert/514/wt-vs-1))

```r
ggplot(mtcars, aes(x = 1, y = wt)) + geom_violin(aes(fill = factor(vs)))
```

![](https://plot.ly/~cpsievert/514/wt-vs-1.png)

Unfortunately, this doesn't really work when x is mapped to a factor variable. In this case, we _could_ override the x scale to be continuous behind the scenes, but the labels won't make any sense. Unless we can explicitly override the tick/label placement/content in plotly (which doesn't seems possible), it seems the only decent option is to turn off the x-axis ticks/labels (and encourage users to map the x variable to fill as well). Although this is possible, it'd probably require geom specific code in ggplotly.R and also means `geom_violin()` probably wouldn't play nice with other geoms.

@chriddyp @tdhock do you think this is worth supporting/exploring any further?

**Comment by tdhock** [comment]
I don't think that implementing a violin as a polygon is a good idea. I think it would be best to upload the raw y values to the plotly server, so then it would be easier to re-mix the data and plot it in a different way if you want.

**Comment by chriddyp** [comment]
Agreed - Violin is low priority now. Eventually this will be a chart-type in Plotly, and we'll send up the raw values just like box-plots and histograms.

**Comment by cpsievert** [comment]
Got it, thanks. I'll close for now until plotly provides more support for this.
