### ISSUE TITLE
clean up basic geom conversion code

### ISSUE THREAD

**Issue by tdhock** [ropensci/plotly#203]
My original design for ggplotly included the concept of a "basic" geom which can be directly translated to plotly traces. This simplifies the conversion code since many geoms can be easily converted to a small subset of basic geoms. For example, geom_path is a basic geom, and geom_line and geom_segment are both converted to a path before being converted to a plotly trace. These conversions are implemented in the list of functions toBasic, in trace_generation.R.

I noticed that there are some issues with the current basic geom conversion code:

bar and point are present, but should not be (they are basic geoms).

hline, vline, abline are present, but are not treated as a basic form of geom_path.

**Comment by cpsievert** [comment]
@tdhock I think it'd be worthwhile to have a wiki page on this (with maybe a table/diagram to keep track of all the relationships?)

**Comment by cpsievert** [comment]
This should be fixed in f1900cc3cd464408a60ffadfe3e95460747430e0.
