### ISSUE TITLE
Unable to set credentials, 'No such file or directory'

### ISSUE THREAD

**Issue by arnoud999** [ropensci/plotly#204]
When I try to set my credentials/API key, I get the following error message:

    [1] "Your credentials file:"
    Error in if (file.info(CREDENTIALS_FILE)$size) { : 
      argument is not interpretable as logical
    In addition: Warning message:
    In file.create(abspath) :
      cannot create file '//studfiles.campus.uvt.nl/files/home/home09/u1236118/.plotly/.credentials', reason 'No such file or directory'

I've tried creating the .plotly folder and the .credentials file myself, and I tried running R through a command window as administrator, but in both cases I still saw the same error message.

**Comment by theengineear** [comment]
@arnoud999 , are you on a personal computer? The credentials file tries to get created in `~/.plotly/`. That error seems to be saying `~/.plotly` doesn't exist. As a test, can you open up a terminal and do the following?

```
cd ~/.plotly
```

You've probably got a permissions problem, but I'm sure we can figure out a way to get you up and running.

The *simplest* thing to get going straight-away is to just sign in.

`py <- plotly("your_username", "your_api_key")`

In general, this isn't a great solution as you'll be hard-coding your credentials and you'd have to do it for *every* script.

**Comment by arnoud999** [comment]
Thanks for your quick response!

`cd ~/.plotly` (or `cd ~\.plotly`) doesn't work, probably because I'm running Windows? 

It indeed seems to be a permission problem, I'm on a work computer and my user folder is some kind of network drive. Is it possible to change the location of `.plotly`?

**Comment by theengineear** [comment]
@arnoud999 , specifying the location of the `.plotly` folder could be nice, I think that would be pretty easy through an environment variable. We won't have this solution for you immediately, but I could definitely see the utility in this, so I'll see what I can do.

Until then, yes, you'll need to sort out the permission block. I had thought that our R library handled this though, @mkcor , thoughts?

**Comment by mkcor** [comment]
@theengineear You are right, I remember troubleshooting Windows users in the past...  But this may be yet another thing...  It could be a thing to let users specify/overwrite environment variable `PLOTLY_DIR`...

I think Windows does not understand `~` (which is why our R code needs the `path.expand("~")` by the way). @arnoud999 It looks like the 'home' on this workstation is not quite the home the way we usually assume.

Can you try and run, say:
```r
py <- plotly("rAPI", "yu680v5eii")
```
Please?

**Comment by arnoud999** [comment]
Unfortunately, I get the same error:

    > py <- plotly("rAPI", "yu680v5eii")
    Error in if (file.info(CONFIG_FILE)$size) { : 
      argument is not interpretable as logical
    In addition: Warning message:
    In file.create(abspath) :
      cannot create file '//studfiles.campus.uvt.nl/files/home/home09/u1236118/.plotly/.config', reason 'No such file or directory'

**Comment by mkcor** [comment]
@arnoud999 It's not the same error! The `CREDENTIALS` info is in but you are missing the `CONFIG` info, so please try this workaround:
```r
py <- plotly(username="rAPI", key="yu680v5eii", base_url="https://plot.ly")
```
Let me know how it goes!

**Comment by arnoud999** [comment]
That works, thanks a lot! :+1:
