### ISSUE TITLE
post a comment after building test table

### ISSUE THREAD

**Issue by tdhock** [ropensci/plotly#207]
after building the plotly test table, the github API could be used to post a comment to the relevant PR

https://developer.github.com/v3/issues/comments/#create-a-comment

this could save developer time (less copy-pasting test table links), at the risk of overloading PR comments with lots of automatically generated links to the test tables.

**Comment by cpsievert** [comment]
I'd be even more interested in having the bot post comments when the travis build is done. I often find myself returning to the PR page only to see that stupid yellow dot :cry: 

I suppose it wouldn't be too hard to provide links to tests added/removed as well

**Comment by cpsievert** [comment]
I think we want comments on pull requests, not issues, so this would be the right page:

https://developer.github.com/v3/pulls/comments/#create-a-comment

(I'll submit something for this today hopefully)
