### ISSUE TITLE
Insecure Platform Warning, Not Data Streamed

### ISSUE THREAD

**Issue by Aidoboy** [ropensci/plotly#216]
I'm trying to run the Python streaming tutorial on a Pi, and when I do, I get this, and no data appaers of the web page it makes:

    /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning:
    
    A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.

Does anyone know why?

**Comment by cpsievert** [comment]
This repo is for plotly's R package. I think this would be a more appropriate place for your issue:

https://github.com/plotly/python-user-guide

**Comment by Aidoboy** [comment]
I'll try, but nothing seems to be happening there. In the mean time I'd like to keep this open, if just to have somewhere that people can see it.

**Comment by Aidoboy** [comment]
[Someone else got it.](https://github.com/plotly/python-user-guide/issues/15#issuecomment-100037103)
