### ISSUE TITLE
Equal scaling of axes not working

### ISSUE THREAD

**Issue by 13bzhang** [ropensci/plotly#218]
This is one of the unsupported features from the cookbook, see Issue #161.

There's a problem with setting the scaling of the axes to an equal ratio, with one visual unit being representing the same numeric unit on both axes. There's also a problem when I set them to ratios other than 1:1.

```
# Data where x ranges from 0-10, y ranges from 0-30
set.seed(202)
dat <- data.frame(
    xval = runif(40,0,10),
    yval = runif(40,0,30)
)
sp <- ggplot(dat, aes(xval, yval)) + geom_point()

# Force equal scaling
sp + coord_fixed()
```

Cookbook:
![1-1_scaling](https://cloud.githubusercontent.com/assets/6131842/7619028/0be0c3be-f984-11e4-9f4b-435e75a6d29b.png)

Plotly:
![1-1_scaling_plotly](https://cloud.githubusercontent.com/assets/6131842/7619052/37f48904-f984-11e4-9cde-d961dc05f08a.png)

```
# Equal scaling, with the total x axis the same length as the total y axis
sp + coord_fixed(ratio=1/3)
```
Cookbook:
![1-3_scaling](https://cloud.githubusercontent.com/assets/6131842/7619084/58f61910-f984-11e4-9984-ec331c0f88da.png)

Plotly:
![1-3_scaling_plotly](https://cloud.githubusercontent.com/assets/6131842/7619101/77c349e4-f984-11e4-9c69-a6dec554cf10.png)

cc @cpsievert @chriddyp @mkcor

**Comment by 13bzhang** [comment]
Here's a solution I came up with:

https://github.com/ropensci/plotly/blob/baobao-equal_axes/R/ggplotly.R#L771-785
```
  # fixed coordinates: if the coordinates ratio is not NULL, then
  # we make the size of the plot according to the specified ratio
  # note: we set the biggest dimension to 600
  if (!is.null(p$coordinates$ratio)){
    x.range <- range(built[[2]]$ranges[[1]]$x.major_source, na.rm = TRUE)
    y.range <- range(built[[2]]$ranges[[1]]$y.major_source, na.rm = TRUE)
    y.x.ratio <- (y.range[2] - y.range[1])/(x.range[2] - x.range[1])
    if (y.x.ratio > 1){
      layout$height <- 600
      layout$width <- layout$height*(1/p$coordinates$ratio)*(1/y.x.ratio) 
    } else{
      layout$width <- 600
      layout$height <- layout$height*(1/p$coordinates$ratio)*y.x.ratio 
    }
  }
```
What I did was if the user specified a coordinate ratio, the height and width in layout would be in that ratio. I was not sure how big the dimensions could get so I set the biggest dimension (whether it's x or y) to 600.

The new images look like this.

Cookbook:
![1-1_scaling](https://cloud.githubusercontent.com/assets/6131842/7643055/17e1be08-fa64-11e4-83d2-f6a0bc12b083.png)

Plotly:
![new_1-1_scaling_plotly](https://cloud.githubusercontent.com/assets/6131842/7643060/20390bd8-fa64-11e4-9fc2-24d473df05a1.png)

Cookbook:
![1-3_scaling](https://cloud.githubusercontent.com/assets/6131842/7643064/2610657e-fa64-11e4-8ed1-0511c8a884ed.png)

Plotly:
![new_1-3_scaling_plotly](https://cloud.githubusercontent.com/assets/6131842/7643068/2d56ef9c-fa64-11e4-9220-1a1708f81550.png)

Questions, suggestions, comments welcome!
cc @cpsievert  @chriddyp  @mkcor

**Comment by chriddyp** [comment]
that seems like the right approach!

**Comment by cpsievert** [comment]
Closing in favor of #342
