### ISSUE TITLE
ggdendro lattice dendrograms

### ISSUE THREAD

**Issue by jackparmer** [ropensci/plotly#219]
Would be cool if we had a wrapper function to make heatmap dendrograms like this:

![image](https://cloud.githubusercontent.com/assets/1865834/7623909/06a5f650-f9e1-11e4-8511-a35a99526cc1.png)

**Comment by cpsievert** [comment]
Do you by chance have the code for that one? It looks like plotly almost translates this more basic example, but not quite.

```r
library(ggplot2)
library(ggdendro)
hc <- hclust(dist(USArrests), "ave")
hcdata <- dendro_data(hc, type="rectangle")
p <- ggplot() + 
    geom_segment(data=segment(hcdata), aes(x=x, y=y, xend=xend, yend=yend)) +
    geom_text(data=label(hcdata), aes(x=x, y=y, label=label, hjust=0), size=3) +
    coord_flip() + 
    scale_y_reverse(expand=c(0.2, 0))
```

![rplot](https://cloud.githubusercontent.com/assets/1365941/7624079/cd2da05e-f9a8-11e4-9318-ce77e199639f.png)

versus

![https://plot.ly/~sadjnawer/0](https://plot.ly/~sadjnawer/0.png)

**Comment by jackparmer** [comment]
Oh yeah, sorry! The code is from this SO issue:

http://stackoverflow.com/questions/6673162/reproducing-lattice-dendrogram-graph-with-ggplot2

One issue with the conversion is it doesn't look like ggplotly supports R grids to Plotly subplots (https://github.com/ropensci/plotly/issues/220)

**Comment by cpsievert** [comment]
When we merge #226, it should close this issue (thanks to `subplot()`).

```r
library(ggplot2)
library(ggdendro)

#dendogram data
x <- as.matrix(scale(mtcars))
dd.col <- as.dendrogram(hclust(dist(x)))
dd.row <- as.dendrogram(hclust(dist(t(x))))
dx <- dendro_data(dd.row)
dy <- dendro_data(dd.col)

# helper function for creating dendograms
ggdend <- function(df) {
  ggplot() + 
    geom_segment(data = df, aes(x=x, y=y, xend=xend, yend=yend)) +
    labs(x = "", y = "") + theme_minimal() + 
    theme(axis.text = element_blank(), axis.ticks = element_blank(),
          panel.grid = element_blank())
}

# x/y dendograms
px <- ggdend(dx$segments)
py <- ggdend(dy$segments) + coord_flip()

# heatmap
col.ord <- order.dendrogram(dd.col)
row.ord <- order.dendrogram(dd.row)
xx <- scale(mtcars)[col.ord, row.ord]
xx_names <- attr(xx, "dimnames")
df <- as.data.frame(xx)
colnames(df) <- xx_names[[2]]
df$car <- xx_names[[1]]
df$car <- with(df, factor(car, levels=car, ordered=TRUE))
mdf <- reshape2::melt(df, id.vars="car")
p <- ggplot(mdf, aes(x = variable, y = car)) + geom_tile(aes(fill = value))


# hide axis ticks and grid lines
eaxis <- list(
  showticklabels = FALSE,
  showgrid = FALSE
)

p_empty <- plot_ly() %>% 
  # note that margin applies to entire plot, so we may 
  # add it here to make tick labels more readable
  layout(margin = list(l = 200),
         xaxis = eaxis,
         yaxis = eaxis)

subplot(px, p_empty, p, py, nrows = 2, margin = 0.01)
```

![https://plot.ly/~agvd/550](https://plot.ly/~agvd/550.png)

**Comment by jackparmer** [comment]
Carson's the man.

**Comment by cpsievert** [comment]
@jackparmer perhaps we should put this example somewhere so it's more visible? Any ideas where?

**Comment by chriddyp** [comment]
sweet! I'll add it to https://github.com/plotly/documentation/tree/source

**Comment by chriddyp** [comment]
https://github.com/plotly/documentation/commit/42332d6abc9e9f280771b36b4fb4959383c14549, https://plot.ly/ggplot2/ggdendro-dendrograms/
