### ISSUE TITLE
Support for R grid package in ggplotly

### ISSUE THREAD

**Issue by jackparmer** [ropensci/plotly#220]
For multiple plots that are laid out in a grid using the R grid package, looks like ggplotly only grabs the first of those plots:

Ie, this:

![image](https://cloud.githubusercontent.com/assets/1865834/7623946/b2bf2d76-f9e1-11e4-9976-1842e1471244.png)

Turns into this with ggplotly:

![image](https://cloud.githubusercontent.com/assets/1865834/7623948/c1d17abc-f9e1-11e4-9e78-282895acf1ed.png)

Would be cool if we used Plotly subplots for these.

https://siguniang.wordpress.com/2010/11/21/rviewports-grid-in-ggplot2/

**Comment by cpsievert** [comment]
I'm pretty sure translating that code directly isn't possible because of the package design and R internals.

However, we could make it easier to make subplots, which is something I can take into consideration for the redesign. Maybe we could handle a list of ggplots, so something like this:

```r
ps <- list(
  plot1 = qplot(rnorm(100)),
  plot2 = qplot(rnorm(100)),
  layout = list(yaxis = list(domain = c(0, 0.3)))
)
plotly(ps)
```

**Comment by jackparmer** [comment]
That would be cool!

**Comment by cpsievert** [comment]
The new `subplot()` function is aimed at this problem. @jackparmer feel free to open another issue if there is some sort of functionality that you think `subplot()` should support but doesn't.
