### ISSUE TITLE
Ordering of traces is wrong

### ISSUE THREAD

**Issue by jpevitt** [ropensci/plotly#225]
Hey guys, I'm pretty new to the plotly API so if I'm missing something please let me know. I have a 100% stacked area chart in ggplot2 that I'm trying to convert into a plotly plot. I followed the - pretty simple - steps on your API site which took me to the URL for it, except on the site my colors and/or lines entirely disappear leaving me with the entire plot blacked out in some random color.

**Comment by 13bzhang** [comment]
Sorry to hear that you are experiencing problems. Do you have code and images that you can share with us?

**Comment by jpevitt** [comment]
Thanks for the reply. I've attached a folder containing code and images.
Ideally, I would like the plotly version to be exactly the same as the
ggplot version but with the added benefit of being interactive in standard
plotly fashion.

Best,

Jason

On Fri, May 29, 2015 at 6:07 PM, Baobao Zhang <notifications@github.com>
wrote:

> Sorry to hear that you are experiencing problems. Do you have code and
> images that you can share with us?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/plotly/issues/225#issuecomment-106955700>.
>

Year	AA	Bio	Childrens	Christian	Finance	Hist	Horror	Lit	Military	MTC	Politics	Romance	SciFi	Sports	Westerns	YA
1902	0.000	0.033	0.000	0.000	0.000	0.333	0.000	0.500	0.000	0.033	0.000	0.067	0.000	0.000	0.033	0.000
1903	0.000	0.033	0.000	0.000	0.000	0.233	0.000	0.500	0.000	0.067	0.000	0.100	0.000	0.000	0.067	0.000
1904	0.000	0.033	0.000	0.000	0.000	0.133	0.000	0.567	0.000	0.067	0.000	0.133	0.000	0.000	0.067	0.000
1905	0.000	0.067	0.000	0.000	0.000	0.100	0.000	0.633	0.000	0.033	0.000	0.133	0.000	0.000	0.033	0.000
1906	0.000	0.100	0.000	0.000	0.000	0.100	0.000	0.633	0.000	0.000	0.000	0.100	0.000	0.000	0.067	0.000
1907	0.000	0.100	0.000	0.000	0.000	0.033	0.000	0.733	0.000	0.000	0.000	0.067	0.000	0.000	0.067	0.000
1908	0.000	0.100	0.000	0.000	0.000	0.100	0.000	0.700	0.000	0.000	0.000	0.000	0.000	0.000	0.100	0.000
1909	0.000	0.100	0.000	0.000	0.000	0.100	0.000	0.667	0.000	0.033	0.000	0.033	0.000	0.000	0.067	0.000
1910	0.000	0.067	0.000	0.000	0.000	0.133	0.000	0.567	0.000	0.100	0.000	0.067	0.000	0.000	0.067	0.000
1911	0.000	0.033	0.000	0.000	0.000	0.100	0.000	0.633	0.000	0.100	0.000	0.100	0.000	0.000	0.033	0.000
1912	0.000	0.000	0.000	0.000	0.000	0.167	0.000	0.633	0.000	0.067	0.000	0.100	0.000	0.000	0.033	0.000
1913	0.000	0.000	0.000	0.000	0.000	0.200	0.000	0.700	0.000	0.000	0.000	0.067	0.000	0.000	0.033	0.000
1914	0.000	0.033	0.000	0.000	0.000	0.233	0.000	0.633	0.000	0.000	0.000	0.067	0.000	0.000	0.033	0.000
1915	0.000	0.033	0.000	0.000	0.000	0.200	0.000	0.633	0.000	0.033	0.000	0.067	0.000	0.000	0.033	0.000
1916	0.000	0.033	0.000	0.000	0.000	0.200	0.000	0.533	0.000	0.033	0.000	0.133	0.000	0.000	0.067	0.000
1917	0.000	0.000	0.000	0.000	0.000	0.233	0.000	0.500	0.000	0.033	0.000	0.133	0.000	0.000	0.100	0.000
1918	0.000	0.000	0.000	0.000	0.000	0.200	0.000	0.467	0.000	0.067	0.000	0.167	0.000	0.000	0.100	0.000
1919	0.000	0.000	0.000	0.000	0.000	0.200	0.000	0.500	0.000	0.100	0.000	0.100	0.000	0.000	0.100	0.000
1920	0.000	0.000	0.000	0.000	0.000	0.200	0.000	0.467	0.000	0.133	0.000	0.100	0.000	0.000	0.100	0.000
1921	0.000	0.000	0.000	0.000	0.000	0.200	0.000	0.567	0.000	0.100	0.000	0.033	0.000	0.000	0.100	0.000
1922	0.000	0.000	0.000	0.000	0.000	0.267	0.000	0.467	0.000	0.100	0.000	0.067	0.000	0.000	0.100	0.000
1923	0.000	0.000	0.000	0.000	0.000	0.300	0.000	0.467	0.000	0.100	0.000	0.033	0.000	0.000	0.100	0.000
1924	0.000	0.000	0.000	0.000	0.000	0.333	0.000	0.400	0.000	0.067	0.000	0.067	0.000	0.000	0.133	0.000
1925	0.000	0.000	0.000	0.000	0.000	0.233	0.000	0.600	0.000	0.033	0.000	0.033	0.000	0.000	0.100	0.000
1926	0.000	0.000	0.000	0.000	0.000	0.200	0.000	0.633	0.000	0.000	0.000	0.033	0.033	0.000	0.100	0.000
1927	0.000	0.000	0.000	0.000	0.000	0.133	0.000	0.700	0.000	0.033	0.000	0.067	0.033	0.000	0.033	0.000
1928	0.000	0.000	0.000	0.000	0.000	0.133	0.033	0.567	0.000	0.067	0.000	0.133	0.033	0.000	0.033	0.000
1929	0.033	0.000	0.000	0.000	0.000	0.133	0.033	0.567	0.000	0.100	0.000	0.133	0.000	0.000	0.000	0.000
1930	0.033	0.000	0.000	0.000	0.000	0.133	0.033	0.567	0.000	0.100	0.000	0.100	0.000	0.000	0.033	0.000
1931	0.033	0.000	0.000	0.000	0.000	0.167	0.000	0.633	0.000	0.067	0.000	0.067	0.000	0.000	0.033	0.000
1932	0.000	0.000	0.000	0.000	0.000	0.200	0.000	0.633	0.000	0.033	0.000	0.100	0.000	0.000	0.033	0.000
1933	0.000	0.000	0.000	0.000	0.000	0.300	0.000	0.600	0.000	0.000	0.000	0.100	0.000	0.000	0.000	0.000
1934	0.000	0.000	0.000	0.000	0.000	0.367	0.000	0.567	0.000	0.000	0.000	0.067	0.000	0.000	0.000	0.000
1935	0.000	0.000	0.000	0.000	0.000	0.300	0.000	0.633	0.000	0.000	0.000	0.033	0.000	0.000	0.033	0.000
1936	0.000	0.000	0.000	0.000	0.000	0.333	0.000	0.567	0.000	0.033	0.000	0.033	0.000	0.000	0.033	0.000
1937	0.000	0.000	0.000	0.000	0.000	0.333	0.000	0.567	0.000	0.033	0.000	0.033	0.000	0.000	0.033	0.000
1938	0.000	0.000	0.000	0.000	0.000	0.367	0.000	0.567	0.000	0.033	0.000	0.033	0.000	0.000	0.000	0.000
1939	0.000	0.000	0.000	0.033	0.000	0.300	0.000	0.633	0.000	0.033	0.000	0.000	0.000	0.000	0.000	0.000
1940	0.000	0.000	0.000	0.067	0.000	0.233	0.000	0.667	0.000	0.033	0.000	0.000	0.000	0.000	0.000	0.000
1941	0.000	0.000	0.000	0.067	0.000	0.233	0.000	0.633	0.000	0.033	0.000	0.000	0.000	0.000	0.033	0.000
1942	0.000	0.000	0.000	0.033	0.000	0.400	0.000	0.533	0.000	0.000	0.000	0.000	0.000	0.000	0.033	0.000
1943	0.000	0.000	0.000	0.033	0.000	0.500	0.000	0.433	0.000	0.000	0.000	0.000	0.000	0.000	0.033	0.000
1944	0.000	0.000	0.000	0.067	0.000	0.467	0.000	0.400	0.000	0.033	0.000	0.033	0.000	0.000	0.000	0.000
1945	0.033	0.000	0.000	0.067	0.000	0.333	0.000	0.467	0.000	0.033	0.000	0.067	0.000	0.000	0.000	0.000
1946	0.033	0.033	0.000	0.033	0.000	0.200	0.000	0.600	0.000	0.033	0.000	0.067	0.000	0.000	0.000	0.000
1947	0.033	0.033	0.000	0.000	0.000	0.267	0.000	0.633	0.000	0.000	0.000	0.033	0.000	0.000	0.000	0.000
1948	0.000	0.033	0.000	0.000	0.000	0.333	0.000	0.633	0.000	0.000	0.000	0.000	0.000	0.000	0.000	0.000
1949	0.000	0.000	0.000	0.033	0.000	0.400	0.000	0.567	0.000	0.000	0.000	0.000	0.000	0.000	0.000	0.000
1950	0.000	0.000	0.000	0.033	0.000	0.367	0.000	0.567	0.000	0.000	0.000	0.033	0.000	0.000	0.000	0.000
1951	0.000	0.000	0.000	0.100	0.000	0.300	0.000	0.567	0.000	0.000	0.000	0.033	0.000	0.000	0.000	0.000
1952	0.000	0.000	0.000	0.067	0.000	0.200	0.000	0.667	0.000	0.000	0.000	0.033	0.000	0.000	0.033	0.000
1953	0.000	0.000	0.000	0.067	0.000	0.300	0.000	0.567	0.000	0.000	0.000	0.033	0.000	0.000	0.033	0.000
1954	0.000	0.000	0.000	0.000	0.000	0.267	0.000	0.667	0.000	0.000	0.000	0.033	0.000	0.000	0.033	0.000
1955	0.000	0.000	0.000	0.000	0.000	0.300	0.000	0.667	0.000	0.000	0.000	0.033	0.000	0.000	0.000	0.000
1956	0.000	0.000	0.033	0.000	0.000	0.200	0.000	0.733	0.000	0.000	0.000	0.033	0.000	0.000	0.000	0.000
1957	0.000	0.000	0.067	0.000	0.000	0.133	0.000	0.667	0.000	0.067	0.000	0.067	0.000	0.000	0.000	0.000
1958	0.000	0.000	0.100	0.000	0.000	0.100	0.000	0.567	0.000	0.100	0.000	0.100	0.000	0.000	0.033	0.000
1959	0.000	0.000	0.067	0.000	0.000	0.067	0.000	0.600	0.000	0.100	0.033	0.100	0.000	0.000	0.033	0.000
1960	0.000	0.000	0.033	0.000	0.000	0.167	0.000	0.567	0.000	0.067	0.067	0.067	0.000	0.000	0.033	0.000
1961	0.000	0.000	0.033	0.000	0.000	0.233	0.000	0.567	0.000	0.067	0.067	0.033	0.000	0.000	0.000	0.000
1962	0.000	0.000	0.033	0.000	0.000	0.200	0.000	0.533	0.000	0.133	0.067	0.033	0.000	0.000	0.000	0.000
1963	0.000	0.000	0.033	0.033	0.000	0.167	0.000	0.600	0.000	0.100	0.033	0.033	0.000	0.000	0.000	0.000
1964	0.000	0.000	0.000	0.033	0.000	0.133	0.000	0.567	0.000	0.200	0.033	0.033	0.000	0.000	0.000	0.000
1965	0.000	0.000	0.000	0.033	0.000	0.167	0.033	0.533	0.000	0.233	0.000	0.000	0.000	0.000	0.000	0.000
1966	0.000	0.000	0.000	0.000	0.000	0.100	0.033	0.500	0.000	0.300	0.033	0.033	0.000	0.000	0.000	0.000
1967	0.000	0.000	0.000	0.000	0.000	0.100	0.067	0.500	0.000	0.200	0.033	0.100	0.000	0.000	0.000	0.000
1968	0.000	0.000	0.000	0.033	0.000	0.033	0.033	0.467	0.000	0.200	0.067	0.133	0.033	0.000	0.000	0.000
1969	0.000	0.000	0.000	0.033	0.000	0.033	0.033	0.467	0.000	0.200	0.033	0.167	0.033	0.000	0.000	0.000
1970	0.000	0.000	0.000	0.033	0.000	0.067	0.000	0.433	0.000	0.200	0.033	0.200	0.033	0.000	0.000	0.000
1971	0.000	0.000	0.000	0.000	0.000	0.133	0.033	0.467	0.000	0.200	0.000	0.167	0.000	0.000	0.000	0.000
1972	0.000	0.000	0.000	0.033	0.000	0.167	0.033	0.433	0.000	0.200	0.000	0.100	0.000	0.033	0.000	0.000
1973	0.000	0.000	0.000	0.033	0.033	0.133	0.033	0.400	0.000	0.267	0.000	0.000	0.067	0.033	0.000	0.000
1974	0.000	0.000	0.033	0.033	0.033	0.100	0.000	0.400	0.000	0.300	0.000	0.000	0.067	0.033	0.000	0.000
1975	0.000	0.000	0.033	0.000	0.033	0.133	0.000	0.333	0.000	0.400	0.000	0.000	0.067	0.000	0.000	0.000
1976	0.000	0.000	0.033	0.000	0.000	0.133	0.000	0.300	0.000	0.467	0.000	0.000	0.067	0.000	0.000	0.000
1977	0.000	0.000	0.000	0.000	0.000	0.167	0.000	0.300	0.000	0.367	0.000	0.067	0.100	0.000	0.000	0.000
1978	0.000	0.000	0.000	0.000	0.000	0.167	0.000	0.267	0.000	0.333	0.000	0.133	0.100	0.000	0.000	0.000
1979	0.000	0.000	0.000	0.000	0.000	0.167	0.033	0.300	0.033	0.267	0.000	0.133	0.067	0.000	0.000	0.000
1980	0.000	0.000	0.000	0.000	0.000	0.133	0.067	0.200	0.033	0.433	0.000	0.100	0.033	0.000	0.000	0.000
1981	0.000	0.000	0.033	0.000	0.000	0.133	0.100	0.200	0.033	0.433	0.000	0.033	0.033	0.000	0.000	0.000
1982	0.000	0.000	0.033	0.000	0.000	0.167	0.100	0.133	0.000	0.433	0.000	0.067	0.067	0.000	0.000	0.000
1983	0.000	0.000	0.033	0.000	0.000	0.167	0.133	0.100	0.000	0.300	0.000	0.100	0.133	0.000	0.033	0.000
1984	0.000	0.000	0.033	0.000	0.000	0.167	0.100	0.067	0.000	0.300	0.000	0.133	0.167	0.000	0.033	0.000
1985	0.000	0.000	0.033	0.000	0.000	0.133	0.100	0.100	0.000	0.233	0.000	0.200	0.133	0.000	0.067	0.000
1986	0.000	0.000	0.033	0.000	0.000	0.100	0.067	0.100	0.000	0.300	0.000	0.267	0.067	0.000	0.067	0.000
1987	0.000	0.000	0.000	0.000	0.000	0.067	0.167	0.100	0.000	0.267	0.000	0.300	0.033	0.000	0.067	0.000
1988	0.000	0.000	0.000	0.000	0.000	0.100	0.167	0.067	0.000	0.333	0.000	0.300	0.000	0.000	0.033	0.000
1989	0.000	0.000	0.000	0.000	0.000	0.200	0.167	0.100	0.000	0.300	0.000	0.233	0.000	0.000	0.000	0.000
1990	0.000	0.000	0.000	0.000	0.000	0.167	0.167	0.100	0.000	0.300	0.000	0.267	0.000	0.000	0.000	0.000
1991	0.000	0.000	0.000	0.000	0.000	0.167	0.167	0.067	0.000	0.333	0.000	0.267	0.000	0.000	0.000	0.000
1992	0.000	0.000	0.000	0.000	0.000	0.100	0.233	0.033	0.000	0.333	0.000	0.300	0.000	0.000	0.000	0.000
1993	0.000	0.000	0.000	0.000	0.000	0.100	0.200	0.033	0.000	0.367	0.000	0.300	0.000	0.000	0.000	0.000
1994	0.000	0.000	0.000	0.000	0.000	0.033	0.200	0.067	0.000	0.333	0.000	0.333	0.033	0.000	0.000	0.000
1995	0.000	0.000	0.000	0.033	0.000	0.000	0.133	0.133	0.000	0.333	0.000	0.300	0.067	0.000	0.000	0.000
1996	0.000	0.000	0.000	0.033	0.000	0.000	0.133	0.133	0.000	0.333	0.033	0.267	0.067	0.000	0.000	0.000
1997	0.000	0.000	0.000	0.033	0.000	0.000	0.100	0.133	0.000	0.433	0.033	0.233	0.033	0.000	0.000	0.000
1998	0.033	0.000	0.000	0.000	0.000	0.000	0.100	0.100	0.000	0.467	0.033	0.267	0.000	0.000	0.000	0.000
1999	0.033	0.000	0.000	0.067	0.000	0.000	0.100	0.100	0.000	0.433	0.000	0.233	0.033	0.000	0.000	0.000
2000	0.033	0.000	0.000	0.133	0.000	0.000	0.100	0.067	0.000	0.400	0.000	0.233	0.033	0.000	0.000	0.000
2001	0.000	0.000	0.000	0.167	0.000	0.000	0.133	0.067	0.000	0.400	0.000	0.200	0.033	0.000	0.000	0.000
2002	0.000	0.000	0.000	0.133	0.000	0.000	0.100	0.100	0.000	0.500	0.000	0.167	0.000	0.000	0.000	0.000
2003	0.000	0.000	0.000	0.100	0.000	0.000	0.100	0.133	0.000	0.567	0.000	0.100	0.000	0.000	0.000	0.000
2004	0.000	0.000	0.000	0.100	0.000	0.000	0.033	0.133	0.000	0.700	0.000	0.033	0.000	0.000	0.000	0.000
2005	0.000	0.000	0.000	0.100	0.000	0.000	0.000	0.100	0.000	0.700	0.000	0.100	0.000	0.000	0.000	0.000
2006	0.000	0.000	0.000	0.067	0.000	0.000	0.067	0.100	0.000	0.633	0.000	0.067	0.033	0.000	0.000	0.033
2007	0.000	0.000	0.000	0.033	0.000	0.000	0.100	0.100	0.000	0.567	0.000	0.067	0.033	0.033	0.000	0.067
2008	0.000	0.000	0.000	0.000	0.000	0.000	0.133	0.133	0.000	0.533	0.000	0.000	0.033	0.033	0.000	0.133
2009	0.000	0.000	0.000	0.000	0.000	0.033	0.100	0.100	0.000	0.533	0.000	0.000	0.033	0.033	0.000	0.167
2010	0.000	0.000	0.000	0.000	0.000	0.067	0.100	0.100	0.000	0.533	0.000	0.000	0.033	0.000	0.000	0.167
2011	0.000	0.000	0.000	0.000	0.000	0.067	0.100	0.033	0.000	0.533	0.000	0.000	0.133	0.000	0.000	0.133
2012	0.000	0.000	0.000	0.000	0.000	0.033	0.067	0.033	0.000	0.400	0.000	0.133	0.133	0.000	0.000	0.200
2013	0.000	0.000	0.000	0.000	0.000	0.000	0.033	0.000	0.000	0.300	0.000	0.133	0.167	0.000	0.000	0.367
2014	0.000	0.000	0.000	0.000	0.000	0.067	0.033	0.067	0.000	0.267	0.000	0.167	0.067	0.000	0.000	0.333

**Comment by 13bzhang** [comment]
@jpevitt Thanks for your reply. But I cannot find the attached folder. All I see if a a bunch of numbers. Can you post the code directly to this issue or upload your folder as a repo or a gist on GitHub?

**Comment by jpevitt** [comment]
Sorry, answered through email, didn't realize it wouldn't display properly.
Here is my code:
    df <- read.delim(file.choose(), header=T)
    dfm <- melt(df, id.vars="Year")
    full <-
       ggplot(data=dfm, aes(x=Year, y=value)) +
       fte_theme(SCALE, MARGIN) +
       geom_area(aes(fill=variable)) +
       labs(title="Generic Title", x=NULL, y=NULL) +
       theme(legend.position="right") +
       theme(legend.title=element_blank()) +
       scale_y_continuous(labels=percent)
    library(plotly)
    py <- plotly()
    py$ggplotly(full)

It results in this ggplot plot when I render it in R
![ggplot screenshot](https://cloud.githubusercontent.com/assets/9859131/7898984/a04634e8-06d7-11e5-8977-a6b3a9dc48c3.png)

But on plotly it results in this:
![plotly screenshot](https://cloud.githubusercontent.com/assets/9859131/7898987/ab6fa4a8-06d7-11e5-9791-4353e1e37b83.png)

**Comment by 13bzhang** [comment]
Thanks for sharing. I will look into this.

**Comment by cpsievert** [comment]
I'm not exactly sure what's going wrong yet, but here is a reproducible example to help debug:

```r
library(dplyr)
df <- diamonds %>% group_by(carat, cut) %>% 
  summarise(n = n()) %>% mutate(freq = n/sum(n))
p <- ggplot(data = df, aes(x = carat, y = freq, fill = cut)) + 
  geom_area()
```

![https://plot.ly/~cpsievert/634/freq-vs-carat/](https://plot.ly/~cpsievert/634/freq-vs-carat.png)

**Comment by cpsievert** [comment]
Ah, this is related to the order in which the traces are drawn. If you hover over the example I provide above, you'll see hover info for all the traces. @13bzhang does that make sense? Feel free to tackle this one if you'd like.

**Comment by 13bzhang** [comment]
Yeah I can take this one.

**Comment by 13bzhang** [comment]
I have been working on this one for the past few days. So I noticed that stacked densities also don't work with the current code. For instance:

```r
p <- ggplot(data = movies, aes(x = rating, fill = mpaa,)) + 
  geom_density(position = "stack")
py$ggplotly(p)
```
ggplot2
![225_stacked_density](https://cloud.githubusercontent.com/assets/6131842/7982044/82a78dee-0a81-11e5-8e10-8db00a8d7059.png)

Plotly
![225_bad_density](https://cloud.githubusercontent.com/assets/6131842/7982047/8b7f139c-0a81-11e5-90e6-ca466f68f592.png)

The problem is that the order of the traces are laid in reverse. I played around with the code in `trace_generation.R` a bit and added the following:

```r
   if (g$geom == "area" | g$geom == "density"){
     traces <- rev(traces)
   }
```
Again, this is really unsophisticated but just a first cut. 

I was able to produce the following:

ggplot2
![225_area](https://cloud.githubusercontent.com/assets/6131842/7982128/703f542e-0a82-11e5-8c45-3ab11f243685.png)

Plotly
![225_first_try_area](https://cloud.githubusercontent.com/assets/6131842/7982086/f8de6fdc-0a81-11e5-8c07-7b0df791bd9c.png)

Plotly
![225_first_try_density](https://cloud.githubusercontent.com/assets/6131842/7982089/05ebab7c-0a82-11e5-8956-f6128590533e.png)

Note some problems still left:
* the legend is reversed in the `area` example
* the legend doesn't show up in the `density` example

Maybe the solution is to make special cases for these types of geoms like in 
https://github.com/ropensci/plotly/blob/master/R/trace_generation.R#L251-L263
?

@cpsievert @chriddyp

**Comment by cpsievert** [comment]
It looks like this problem isn't necessarily specific to a geom. For example,

```r
qplot(wt, drat, color = gear, data = mtcars)
```

leads to

![](https://plot.ly/~cpsievert/943/drat-vs-wt.png)

That legend should have 3 at the top and 1 at the bottom. I think you can fix this by having trace "3" be the first trace, trace "2" be the second, and trace "1" be the third. 

You may also need to add some special handling for the area geom, but I'm not sure.

**Comment by cpsievert** [comment]
@13bzhang sorry, I didn't read your post carefully. I wouldn't worry about the ordering of the legend, in fact, I think the plotly version is more sensible than ggplot2. Also, the legend problem is reported in #212.

That being said, I'd start a PR with your ordering fix and include a test!

**Comment by 13bzhang** [comment]
@cpsievert If it's a more general problem, then the fix should be somewhat easier.

**Comment by cpsievert** [comment]
Fixed via a4a9a1d
