### ISSUE TITLE
Plotly installation

### ISSUE THREAD

**Issue by vishy730** [ropensci/plotly#229]
Hi,
I am getting the below message when installing plotly. devtools installed.

install_github("ropensci/plotly")
Installing plotly
"C:/PROGRA~1/R/R-32~1.0/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore CMD INSTALL  \
  "C:/Users/Administrator/AppData/Local/Temp/RtmpId0fWd/devtoolsaa44f0b708d/ropensci-plotly-6ff8831"  \
  --library="C:/Program Files/R/R-3.2.0/library" --install-tests

**Comment by cpsievert** [comment]
Hi @vishy730, that's a message, not an error. If you received an error, please report that as well.

**Comment by vishy730** [comment]
Hi cpsievert,

I got only this.. no error nothing and not even successfull installation

**Comment by cpsievert** [comment]
What happens if you type `library(plotly)`?

**Comment by vishy730** [comment]
could solve the issue.. added R path in environment variables and solved the problem. Thanks for your time.
