### ISSUE TITLE
geom_smooth() not working

### ISSUE THREAD

**Issue by 13bzhang** [ropensci/plotly#231]
There is a problem with `geom_smooth()` that a user had alerted us to. 

Code:

```r
d <- diamonds[sample(nrow(diamonds),1000),]
p <-ggplot(data=d, aes(x=carat, y=price)) + 
  geom_point(aes(text=clarity)) +
  geom_smooth(method=lm) +
  theme_minimal() +
  ggtitle("A title") +
  labs(y = "y", x = "x")
```

ggplot 

![geom_smooth_lm_ggplot2](https://cloud.githubusercontent.com/assets/6131842/8123502/c138323a-1098-11e5-937d-121154c5f04d.png)

Plotly

Link: https://plot.ly/~13bzhang/787/a-title/

![geom_smooth_lm_bad](https://cloud.githubusercontent.com/assets/6131842/8123508/d078e9ba-1098-11e5-8248-20801716681b.png)

Other `geom_smooth` smoothers have similar problems. I'm looking into this.

@cpsievert @chriddyp @mkcor

**Comment by 13bzhang** [comment]
@cpsievert It was working up until we merged Carson Density Cookbook into master. When you said you couldn't reproduce the error, were you on the current master branch?

**Comment by 13bzhang** [comment]
@cpsievert Ok, I went back several commits on `master`, before we merged in your Density Cookbook and the problem still persists. Do you think it's something on the Plotly server that's causing it?

**Comment by cpsievert** [comment]
I used that code on branch `carson-dsl` in #226 to create (so it seems to work) -> https://plot.ly/1096/~cpsievert/

I don't have time to look into this right now so maybe we should suggest installing the new branch 

```r
devtools::install_github("ropensci/plotly@carson-dsl")
```

**Comment by cpsievert** [comment]
Also, could you provide a link to the plotly's that your screenshots are from?

**Comment by mkcor** [comment]
@cpsievert https://plot.ly/~abtran/331 vs https://plot.ly/~abtran/299

**Comment by 13bzhang** [comment]
@cpsievert I added the link. 

Also I tried:

```r
devtools::install_github("ropensci/plotly@carson-dsl")
library(plotly)
# make ggplot
d <- diamonds[sample(nrow(diamonds),1000),]
p <-ggplot(data=d, aes(x=carat, y=price)) + 
  geom_point(aes(text=clarity)) +
  geom_smooth(method=lm) +
  theme_minimal() +
  ggtitle("A title") +
  labs(y = "y", x = "x")
# send it up to Plotly
py$ggplotly(p)
```
And got this: https://plot.ly/~13bzhang/798/a-title/

The weird thing is the picture on the Preview looks fine:
![screenshot from 2015-06-12 14 42 28](https://cloud.githubusercontent.com/assets/6131842/8137420/51f3b010-1111-11e5-8b18-e05f3f47bf24.png)

**Comment by 13bzhang** [comment]
Now it's working `devtools::install_github("ropensci/plotly@carson-dsl")`. 
See https://plot.ly/~13bzhang/818.png

**Comment by cpsievert** [comment]
This seems to be working on master now.
