### ISSUE TITLE
ggplot2 to plotly.

### ISSUE THREAD

**Issue by Dilip1991** [ropensci/plotly#234]
Hey , i am trying to convert ggplot2 plot to plotly. While assigning   py$ggplotly()     facing a a error like Error: Not found. Please help.

**Comment by 13bzhang** [comment]
@Dilip1991 Hi! A couple of questions: 

1. Did you run `library(plotly`)?
2. Did you set your credentials using `set_credentials_file("username", "API key")`?
3. Did you first instantiate a Plotly object:  `py <- plotly()`?
4. Which branch of `plotly` are you using?

Here some directions to get you started: https://plot.ly/ggplot2/getting-started/

**Comment by Dilip1991** [comment]
Yes , I have done all of that.

> library(plotly)
>  py <- plotly("DemoAccount", "lr1c37zw81")
>  ggiris <- qplot(Petal.Width, Sepal.Length, data = iris, color = Species)
>  py$ggplotly(ggiris)
Error: NOT FOUND
> packageVersion("plotly")
[1] ‘0.6.3’
![error](https://cloud.githubusercontent.com/assets/12796297/8370905/b28be84e-1bec-11e5-9e23-e8571ce16b66.JPG)

>

**Comment by 13bzhang** [comment]
Just to confirm, R is outputting `ggiris` correctly, right?
Also can you please share with us the output from `sessionInfo()`?

**Comment by Dilip1991** [comment]
Yes , R is outputting ggiris Correctly.
![session info](https://cloud.githubusercontent.com/assets/12796297/8371865/f25e4dc8-1bfa-11e5-921e-2bb0689d20aa.JPG)

**Comment by 13bzhang** [comment]
@Dilip1991 Hi! Thanks for sharing this information with us.
A couple of questions:
Have you had this problem before you upgraded to R 3.2.1?
Has `plotly` worked for you after you upgraded to R 3.2.1?
Does it fail to work even after restarting a R session (after closing R and reopening it)?
Thanks for being patient.

**Comment by Dilip1991** [comment]
Yes , I have same problem in R console and R studio both before and after upgrading. 

plotly() never supported before as well as now. Yes it is fail to to work after Restarting or closing the session. 

I have tried alot to overcome it. But it is showing same error everytime.

**Comment by 13bzhang** [comment]
Sorry I don't have access to a Windows machine right now to test it now but I will first thing in the morning.

**Comment by Dilip1991** [comment]
Yes Mam , Its ok. Take your time. 
Thanks for your support.

**Comment by Dilip1991** [comment]
Hey , Just now I have check , it is working fine on my friends laptop. I don't know whats the issue with me. 

Thanku for your kind support.

**Comment by cpsievert** [comment]
Hi @Dilip1991, 

The new version might solve your problems. Try reinstalling (`devtools::install_github("ropensci/plotly")`) and then set your credentials with:

```r
Sys.setenv("plotly_username"="your_plotly_username")
Sys.setenv("plotly_api_key"="your_api_key")
```
