### ISSUE TITLE
Problem with plotly and wordcloud

### ISSUE THREAD

**Issue by jeandut** [ropensci/plotly#237]
Hello, I recently discovered this library it has been a great experience ! Thanks a lot for your work !
I am currently building an application using wordclouds as regular plots and plotly for some other plots and I think there is a conflict between the two libraries plotly and maybe tm/wordcloud. Because I get the message:
`Error in gg2list(gg_ideal_point) : object 'nann' not found`
I think I have seen some recent issue about a conflict between plotly and the package NLP, but I think it was solved. What do you think ?

**Comment by 13bzhang** [comment]
Hi @jeandut ! Are you still having this problem? If yes, you might consider using the branch `baobao-fix_exists` instead, where I fixed the problem.

To install, you would:

```r
devtools::install_github("ropensci/plotly@baobao-fix_exists")
library(plotly)
```

**Comment by jeandut** [comment]
Yes I had to do a small fix by loading and then immediately unloading the package tm (which calls NLP) inside my function. I will use your fix then it is much cleaner. Thanks a lot !

Date: Wed, 8 Jul 2015 23:00:09 -0700
