### ISSUE TITLE
ggplot stacked bars linked by the stacks

### ISSUE THREAD

**Issue by goplu** [ropensci/plotly#238]
Hi,

I am trying to plot stacked bars and link each stack based on its colour. In other words, I'm trying to make something like alluvial plot, but not with parallel coordianate data. For some x-axis columns, some of the stacks are missing, while some stacks are appearing only in the second or third columns. While I prefer to show all the stacks, I would like to link the ones that are shared between columns.

Can anyone help with that? Thanks a lot!

**Comment by 13bzhang** [comment]
Hi @goplu, thanks for letting us know. Can you share with me your code and images of the plots that are giving you problems?

**Comment by cpsievert** [comment]
@goplu are you using the R package to create your plot? If so, please include code used to generate the plot as well as a link to the plot itself and we'd be more than happy to help. If not, please contact feedback@plot.ly with your questions
