### ISSUE TITLE
Plotly not available for R version 3.2.1?

### ISSUE THREAD

**Issue by lwgreen788** [ropensci/plotly#239]
Hello,

I'm trying to follow the R shiny plotly example here: https://github.com/cldougl/plotly-shiny/tree/master/Examples/Diamonds

The plot won't display, even with my own plotly username and API key. I had to install plotly from github using devtools, since R gave the following message:

> install.packages("plotly")
Warning in install.packages :
  package ‘plotly’ is not available (for R version 3.2.1)

Has anyone else had this issue?

**Comment by 13bzhang** [comment]
Hi @lwgreen788 , our package is not on CRAN yet so you can't `install.packages` yet. Right now you have to download it from GitHub.

**Comment by 13bzhang** [comment]
Thanks for trying out Plotly!

**Comment by lwgreen788** [comment]
Okay, thanks!

**Comment by cpsievert** [comment]
Hi @lwgreen788! 

In the next few weeks we'll be merging #226. You can run that example using the new version by doing:

```r
devtools::install_github("ropensci/plotly@carson-dsl")
shiny::runApp(system.file("examples/Diamonds", package = "plotly"))
```

And here is the source for that example -> https://github.com/ropensci/plotly/tree/carson-dsl/inst/examples/Diamonds
