### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by MyPencil** [ropensci/plotly#240]
When i try and install plotly I'm getting this error message

> library("devtools")
> install_github("ropensci/plotly")
Downloading github repo ropensci/plotly@master
Error in packageVersion("RCurl") : package ‘RCurl’ not found

**Comment by 13bzhang** [comment]
Hi @MyPencil , have you tried installing `RCurl`? I know it can be a bit tricky to install. If `install.packages("RCurl")` doesn't work, you might have to install it by compiling from the source:

`
install.packages("RCurl_1.95-4.7.zip", repos=NULL, type="source")
`

The code above is for Windows. You might have to change the `"RCurl_1.95-4.7.zip"` part if you are using OS X. See the "Downloads" section of https://cran.r-project.org/web/packages/RCurl/index.html to see which binaries zip file you should use.

**Comment by cpsievert** [comment]
Hi @MyPencil, I don't think the new version (as of today) requires RCurl, so I'm closing but feel free to re-open if you still have issues.

**Comment by MyPencil** [comment]
I changed up the command to 

devtools::install_github("ropensci/plotly")

seems to be working fine now.
