### ISSUE TITLE
if `offline=FALSE`, better indicator that the iframes won't render in the rstudio web viewer

### ISSUE THREAD

**Issue by chriddyp** [ropensci/plotly#245]
if offline is disabled, it's confusing to see a blank screen when you `runApp`

![image](https://cloud.githubusercontent.com/assets/1280389/9040970/78fe832a-39d3-11e5-82e2-110f439bd06c.png)

A couple options:
- Is it possible to open the app in the web browser instead of the rstudio viewer **if** `offline=FALSE`?
- Maybe show a "Unfortunately, IFrames like this plotly graph can't be viewed in RStudio. [View this app in your web browser instead](https://localhost:4000)" placeholder instead of the blank iframe. If the `onerror` event is fired from shiny, we could show the placeholder on that event: http://stackoverflow.com/questions/15273042/catch-error-if-iframe-src-fails-to-load-error-refused-to-display-http-ww

**Comment by cpsievert** [comment]
Good point. Unfortunately, it appears that the RStudio viewer blocks alert() messages as well. One (easy) solution would be relay a message to the R console, but that might easily be missed (especially if the app spits output to the console). Maybe the more robust solution is to insert a div when the onerror message fires?
