### ISSUE TITLE
plotly installation not working

### ISSUE THREAD

**Issue by corinne-riddell** [ropensci/plotly#249]
I tried to update my plotly installation on R version 3.1.3 on Mac OS but there's an error when installing the dependency 'viridis' package. Here's a screenshot of the problem:
![screen shot 2015-08-09 at 6 29 17 pm](https://cloud.githubusercontent.com/assets/12090129/9157263/23814242-3ec5-11e5-88aa-192f04de4b6d.png)

**Comment by cpsievert** [comment]
Try doing `install.packages('viridis', type = 'source')`

**Comment by corinne-riddell** [comment]
Thanks @cpsievert - that worked!
