### ISSUE TITLE
test against multiple versions of R

### ISSUE THREAD

**Issue by chriddyp** [ropensci/plotly#255]
https://github.com/ropensci/plotly/issues/254 was discovered today against R 3.1.3. We should test against multiple versions of R releases to avoid this in the future. It looks like this repo is a good start at this: https://github.com/metacran/r-builder

**Comment by cpsievert** [comment]
CRAN provides checks for multiple versions of R and systems -- https://cran.r-project.org/web/checks/check_results_plotly.html

IMO, now that we're on CRAN, setting this up on Travis would be more trouble than its worth
