### ISSUE TITLE
filename doesn't work with `subplot`

### ISSUE THREAD

**Issue by chriddyp** [ropensci/plotly#267]
```
subplot(plot_ly(economics, x = date, y = uempmed, filename="subplot-example"), plot_ly(economics, x = date, y = uempmed))
```

creates a file named `"dates vs uemped"` instead of `"subplot-example"`

**Comment by chriddyp** [comment]
![image](https://cloud.githubusercontent.com/assets/1280389/9285908/cf538548-42b8-11e5-8725-7c5e529b939b.png)

**Comment by cpsievert** [comment]
Here are a couple workarounds. I'd eventually like to support your example, but these approaches should always work:

(1) Add a title

```r
s <- subplot(plot_ly(economics, x = date, y = uempmed), plot_ly(economics, x = date, y = uempmed)) 
# When a filename doesn't exist, but a title does, that is used as the filename
s %>% layout(title = "MyPlot")
```

(2) Build the plot and attach a filename. Note that this approach should work for any type of plot (ggplot/plotly/subplot/etc)

```r
s <- plotly_build(s)
s$filename <- "AnotherPlot"
s
```

**Comment by chriddyp** [comment]
nice, thx!

**Comment by cldougl** [comment]
updated docs ( https://plot.ly/r/subplots/ & https://plot.ly/r/file-options/ ) w/ overwriting subplots info

**Comment by cpsievert** [comment]
This is no longer a problem now that users will have to always use `plotly_POST(..., filename = "foo")`
