### ISSUE TITLE
offline js not injected into markdown after you run `knitr::knit` the first time

### ISSUE THREAD

**Issue by chriddyp** [ropensci/plotly#271]
https://github.com/ropensci/plotly/blob/master/R/print.R#L81

once `knitr::knit` is run once, `knit_meta` has `plotly` in it, and so it won't inject the script the next time `knit` is called. 

current workaround is to call `knitr::knit_meta(clean=TRUE)` before you `knit`. 

is it possible clean `knit_meta` at the end of the `knit` call? 

cc @cpsievert

**Comment by cpsievert** [comment]
Yea, I'm not immediately of a great way to fix this problem. (I think) another workaround is to knit in a new environment each time (the knit button in RStudio does this). For example,

```r
knitr::knit("index.Rmd", envir = new.env())
```

**Comment by cpsievert** [comment]
This is fixed now that we've switched to **htmlwidgets** (in #287)
