### ISSUE TITLE
offline plots in for loops

### ISSUE THREAD

**Issue by chriddyp** [ropensci/plotly#273]
a current workaround is:

    ```{r, results="asis"}
    for(i in 1:3) {
        fig <- list(data=list(list(x=rnorm(100), type="histogram")), layout=list(title=paste(c('plot', i, sep=" "))))
        cat(knit_print.offline(fig %>% offline))
    }
    ```

maybe there is an easier way?

**Comment by cpsievert** [comment]
[It looks like ggvis suffers from the same problem](https://groups.google.com/forum/#!topic/ggvis/HPhAaSttQzU). I have a feeling it's because knitr can only call `knit_print()` once per chunk. I suppose my advice would be to use `subplot()` instead

    ```{r}
    n <- 10
    df <- data.frame(
      x = c(replicate(3, rnorm(n))),
      plot = rep(1:3, each = n)
    )
    df %>%
      plot_ly(x = x, group = plot, xaxis = paste0("x", plot), 
              type = "histogram") %>% 
      subplot() %>% offline()
    ```

**Comment by cpsievert** [comment]
Looks like @yihui will provide [a solution](https://github.com/ramnathv/htmlwidgets/pull/110) for us :blush:

**Comment by yihui** [comment]
Here is the easy way:

    ```{r}
    res <- lapply(1:3, function(i) {
        fig <- list(data=list(list(x=rnorm(100), type="histogram")), layout=list(title=paste(c('plot', i, sep=" "))))
        fig %>% offline
    })
    htmltools::tagList(res)
    ```

**Comment by cpsievert** [comment]
`offline()` has been deprecated since plotly.js went open source.

Here is the current way to do this:

    ```{r}
    library(plotly)
    htmltools::tagList(lapply(1:3, function(x) { as.widget(plot_ly(x = rnorm(10))) }))
    ```

Or, if you prefer a for loop:

    ```{r}
    l <- htmltools::tagList()
    for (i in 1:3) {
      l[[i]] <- as.widget(plot_ly(x = rnorm(10)))
    }
    l
    ```

**Comment by GegznaV** [comment]
Nice workarround. Unfortunately, I'm not able to use it in my current automated analysis where in each iteration of `for` loop `plotly` graphs are followed by tables, results of some statistical tests, etc. Printing all plots in one place would be confusing and not using `for` loop would mean, that analysis is not automated. 
Now it is not clear for me is it a bug/limitation in `knitr` or in `plotly`, as I noticed that result of `pander()` also does not print from inside `for` loop in `.Rmd` file?

**Comment by timelyportfolio** [comment]
@GegznaV, what are you using to make the tables?  Do you have a small code sample?  This can still be made to work with a combination of `plotly` and tables.

**Comment by GegznaV** [comment]
simple example:

---
title: "Untitled"
output: html_document
---


```{r, include=FALSE}
library(ggplot2)
library(plotly)
library(magrittr)
library(pander)
```


```{r, warning=FALSE}
for(i in c("vs", "am", "gear", "carb")){
   
     print(i)
    
    mtcars$am <- as.factor(mtcars[[i]])
    # plot 1
    {ggplot(mtcars,aes(x = mpg, y = disp, color = am)) + geom_point()}  %>%
        ggplotly
    
    # plot 2
    {ggplot(mtcars,aes(x = mpg, fill = am)) + geom_density(alpha = .3)}  %>%
        ggplotly
    
    # table 1
    summary(mtcars[,c("mpg","disp",i)]) %>% pander
    
    # table 2: Kruskal-Wallis test
    kruskal.test(mtcars$mpg, mtcars[[i]])  %>% pander
           
}
```

**Comment by timelyportfolio** [comment]
@GegznaV, this is a hack in the ugliest of forms, but it does work.

```
        ---
        title: "Untitled"
        output: html_document
        ---
        
        ```{r results='asis'}
        library(ggplot2)
        library(plotly)
        library(magrittr)
        library(htmltools)
        library(pander)
        
        # turn off pander auto asis
        pander::panderOptions('knitr.auto.asis', FALSE)
        
        # create a container for our output
        output <- list()
        
        # loop through columns
        for(i in c("vs", "am", "gear", "carb")){
          # get column
          mtcars$am <- as.factor(mtcars[[i]])
          
          # plot 1
          output[[length(output) + 1]] <- {
            ggplot(mtcars,aes(x = mpg, y = disp, color = am)) + geom_point()
          }  %>%  ggplotly %>%  as.widget
          
              # plot 2
          output[[length(output) + 1]] <- {
            ggplot(mtcars,aes(x = mpg, fill = am)) + geom_density(alpha = .3)
          }  %>% ggplotly %>%  as.widget
        
          output[[length(output) + 1]] <-  paste0(
            capture.output(summary(mtcars[,c("mpg","disp",i)]) %>% pander),
            collapse="\n"
          )
        }
        
        # now cat/print all of the content
        for(j in 1:length(output)){
          x <- output[[j]]
          #  we know only character and htmlwidget in this case
          #   if more need to handle appropriately
          if(inherits(x,"character")){
            # noquote critical here
            #  also turn off auto.asis very important
            cat(noquote(paste0(x,collapse="\n")))
          } else {
            # print the html piece of the htmlwidgets
            cat(renderTags(x)$html)
          }
        }
        
        ```
        
        ```{r echo=FALSE, messages=FALSE, warning=FALSE}
        # attach the Dependencies
        # since the do not get included with renderTags(...)$html
        deps <- lapply(
          Filter(function(x){inherits(x,"htmlwidget")},output),
          function(hw){
            renderTags(hw)$dependencies
          }
        )
        
        attachDependencies(
          tagList(),
          unlist(deps,recursive=FALSE)
        )
        ```
```

**Comment by Henry-E** [comment]
https://github.com/ropensci/plotly/issues/273#issuecomment-217982315

@timelyportfolio For printing out html widgets and other things created in a for loop, this process is incredibly involved. Still, it is the closest fit to how I've been creating dynamic documents in rmarkdown. If I want to extend the example given to new options, like datatables or character output without a table in it, what's the best way to figure out what I should looking to put into the print statement? How do you debug such things when testing them out.

**Comment by tacormier** [comment]
I have a related question. I am trying to use ggplotly in a nested loop. It works fine in a single loop, but when I nest it within another loop (necessary for output html document structure) it doesn't print the plots. I need the plots from the while loop to be under the heading established in the for loop. Here is a simplified example:

```library(ggplot2)
library(plotly)

#+ results='asis', echo = FALSE
for (i in c('A','B')) {
  cat("## This is a heading for ", i, "\n")

  v <- 1
  l <- htmltools::tagList()

  while (v <= 3) {
    print(noquote(v))
    df <- data.frame(x=v, y=10)
    p <- ggplot(df, aes(x=x, y=y)) + geom_point()
    ggp <- ggplotly(p)
    l[[v]] <- ggp

    v=v+1
    cat('\n')
  
  }

  l
}
```
If I just run the while loop and comment out the outer for-loop, it works and prints the graphs. Once I add in that outer loop, I have problems. Any thoughts on a work-around. Perhaps the widget solution above would work, but I wanted to post the question in case there's an easier, more straightforward answer.

Many thanks!

**Comment by PhilipBerg** [comment]
Doing this in a nested for loop wont work. I would provide a MWE, but it seems so simple I don't see the point.

**Comment by wetlandscapes** [comment]
[#237 (comment)](https://github.com/ropensci/plotly/issues/273#issuecomment-217982315)

Thank you @timelyportfolio for your solution. I was trying to get some ggplotly outputs rendered as tabsets from an rmarkdown to html_output, but couldn't figure it out. It was driving me mad. I was able to plot everything with modified form to your solution. Cheers!

**Comment by philsinn** [comment]
Quite an easy way to add tables and plots (and more plots and titles etc.) in a loop in RMarkdown is:

```{r, results="asis"}
```{r, results='asis'}

htmltools::tagList(plot_ly(x = rnorm(10), type = "histogram"))

for (i in 1:3) {
  
  cat(summary(mtcars[,i]) %>% pander::pander())
 
  cat("\n\n")
  
  print(htmltools::tagList(plot_ly(x = rnorm(10), type = "histogram")))
  
  cat("\n\n")
}
```

You only need to watch out that the plotly libs get included. Therefore I first create a plot outside the loop.

**Comment by pczhang** [comment]
Dear all,

I am trying an approach combining solutions from @timelyportfolio and @ghost.

test.Rmd below

```{r, include = F}
library(plotly)
```

```{r, results='asis'}
plotlist = list()

for (i in 1:3) {
    cat("# Section ", i, "\n\n")
    p <- plot_ly(x = rnorm(10), type = "histogram")
    plotlist[[i]] = p
    print(htmltools::tagList(p))
    cat("\n\n")
}
```

```{r, results = "asis"}
deps <- lapply(
    Filter(function(x){inherits(x,"htmlwidget")}, plotlist),
    function(hw){
        htmltools::renderTags(hw)$dependencies
    }
)

htmltools::attachDependencies(
               htmltools::tagList(),
               unlist(deps,recursive=FALSE)
           )
```

The plots will be shown when I do render("test.Rmd") and open test.html from my browser. However, it won't appear when I put the Rmd file in the shiny server. I wonder what is the difference between these two. Any way to modify it so it will also work in the shiny server.

Thanks!

**Comment by mayank7j-shell** [comment]
Hi @yihui, @cpsievert and everyone,

Thank you for your quick fix with `htmltools::tagList`. This works as expected in the normal flow of things - creating plots within for loop and then using `tagList` to print them in reports. 

However, when we combine this with [native collapsible sections](https://www.emmanuelgautier.com/blog/markdown-collapsible-section) in markdown, the plotly plots don't render and just churn out empty div under the collapsible sections. 

However, as proposed above, printing 1 plotly plot outside the collapsible sections renders them correctly. However, with our current implementation we want to have all the sections collapsible in the rmd report.

Any suggestions to solve this is highly appreciated. Thank you so much for your time.

**Comment by HDash** [comment]
https://github.com/plotly/plotly.R/issues/273#issuecomment-2139786023

@mayank7j-shell Simply add the following chunk at the start of your RMarkdown document-

```
```{r include = FALSE}
htmltools::tagList(plot_ly(x = rnorm(10), type = "histogram"))
```‎ 
```

This ensures the Plotly JS dependencies are loaded before Plotly functions are called in a `for` loop.   
(Source: [StackOverflow](https://stackoverflow.com/questions/36234169/plotly-charts-in-a-for-loop))
