### ISSUE TITLE
install_github on mac error

### ISSUE THREAD

**Issue by ElianoMarques** [ropensci/plotly#276]
Hi,

I'm running ```devtools::install_github("ropensci/plotly") ``` and I'm getting the following error.
```
Error : .onAttach failed in attachNamespace() for 'plotly', details:
  call: normalizePath("~", mustWork = TRUE)
  error: path[1]="/Users/elianomarques/~": No such file or directory
Error: loading failed
Execution halted
 ```
Could you by any chance have a look at this?

Thank you,
Eliano

**Comment by cpsievert** [comment]
try `devtools::install_github("ropensci/plotly")`

**Comment by ElianoMarques** [comment]
Sorry - I meant I've tried ```devtools::install_github("ropensci/plotly") ```

**Comment by cpsievert** [comment]
Hmm, are you using RStudio? If so, [this post might help](http://stackoverflow.com/questions/19086111/package-mgcv-could-not-be-loaded-only-in-rstudio)

If that doesn't help, you could include the output of `devtools::session_info()`?

**Comment by ElianoMarques** [comment]
Didn't work. Here is the session info. 
```
Session info --------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.0 (2015-04-16)
 system   x86_64, darwin13.4.0        
 ui       RStudio (0.99.467)          
 language (EN)                        
 collate  en_GB.UTF-8                 
 tz       Atlantic/Madeira  ```

**Comment by cpsievert** [comment]
I think you'll have to [either remove RStudio's user settings or upgrade your version of R](https://github.com/robjhyndman/forecast/issues/123#issuecomment-127163275) (I'd recommend you do the latter, if possible)

**Comment by ElianoMarques** [comment]
None of the options worked. I think he is trying to write to users/myname/~path but my library is not there and it can't find the path. I've tried also 
```
library(devtools)
with_libpaths(new = "/Library/Frameworks/R.framework/Versions/3.2/Resources/library",
              devtools::install_github("ropensci/plotly"))
```
But had no luck. Please note that the version of R was updated to 3.2.1 but bear in mind i'm using Revolution R Open framework inside R Studio.

**Comment by cpsievert** [comment]
Maybe your version of devtools is out of date? Try running `install.packages('devtools')`. It'd be helpful if I had the _complete_ output of `devtools::session_info()` and/or `sessionInfo()`

**Comment by jeromefroe** [comment]
Hello, I am having the same issue downloading plotly, the error message I receive after running `devtools::install_github("ropensci/plotly")` is:

    Error : .onAttach failed in attachNamespace() for 'plotly', details:
      call: normalizePath("~", mustWork = TRUE)
      error: path[1]="/Users/jeromefroelich/~": No such file or directory
    Error: loading failed
    Execution halted

the output from `sessionInfo()` is:

    R version 3.2.2 (2015-08-14)
    Platform: x86_64-apple-darwin13.4.0 (64-bit)
    Running under: OS X 10.10.5 (Yosemite)

    locale:
     [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods  
    [7] base     

    loaded via a namespace (and not attached):
     [1] httr_1.0.0     R6_2.1.1       magrittr_1.5   tools_3.2.2   
     [5] curl_0.9.3     memoise_0.2.1  stringi_0.5-5  stringr_1.0.0 
     [9] digest_0.6.8   devtools_1.9.1

Has anyone found a solution? Thanks!

**Comment by ElianoMarques** [comment]
My error was gone once I updated R. Are you using through rstudio? Can you try R through terminal or simple tool? does the error persist? 

Eliano

**Comment by jeromefroe** [comment]
Hi Eliano, thanks for the quick response! I am using Rstudio, but I tried the command from the terminal and got the same error response. I saw above that you were using Revolution R and so am I. When you updated R, did you update to to the newest plain R or the newest Revolution R? I wondering if the bug may be caused by Revolution R.

**Comment by jeromefroe** [comment]
Got it! I was able to install `plotly` by first removing the old version of the `plotly` package I had on my computer with`remove.packages("plotly")` (probably should have tried this earlier). Eliano, that may explain why you were able to download it after updating R, if all of your packages were removed upon updating as happens sometimes.

**Comment by ElianoMarques** [comment]
Great that is working now. Plotly is a good lib for viz.
Eliano
