### ISSUE TITLE
Installation issue: ERROR: dependency 'jsonlite' is not available for package 'plotly'

### ISSUE THREAD

**Issue by chriddyp** [ropensci/plotly#282]
Any recommendation for ?
"ERROR: dependency 'jsonlite' is not available for package 'plotly'

removing 'C:/Users/Owner/Documents/R/win-library/3.2/plotly' Error: Command failed (1)"
version.string R version 3.2.1 (2015-06-18)

as reported by @chabir

**Comment by cpsievert** [comment]
Hey @chabir, thanks for reporting. What happens when you do `install.packages('jsonlite')`?

**Comment by chabir** [comment]
Thanks!
At first, it failed to install jsonlite... I restarted R, tried Jsonlite again and plotly and it works...
