### ISSUE TITLE
Using development version of ggplot2

### ISSUE THREAD

**Issue by akhst7** [ropensci/plotly#288]
Hi, 
I tried to install the plotly by `<install_github("ropensci/plotly")>` but installation failed with a following error;

>Error in seq.default(1, idx - 1) : 'to' must be of length 1
>Error : unable to load R code in package ‘plotly’
>ERROR: lazy loading failed for package ‘plotly’

Here is my setup;

1. platform       x86_64-apple-darwin15.0.0   
2. arch           x86_64                      
3. os             darwin15.0.0                
4. system         x86_64, darwin15.0.0        
5. status                                     
6. major          3                           
7. minor          2.2                         
8. year           2015                        
9. month          08                          
10. day            14                          
11. svn rev        69053                       
12. language       R                           
13. version.string R version 3.2.2 (2015-08-14)
nickname       Fire Safety

**Comment by cpsievert** [comment]
You probably have the development version of __ggplot2__ which is currently incompatible with __plotly__. You have 2 options:

1. Use the CRAN version of __ggplot2__: `install.packages(ggplot2)`
2. Be brave and try out our fix for the dev version of __ggplot2__ (this is a work in progress): `devtools::install_github('ropensci/plotly@fix-ggplot2')`

(When __ggplot2__ 1.1 hits CRAN, we'll have the proper fixes for it, and also require it to install __plotly__)

**Comment by neuwirthe** [comment]
Installing the dev version solved the problem. Thanks.

**Comment by cpsievert** [comment]
You can now fix this by grabbing the most recent ggplot2/plotly packages on CRAN (`update.packages()`)
