### ISSUE TITLE
Create subsecond graph within Rshiny

### ISSUE THREAD

**Issue by TonyDIRL** [ropensci/plotly#290]
Hi,

I'd like to replicate the following chart within rshiny:

```
RDData <- xts(runif(100,0,1), order.by=seq(as.POSIXct("2015-04-01 10:00:00"),    as.POSIXct("2015-04-01 10:01:01"), length = 100),tz="GMT"); 
names(RDData)<-c("Data1");
plot_ly(x = index(RDData), y = RDData$Data1,type = "scatter")
```

Note how the x-axis correctly reflects subsecond timestamps.

Now in rshiny 

```
#ui.R
shinyUI(fluidPage(
  titlePanel("SubSecond"),
  mainPanel(
    plotlyOutput("trendPlot")
  )
)) 
#server.R
shinyServer(function(input, output) {
output$trendPlot <- renderPlotly({
    p <- plot_ly(x = index(RDData), y = RDData$Data1,type = "scatter")
    layout(p,autosize=T, yaxis=list(type = "linear",autorange=T,nticks=25), xaxis = list(type =     "date",autorange=T,nticks=25))
  })
})
```

Produces a malformed graph. Could you provide some pointers on the correct layout parameters?

Also tried ggplotly but ggplot itself has issues with rounding to the nearest second.

Thanks

**Comment by cpsievert** [comment]
Does changing `plot_ly(x = index(RDData), y = RDData$Data1, type = "scatter")` to `plot_ly(x = index(RDData), y = as.numeric(RDData$Data1), type = "scatter")` fix it?

**Comment by TonyDIRL** [comment]
Thanks for the response @cpsievert .
However, if I run the following without any layout specifications produces the image below
```
shinyServer(function(input, output) {
output$trendPlot <- renderPlotly({
    p <- plot_ly(x = index(RDData), y = as.numeric(RDData$Data1),type = "scatter")  
  })
})
```
Note, how all the subsecond datapoints are grouped as one at 10:00:00. 

![subsecond](https://cloud.githubusercontent.com/assets/7284709/10844939/d10af462-7f3e-11e5-803c-71c15e1651c9.png)

**Comment by cpsievert** [comment]
We're about to merge #287, which will change the way plotly talks to shiny. Using that branch, this seems to work.

```r
# install the htmlwidgets branch, if need be
devtools::install_github("ropensci/plotly@htmlwidgets")
```

```r
library(shiny)
library(plotly)
library(xts)
x <- seq(
  as.POSIXct("2015-04-01 10:00:00"),    
  as.POSIXct("2015-04-01 10:01:01"), 
  length = 100
)
RDData <- xts(
  runif(100, 0, 1), 
  order.by = x, 
  tz = "GMT"
) 
names(RDData) <- c("Data1")
ui <- bootstrapPage(
  plotlyOutput("trendPlot")
)
server <- function(input, output) {
  output$trendPlot <- renderPlotly({
    p <- plot_ly(x = index(RDData), y = as.numeric(RDData$Data1), type = "scatter")
    p
  })
}
runApp(shinyApp(ui, server))
```

Note that `RDData$Data1` is a numeric matrix (with one column), but **plotly** expects a vector, so you'll need the `as.numeric()`

**Comment by TonyDIRL** [comment]
Hi,

I see 287 has been merged with master and can confirm the XTS index is handled correctly without converting it to character.

Awesome.
