### ISSUE TITLE
Error bars

### ISSUE THREAD

**Issue by jm-contreras** [ropensci/plotly#30]
Ggplot bar graphs and scatter plots that have error bars (i.e., those created with *geom_errorbar*) yield the following error:
```
Error in layer2traces(L, df, misc) : 
  conversion not implemented for geom_errorbar (basic geom_errorbar)
```

**Comment by mkcor** [comment]
Hello @jm-contreras !

Please upgrade your "plotly" package. Basic support of `geom_errorbar` is now provided. Let us know how things go.

Happy plotting!

**Comment by jm-contreras** [comment]
Thanks for the update!

**Comment by chriddyp** [comment]
hey @jm-contreras - just going to close this issue now, if you're still having any issues feel free to re-open (or create a new issue)
