### ISSUE TITLE
ggplotly scale_size_continuous not applying?

### ISSUE THREAD

**Issue by vinhdizzo** [ropensci/plotly#300]
Hi,

I have a plot created from ggplot2 with `size=size_var` in the `aes` and `scale_size_continuous(range = c(5, 25), labels=dollar)`.  However, `ggplotly` doesn't appear to preserve these sizes.  Thoughts?

**Comment by cpsievert** [comment]
Can you please provide a reproducible example?

**Comment by vinhdizzo** [comment]
Sorry, here it is:
```r
library(plotly)
library(scales)
df <- data.frame(x=1:10, y=rep(1:10, each=10), heat=runif(10*10)*100, weight=runif(10*10)*1000000)
g <- ggplot(df, aes(x=x, y=y, col=heat, size=weight)) +
  geom_point()
g_big <- g + scale_size_continuous(range = c(5, 25), labels=dollar)
g ## base
g_big ## blown up
ggplotly(g) ## base
ggplotly(g_big) ## should be blown up but not; looks like above
```

**Comment by cpsievert** [comment]
This doesn't seem to be a problem when using the dev version of ggplot2:

```r
devtools::install_github("hadley/ggplot2")
devtools::install_github("ropensci/plotly@fix-ggplot2")
```

Within the next few weeks, these changes will hit CRAN.

**Comment by vinhdizzo** [comment]
Confirming that the dev versions work.  Thanks.
