### ISSUE TITLE
More vignettes

### ISSUE THREAD

**Issue by cpsievert** [ropensci/plotly#303]
The intro vignette is probably too long. It could be split up into:

(1) Intro
(2) Trace types (providing at least one example of each)
(3) "Special" (scaled) arguments

**Comment by cpsievert** [comment]
More topics we should document:
  - [] Adding annotations (see #170)
  - [] Working with margins

**Comment by DarioS** [comment]
Also, the [vignette on CRAN](https://cran.r-project.org/web/packages/plotly/vignettes/intro.html) has no visible plots, except for one, which is simply a static image to demonstrate `plotly_POST`. I checked with both Internet Explorer and Firefox 44.
