### ISSUE TITLE
ggplot colour legend title is wrong

### ISSUE THREAD

**Issue by jemus42** [ropensci/plotly#306]
Probably related to #159?

Minimal example:

```
library(ggplot2)
library(plotly)

p <- ggplot(data = mtcars, aes(x = wt, y = mpg, colour = as.factor(cyl))) +
  geom_point() +
  labs(x = "Weight", y = "Miles per Gallon", colour = "Cylinders")

ggplotly(p)
```

## ggplot2:

![](http://dump.jemu.name/O1b9B.png)

## ggplotly:

![](http://dump.jemu.name/qrolB.png)

## Edit for clarity:

* `plotly_2.0.3` from GitHub installed minutes ago
*  `ggplot2_1.0.1` from CRAN

**Comment by cpsievert** [comment]
This should be fixed via 6053d9b, please reopen if it isn't.
