### ISSUE TITLE
add geom_hex support

### ISSUE THREAD

**Issue by mikejiang** [ropensci/plotly#307]

**Comment by cpsievert** [comment]
plotlyjs doesn't natively support hexagonal binning, but maybe we could do some sort of hack with markers with symbol="hexagon"?

**Comment by cpsievert** [comment]
Closing in favor of #348

**Comment by maxheld83** [comment]
Browsing through the code, I just realised that this *is* in fact already implemented.
Sorry for being so dense.

```
m <- ggplot2::ggplot(faithful, aes(x = eruptions, y = waiting)) + geom_hex()
plotly::ggplotly(m)
```

Fantastic.

**Comment by cpsievert** [comment]
It is supported via `ggplotly()`, but not *natively* in plotly.js, so you're issue/request is worthwhile!

**Comment by maxheld83** [comment]
oh ok – thanks. I hadn't even thought that was possible that `ggplotly()` could do something that `plotly` couldn't.

**Comment by cpsievert** [comment]
plotly.js doesn't do hexgonal binning, but you can always do it yourself and pass the x/y data representing the hexagons to a scatter trace
