### ISSUE TITLE
embed exported plotly visualization (html) within powerpoint?

### ISSUE THREAD

**Issue by vinhdizzo** [ropensci/plotly#308]
Hi,

I'd like to embed a plotly visualization exported [using](https://github.com/ropensci/plotly/issues/294#issuecomment-154598412) `htmlwidgets::SaveWidget` inside Powerpoint (work requirement).  I'm aware of the plotly [plugin](https://store.office.com/plotly-d3-js-charts-for-powerpoint-and-excel-WA104379485.aspx) for Office, but my visualizations are not hosted on the plotly service due to confidentiality reasons, hence the local save of the html file.

To embed html files, one could use [LiveWeb](http://skp.mvps.org/liveweb.htm) like [this](http://www.mango-solutions.com/wp/2015/02/embedding-r-generated-interactive-html-pages-in-ms-powerpoint/) post, or use utilize the Web Browser object in a macro as [here](http://www.clearlyandsimply.com/clearly_and_simply/2012/05/embed-tableau-visualizations-in-powerpoint.html).

I was able to successfully embed a basic html file, both locally and on the internet.  However, it appears my exported plotly visualization is not rendering using the LiveWeb plugin (or the macro method).

Would anyone happen to know why the visualization is not rendering?  Is it because of javascript?  Is there a way to get it to work?  I know it's probably more appropriate to ask the authors of LiveWeb, but I figure I'd get a better chance from the open source community.  I've also raised a similar [question](https://github.com/ramnathv/htmlwidgets/issues/170) on `htmlwidgets`.  Thank you for your help.

**Comment by vinhdizzo** [comment]
Contacted the LiveWeb author, and to get the plotly visualizations to load, just follow the instructions filed under *"How can I force the browser control to use a specific rendering engine when I don't have access to the server."* on the [FAQ](http://skp.mvps.org/livewebfaq.htm) for IE10 or above.

**Comment by xigrug** [comment]
> 联系LiveWeb作者，并获得要加载的图形可视化，只需按照_“当我无法访问服务器时如何强制浏览器控件使用特定的渲染引擎”中提供的说明进行操作。_在IE10或以上的[常见问题解答](http://skp.mvps.org/livewebfaq.htm)中。

I have the save problem
