### ISSUE TITLE
Suppression of jittered values et al.

### ISSUE THREAD

**Issue by pssguy** [ropensci/plotly#309]
I have a plot where I need to jitter data to show all values
Here is a much simplified version
```
library(ggplot2)
 library(plotly)
 library(dplyr)
 
 df <- data.frame(Goals=c(1,1,4),
jitGoals=c(1.1,0.9,4.2),
Seq=c(1,1,2),
jitSeq=c(0.9,1,2.1),
name=c("A","B","C"))
 
 
 p <-   df %>% 
   ggplot(aes(x=jitGoals,y=jitSeq)) +
   geom_point(aes(text = paste("Name:",name,"<br> Goals:",Goals,"<br> Sequence:",Seq)), size = 4) +
   ylab("Best Scoring Sequence - jittered to show all Players") +
   xlab("Career Goals")
 
 
 ggplotly(p)
```

a) Can I suppress showing the jitGoals/jitSeq values - they just confuse
b) Is there a way to set to "Show closest data on hover' as default
c) Is there a way to substitute click for hover

```
sessionInfo()
dplyr_0.4.3   plotly_2.0.3  ggplot2_1.0.1
```

I have reverted to CRAN version of ggplot but would rather have dev version for other charts
In issue #288 you refer to your fix - but seemed a little flaky at first glance

Do you know when ggplot2 1.1 is likely to be available (if at 1.0.1 now seems like could be ways off)

**Comment by cpsievert** [comment]
It's easiest to do a plot like this with plotly's native syntax:

```r
library(plotly)
plot_ly(mtcars, x = mpg, y = disp, mode = "markers", hoverinfo = "text",
        text = row.names(mtcars)) %>%
  layout(hovermode = "closest")
```

That being said, here is how you can do it with ggplot2 (the new ggplot2 should hit CRAN in a few weeks)

```r
library(plotly)

df <- data.frame(
  Goals = c(1,1,4),
  jitGoals = c(1.1,0.9,4.2),
  Seq = c(1,1,2),
  jitSeq = c(0.9,1,2.1),
  name = c("A","B","C")
)

p <- df %>% 
  ggplot(aes(x = jitGoals,y = jitSeq)) +
  geom_point(aes(text = paste("Name:",name,"<br> Goals:",Goals,"<br> Sequence:",Seq)), size  =  4) +
  ylab("Best Scoring Sequence - jittered to show all Players") +
  xlab("Career Goals")

p2 <- layout(ggplotly(p), hovermode = "closest")

l <- plotly_build(p2)
l$data <- lapply(l$data, function(x) { x$hoverinfo <- "text"; x })
l
```

**Comment by cpsievert** [comment]
> Is there a way to substitute click for hover

I'm not quite sure what you mean, could you clarify?

**Comment by pssguy** [comment]
Thanks for the swift response

Currently, if you hover over a point the relevant text appears. When you hover off the text disappears.
I'm guessing it is not available in the plotly but it would be nice to have option to show text when you actually click on a point - like in ggvis add_tooltip  This can be useful for e.g. captured images

**Comment by chriddyp** [comment]
@pssguy great suggestion! wiring in a custom `click` events is straightforward with the underlying [plotly.js javascript library](https://github.com/plotly/plotly.js), here is an example: https://plot.ly/javascript/click-events/.

**Comment by pssguy** [comment]
@chriddyp Thanks for this.  I'll take a look but straightforward  javascript isn't a phrase that comes easily to me!
