### ISSUE TITLE
Cannot suppress hoverinfo for size 

### ISSUE THREAD

**Issue by Vestaxis** [ropensci/plotly#310]
Hi, 

First off: many thanks for this package. 

I'm adding custom text to the hoverinfo shown in a plotly plot. I'd like to suppress all other data shown. This works fine for x and y values, but not for values for size: 

library(plotly)
plot_ly(mtcars, x = mpg, y = disp, mode = "markers", size = hp, hoverinfo = "text",
        text = row.names(mtcars)) %>%
  layout(hovermode = "closest")

You'll notice that even if I only specified hoverinfo = "text", I still see 'hp (size): value' in the tooltip. 

Any guidance on how to fix this is much appreciated.

**Comment by cpsievert** [comment]
You can always use `plotly_build()` to obtain the actual list sent to plotlyjs

```r
library(plotly)
p <- plot_ly(mtcars, x = mpg, y = disp, mode = "markers", size = hp, 
             hoverinfo = "text", text = row.names(mtcars)) %>%
  layout(hovermode = "closest")
l <- plotly_build(p)
```

You can always modify this list object by hand to override defaults, so this will do the trick:

```r
l$data[[1]]$text <- row.names(mtcars)
l
```

**Comment by Vestaxis** [comment]
Thanks a lot for the suggestion. 

Things unfortunately aren't that easy when I group my plot using color: 

mtcars$cyl <- as.factor(mtcars$cyl)
p <- plot_ly(mtcars, x = mpg, y = disp, mode = "markers", color = cyl, size = hp,
             hoverinfo = "text", text = row.names(mtcars)) %>%
  layout(hovermode = "closest")
l <- plotly_build(p)

l$data is now a list of three for each level of cyl. This start getting tricky because I need to know the list where data corresponding to a certain levels ends up in. I've now built a custom function that checks this based on l$data[[1]]$name but it seems quite vulnerable to changes in the package.
