### ISSUE TITLE
geom_segment doesn't work with factors

### ISSUE THREAD

**Issue by tom-christie** [ropensci/plotly#321]
When I use factors as my y-variable with geom_segment, I get an error.  This works in ggplot:

    library(plotly)
    mtcars$name = rownames(mtcars)
    ggplot(mtcars,aes(x=wt,xend=qsec,y=name,yend=name))+
      geom_segment()

but this:

    ggplotly()

throws this error:

    Error in .subset2(x, i, exact = exact) : subscript out of bounds

with this trace:

    6: (function(x, i, exact) if (is.matrix(i)) as.matrix(x)[[i]] else .subset2(x, 
           i, exact = exact))(x, ..., exact = exact)
    5: `[[.data.frame`(l$data, col.name)
    4: l$data[[col.name]]
    3: layer2traces(L, df, misc)
    2: gg2list(p)
    1: ggplotly()

**Comment by cpsievert** [comment]
Fixed in 9a5714e
