### ISSUE TITLE
scatterplot hover text in unexpected position

### ISSUE THREAD

**Issue by pstoyanov** [ropensci/plotly#322]
[unexpected behavior]
In case there are several points with the same x coordinate, the hover text is placed at and refers to another point (sometimes the lowest, sometimes the highest, or the middle one). This also appears to happen even when the respective point is outside the currently shown region of the figure (i.e. the user has zoomed in).

For me, expected behavior is the hover text to be placed at the point under the mouse cursor.

To reproduce -- easily done in the example on the github front page (or any of the other interactive examples on the plot.ly site), zoom in until there's only one point shown, and hover over it.

Thanks for all your work!

**Comment by cpsievert** [comment]
I think you want `layout(gg, hovermode = "closest")`?

**Comment by pstoyanov** [comment]
Yes, you are absolutely correct. Thank you! 
Maybe this should be the default for scatterplots?

**Comment by cpsievert** [comment]
This is the default is plotlyjs and I think it's generally a good idea to keep consistency with defaults.
