### ISSUE TITLE
Bold Axis Labels

### ISSUE THREAD

**Issue by robertleitner** [ropensci/plotly#324]
Am I just blindfolded, or is ther no way to set the axis tick labels bold? 

Thanks,
Bob

**Comment by cpsievert** [comment]
I don't think there is currently. Feel free to request this over at https://github.com/plotly/plotly.js

**Comment by chriddyp** [comment]
@robertleitner - Actually, `plotly.js` supports a subset of html labels. So, use `<b>bold text</b>`

> Plotly uses a subset of HTML tags to do things like newline (`<br>`), bold (`<b></b>`), italics (`<i></i>`), hyperlinks (`<a href='...'></a>`). Tags `<em>`, `<sup>`, `<sub>` `<span>` are also supported.

Reference: https://plot.ly/r/reference/

**Comment by jjc12** [comment]
@chriddyp Plot.ly for Python uses this as well. Typing `x = '<b>Title</b>'` will bold `x`.

**Comment by Nosferuity** [comment]
I found a workaround today which does not need you to set the tags when generating the tick labels, but setting it after the plot has been generated.
You can just update your ticklabels with a suffix and a prefix which recognizes html tags.

This worked for me:
`fig.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")`

I found this thread when searching for a souloution and wanted to leave my answer somewhere for people to find.

**Comment by nitramwin** [comment]
Great idea with the `tickprefix` and `ticksuffix`. 

> `fig.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")`

**Comment by houssame17** [comment]
> I found a workaround today which does not need you to set the tags when generating the tick labels, but setting it after the plot has been generated. You can just update your ticklabels with a suffix and a prefix which recognizes html tags.
> 
> This worked for me: `fig.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")`
> 
> I found this thread when searching for a souloution and wanted to leave my answer somewhere for people to find.

This worked for me too. Thank you for sharing.
