### ISSUE TITLE
multiline hover text?

### ISSUE THREAD

**Issue by zippeurfou** [ropensci/plotly#326]
Would that be possible to have the text on hover being multiline?
```
 library(plotly)
 set.seed(100)
 d <- diamonds[sample(nrow(diamonds), 1000), ]
 dd<- plot_ly(d, x = carat, y = price, text = paste("Clarity: ", clarity,"\n lol"),
        mode = "markers", color = carat, size = carat)
 h<- plotly_build(dd)
h
```
will generate this: https://infinit.io/_/3cJcaNd

As you can see "lol" is on the same line.

**Comment by zippeurfou** [comment]
Closing it as actually <br> do the job even if it is really not obvious.

**Comment by cpsievert** [comment]
https://plot.ly/r/choropleth-maps/ has an example of this

**Comment by zippeurfou** [comment]
Thanks for the help. As an enhancement it could be cool to have an option where you just input "all" and it get all the column with the same formating as the example
