### ISSUE TITLE
Add column/row scaling to plotly heatmap.

### ISSUE THREAD

**Issue by ziyadsaeed** [ropensci/plotly#330]
d3heatmap package has column or row scaling as options that allows each column or row to have the same color scaling. plotly uses the entire matrix for the color scaling.

**Comment by chriddyp** [comment]
this is out of the scope of the `R` library, unless we plotted each row as a separate subplot with it's own colorscale. Instead, open an issue in the [plot.js](https://github.com/plotly/plotly.js) repository (the JS library that this package uses)
