### ISSUE TITLE
Add deleteTraces and moveTraces to the R api

### ISSUE THREAD

**Issue by ziyadsaeed** [ropensci/plotly#331]
The javascript plotly.js has deleteTraces and moveTraces function. Please add these function to the r api

**Comment by cpsievert** [comment]
Do you have a use case for having this functionality in R? I don't think many people want/need this functionality from R, so I'm not convinced we need an official interface, but you can always build/modify the underlying list representation, for example:

```r
f <- get_figure("cpsievert", “600”)
l <- plotly_build(f)
# reverse the order of the traces
l$data <- rev(l$data)
# view it
l
# remove the 2nd trace
l$data[[2]] <- NULL
l
```

**Comment by ziyadsaeed** [comment]
In shiny applications the user decides which variables to plot by selecting and deselecting them. Deselecting a variable should effectively delete the trace from the plot rather than re-render it. 
Looks like you have a good alternative to NULL the data to have it removed.

**Comment by ucg8j** [comment]
I have a [use case and a reproducible example that I posted to StackOverflow](http://stackoverflow.com/questions/34282971/how-to-remove-change-the-label-in-a-plotly-geom-vline-in-r) yesterday. As detailed on the SO post, I don't necessarily want to remove the trace.... just the erroneous Y-values. Also, it would be great if the [documentation of the example](https://plot.ly/ggplot2/histograms/#adding-lines-to-histograms-in-r) was updated to include how to suppress elements of a trace, as the example clearly shows erroneous numbers too.

**Comment by cpsievert** [comment]
Especially now that we have `htmlwidgets::onRender()`, I don't think it's worthwhile to reinvent the plotly.js API in R. Here is [an example](https://github.com/ropensci/plotly/blob/master/inst/examples/onRenderHover/index.Rmd) of using `onRender`

**Comment by ziyadsaeed** [comment]
How does this help with adding and deleting traces?

**Comment by daattali** [comment]
I also came across a usecase for removing a trace. I want to be able to remove a line from an existing plot. My current solution is to re-render the plot without the line, but it'd be nice if I could `removeTrace()`. 

 It's entirely possible there's a better way to do what I want to

**Comment by daattali** [comment]
I found out I can do what I wanted with `plotlyProxyInvoke("deleteTraces", ...)`, though it still feels that having an R API for it would be nice
