### ISSUE TITLE
set the R config variable `plotly_domain` inside JS as `window.PLOTLY_ENV.BASE_URL`

### ISSUE THREAD

**Issue by chriddyp** [ropensci/plotly#333]
In `plotly.js`, we use `window.PLOTLY_ENV.BASE_URL` (https://github.com/plotly/plotly.js/blob/master/src/plots/plots.js#L370) to determine which cloud to send the graph to. If the user set `plotly_domain` inside their R `ENV`, we need to set that in the JS `window.PLOTLY_ENV.BASE_URL` so that charts don't get sent outside the network.

**Comment by cpsievert** [comment]
Ah, good catch. And just out of curiosity, this would only apply if someone makes the plot locally, then clicks the "save and edit in cloud" in the modebar, right?

**Comment by chriddyp** [comment]
@cpsievert yup, that's right.
