### ISSUE TITLE
(Request for Guidance / Disposition) Minimum System Requirements:  "hello world" examples failing under R API

### ISSUE THREAD

**Issue by bamcdougall** [ropensci/plotly#336]
Hi Plotly Team,

I am unable to execute successfully several "hello world" examples provided on your main public website that implement the R API.  Perhaps the solution is documenting minimum system requirements near these instructions. (I wasn't able to locate a statement of minimum system requirements. I did update all the libraries associated with my version of R, which is shown in the following paragraph.)

My system info
##                  R x64 3.1.2, git scm 1.9.5

These are the "hello world" instructions / examples that I used:
    devtools::install_github("ropensci/plotly")
    library(plotly)
    library(ggplot2)
    p <- ggplot(data = d, aes(x = carat, y = price)) +
    geom_point(aes(text = paste("Clarity:", clarity)), size = 4) +
    geom_smooth(aes(colour = cut, fill = cut)) + facet_wrap(~ cut)
    p ## generates pretty ggplot!
    (gg <- ggplotly(p)) ## nothing...big donutz. My PlotViewer empties on execution of this command.

The simple example provided as part of https://plot.ly/r/getting-started/ also does not work on my installation. (NOTE:  there are no error messages.)

I did peruse RStudio site and several other usual suspect resources trying to determine a solution, but was unsuccessful.

Thank you for any guidance that you may be able to provide.

Best regards.

Brendan McDougall

**Comment by cpsievert** [comment]
Please include error messages as well as the output of `devtools::session_info()`

**Comment by bamcdougall** [comment]
Hi Carson,
e 
Surprisingly, there were no error messages in the output from 

Aside from the list of installed packages (version, date, source), there was only the system info, which was:
Session info ---------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.1.2 (2014-10-31)
 system   x86_64, mingw32             
 ui       RStudio (0.98.1102)         
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Los_Angeles         
 date     2015-12-10

**Comment by cpsievert** [comment]
The version of ggplot2 that you have is important, but now that I think of it, you probably need to just update RStudio.

**Comment by bamcdougall** [comment]
Thanks Carson. You are probably correct. (I did update all my libraries before installing the new plotly library, so I suspect that the issue is not ggplot2, which session_info() reports is version 1.0.1 from 3/17/2015)

**Comment by cpsievert** [comment]
Your welcome, please let us know if that fixes it.
