### ISSUE TITLE
Specify local filename

### ISSUE THREAD

**Issue by joshmyzie2** [ropensci/plotly#338]
Apologies in advance because I'm probably just not looking in the right place, but I can't find any option to specify the filename where a local plot is saved using `plot_ly`.  The only relevant option seems to be used only when uploading to the plotly server.

My use case is that I'm creating plots on a remote server, and I want to be able to have a browser open on my local machine pointing to a single file that will display my plots.

**Comment by cpsievert** [comment]
I think you're looking for this? https://github.com/ropensci/plotly/issues/294

**Comment by joshmyzie2** [comment]
@cpsievert Yes, indeed.
