### ISSUE TITLE
Plotly does not show Chinese properly

### ISSUE THREAD

**Issue by LennyValentino** [ropensci/plotly#343]
Plotly does not show Chinese properly, seems like an encoding problem. Can anyone help? Thanks in advance!!

**Comment by cpsievert** [comment]
Please provide a [reproducible example](http://adv-r.had.co.nz/Reproducibility.html)

**Comment by cpsievert** [comment]
Appears to be working:

```r
plot_ly(x = 1, y = 1, text = "学生", mode = "text")
```

Please reopen if you still have problems
