### ISSUE TITLE
Boxplot legends

### ISSUE THREAD

**Issue by cpsievert** [ropensci/plotly#345]
I'm not convinced we can/should provide legends for boxplots (see also #230). As far as I know, you can't draw multiple boxes in a single trace, so there must be a legend entry for unique x, making the legend redundant. For example, we could provide a legend for something like this:

```r
library(plotly)
dat <- data.frame(
  cond = factor(rep(c("A", "B", "C", "D"), each = 200)), 
  col = factor(rep(c("C1", "C2"), each = 400)), 
  rating = c(rnorm(200), rnorm(200, mean = .8), rnorm(200, mean = .4), rnorm(200, mean = .2))
)
ggplot(dat, aes(x=cond, y=rating)) + 
  geom_boxplot(aes(fill=cond))
```

![rplot01](https://cloud.githubusercontent.com/assets/1365941/11764664/5af2185e-a0ff-11e5-9a38-191e01e5f54b.png)

It'd be more useful to have a legend when color/fill is nested in x, but I don't think we could do something like this in plotlyjs, right @chriddyp?

```r
ggplot(dat, aes(x=cond, y=rating)) + 
  geom_boxplot(aes(fill=col))
```

![rplot](https://cloud.githubusercontent.com/assets/1365941/11764661/46480c56-a0ff-11e5-8890-ee050d5a4347.png)

**Comment by cpsievert** [comment]
For now [we'll go ahead and show a legend for each x value](http://cpsievert.github.io/plotly-test-table/0bcd5bf/boxplot-fillcolor/)

**Comment by chriddyp** [comment]
hey @cpsievert - actually you *can*. Here's an example: https://plot.ly/~patsy.cline/35.embed. You have to include an `x` value for every single `y` value, i.e.:

```
{
    "x": [1, 1, 1]
    "y": [2, 1, 5]
}
```

Or

hey @cpsievert - actually you *can*. Here's an example: https://plot.ly/~patsy.cline/35.embed. You have to include an `x` value for every single `y` value, i.e.:

```
{
    "x": [1, 1, 1, 2, 2, 2],
    "y": [2, 1, 5, 3, 1, 5]
}
```
