### ISSUE TITLE
Modifying marker size

### ISSUE THREAD

**Issue by pssguy** [ropensci/plotly#349]
Not sure if this is an issue or lack of understanding how to use reference but the following code

```
plot_ly(df, x = plGameOrder, y = mins,
        mode='markers',
        color=Team,
        #size=points,
        hoverinfo = "text",
        text = paste(Team," v ",Opponents,
                     "<br>",gameDate,
                     "<br>On: ",on,
                     "<br>Off: ",off,
                     "<br>Goals ",Goals,
                     "<br>Assists ",Assists)
        ) %>%
  layout(hovermode = "closest",
         xaxis=list(title="Games Played"),
         yaxis=list(title="Minutes Played")
         )
```

Produces a great plot with hoverInfo as required

However, If I remove the comment from the size the chart point size is related to the value points(Goals+Assists) but the actual diameters are far larger than desired

Also the hoverinfo has an added, unwanted, line at the bottom of the text  e.g.  "points (size): 2"

**Comment by cpsievert** [comment]
You can use the `marker.sizeref` property to modify the percentage of the plotting area that the markers occupy:

```r
plot_ly(mtcars, x = mpg, y = disp, mode = "markers", size = cyl, marker = list(sizeref = 5))
plot_ly(mtcars, x = mpg, y = disp, mode = "markers", size = cyl, marker = list(sizeref = 10))
```

There currently isn't a way to remove the additional size tooltip info, but IMO, you shouldn't remove it (otherwise it isn't clear what the size scale/variable is)

**Comment by pssguy** [comment]
@cpsievert Thanks for swift reply. Kinda counter-intuitive that you get smaller size point size with larger sizeref ? 
In my case, the point size is related to an addition of two variables, Goals and Assists. I want to have those shown in tooltip but not the combination. I can explain textually on chart that point size relates to this combo. If you (or plotly developers) are able to offer its removal as an option it would be highly desirable. It's pretty distracting , as is

**Comment by Vestaxis** [comment]
See #310.
