### ISSUE TITLE
Conversion not implemented for geom_map (basic geom_map)

### ISSUE THREAD

**Issue by tarrade** [ropensci/plotly#352]
Hi there,

when I try to use ggplot+geom_map+ggplotly I get the following message :

"Warning in layer2traces(L, df, misc) :
  Conversion not implemented for geom_map (basic geom_map), ignoring. Please open an issue with your example code at https://github.com/ropensci/plotly/issues"

My code is the folowing (display value in the map of the US):

        g <- ggplot(dataframe, aes(map_id = STATE))
        g <- g + geom_map(aes_string(fill = fill), map = states_map, colour='black')
        g <- g + expand_limits(x = states_map$long, y = states_map$lat)
        g <- g + theme_bw()
        g <- g + theme(legend.position = "bottom",
                      axis.ticks = element_blank(), 
                      axis.title = element_blank(), 
                      axis.text =  element_blank())
        g <- g + scale_fill_gradient(low="white", high="blue", name="Damage to the economy of the United States in (billion of USD)") 
        g <- g + guides(fill = guide_colorbar(barwidth = 10, barheight = .5)) 
        g <- g + geom_text(data=cnames, aes(long, lat, label = region,  
                                           angle=angle, map_id =NULL), size=2.5)

        ggplotly(g)

I get the folloing map:
<img width="1417" alt="screen shot 2015-12-15 at 11 30 33" src="https://cloud.githubusercontent.com/assets/12021701/11808286/d6e606a6-a31f-11e5-8c51-82fdf87ea232.png">

instead of something like that without ggploty
<img width="734" alt="screen shot 2015-12-15 at 11 36 30" src="https://cloud.githubusercontent.com/assets/12021701/11808340/2b3e6f90-a320-11e5-9de8-bdfeae0ebec5.png">

Thanks
Cheers

sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] plotly_2.0.10   mapproj_1.2-4   maps_3.0.1      dplyr_0.4.3     Rmisc_1.5       plyr_1.8.3      lattice_0.20-33
[8] ggplot2_1.0.1   shiny_0.12.2   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.2      viridis_0.3.1    base64enc_0.1-3  bitops_1.0-6     tools_3.2.2      testthat_0.11.0 
 [7] digest_0.6.8     jsonlite_0.9.19  memoise_0.2.1    gtable_0.1.2     DBI_0.3.1        swirl_2.2.21    
[13] yaml_2.1.13      parallel_3.2.2   proto_0.3-10     gridExtra_2.0.0  httr_1.0.0       stringr_1.0.0   
[19] htmlwidgets_0.5  grid_3.2.2       R6_2.1.1         reshape2_1.4.1   magrittr_1.5     scales_0.3.0    
[25] htmltools_0.2.6  MASS_7.3-45      assertthat_0.1   mime_0.4         xtable_1.8-0     colorspace_1.2-6
[31] httpuv_1.3.3     labeling_0.3     stringi_1.0-1    lazyeval_0.1.10  RCurl_1.95-4.7   munsell_0.4.2   
[37] crayon_1.3.1   
Fabien

**Comment by cpsievert** [comment]
At least for now, you'll have to use `geom_polygon()` instead of `geom_map()` if you want a map via ggplot2. That being said, things will be much more efficient if you instead use our built-in support for choropleths -- https://plot.ly/r/choropleth-maps/

And here is a basic example similar to the one you've provided:

```r
library(plotly)

# specify some map projection/options
g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  lakecolor = toRGB('white')
)

plot_ly(z = state.area, text = state.name, locations = state.abb,
        type = 'choropleth', locationmode = 'USA-states') %>%
  layout(geo = g)
```

![screen shot 2015-12-21 at 12 55 54 pm](https://cloud.githubusercontent.com/assets/1365941/11938702/3ab18270-a7e2-11e5-9b09-5049e6c37dac.png)

**Comment by cpsievert** [comment]
I'll keep a note of this in #348

**Comment by tarrade** [comment]
Hi there,

Thanks for the comments and I will try  choropleths

Thanks again
Cheers
Fabien
