### ISSUE TITLE
plot_ly colors argument

### ISSUE THREAD

**Issue by jkraut** [ropensci/plotly#358]
I may be missing something in the documentation, but the color argument to the `plot_ly` call suggests you can pass "a vector of colors to interpolate in hexadecimal "#RRGGBB" format" to the function.  This does not work as intended.  The code below renders a plot with all bars the same color.  If I don't subset the my.colors vector and pass the entire vector to the function call, it renders 5 different colors, but not the first 5 of the vector nor the last 5 of the vector.  I am not sure how the colors are being interpreted and passed to the attributes.

```
library(plotly)
library(dplyr)
my.colors <- c("#fe8268", "#81e8fe", "#fed681", "#81fed6", "#fe81a9", "#ffe2cd", "#cff6ff",
               "#fffbcd", "#e7fff7", "#ffe7ee")

temp.df <- data.frame(Category = LETTERS[1:5], Value = 1:5, stringsAsFactors = F)

temp.df %>%
    arrange(desc(Value)) %>%
  plot_ly(x = Category, y = Value, type = "bar", color = Category,
          colors = my.colors[1:5]) %>%
    layout(title = "Color argument does not work", 
           yaxis = list(title =  'Number'))```

**Comment by cpsievert** [comment]
Thanks!
