### ISSUE TITLE
Double interactive data entry and legend settings

### ISSUE THREAD

**Issue by fwang2** [ropensci/plotly#36]
hi all,

I am not sure if this is a bug or just my part of doing: I am converting a basic line graph with multiple lines - a data frame column named "stripe" is mapped to both "shape" and "color". The R output looks like:

![screen shot 2014-05-21 at 9 53 38 pm](https://cloud.githubusercontent.com/assets/67058/3049013/0a0aac10-e154-11e3-8c49-fc68737bc4d7.png)

but the `py$gplotly()` output looks like:
https://plot.ly/~fwang2/8/mpi-io-wide-stripe-read-scaling/

There are two major issues:

1. Legends are messed up
2. Move mouse to data point, it shows double entries.

Did I miss something here?

TIA,

Feiyi

**Comment by mkcor** [comment]
@fwang2 @msund Let me close this issue and refer to #159 for any update.
