### ISSUE TITLE
plotly linetype missing

### ISSUE THREAD

**Issue by zippeurfou** [ropensci/plotly#360]
from this file https://github.com/ropensci/plotly/blob/master/tests/testthat/test-ggplot-linetype.R
and this one http://sape.inf.usi.ch/quick-reference/ggplot2/linetype

You can see that some of them are missing such as F1 that is really handy

**Comment by cpsievert** [comment]
Closing since plotly.js currently supports these line types:

```r
> plotly:::Schema$traces$scatter$attributes$line$dash$values
[1] "solid"       "dot"         "dash"        "longdash"    "dashdot"    
[6] "longdashdot"
```

Feel free to request more linetypes here https://github.com/plotly/plotly.js
