### ISSUE TITLE
plotly_build() + changes to plotly object (e.g. hoverinfo) + config() overrides changes

### ISSUE THREAD

**Issue by ucg8j** [ropensci/plotly#361]
It's possible there is another way of doing this, however it appears there is an issue in configuring a custom plot resulting from e.g. p <- plotly_build()

E.g.
    #create plotly object
    p <- plotly_build(gg)

    #append additional options to plot object
    p$data[[1]]$hoverinfo <- "name+x" #hover options for 'average'
    p$data[[2]]$hoverinfo <- "name+x" #hover options for 'median'

    #display plot
    plotly_build(p)
    config(displayModeBar = F, showLink = F) 

I have posted a [full reproducible example on stackoverflow](http://stackoverflow.com/questions/34328259/r-plotly-how-to-use-config-in-conjunction-with-plotly-build).

**Comment by cpsievert** [comment]
The accepted answer provides the suggestion I would have made.
