### ISSUE TITLE
doubleClick to reset graph not working when type = "scattergl"

### ISSUE THREAD

**Issue by jamaz1** [ropensci/plotly#363]
I'm running on Rstudio and encountered a problem when I used "scattergl" as plot type. I can not reset or autoscale the plot by doubleClicking on the graph.

Thus,
plot_ly(df, y = value, group = variable, <b>type = "scattergl"</b>, mode = "lines+markers") %>% layout(hovermode="closest")
breaks the double-clicking feature.<br>
Even if I use
<b>config(doubleClick = "reset")</B> or <b>config(doubleClick = "autosize")</b> (or "reset+autosize" for that matter)
it doesn't work.

**Comment by cpsievert** [comment]
This is a known limitation of 2d WebGL traces in plotly.js (see last bullet of [this comment](https://github.com/plotly/plotly.js/issues/130#issue-122750686)). Please subscribe to that issue to track its progress.
