### ISSUE TITLE
How to create aLine and Scatter plot combination

### ISSUE THREAD

**Issue by pssguy** [ropensci/plotly#369]
I cannot follow from the [examples](https://plot.ly/r/line-and-scatter/) how to combine two plots using add_trace

```
plot_ly(df, x = a, y = b, mode = "markers", color = c)
plot_ly(subset(df,d=1), x = a, y = b, mode = "line")
```
The plots work fine individually

**Comment by cpsievert** [comment]
I'm not sure I understand the question/problem. Also note the new contributing guidelines https://github.com/ropensci/plotly/blob/master/CONTRIBUTING.md#opening-issues

**Comment by pssguy** [comment]
Thanks for highlighting new guidelines.

 I have posted an example on [StackOverflow](http://stackoverflow.com/questions/34444906/how-can-i-combine-a-line-and-scatter-on-same-plotly-chart)
