### ISSUE TITLE
Shapes are always on top (foreground)

### ISSUE THREAD

**Issue by zerweck** [ropensci/plotly#370]
When one adds a trace to an existing plot, it will be drawn on top of earlier defined traces. However, when one adds a shape, it will always be on top of everything else. Example:
```R
library(plotly)
p <- plot_ly(economics, x = date, y = uempmed, name = "unemployment",line=list(color="yellow"))

p <- layout(p, title = 'Highlighting with Rectangles', 
            shapes = list(
              list(type = "rect", 
                   fillcolor = "blue", line = list(color = "blue"), opacity = 0.5, 
                   x0 = "1980-01-01", x1 = "1985-01-01", xref = "x", 
                   y0 = 4, y1 = 12.5, yref = "y"))) 

p # Shapes are in front of the line
p <- add_trace(economics, x = date, y = uempmed, name = "unemployment",line=list(color="white"))
p # Shapes are still in front of the line

```

Is this intended or unwanted behaviour? 

Using plotly_2.0.18.

**Comment by cpsievert** [comment]
Unfortunately [plotly.js](https://github.com/plotly/plotly.js) doesn't currently support drawing traces on top of shapes, but you're welcome to file a feature request! https://github.com/plotly/plotly.js/issues/new
