### ISSUE TITLE
Turn off when turning off a group geom_smooth

### ISSUE THREAD

**Issue by talgalili** [ropensci/plotly#377]
When creating a scatter plot with an overlay of geom_smooth, we can turn off the points of a group, but the geom_smooth of the line remains.

Example:

```r
library(ggplot2)
library(plotly)

p <- ggplot(iris, aes(x = Sepal.Length, y = Petal.Length, color = Species)) + 
  geom_point() + 
  geom_smooth(method = lm)

ggplotly(p)
```

Example: virginica was turned off but the blue line was not removed

![image](https://cloud.githubusercontent.com/assets/976006/12031807/99f4a5c2-ae19-11e5-81ed-b43940d502ba.png)

**Comment by cpsievert** [comment]
I don't think it is possible to turn off both the points and lines from a single legend entry in plotlyjs. So the question is, do we want to provide another legend for the lines? I'm not sure the extra confusion for having an extra legend would be worth it.

**Comment by talgalili** [comment]
Just to update, the new ggplotly now shows a legend for both the point and the line, but it cannot be turned off individually. Also, when turning it off, the shaded line (the CI line), is still present.

![image](https://cloud.githubusercontent.com/assets/976006/13592748/e0e9c7bc-e4fd-11e5-9822-14aeba6e6838.png)

**Comment by cpsievert** [comment]
Im pretty sure bb8c17482bd957e9f18644d1bef478384181370c solves this problem

**Comment by talgalili** [comment]
Just to confirm that this issue is now resolved:

![image](https://cloud.githubusercontent.com/assets/976006/13847804/a9f00b48-ec57-11e5-9d9e-5ccdb5021f6a.png)
