### ISSUE TITLE
Redundant legend entries in facet_*()

### ISSUE THREAD

**Issue by talgalili** [ropensci/plotly#378]
Currently, using facets for scatterplot matrix, combined with subgroup colors, produces a list of groups labels for each facet, making the graph un readable. Here is how it looks:

![image](https://cloud.githubusercontent.com/assets/976006/12031947/71eadb30-ae1b-11e5-955d-8751bfbc8895.png)

Instead of looking like this (in ggplot2):

![image](https://cloud.githubusercontent.com/assets/976006/12031970/b52d4fea-ae1b-11e5-99c4-c0c20393e13e.png)

Here is the code to reproduce:

```r  
  # https://gastonsanchez.wordpress.com/2012/08/27/scatterplot-matrices-with-ggplot/
  # another option
  makePairs <- function(data) 
  {
    grid <- expand.grid(x = 1:ncol(data), y = 1:ncol(data))
    grid <- subset(grid, x != y)
    all <- do.call("rbind", lapply(1:nrow(grid), function(i) {
      xcol <- grid[i, "x"]
      ycol <- grid[i, "y"]
      data.frame(xvar = names(data)[ycol], yvar = names(data)[xcol], 
                 x = data[, xcol], y = data[, ycol], data)
    }))
    all$xvar <- factor(all$xvar, levels = names(data))
    all$yvar <- factor(all$yvar, levels = names(data))
    densities <- do.call("rbind", lapply(1:ncol(data), function(i) {
      data.frame(xvar = names(data)[i], yvar = names(data)[i], x = data[, i])
    }))
    list(all=all, densities=densities)
  }
  
  # expand iris data frame for pairs plot
  gg1 = makePairs(iris[,-5])
  
  # new data frame mega iris
  mega_iris = data.frame(gg1$all, Species=rep(iris$Species, length=nrow(gg1$all)))
  
  library(ggplot2)
  # pairs plot
  p <- ggplot(mega_iris, aes_string(x = "x", y = "y")) + 
    facet_grid(xvar ~ yvar, scales = "free") + 
    geom_point(aes(colour=Species), na.rm = TRUE, alpha=0.8) + # geom_smooth(method = lm) + 
    stat_density(aes(x = x, y = ..scaled.. * diff(range(x)) + min(x)), 
                 data = gg1$densities, position = "identity", 
                 colour = "grey20", geom = "line")
 
  library(plotly)
  ggplotly(p)
 
```

**Comment by cpsievert** [comment]
A more minimal example of the same problem:

```r
library(plotly)
g <- ggplot(mtcars, aes(x = mpg, y = disp, color = factor(cyl))) + geom_point() + facet_wrap(~vs)
ggplotly(g)
```

**Comment by cpsievert** [comment]
This should be fixed in f1900cc3cd464408a60ffadfe3e95460747430e0. Let us know if you still have problems.

**Comment by talgalili** [comment]
In the minimal example the issue is resolved, but in the example I originally gave the issue still remains:

![image](https://cloud.githubusercontent.com/assets/976006/13847758/5df83e86-ec57-11e5-8825-b6ae8159ca80.png)

**Comment by beaulucas** [comment]
I have debugged this issue a bit. It appears when you specify a scale_color|fill_ value without declaring the relevant color|fill|etc in any aesthetics, the duplicate legends per facet appear.

These work:

```
cars_plot <- ggplot(mtcars, aes(x = mpg, y = disp, color = factor(cyl))) +
  geom_point() + 
  facet_wrap(~vs)
cars_plot
ggplotly(cars_plot)
```

Both produce this:

![screen shot 2017-12-07 at 1 27 08 pm](https://user-images.githubusercontent.com/13844396/33739558-5c0cd078-db52-11e7-9e46-bd5a5c5a87ad.png)


This doesn't work:

```
cars_plot <- ggplot(mtcars, aes(x = mpg, y = disp, color = factor(cyl), fill = factor(cyl))) +
  geom_point() + 
  scale_fill_brewer() +
  facet_wrap(~vs)
cars_plot
ggplotly(cars_plot)
```

Take out the fill in the aes mapping now, but keep the scale_fill_brewer() call. This is useless code as there is no fill aesthetic, , but it breaks the plotly legend.

![screen shot 2017-12-07 at 1 26 08 pm](https://user-images.githubusercontent.com/13844396/33739503-33230a4c-db52-11e7-9640-5261fc65e568.png)
