### ISSUE TITLE
Inaccurate data with ggplotly, facet and geom_bar

### ISSUE THREAD

**Issue by vancelopez** [ropensci/plotly#379]
dia = ggplot(diamonds[diamonds$cut %in% c("Fair", "Good"),], aes(x = cut)) + 
      geom_bar(aes(stat = "identity", fill = cut)) + 
      facet_wrap(~color, nrow=1)
    dia

![image](https://cloud.githubusercontent.com/assets/15697325/12038426/dc1db5fe-ae0c-11e5-9a42-af5b0629ad69.png)

    ggplotly(dia)
![image](https://cloud.githubusercontent.com/assets/15697325/12038571/28cd0958-ae0e-11e5-9c37-b9e1025c05c7.png)

    devtools::session_info()
    Session info --------------------------
    setting  value                       
    version  R version 3.2.0 (2015-04-16)
    system   x86_64, mingw32             
    ui       RStudio (0.99.489)          
    language (EN)                        
    collate  English_United States.1252  
    tz       America/Los_Angeles         
    date     2015-12-29
    Packages ------------------------------
    package     * version date       source        
    assertthat    0.1     2013-12-06 CRAN (R 3.2.0)
    base64enc     0.1-3   2015-07-28 CRAN (R 3.2.2)
    colorspace    1.2-6   2015-03-11 CRAN (R 3.2.0)
    DBI           0.3.1   2014-09-24 CRAN (R 3.2.0)
    devtools      1.9.1   2015-09-11 CRAN (R 3.2.2)
    digest        0.6.8   2014-12-31 CRAN (R 3.2.0)
    dplyr       * 0.4.3   2015-09-01 CRAN (R 3.2.2)
    ggplot2     * 2.0.0   2015-12-18 CRAN (R 3.2.3)
    gridExtra     2.0.0   2015-07-14 CRAN (R 3.2.2)
    gtable        0.1.2   2012-12-05 CRAN (R 3.2.0)
    htmltools     0.2.6   2014-09-08 CRAN (R 3.2.1)
    htmlwidgets   0.5     2015-06-21 CRAN (R 3.2.1)
    httr          1.0.0   2015-06-25 CRAN (R 3.2.2)
    jsonlite      0.9.19  2015-11-28 CRAN (R 3.2.2)
    labeling      0.3     2014-08-23 CRAN (R 3.2.0)
    lazyeval      0.1.10  2015-01-02 CRAN (R 3.2.0)
    magrittr      1.5     2014-11-22 CRAN (R 3.2.0)
    memoise       0.2.1   2014-04-22 CRAN (R 3.2.2)
    munsell       0.4.2   2013-07-11 CRAN (R 3.2.0)
    plotly      * 2.0.16  2015-12-20 CRAN (R 3.2.3)
    plyr          1.8.3   2015-06-12 CRAN (R 3.2.0)
    R6            2.1.1   2015-08-19 CRAN (R 3.2.2)
    Rcpp          0.12.2  2015-11-15 CRAN (R 3.2.2)
    scales        0.3.0   2015-08-25 CRAN (R 3.2.2)
    stringi       1.0-1   2015-10-22 CRAN (R 3.2.2)
    stringr       1.0.0   2015-04-30 CRAN (R 3.2.0)
    viridis       0.3.1   2015-10-11 CRAN (R 3.2.2)
    yaml          2.1.13  2014-06-12 CRAN (R 3.2.1)

**Comment by cpsievert** [comment]
This should be fixed in f1900cc3cd464408a60ffadfe3e95460747430e0. Let us know if you still have problems.
