### ISSUE TITLE
ggplot and alpha not replicated in ggplotly

### ISSUE THREAD

**Issue by federicou** [ropensci/plotly#386]
It seems that even a simple plot (ggplot) cannot be converted.

gg <- ggplot(mtcars,aes(cyl,wt)) + geom_point(aes(size=gear,alpha=cyl)) + scale_size(range=c(5,12))
ggplotly(gg)

As you can see the result is pretty different. No way to display a proper legend (with size scales and opacity scales).

**Comment by cpsievert** [comment]
Thanks!

**Comment by talgalili** [comment]
Looks great, thank you.

**Comment by federicou** [comment]
Thanks!
