### ISSUE TITLE
Opacity as attribute linked to a continuous variable

### ISSUE THREAD

**Issue by federicou** [ropensci/plotly#389]
Trying to reproduce the following chart with plot_ly function in R 

gg <- ggplot(mtcars,aes(cyl,wt)) + geom_point(aes(size=gear,alpha=cyl)) + scale_size(range=c(5,12))
ggplotly(gg)

I've used the following command:

plot_ly(data = mtcars, x = cyl, y = wt, size = gear, opacity = cyl, type = "scatter", mode = "markers")

Unfortunately the opacity of the markers is always the same while should vary accordingly to the values of the variable selected (cyl)

**Comment by pssguy** [comment]
I had a somewhat similar issue answered here
http://stackoverflow.com/questions/34683630/how-can-i-vary-opacity-in-a-plotly-r-chart

It might help

**Comment by federicou** [comment]
Actually I was looking for something more integrated in the library.
It is clear that adding a variable with the proper (from 0 to 1) values of opacity will solve the issue.
Another solutions is to write the proper values of the markers after having normalized the values of the variable but still it is not the right solution for the library but maybe a workaround.
BTW the latter option is not working in 3d scatter since in that case you need to use RGBA instead of opacity (for performances reasons).

**Comment by cpsievert** [comment]
`opacity` isn't (yet) an official argument to `plot_ly()`, so no special scaling/handling is applied. You can check that by looking at the data sent to plotlyjs:

```r
p <- plot_ly(mtcars, x = wt, y = mpg, opacity = hp, mode = "markers")
str(plotly_build(p)$data[[1]])
#> List of 6
#> $ type   : chr "scatter"
#> $ inherit: logi FALSE
#> $ x      : num [1:32] 2.62 2.88 2.32 3.21 3.44 ...
#> $ y      : num [1:32] 21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
#> $ opacity: num [1:32] 110 110 93 110 175 105 245 62 95 123 ...
#> $ mode   : chr "markers"
```

If you look at [the reference](https://plot.ly/r/reference/#scatter-marker-opacity), opacity is a marker property, and accepts values between 0 and 1, so you could do the structuring/scaling yourself:

```r
mtcars$disp <- scales::rescale(mtcars$disp)
plot_ly(mtcars, x = wt, y = mpg, marker = list(opacity = hp), type="scattergl", mode = "markers")
```

Notice that I'm also using a scattergl trace here. For some reason, the default scatter trace doesn't appear to support an array of values for opacity, but maybe I'm wrong, @etpinard is that true? If so, would it be possible to add support?

**Comment by cpsievert** [comment]
The new `alpha` argument introduced in version 4.0 makes it easy to apply alpha transparency to the `color` argument

**Comment by federicou** [comment]
Do you have an example for this new feature?

**Comment by cpsievert** [comment]
`plot_ly(x = rnorm(1e4), y = rnorm(1e4), alpha = 0.05) %>% toWebGL()`

**Comment by iparperspective** [comment]
I am trying to get a continuous transparency according to the same continuous variable that sets the color. none of the proposed code above works for me and, in fact, I am getting very strange results since the colorbar and marker's colors do not match + transparency seems the same for all colors.

plot_ly(x = rnorm(100), y = rnorm(100), z = rnorm(100), 
        color = rbeta(100,shape1=1,shape2=1),alpha=.2,
        type = "scatter3d", mode= "markers",
        colors=colorRamp(c("blue","red")))

I'd like to get low transparency at high color values and vice versa. Is this possible in the currrent version of plot_ly?

setting opacity instead of alpha seems to fix the colouring vs colorbar but not the transparency issue.

plot_ly(x = rnorm(100), y = rnorm(100), z = rnorm(100), 
        color = rbeta(100,shape1=1,shape2=1),opacity=.2,
        type = "scatter3d", mode= "markers",
        colors=colorRamp(c("blue","red")))
