### ISSUE TITLE
geom_bar() + coord_flip() doesn't work

### ISSUE THREAD

**Issue by jseppanen** [ropensci/plotly#390]
When plotting a bar chart with ggplot2 and plotly, the plot is empty on our enterprise plotly server.

This is the expected result:
![empty_plot_ggplot](https://cloud.githubusercontent.com/assets/83203/12302114/46044bec-ba2c-11e5-9825-bd6f26ef1910.png)

This is what I get with plotly:
![empty_plot_plotly](https://cloud.githubusercontent.com/assets/83203/12302185/975bd046-ba2c-11e5-92d0-f2a0d5bedab1.png)

Code:

```
library(ggplot2)
library(scales)
library(plotly)

d <- read.csv('empty_plot_data.csv.txt')

png('empty_plot_ggplot.png', w=500, h=300, res=96)
p <- ggplot(d, aes(purchase, revenue, fill=currency)) +
    geom_bar(stat='identity') +
    scale_y_continuous(label=dollar) +
    scale_fill_manual(values=c('limegreen', 'orange')) +
    labs(x=NULL, y='Revenue (USD)', title='Stuff bought') +
    coord_flip() +
    theme_bw()
print(p)
dev.off()

t <- plotly_POST(p, filename='empty_plot',
                 fileopt='overwrite', world_readable=TRUE)
```

csv file:
[empty_plot_data.csv.txt](https://github.com/ropensci/plotly/files/89254/empty_plot_data.csv.txt)

**Comment by cpsievert** [comment]
There are a couple problems here. The biggest of which is that `coord_flip()` doesn't currently work with `geom_bar()`:

```r
d <- read.csv("https://github.com/ropensci/plotly/files/89254/empty_plot_data.csv.txt")
p <- ggplot(d, aes(purchase, revenue, fill = currency)) +
  geom_bar(stat = 'identity') + 
  coord_flip()
ggplotly(p)
```

We'll provide a fix for this eventually, but for the time being, you could build the plot and change the orientation of the bars

```r
l <- plotly_build(p)
l$data[[1]]$orientation <- "h"
l$data[[2]]$orientation <- "h"
l
```

PS. It's a [known](https://github.com/ropensci/plotly/issues/392) [issue](https://github.com/ropensci/plotly/issues/185) that we don't yet convert some tick label formats such as `scale_y_continuous(label=dollar)`, so I'll be ignoring that in this issue.

**Comment by raghavkgarg** [comment]
How Does reorder (or sort)  works in plotly , like in above example lowest value(some stuff row) at lowest place and highest value at top(plain stuff row).
