### ISSUE TITLE
Time Series Heatmap

### ISSUE THREAD

**Issue by TonyDIRL** [ropensci/plotly#397]
Hi,

This is a general query and not a specific request, apologies if this is an inappropriate place to post.

I'm interested in building a graph in plotly similar to that displayed here 
http://tinyurl.com/zpbpjle

Essentially at every timestep there is a vertical heatmap. There is then a line chart plotted over this heatmap, and a barchart at the bottom, Each chart type shares the same time X-axis but varying Y-axes.

Would this be possible? Appreciate any suggestions.

Cheers,
Anthony

**Comment by cpsievert** [comment]
StackOverflow would be a better platform for this question -- https://github.com/ropensci/plotly/blob/master/CONTRIBUTING.md#opening-issues
