### ISSUE TITLE
ggplotly does not render in Jupyter

### ISSUE THREAD

**Issue by rcrezende** [ropensci/plotly#398]
When executing the following in the Jupyter Notebook no plot is returned.

```{r}
library(plotly)

dsamp <- diamonds[sample(nrow(diamonds), 1000), ]
qplot(carat, price, data=dsamp, colour=clarity)

ggplotly()
```
Is there any plan on supporting Jupyter?

**Comment by cpsievert** [comment]
This is a known limitation of the htmlwidgets framework -- https://github.com/ramnathv/htmlwidgets/issues/144

**Comment by millermd69** [comment]
I am new to plotly.  I attempted to use the `embed_notebook()` function but an error was generated
`Error in embed_notebook(pp): x must be a plotly figure`

```
library(plotly)
p <- ggplot(data = diamonds, aes(x = cut, fill = clarity)) +
            geom_bar(position = "dodge")
pp <- ggplotly(p)
embed_notebook(pp)
```

Shouldn't this function render the interactive graph in Jupyter?

**Comment by cpsievert** [comment]
Thanks for point that out @millermd69, #409 fixes that error.  

PS. unless htmlwidgets provides "native" support for Jupyter, I think the best we can do is [save each plot to disk](https://github.com/ropensci/plotly/issues/294#issuecomment-154598744) and embed as an `<iframe>`. Unfortunately, that means the HTML files will reside on disk after exiting the notebook, as I'm not sure of a good way to clean up those files upon exit. If anyone has a better solution, I'm all ears!

**Comment by randy3k** [comment]
with the latest plotly, htmlwidgets and jupyter, the follow works.
```
library(plotly)

dsamp <- diamonds[sample(nrow(diamonds), 1000), ]
p <- qplot(carat, price, data=dsamp, colour=clarity)
as.widget(ggplotly(p))
```
