### ISSUE TITLE
Abnormal in geom_smooth

### ISSUE THREAD

**Issue by jonwenjen** [ropensci/plotly#399]
In ggplot2, it's a smooth ine.
But same code in plotly it become strange curve as attachment.

Code:
test = paste ("select * from file order by WFR",sep="")    
d <- read.csv.sql("raw1.csv", sql = test)
d$WFR <- factor(d$WFR, levels = unique(as.character(d$WFR)))
g <- ggplot(d,aes(x=WFR,y=BINE, colour = Group1)) + geom_point() + geom_smooth(aes(group=1))
p <- ggplotly(g)
p
![2016-01-15 22_32_48-can t keep order as input in plotly by ggplot2 - jonwenjen gmail com - gmail](https://cloud.githubusercontent.com/assets/16720823/12355489/00a7b98c-bbd8-11e5-8611-b2d124d603f2.png)

**Comment by cpsievert** [comment]
Would it be possible to share the csv file as well?

**Comment by jonwenjen** [comment]
Hi cpsievert

File is as following.


[raw1.zip](https://github.com/ropensci/plotly/files/94431/raw1.zip)

**Comment by cpsievert** [comment]
This should be fixed in f1900cc3cd464408a60ffadfe3e95460747430e0. Let us know if you still have problems.
