### ISSUE TITLE
Proposed re-design

### ISSUE THREAD

**Issue by chriddyp** [ropensci/plotly#40]
With the configuration files we can re-architect the module to be a little more "R"-y. I propose the following interface:

### Before

```
py = plotly(username, key)
trace0 = list(x=...y=...)
py$plotly(trace0)
```

### After

```
plotly:::set_credentials(username, key)
plotly:::plot(trace0)
```
Or, if you prefer to send your credentials on a per-call basis (e.g. you're using the R demo account):

```
plotly:::plot(trace0, username=..., key=....)
```

And similarly for the other functions:

```
plotly:::ggplotly(..., plotly_options)
plotly:::plot(..., plotly_options)
plotly:::export_image(..., plotly_options)
plotly:::get_figure(..., plotly_options)
```

### With additional functionality ...

```
figure = plotly:::get_figure(file_owner, file_id, plotly_options) # returns a list of lists of lists of ... (plotly's JSON graph JSON)

data = plotly:::get_data(figure) # doesn't make a request to plotly, it just removes strips keys out of the named list
```

### A few questions I have (because I'm not an R expert)

1 - Is it the R convention to have nested modules/functions?

e.g. in Python we do: 
```
import plotly.plotly as py

# all the functions in py, call the plotly servers
py.plot(...)
py.iplot(...)
py.get_figure(...)
py.image.save_as(...)

# other functions, like tools, are in a separate namespace:

```python
import plotly.tools as tls
tls.embed(figure)
```

Do we do a similar thing in R? Or do we keep all the functions at the same "level", e.g.

This:

```
plotly:::embed(figure)
```
or this:

```
plotly:::tools:::embed(figure) #??
```

**Comment by cpsievert** [comment]
I agree with @chriddyp that the current interface is confusing. As I understand it, the main reason for having a function return a list of functions is to enable a mutable state. As far I can tell, that isn't necessary here.

In addition to avoiding [permission issues](https://github.com/ropensci/plotly/issues/204) when reading/writing credentials to disk, if we kept track of them via environment variables, you could still specify non-default credential on a per-call basis:

```r
plotly <- function(p, username, key, ...) {
  if (missing(username)) username <- Sys.getenv("PLOTLY_USER")
  if (missing(username)) username <- Sys.getenv("PLOTLY_KEY")

  ....
}
```

Then you could just do

```r
# use default credentials
plotly::plotly(qplot(1:10))
```

or 

```r
plotly::plotly(qplot(1:10), "my_username", "my_key")
```

I'd be interested in helping with a redesign, but the changes would be backwards-incompatible and it might be a lot of work.

Also, @chriddyp, I don't think nested namespaces are possible in R. However, it's worth noting that with knitr, we can control printing of objects based on their class. We do this in animint. For example,

    ```r
    (p <- qplot(1:10))
    ```

would embed a ggplot2 plot

    ```r
    structure(p, class = "animint")
    ```

calls `animint2dir` and embeds the animint plot
