### ISSUE TITLE
movies dataset is no longer in ggplot2, so the official example does not work

### ISSUE THREAD

**Issue by Deleetdk** [ropensci/plotly#400]
https://plot.ly/r/shiny-tutorial/

The movies dataset has been removed from ggplot2, so the example code does not work.

**Comment by yankev** [comment]
It's possible to host the data set, and use the following command to read the data: 

```
movies <- read.table("hosturl/movies.tab", sep="\t", header=TRUE, quote="", comment="")
#Reference: http://had.co.nz/data/movies/
```
Alternatively, somebody submitted a pull-request that requires the installation of the R package `ggplot2movies`.
