### ISSUE TITLE
Error with geom_vline

### ISSUE THREAD

**Issue by speedreader** [ropensci/plotly#402]
Using geom_vline to add vertical lines to a ggplot/plotly doesn't work. Fails on the examples here:

https://plot.ly/ggplot2/geom_abline/

Small segments where the vertical lines should draw appear at the bottom on the x-axis but they don't extend up the plot. See attached screenshot.

![index](https://cloud.githubusercontent.com/assets/16739809/12375762/3840bfe0-bc98-11e5-9d73-10f35c1a4cc2.png)

**Comment by cpsievert** [comment]
Bug confirmed, thanks.
