### ISSUE TITLE
Documenting heatmaps

### ISSUE THREAD

**Issue by ziyadsaeed** [ropensci/plotly#405]
The heatmap documentation only shows how to change color palette for the heatmap and how to add categorical axis. Other than that it has no documentation

**Comment by speedreader** [comment]
Seems to be in the full documentation. Are you commenting on the examples? Whether or not between the documentation and the examples there are clear uses for all of the possibilities might be its own issues (and one I've come up against) but Heatmaps look to be covered in the documentation for the different libraries. 

https://plot.ly/r/reference/#heatmap
https://plot.ly/python/reference/#heatmap
https://plot.ly/javascript/reference/#heatmap

**Comment by cpsievert** [comment]
@ziyadsaeed if there is anything in particular you'd like to see, please request it here -- https://github.com/plotly/documentation
