### ISSUE TITLE
R : How to change color bar when using group argument ?

### ISSUE THREAD

**Issue by prise6** [ropensci/plotly#412]
Hi everyone,
Here's my question, i didn't find any reference about changing bar color when using group argument in `plot_ly` function.

Silly Example :
```{r}
plot_ly(iris, x = Sepal.Length, y = Petal.Width, group = Species, type = "bar")
```
How can i change group bar colors ?
I know i have to change the color for each trace, but how ?

Thank you.

**Comment by cpsievert** [comment]
If you use the `color` argument, you can control the color scheme via `colors`.

For future reference, when opening issues, please follow the contributing guidelines -- https://github.com/ropensci/plotly/blob/master/CONTRIBUTING.md#opening-issues

**Comment by prise6** [comment]
Sorry, i thought it was an issue because it doesn't work for me. Well, i'll try to find out why.
Thanks anyway !
