### ISSUE TITLE
Plotly for Ggplot2 Main Page Bug

### ISSUE THREAD

**Issue by rudeboybert** [ropensci/plotly#414]
On the [Plotly for Ggplot2 Main Page](https://plot.ly/ggplot2/) on plot.ly, your second example does not work. It is currently

```
p <- ggplot(data = d, aes(x = carat, y = price)) +
  geom_point(aes(text = paste("Clarity:", clarity)), size = 4) +
  geom_smooth(aes(colour = cut, fill = cut)) + facet_wrap(~ cut)

(gg <- ggplotly(p))
```

You forgot to assign the sample of 1000 rows from the `diamonds` dataset assigned to `d` as shown on the [README of the repo](https://github.com/ropensci/plotly#introduction):

```
set.seed(100)
d <- diamonds[sample(nrow(diamonds), 1000), ]
p <- ggplot(data = d, aes(x = carat, y = price)) +
  geom_point(aes(text = paste("Clarity:", clarity)), size = 4) +
  geom_smooth(aes(colour = cut, fill = cut)) + facet_wrap(~ cut)

(gg <- ggplotly(p))
```

**Comment by royr2** [comment]
@cpsievert  I can take this...

**Comment by cpsievert** [comment]
@royr2 that'd be great, feel free to take any of the issues labelled documentation, thanks!

**Comment by royr2** [comment]
@cpsievert - have updated main page. Feel free to close...

**Comment by cpsievert** [comment]
Thanks!
