### ISSUE TITLE
Making population pyramids with Plotly

### ISSUE THREAD

**Issue by walkerke** [ropensci/plotly#419]
First and foremost - thanks for the great work on the package, the API is fantastic!

  I commonly build population pyramids and I'd like to use Plotly to do this as well.  However, I'm running into a couple issues when doing this, so I thought I'd see if anyone had some feedback on these issues.

Normally when setting up a population pyramid I set the population values for one of the genders to negative numbers to built a "pyramid" around a central axis.  For example:

```r
library(plotly)

age <- rep(1:5, 2)

sex <- rep(c('Male', 'Female'), each = 5)

pop <- c(-1000, -944, -888, -762, -667, 1100, 999, 844, 789, 655)

df <- data.frame(age, sex, pop)

plot_ly(df, x = pop, y = age, group = sex, type = 'bar', orientation = 'h')
```
![image](https://cloud.githubusercontent.com/assets/4872833/12510479/bffc3e38-c0cf-11e5-90b8-dbfd6d8c3378.png)

On the right track here, but I want the bars to align, as in a stacked bar chart.  When I change the `barmode` to `'stack'`, I get this:

```r
plot_ly(df, x = pop, y = age, group = sex, type = 'bar', orientation = 'h') %>%
    layout(barmode = 'stack')
```

![image](https://cloud.githubusercontent.com/assets/4872833/12510503/f222a2e4-c0cf-11e5-9393-c699a9baf2d3.png)

Alternatively, I also tried adding the genders as separate traces, but Plotly then plots positive numbers as negative:

```r
library(dplyr)

male <- filter(df, sex == 'Male')

female <- filter(df, sex == 'Female')

plot_ly(male, x = pop, y = age, type = 'bar', orientation = 'h') %>%
    add_trace(female, type = 'bar', x = pop, y = age, orientation = 'h') %>%
    layout(barmode = 'stack')
```
![image](https://cloud.githubusercontent.com/assets/4872833/12517834/8c54f018-c0fa-11e5-823f-439d59b395bd.png)

If you have any ideas about this, please let me know!  

Also: when creating population pyramids, I want to display all of the axis values as absolute values on either side of zero.  In other R/JS libraries, I've passed something like the following to `tickformat`: 

```javascript
function(d) { return d3.format(',.1f')(Math.abs(d)) }
```

I've tried this out in Plotly, both as a string and wrapped in `htmlwidgets::JS()`, like this: 

```r
plot_ly(df, x = pop, y = age, group = sex, type = 'bar', orientation = 'h') %>%
  layout(xaxis = list(
    tickformat = htmlwidgets::JS("function(d) { return d3.format(',.0f')(Math.abs(d)) }")
  ))
```
and I don't get it to change.  I'll keep working on this, but please let me know if you have any pointers!

**Comment by cpsievert** [comment]
This will get you most of the way there:

```r
plot_ly(df, x = pop, y = age, group = sex, type = 'bar', orientation = 'h') %>% 
  layout(bargap = 0, barmode = "overlay")
```

I'm not sure if it's possible to display absolute values in the tick labels. Passing a JS function is an interesting idea, but I don't think plotly.js supports that.

For future reference, we'd like to use issues for just bug reports and feature requests -- https://github.com/ropensci/plotly/blob/master/CONTRIBUTING.md

Feel free to request absolute value tick labels [here](https://github.com/plotly/plotly.js/issues/new)

**Comment by etpinard** [comment]
@walkerke you can use [`tickvals`](https://plot.ly/r/reference/#layout-xaxis-tickvals) and [`ticktext`](https://plot.ly/r/reference/#layout-xaxis-ticktext) to fully customize your graphs's tick values.

**Comment by walkerke** [comment]
Excellent, thank you for the quick reply!  I'll try this out.

**Comment by walkerke** [comment]
Tried it out and everything is working great!  Fantastic library to work with.  For anyone who might come across this issue and is looking for the solution: 

```r
library(plotly)
library(dplyr)

age <- rep(1:5, 2)

sex <- rep(c('Male', 'Female'), each = 5)

pop <- c(-1000, -944, -888, -762, -667, 1100, 999, 844, 789, 655)

df <- data.frame(age, sex, pop) %>%
  mutate(abs_pop = abs(pop))

plot_ly(df, x = pop, y = age, group = sex, type = 'bar', orientation = 'h',
        hoverinfo = 'y+text+name', text = abs_pop) %>%
  layout(bargap = 0.1, barmode = 'overlay',
         xaxis = list(tickmode = 'array', tickvals = c(-1000, -500, 0, 500, 1000),
                      ticktext = c('1000', '500', '0', '500', '1000')))
```
![image](https://cloud.githubusercontent.com/assets/4872833/12521824/89f23818-c112-11e5-8218-5627a9a7a3f9.png)

**Comment by jgonzale** [comment]
@walkerke, I've tried to reproduce this last plot you presented, but I got stuck with this error:

```
Warning in plot_ly(df, x = ~pop, y = ~age, group = ~sex, type = "bar", orientation = "h", : The group argument has been deprecated. Use `group_by()` or split instead.
```

I'm not an R expert, and I don't know how to proceed.

Many thanks!

**Comment by pssguy** [comment]
@jgonzale 
This code will not work with latest version of plotly. There is a lot of coverage of plotly for R including a webinar, book, many examples and a reference guide. All worth investing time on.  This should get the basic chart up for you

```
library(plotly)
library(dplyr)

age <- rep(1:5, 2)

sex <- rep(c('Male', 'Female'), each = 5)

pop <- c(-1000, -944, -888, -762, -667, 1100, 999, 844, 789, 655)

df <- data.frame(age, sex, pop) %>%
  mutate(abs_pop = abs(pop))


df %>% 
  plot_ly(x= ~pop, y=~age,color=~sex) %>% 
  add_bars(orientation = 'h', hoverinfo = 'text', text = ~abs_pop) %>%
  layout(bargap = 0.1, barmode = 'overlay',
         xaxis = list(tickmode = 'array', tickvals = c(-1000, -500, 0, 500, 1000),
                      ticktext = c('1000', '500', '0', '500', '1000')))
```

![pyramidplotly](https://cloud.githubusercontent.com/assets/2775918/25094637/f662a080-234c-11e7-9887-9dc332511748.PNG)

**Comment by jgonzale** [comment]
@pssguy, thank you very much!!

I'm so fortunate there is a large chunk of documentation about plotly out there! (And it's integration with R Markdown etc. etc.)

Great!
