### ISSUE TITLE
ggplotly - date scale not in limits and linechart data inaccurate

### ISSUE THREAD

**Issue by Aylon1** [ropensci/plotly#422]
Hello and thenks for the great tool that plotly is!

I am using the code from https://plot.ly/ggplot2/scale_x_date/#stock-chart-prices-dashboard with function call

    gg.charts.PerformanceSummary(port.data$returns, main=paste("Summary" , sep= " - "), plot = T)

the ggplot is slightly amended

    gg.xts <- ggplot(df, aes_string( x = "Date", y = "value", group = "variable" )) +
    facet_grid(variable ~ ., scales = "free_y", space = "fixed") +
    geom_line(data = subset(df, variable == "Index")) +
    geom_bar(data = subset(df, variable == "Return"), 
             stat = "identity", 
             position = "identity") +
    geom_line(data = subset(df, variable == "Drawdown")) +
    geom_hline(yintercept = 0, size = 0.5, colour = "black") +
    ggtitle(title.string) +
    theme(axis.text.x = element_text(angle = 0, hjust = 1)) +
    scale_x_datetime(date_breaks = "12 months", 
                     labels = date_format("%m/%Y"), 
                     limits = as.POSIXct(c(first(df$Date),last(df$Date)))) +
    ylab("") +
    xlab("")

and produces the correct result with a distinct negative performance as seen below

![image](https://cloud.githubusercontent.com/assets/13525135/12533226/6cdcdcf2-c229-11e5-8652-09d232acae76.png)

running then ggplotly() creates

![image](https://cloud.githubusercontent.com/assets/13525135/12533235/a99770b2-c229-11e5-9868-777811e99d9f.png)

and clicking autoscale

![image](https://cloud.githubusercontent.com/assets/13525135/12533237/c63942d6-c229-11e5-8af1-ceff84f59361.png)

clearly visible, the negative performance ins gone as can be seen even in further detail when zooming manually in at the right period

![image](https://cloud.githubusercontent.com/assets/13525135/12533245/ffca4d88-c229-11e5-8d34-952e13f65538.png)

Is there a particular reason for these behaviours?   a) that the chart does not scale correctly to the limits and b) that the result of the charting is different?

Return file (.RData)
[returns.zip](https://github.com/ropensci/plotly/files/102069/returns.zip)

Many thanks for your advice.

**Comment by cpsievert** [comment]
This should be fixed in f1900cc3cd464408a60ffadfe3e95460747430e0. Let us know if you still have problems.
