### ISSUE TITLE
Newlines in legend labels causes mis-placed legends in scattergeo

### ISSUE THREAD

**Issue by martinjhnhadley** [ropensci/plotly#431]
# Note

I recognise that advanced legend placement/modification is not on the plotly roadmap (https://github.com/ropensci/plotly/wiki/Unsupported-plotly.js-features) but supposed that as tooltips support `<br>` for newlines that this would be within support for legend labels via `group`.

# Issue

In some instances, introducing newlines (`<br>`) to legend titles leads to incorrect positioning of the legend in `scattergeo` plot_ly plots (data and output of devtools::session_info() at bottom of post)

```r
plot_ly(with.new.lines, lon = lon, lat = lat,
        type = "scattergeo", locationmode = "country",
        group = Letter.Series, showlegend = TRUE) %>%
  layout(geo = geo_layout,
         legend = list(y = 0.5),
         height = "1400px"
  )
```

![image](https://cloud.githubusercontent.com/assets/9363263/12611084/e3d7a056-c4e2-11e5-956f-c2eb073de189.png)

Replacing the newline `<br>` with "and" results in good label placement

```r
plot_ly(with.long.lines, lon = lon, lat = lat,
        type = "scattergeo", locationmode = "country",
        group = Letter.Series, showlegend = TRUE) %>%
  layout(geo = geo_layout,
         legend = list(y = 0.5),
         height = "1400px"
  )
```
![image](https://cloud.githubusercontent.com/assets/9363263/12611110/0af3f8b0-c4e3-11e5-8e1d-1f68f1604e5d.png)

The issue does not arise for very short legend labels:
```r
plot_ly(single.character.new.line, lon = lon, lat = lat,
        type = "scattergeo", locationmode = "country",
        group = Letter.Series, showlegend = TRUE) %>%
  layout(geo = geo_layout,
         legend = list(y = 0.5),
         height = "1400px"
  )
```

![image](https://cloud.githubusercontent.com/assets/9363263/12611227/8b5c3904-c4e3-11e5-9c6b-25198a686b1b.png)

# Data for examples

```r
with.new.lines <- structure(list(lat = structure(c(3L, 2L, 1L), .Label = c("36.162664", 
"38.600423", "39.739236"), class = "factor"), lon = structure(c(1L, 
3L, 2L), .Label = c("-104.990251", "-86.781602", "-90.221624"
), class = "factor"), Letter.Series = c("Albrecht-Fuenfstueck<br>Poetsch-Poetsch<br>", 
"Birkner-Sydow", "Birkner-Sydow<br>Veltisch-Feldwisch<br>")), .Names = c("lat", 
"lon", "Letter.Series"), row.names = c(1L, 3L, 9L), class = "data.frame")
with.long.lines <- with.new.lines
with.long.lines$Letter.Series <- c("Albrecht-Fuenfstueck and Poetsch-Poetsch",
                                   "Birkner-Sydow",
                                   "Birkner-Sydow and Veltisch-Feldwisch")
single.character.new.line <- with.new.lines
single.character.new.line$Letter.Series <- c("A<br>B<br>","C","C<br>D<br>")
```

# devtools::session_info()
```r
Session info -----------------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.3 (2015-12-10)
 system   x86_64, darwin13.4.0        
 ui       RStudio (0.99.491)          
 language (EN)                        
 collate  en_GB.UTF-8                 
 tz       Europe/London               
 date     2016-01-27                  

Packages ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package     * version  date       source                            
 assertthat    0.1      2013-12-06 CRAN (R 3.2.0)                    
 base64enc     0.1-3    2015-07-28 CRAN (R 3.2.0)                    
 bitops        1.0-6    2013-08-17 CRAN (R 3.2.0)                    
 colorspace    1.2-6    2015-03-11 CRAN (R 3.2.0)                    
 DBI           0.3.1    2014-09-24 CRAN (R 3.2.0)                    
 devtools      1.10.0   2016-01-23 CRAN (R 3.2.3)                    
 digest        0.6.8    2014-12-31 CRAN (R 3.2.0)                    
 dplyr       * 0.4.3    2015-09-01 CRAN (R 3.2.0)                    
 ggplot2     * 2.0.0    2015-12-18 CRAN (R 3.2.3)                    
 gridExtra     2.0.0    2015-07-14 CRAN (R 3.2.0)                    
 gtable        0.1.2    2012-12-05 CRAN (R 3.2.0)                    
 htmltools     0.3      2015-12-29 CRAN (R 3.2.3)                    
 htmlwidgets   0.5      2015-06-21 CRAN (R 3.2.0)                    
 httpuv        1.3.3    2015-08-04 CRAN (R 3.2.0)                    
 httr          1.0.0    2015-06-25 CRAN (R 3.2.0)                    
 jsonlite      0.9.19   2015-11-28 CRAN (R 3.2.2)                    
 lattice       0.20-33  2015-07-14 CRAN (R 3.2.0)                    
 lubridate   * 1.5.0    2015-12-03 CRAN (R 3.2.3)                    
 magrittr      1.5      2014-11-22 CRAN (R 3.2.0)                    
 MathJaxR      0.11     2015-06-04 local                             
 memoise       0.2.1    2014-04-22 CRAN (R 3.2.0)                    
 mime          0.4      2015-09-03 CRAN (R 3.2.0)                    
 munsell       0.4.2    2013-07-11 CRAN (R 3.2.0)                    
 plotly      * 2.0.16   2015-12-20 CRAN (R 3.2.3)                    
 plyr        * 1.8.3    2015-06-12 CRAN (R 3.2.0)                    
 R6            2.1.1    2015-08-19 CRAN (R 3.2.3)                    
 Rcpp          0.12.2   2015-11-15 CRAN (R 3.2.2)                    
 RCurl         1.95-4.7 2015-06-30 CRAN (R 3.2.0)                    
 RJSONIO       1.3-0    2014-07-28 CRAN (R 3.2.0)                    
 rsconnect     0.4.1.4  2015-12-19 Github (rstudio/rsconnect@fcac892)
 scales      * 0.3.0    2015-08-25 CRAN (R 3.2.0)                    
 shiny       * 0.12.2   2015-08-05 CRAN (R 3.2.0)                    
 shinythemes * 1.0.1    2015-03-03 CRAN (R 3.2.0)                    
 sp          * 1.1-1    2015-06-05 CRAN (R 3.2.0)                    
 stringi       1.0-1    2015-10-22 CRAN (R 3.2.0)                    
 stringr       1.0.0    2015-04-30 CRAN (R 3.2.0)                    
 viridis       0.3.2    2015-12-31 CRAN (R 3.2.3)                    
 xtable        1.8-0    2015-11-02 CRAN (R 3.2.0)                    
 yaml          2.1.13   2014-06-12 CRAN (R 3.2.0)   
```

**Comment by cpsievert** [comment]
Any input on this @etpinard?

**Comment by etpinard** [comment]
Bug confirmed. The trialling `<br>` in the third legend item seems to mess things up:

http://codepen.io/etpinard/pen/qbYqJb

@martinjhnhadley any reasons for putting a trailing `<br>` in your trace names?

**Comment by martinjhnhadley** [comment]
Two:
1) Laziness from paste0(vec,sep="<br>",collapse="")
2) in the case of multiple newlines within a trace the extra <br> helps distinguish between traces.

However, I'm not wedded to it and will modify the code to remove the trailing <br>. Hadn't explored enough to notice the last trace must include a <br> for the issue to appear. 

Thanks!

**Comment by martinjhnhadley** [comment]
... I commented that on my mobile, the annoying newlines are because of < br >

**Comment by etpinard** [comment]
> I'm not wedded to it and will modify the code to remove the trailing. Hadn't explored enough to notice the last trace must include a for the issue to appear.

All good man. Thanks for the detailed report :beers:

**Comment by martinjhnhadley** [comment]
Hmm, the issue remains with large numbers of traces (ignoring the question of whether so many traces is useful, for a moment) 

![image](https://cloud.githubusercontent.com/assets/9363263/12632574/ecf1ccde-c550-11e5-818b-9175060a99fb.png)

Shiny app: https://livedataoxford.shinyapps.io/german-letters_Conversation_WorldMap/
Zipped version: https://www.dropbox.com/s/dno16t1fpde5sa6/plotly-linebreaking-issue.gz?dl=0

Might be useful for your testing, but it's nearing the limit of usable trace numbers

**Comment by martinjhnhadley** [comment]
Thanks @cpsievert! Using any of the controls can push the legend back to where it should be, althing with resizing the window by even a pixel. All quite odd.

I wonder whether I could fix this all with a little JavaScript that after page load forces the reload of the Plotly containing div, show_world_map. But I'll need to get help writing that as I'm new to JavaScript hoodwinkery

**Comment by cpsievert** [comment]
I believe this was fixed in plotly.js at some point, and should be fixed on the master branch here.

**Comment by martinjhnhadley** [comment]
@cpsievert this has indeed been fixed - thanks! This now loads beautifully, https://livedataoxford.shinyapps.io/german-letters_Conversation_WorldMap/
