### ISSUE TITLE
Setting default 'data on hover' in modebar

### ISSUE THREAD

**Issue by speedreader** [ropensci/plotly#432]
Using plotly in R/shiny. 

Generate a data.frame. 

    exampleDf <- data.frame('x' =rnorm(100, 0, 100), 'y' = rnorm(100, 0, 100), 'z' = rep(1:10,10))

Plot it

    plot_ly(exampleDf, x = x, y = y, mode="markers", marker=list(size = 20, color = 'red', opacity = .6))

In the modebar I can manually select between 'show closest data on hover' and 'compare data on hover'. The latter is the default. I'd like to be able to change that. In the CRAN documentation there are some commands for 'config' but I don't see anything for changing that option. Ultimately, I'd like to be able to suppress the modebar but with the default behavior set to 'show closest data on hover'. With:

    diplayModeBar = F

You can only have 'compare data on hover'. Full example:

    plot_ly(exampleDf, x = x, y = y, mode="markers", marker=list(size = 20, color = 'red', opacity = .6)) %>% config(displayModeBar = F, showLink = F)

**Comment by cpsievert** [comment]
Add `layout(hovermode = 'closest')`

https://plot.ly/r/reference/#layout-hovermode

**Comment by speedreader** [comment]
Thanks and d'oh. Just assumed it would be with the other 'config' commands.
