### ISSUE TITLE
High memory

### ISSUE THREAD

**Issue by fabioand2k** [ropensci/plotly#434]
Hi Carlson,

the problem is not scale, sorry (about #429 issue)

i don't now if i need open or reopen issue, sorry. 

the problem is big number.

library(ggplot2)
library(plotly)

employee <- c('John Doe','Peter Gynn','Jolie Hope')
salary <- c(210000000, 234000000, 268000000)

employ.data <- data.frame(employee, salary)

p <- ggplot(employ.data ,aes(x=employee, y=salary)) +
geom_bar(stat='identity', color="black") 
ggplotly(p)

if you run this dataframe with 
salary <- c(210, 234, 268) = run instantly
and if you run with
salary <- c(210000000, 234000000, 268000000) = crash machine by high memory

the problem is when you use "big numbers" 
thanks

**Comment by cpsievert** [comment]
Yikes! Thanks for crashing my R session ;)

Since ggplot2 doesn't seem to choke on this, I'll classify it as a bug

**Comment by cpsievert** [comment]
This should be fixed in f1900cc3cd464408a60ffadfe3e95460747430e0. Let us know if you still have problems.

**Comment by fabioand2k** [comment]
Thank you my friend!
i will check now :)

**Comment by fabioand2k** [comment]
works like a charm :)
