### ISSUE TITLE
ggplotly with facet_grid creates copies of legend items

### ISSUE THREAD

**Issue by royr2** [ropensci/plotly#438]
Hi @cpsievert 
Is there any way to let each trace remain associated with the same legend item (as opposed to having a new legend item for each plot)? Just the way ggplot2 does it?

thanks !

```{r}
library(plotly)
library(reshape2)

ds <- data.frame(X = 1:100, 
                 Y1 = rnorm(100), 
                 Y2 = rnorm(100), 
                 group = LETTERS[1:4])

ds <- melt(ds, id = c("X", "group"))

ggplot(ds, aes(X, value)) + 
  geom_point(aes(color = group)) +
  facet_wrap(~variable)
ggplotly()
```
ggplot:
![image](https://cloud.githubusercontent.com/assets/6601579/12636741/53008060-c5b5-11e5-9429-a0eb88161ab8.png)

ggplotly:
![image](https://cloud.githubusercontent.com/assets/6601579/12636747/68c401ce-c5b5-11e5-8254-82a65a1450bd.png)

**Comment by cpsievert** [comment]
Duplicate of #378.

**Comment by royr2** [comment]
Okay, thanks...
