### ISSUE TITLE
plotly_POST sharing="secret" not working

### ISSUE THREAD

**Issue by lucacerone** [ropensci/plotly#441]
When I publish a plot (created with ggplot2 and ggplotly) to my company self hosted plotly using
plotly_POST(p, filename="a_plot", sharing="secret")

I then have to go manually to my plotly file, click on the share link, and enable the secret sharing which I think is not what should happen.

I also tried to use "hidden" as the error message doesn't agree with the documentation.

**Comment by cpsievert** [comment]
Does the plot post successfully as a public figure? What do you see if you enter `plotly:::verify("username")` and `plotly:::verify("api_key")` in your R console?

**Comment by cldougl** [comment]
confirmed for me too. 
`plotly_POST` posts as a public figure and my username & api_key are verified.

**Comment by cpsievert** [comment]
Oh, and since you have your own domain, make sure you've set this environment variable: `Sys.setenv("plotly_domain"="https://plotly.your-company.com")`

You can check the value with `Sys.getenv("plotly_domain")`

**Comment by cpsievert** [comment]
Actually, I think I found the bug, pushing a fix shortly.

**Comment by lucacerone** [comment]
Hi Carson, I'll run the verify stuff on Monday. However public worked fine
and all the environment variables are set.

**Comment by lucacerone** [comment]
Oh OK :) then thanks for the quick fix!

**Comment by lucacerone** [comment]
anyway, I installed the commit 6eafd168
but when I use plotly_POST and use share="hidden", the figure is created as private and I have to click on the arrow and check the box saying "enable private share link". I don't think the commit fixed the issue.

In case it helps I also get these message:

```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Couldn't resolve host name
In addition: Warning message:
In plotly_POST(x = p, filename = "r_tests/boh", fileopt = "overwrite",  :
  world_readable is no longer supported. Instead, set the sharing
argument to "private" (you must be logged in to access),
"hidden" (anybody with the obscured URL can access) or "public"
(anybody can view).
```

Despite the message the plot is created correctly in our enterprise plotly installation.

**Comment by cpsievert** [comment]
Previously I was trying to infer API endpoints from the `plotly_domain` environment variable, but going forward, you'll be able to configure both the plotly domain and the API domain

```r
Sys.setenv("plotly_domain" = "https://plotly.your-company.com")
Sys.setenv("plotly_api_domain" = "https://api-plotly.your-company.com")
```

**Comment by cpsievert** [comment]
@royr2 could you update <https://plot.ly/r/getting-started/> to reflect this new environment variable? ^^^

**Comment by royr2** [comment]
Okay done...
