### ISSUE TITLE
Hover info in heatmap shows intermediate values

### ISSUE THREAD

**Issue by ziyadsaeed** [ropensci/plotly#451]
Consider the following example, x, y and z are integer vectors
```r
x = c(1:20)
y = c(10:30)
plot_ly(z = outer(x,y, "*"), x = x,  y = y, type = "heatmap")
```
But plotly heatmap hover shows x and z as integer but y as intermediate floating point
Look at the screenshot below. It shows y as 21.5 which doesn't exist in the y vector
![plotly heatmap hover bug](https://cloud.githubusercontent.com/assets/12503225/12791022/fd176a12-cac6-11e5-9788-f4d5730ff147.jpg)

**Comment by yankev** [comment]
Something to note is that there appears to be an extra unit on the x axis, and one short on the y axis. 
The data in the build looks correct however. 
```
[[1]]$x
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

[[1]]$y
 [1] 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30
```

**Comment by ziyadsaeed** [comment]
@yankev x and y doesn't have to be of the same length.

**Comment by cpsievert** [comment]
I think this is what you want...

```r
x <- c(1:20)
y <- c(10:30)
dim(outer(y, x, "*"))
#> [1] 21 20
p <- plot_ly(z = outer(y, x, "*"), x = x,  y = y, type = "heatmap")
```

**Comment by ziyadsaeed** [comment]
OK this works, but why?

**Comment by cpsievert** [comment]
You need to match the x and y dimensions correctly
