### ISSUE TITLE
Surface and scatter3d

### ISSUE THREAD

**Issue by federicou** [ropensci/plotly#452]
Is it possible to add a surface plot (with add_trace) to a scatter3d chart?

Obviously while keeping the same x,y,z variables.

**Comment by ischurov** [comment]
Yes, this is possible. Just do it with add_trace and put correct `type` :)

See some examples [here](https://github.com/ischurov/hsequantling/blob/master/testcase/lecture-pca-test.Rmd) (I add some `mesh3d` and `surface` objects to `scatter3d` chart there).

P.S. It is better to ask questions on http://stackoverflow.com/ with [plotly](http://stackoverflow.com/questions/tagged/plotly) tag. Issues is for issues, not for questions, so you will get help faster on stackoverflow.
