### ISSUE TITLE
Any way of hiding the mode bar

### ISSUE THREAD

**Issue by pssguy** [ropensci/plotly#459]
I see there is a displayModeBar: false in the [plotly ref](https://plot.ly/javascript/configuration-options/#hide-the-modebar-with-plotly.js) but I cannot find  it in the r plotly reference docs

**Comment by royr2** [comment]
The following works for me. Hope this helps...
```r
plot_ly(x = rnorm(1000), y = rnorm(1000), mode = "markers") %>% 
  layout(title = "Plot") %>% 
  config(displayModeBar = F)
```

Do checkout the package documentation on CRAN [here](https://cran.r-project.org/web/packages/plotly/plotly.pdf).

**Comment by cpsievert** [comment]
I recently changed `config()` to accept arbitrary arguments and also [link to the plotly.js source](https://github.com/ropensci/plotly/blob/fd812f526f10fcb5d977bbbdbbaf47c887e2651e/R/plotly.R#L180-L181) in the reference. That way we won't have to worry about syncing the documentation.

**Comment by pssguy** [comment]
Thanks guys

**Comment by cmohamma** [comment]
Hey guys, I used the following code to hide the mode bar...

```
gg<-gg %>%
  config(displayModeBar = FALSE) %>%
  config(showLink = FALSE)

```

...and this world just fine  in my Rstudio viewer and when I save it as an html file but when I save it to my plotly account, the modebar appears again. This is also the case for when I embed the plot into html say on my personal website for example, any idea whats going on?  Thanks!

**Comment by firasm** [comment]
This should be reopened, as it isn't working!

**Comment by nathancday** [comment]
@firasm `config(displayModeBar = FALSE)` seems to be working for me in a Shiny app with:

`plotly       * 4.9.1   2019-11-07 [1] CRAN (R 3.6.0)`

Could you share more about the situation where it is failing for you?

**Comment by firasm** [comment]
Sorry, should have added more info a month ago when I was fighting this problem.

I'll see if I can get a MWE for testing/debugging, but it works fine in Jupyterlab but upon deployment of the R app to heroku, the modebar was back.

**Comment by davidizquierdogomez** [comment]
I understand that with the line config(displayModeBar = FALSE) I can remove the mode bar in plotly but....how can I delete the mode bar when using ggplotly? 

pp <- ggplotly(gg, width = 800, height = 600,)
plotly::layout(pp,
               xaxis = list(showgrid = F),
               yaxis = list(showgrid = F),
  images = list(
  list(
    source =  image_destination,
    xref = "x",
    yref = "y",
    x = -1,
    y = 12,
    sizex = 13,
    sizey = 12,
    sizing = "stretch",
    opacity = 0.9,
    layer = "below"
  )
))

Thank you very much,
