### ISSUE TITLE
Legend Color for Bar plot

### ISSUE THREAD

**Issue by federicou** [ropensci/plotly#465]
trying to change the colors in a Bar plot, the colors of the legend are not coherent with the applied palette (they are black instead of the colors assigned to the markers)

This is a reproducible example

mtcars %>% plot_ly(x=rownames(mtcars),y=carb,type="bar",group=cyl,marker = list(color=as.character(factor(mtcars$cyl,levels=c("4","6","8"),labels=c("#D8D8D8","#51C439","#53BCD4")))))

**Comment by nicholasjhirad** [comment]
Having the same issue

**Comment by cpsievert** [comment]
Confirmed, thanks. Eventually you should be able to create this plot like this:

```r
mtcars %>% plot_ly(
  x = rownames(mtcars), y = carb, type = "bar",
  color = cyl, colors = c("#D8D8D8","#51C439","#53BCD4")
)
```

**Comment by cpsievert** [comment]
Actually, using the latest version (3.4.13) with the code above gives me this result. 

![rplot](https://cloud.githubusercontent.com/assets/1365941/14336552/7f463bfe-fca8-11e5-8758-d017a978b7a1.png)


Please reopen if you can't replicate.

**Comment by kiezuz** [comment]
#872 still there in the new plotly version 4.5.2
