### ISSUE TITLE
plot_ly ignores parameters "width" and "height"

### ISSUE THREAD

**Issue by drwagner** [ropensci/plotly#466]
Hi

At least in this simple example in RStudio the width and height parameters are ignored:

<code>
plot_ly(economics, x = date, y = uempmed, mode = "markers", width = 200, height = 200) 
</code>

The workaround that I've found is using the layout function which seems to work as expected:

<code>
plot_ly(economics, x = date, y = uempmed, mode = "markers") %>%
  layout(width = 200, height = 200, autosize = FALSE)
</code>

**Comment by cpsievert** [comment]
Both these examples seem to be working now.
