### ISSUE TITLE
event_data() should (try to) return more properties

### ISSUE THREAD

**Issue by pssguy** [ropensci/plotly#468]
I believe you had this on the wish list and wondered if it was operational yet or 
will be in the forseeable future

**Comment by cpsievert** [comment]
hover and click events were added in [plotly.js 1.5.1](https://github.com/plotly/plotly.js/releases/tag/v1.5.1) which is the [current version on the master branch](https://github.com/ropensci/plotly/blob/master/inst/htmlwidgets/plotly.yaml)

**Comment by pssguy** [comment]
Okay, I was a bit out of date with upgrades - shame that is not covered in 'Watch'
Not clear how  the previous event_data("plotly_click") is now handled?

**Comment by cpsievert** [comment]
I just added a [basic example for clicks](https://github.com/ropensci/plotly/blob/feature/transmit/inst/examples/map_click/app.R). More data should be returned, so I'm reopening this issue.

PS. I'm not yet sure if it makes sense to make "plotly_hover" events accessible with `event_data()`, especially considering you can hook to arbitrary events via `htmlwidgets::onRender()`(you'll need the dev version of **htmlwidgets**)

**Comment by pssguy** [comment]
I tried the example above and still get
```
Error in renderPrint: could not find function "event_data"
```
What version should I be installing
Neither devtools::install_github("ropensci/plotly") ver 2.4.4
nor   devtools::install_github("ropensci/plotly@feature/events") ver 2.0.19

have event_data() as a function on the Help pages

I would not use plotly_hover to trigger events if it conflicts with the current hovering which I use for tooltip style info

**Comment by cpsievert** [comment]
You need the feature/transmit branch

**Comment by pssguy** [comment]
OK. Looks good. Should have an example available in next day or so
