### ISSUE TITLE
Can't use both color and size in a scatter plot (for specific datasets)

### ISSUE THREAD

**Issue by yankev** [ropensci/plotly#472]
```
dt = data.frame(category = c("A","B","C"), X = c(1,2,3), Y = c(3,4,5))
test <- plot_ly(data = dt, x = X, y = Y, mode = "markers",
        color = category, size = X)
```
Results in the following:
![broken](https://raw.githubusercontent.com/yankev/test/master/broken_scatter.png)

Though the same plot works using `ggplotly`:
```
g <- ggplot(data=dt) + geom_point(mapping=aes(x = X, y = Y, colour = category, size = X))
ggplotly(g)
```

In addition, I didn't have trouble using both color and size with the `iris` data set and the `plot_ly` function. 
Also if the categories are set to integers instead, there's no issue.
```
dt = data.frame(category = c(1, 2, 3), X = c(1,2,3), Y = c(3,4,5))
test <- plot_ly(data = dt, x = X, y = Y, mode = "markers",
                color = category, size = X)

test
```
As seen here: https://plot.ly/~chelsea_lyn/11140/y-vs-x/
Reference: http://community.plot.ly/t/how-to-color-plotly-bubble-chart-by-any-category-variable/466

**Comment by cpsievert** [comment]
Closed via d2bf2a1eb56d824a091e2cc9afea09a5968dd050.
