### ISSUE TITLE
scale_y_continuous() breaks the upload to plotly

### ISSUE THREAD

**Issue by smach** [ropensci/plotly#473]
Not pressing, just thought you might like to know: When I added a line

    scale_y_continuous(breaks = seq(0, 100, 10))

to my ggplot2 graph, it rendered fine locally with `ggplotly()` but when I tried to upload to my plotly account with `plotly_POST()`, I received a somewhat cryptic error message "Error: Uh oh, an error occurred on the server. "  I eventually discovered that it was the `scale_y_continuous()` command that was the problem.

**Comment by cpsievert** [comment]
This should be fixed in f1900cc3cd464408a60ffadfe3e95460747430e0. Let us know if you still have problems.
