### ISSUE TITLE
plotly_POST(p, sharing="secret") should return the sharekey in url

### ISSUE THREAD

**Issue by cldougl** [ropensci/plotly#474]
plotly_POST(p, sharing="secret") should return the sharekey in url ..similar to how the sharekey is printed in the python api: https://plot.ly/python/privacy/

**Comment by cldougl** [comment]
cc @yankev

**Comment by cpsievert** [comment]
I think you want "hidden", not "secret":

```r
> x <- plotly_POST(plot_ly(), sharing="hidden")
No encoding supplied: defaulting to UTF-8.
Success! Created a new plotly here -> https://plot.ly/~cpsievert/9689?share_key=KkpqfcY2FA5kJhU5QwnUs5
> x$url
[1] "https://plot.ly/~cpsievert/9689?share_key=KkpqfcY2FA5kJhU5QwnUs5"
```

**Comment by cpsievert** [comment]
I suppose we should change it to "secret" for consistency sake?

**Comment by cldougl** [comment]
ahh thanks!
yeah +1 for "secret" for consistency
