### ISSUE TITLE
plotly_IMAGE returning an empty file in RStudio

### ISSUE THREAD

**Issue by jackparmer** [ropensci/plotly#478]
To replicate:

```
fig <- get_figure("Adriano.Santos", 0)
plotly_IMAGE(fig, format = "png", out_file = "output.png")
```

Seems like an issue with the R client, because these image endpoints are working:
https://plot.ly/~Adriano.Santos/0.png
https://plot.ly/~Adriano.Santos/0.jpeg

**Comment by yankev** [comment]
So it seems like it works for a simple example:
```
figure <- plot_ly(data = iris, x = Sepal.Length, y = Petal.Length, mode = "markers")
plotly_POST(figure)
gf<-get_figure("kevintest",41)
plotly_IMAGE(gf, format = "png", out_file = "output.png")
```

Though I've also taken a look at the result of the `plotly_IMAGE` call (ie: request) and I get the following response:
```
Response [https://api.plot.ly/v2/images]
  Date: 2016-03-04 16:21
  Status: 200
  Content-Type: image/png
<EMPTY BODY>
```

**Comment by yankev** [comment]
*Update*:
I played around with the REST API call a bit, and it seems that if you set `scale=1`, everything seems to work fine. 
ie:
```
plotly_IMAGE(fig, format = "png", out_file = "output2.png", scale = 1)
```
