### ISSUE TITLE
Workaround when no graphics device is available (Error: cannot open file 'Rplots.pdf')

### ISSUE THREAD

**Issue by yonicd** [ropensci/plotly#494]
i wrote a [shiny app](https://github.com/yonicd/Elections/tree/master/USA2016/shiny) with plotly and while testing it in the localhost provided with rstudio on windows it looked great. I then deployed it to [shinyapps.io](https://yonicd.shinyapps.io/USAElections/) and got the same result. But when I deploy it on an [ubuntu aws](http://54.191.51.69/Elections/USA2016/shiny) instance it goes crazy.... the date x axis scale is nonresponsive (only shows %x %T), the overlay for trends are all over the place, ... and more. The "bugs" are much more pronounced in the new version of the plotly package. Currently I reverted back to the cran version. 

what could be the specifications of the aws instance that is causing the plotly library to go crazy?

**Comment by cpsievert** [comment]
Hmm, it might have to do [`eval(parse())`](https://github.com/yonicd/Elections/blob/master/USA2016/shiny/server.r#L195), but could have to do with R/shiny server version you're running on your instance

**Comment by yonicd** [comment]
the `eval(parse(...))` is working on the other platforms so it shouldnt be a problem. i tried to remove the deb package to reinstall the server from scratch but couldnt for some reason:

this is after i reinstalled the server from the rstudio [site](https://www.rstudio.com/products/shiny/download-server/)

```
ubuntu@ip-172-31-24-42:~$ ls
shiny-server-1.4.1.759-amd64.deb  shiny-server-1.4.2.786-amd64.deb  shiny-server-1.4.2.786-amd64.deb.1
```

would these redundant versions be the cause the problem?

**Comment by yonicd** [comment]
I figured out its one problem that is causing a lot of the graphs to look bad. the dates get mixed up so the x date axis isnt monotonous. what could cause that?

when i install the current plotly package i get this error: `cannot open file 'Rplots.pdf'`
i thought it was from the ggsave function in the download handler but i removed that button and it still gives same error. (again this is only in the aws server)

**Comment by cpsievert** [comment]
Hmm, a minimal example of the date problem would be great. 

Are you using `devtools::install_github("ropensci/plotly")` to install?

**Comment by yonicd** [comment]
simple [example](http://54.191.51.69/plotlytest/), [r files](https://github.com/yonicd/plotlytest)

the plotly package version is in the ggtitle.

**Comment by cpsievert** [comment]
Thanks, I'll be creating a separate issue for that example

**Comment by yonicd** [comment]
i added the economics df to be sure its not "my data" that is causing the problem (its not). One weird by product of updating the plotly build is that its giving out an error of Rplots.pdf that it can produce. Currently i reverted it back again to the cran build to the plot will be shown

**Comment by cpsievert** [comment]
Can you provide code to replicate the `cannot open file 'Rplots.pdf'` error?

**Comment by yonicd** [comment]
its a byproduct of plotly installation. it is kind of hard to do since it comes up when i run shiny from the linux server. on my windows r/rstudio it is an error only when using ggsave because it cant write to the pdf file. 

this is an [example](http://stackoverflow.com/questions/24191231/ggsave-error-cannot-open-file) of other people getting the error. another [example](http://stackoverflow.com/questions/17348359/how-to-stop-r-from-creating-empty-rplots-pdf-file-when-using-ggsave-and-rscript)

**Comment by yonicd** [comment]
this is from the shiny-server log

```
root@ip-172-31-24-42:/var/log/shiny-server# cat plotlytest-shiny-20160313-072240-49377.log

Attaching package: ‘plotly’

The following object is masked from ‘package:ggplot2’:

    last_plot

The following object is masked from ‘package:graphics’:

    layout


Listening on http://127.0.0.1:49377
ERROR: [on_request_read] connection reset by peer
Warning: Error in <Anonymous>: cannot open file 'Rplots.pdf'
Stack trace (innermost first):
    76: <Anonymous>
    75: grid.Call
    74: convertUnit
    73: grid::convertHeight
    72: unitConvert
    71: gg2list
    70: plotly_build
    69: as.widget
    68: func
    67: output$TestPlot
     1: runApp
```

**Comment by cpsievert** [comment]
Ah, I have a feeling `grid.Call` is throwing that error because it can't open a device window. As [this suggests](http://stackoverflow.com/questions/17012518/why-does-this-r-ggplot2-code-bring-up-a-blank-display-device/17014195#17014195), instead of just evaluating `p`, try evaluating this:

```r
png("NUL")
p
dev.off()
```

Let me know how it goes!

**Comment by yonicd** [comment]
[works!](http://54.191.51.69/plotlytest/)

now the parser on the shinyAce is causing problems. but that is something workable.

thanks!

**Comment by yonicd** [comment]
A follow up remark/question. After i published the app and got many simultaneous users I get "too many open devices" error on plots. could this be a shiny thing or a result of the workaround we did for plotly?

**Comment by cpsievert** [comment]
Hmm, it's probably a limitation of your machine (it can only open so many graphics devices). Chalking this up as motivation for pursuing an approach that doesn't make calls to the graphics device as I elude to in https://github.com/ropensci/plotly/issues/489

**Comment by yonicd** [comment]
Is there any way to force close devices when an instance is running?

**Comment by dbuijs** [comment]
I had this exact issue. I found it was completely addressed by changing the owner and group of my shiny app folder to shiny:shiny (since all shiny apps are run as the shiny user).

**Comment by hutchike** [comment]
@dbuijs thanks! `chown -R shiny:shiny /srv/shiny-server` worked for me too 👍

**Comment by vielleicht** [comment]
I used the following code and it works with secondly update for hours
`if (names(dev.cur()) != "null device") dev.off()
pdf(NULL)
`
I first didn't use the `dev.off()` and then it crashed after some time.

**Comment by merl-dev** [comment]
So what is the bottom line on solving the problem `Warning: Error in <Anonymous>: cannot open file 'Rplots.pdf'`.

Am I to change owner as suggested by @dbuijs? and isn't this a bad hack?

or,

```
if (names(dev.cur()) != "null device") dev.off()
pdf(NULL)
```
And where are we supposed to put these lines?

**Comment by gcmicah** [comment]
can someone please tell me which file and where to add  pdf(NULL) ? thanks.

**Comment by z4chry** [comment]
@gcmicah it goes in server.R within the function that is generating the plot. 

What worked for me was `pdf(file = NULL)`. 

Here's what it looks like for me:
`      tm <- treemap(
        df,
        index   = c("Ch", "Q"),
        vSize   = "F",
        vColor  = "Ch",
        pdf(file = NULL)
      )`

**Comment by cbielow** [comment]
just to comment on some code here:
If you just do `pdf(file = NULL)`, you will open a new device every time this line is executed. Doing this in a server application, which might run for a long time, will probably lead to a crash at some point.

So, you have to close the device again. Thus, some people have suggested this:
```
if (names(dev.cur()) != "null device") dev.off()        ## bad idea
pdf(file = NULL)

# code which gave the 'Error: cannot open file 'Rplots.pdf')' here...
```
This is not optimal, because you are closing the plotting device of your caller (which might not be what he wanted!). Imagine your code being used in a report-generation script....
So, IMHO opening a new device and closing it after you are done is a better approach:
```
pdf(tempfile(pattern=".pdf")) ## create a real file, since the pdf(NULL) might not be able to fulfill all requests-
dummy_dev_id = dev.cur()   ## remember the device number
on.exit({                     # when leaving the function, close our device (avoid leaving zombies)
  if (dummy_dev_id %in% dev.list()) {
    dev.off(dummy_dev_id ) 
  } else warning("Dummy graphics device was closed by someone else. This should not have happened...")
})  

# code which gave the 'Error: cannot open file 'Rplots.pdf')' here...
```

**Comment by de-mim-1974** [comment]
Got 'cannot open file 'Rplots.pdf'' error, get not many results by google. Short Info to my solution (on Windows):
In the current R working directory, the user under whom the code was executed had no write permissions. After I had given write permissions to the directory, the error no longer occurred. So give write permissions or change the working directory by setwd() command.
