### ISSUE TITLE
Labels as null does not work with ggplotly

### ISSUE THREAD

**Issue by chrstphe** [ropensci/plotly#495]
I usually strip quite a lot of chart junk by setting labels to `labs(x=NULL, y=NULL, color = NULL)` but ggplotly ಠ_ಠ

# Reproducible example
Remove comment on labs row to cause unwanted behaviour.
```
library(plotly)
library(ggplot2)
library(scales)

# dates
dates <- seq(as.Date('2015-12-07'), as.Date('2016-02-29'), by = '7 days')

# Data
ca <- data.frame(week_begin_date = rep(dates, 3*2), 
                 sum_spend = rnorm(length(rep(dates, 3*2)), c(.2e7, 1e6, 3e6), 1000000), 
                 countrygrp = c('US', 'UK', 'ROW'), 
                 activitydays = rep(c('Dedicated', 'Casual'), each=length(rep(dates, 3*2))/2))

p.countries.revenue <- ggplot(ca, aes(as.Date(week_begin_date),
                                                  sum_spend, color = countrygrp)) +
  geom_line() + 
  geom_point() +
  facet_grid(~activitydays) + 
  #labs(x = NULL, y = NULL, color = NULL) +
  scale_y_continuous(labels = dollar, breaks = seq(0, 1e8, by=1e6)) +
  scale_x_date(date_breaks = '1 week', labels=date_format("W%V"))# + kingtheme("top", numcolors=ifelse(numcategories > 8, numcategories, 8), texttilt = T, grid = 'y', axis = F, border = F, textsize = 12)
p.countries.revenue

myplotlyplot <- ggplotly(p = p.countries.revenue)
myplotlyplot
```

**Comment by cpsievert** [comment]
Are you using the CRAN or github version? Github has a ton of improvements that should hit CRAN in the next couple days. You can install for now with `devtools::install_github("ropensci/plotly")`. That gives me this result:

![https://plot.ly/~cpsievert/9870](https://plot.ly/~cpsievert/9870.png)

I'll be submitting a patch shortly for the redundant legend entries

**Comment by chrstphe** [comment]
I was using the github version but it works now using the latest version (even the duplicated legend items are gone), thanks a lot!
