### ISSUE TITLE
Legend and X Axis DATE issue with Plotly latest DEV build

### ISSUE THREAD

**Issue by ahsanshah** [ropensci/plotly#498]
I see 2 issues with PLotlys latest DEV build. 

1.  How to change the hover over info on Linux X Date Axis which now defaults to Millisend for EPOCH

2.  How do we fix the legend positions as it does not accept the legend position options from MASTER plotly (pre Dev branch)

All code for this has been provided in the following closed case:  https://github.com/ropensci/plotly/issues/482

![image](https://cloud.githubusercontent.com/assets/14385814/13718512/b170a24a-e7b8-11e5-816b-56b4253ae845.png)

Thanks

**Comment by cpsievert** [comment]
The latest Github version should fix (1) and for (2) you can do something similar to [this](https://github.com/ropensci/plotly/issues/482#issuecomment-193502229)

**Comment by ahsanshah** [comment]
Ok so I fixed the legend with edits to the layout margin (issue #2)

However, for issue #1, even with the latest GITHUB version the MARKERS for the add_trace does NOT align with the DATE.  As you recommended I am using the following to show the markers:

x = as.numeric(startlocal) * 24 * 60 * 60 * 1000

Howwever, the hover over is not showing the DATE values.  Instead it still shows the milliseconds for the Epoch.  This was working fine with the older build.

![image](https://cloud.githubusercontent.com/assets/14385814/13721466/4bb84834-e7f6-11e5-81b3-5dedcebd6971.png)

**Comment by ahsanshah** [comment]
I also notice that autosize = "FALSE" or "F" does not prevent autosizing, that may be a separate issue.
