### ISSUE TITLE
Legend and X Axis DATE issue with Plotly latest DEV build #498

### ISSUE THREAD

**Issue by ahsanshah** [ropensci/plotly#501]
This issue is not resolved but as I cannot reopen it I am opening a new one:
https://github.com/ropensci/plotly/issues/498

As recommended, I have tries this with all 3 builds of Plotly:

install.packages("plotly")
devtools::install_github("ropensci/plotly")
devtools::install_github("ropensci/plotly@rewrite")

It seems there is still something that is wrong with how ggplotly converts Date X axis values in Linux.  

On Windows, I see  a proper hover of both the Markers and the geoms when I scroll across. It is showing the value of DATE.

![image](https://cloud.githubusercontent.com/assets/14385814/13725676/9bbca20a-e876-11e5-82ec-5aa362892004.png)

On Linux, with the CRAN build, the dates for the X axis do not align at all (see the original screenshot from https://github.com/ropensci/plotly/issues/482)

With the GITHUB and the LATEST DEV BRANCH. I added the following for as requested:

as.numeric(startlocal) * 24 * 60 * 60 * 1000,

However, this does NOT fix the following issues:

1.  The X Axis for the markers do not show DATES.  I only see the linux ms timestamp
2.  The hover over on the bottom does not show each DATE like it did on WIndows

![image](https://cloud.githubusercontent.com/assets/14385814/13725708/8ea3dab0-e877-11e5-8126-b66573b2b475.png)

**Comment by cpsievert** [comment]
For a number of technical reasons, going forward, we won't be showing hover info on the axis for plots generated via `ggplotly()`. Also, since you're using `ggplotly()`, then `add_trace()`, you'll have to format the hoverinfo yourself in that additional trace, for example:

```r
library(plotly)
g <- ggplot(economics, aes(date, unemploy)) + geom_line()

x <- as.numeric(economics$date) * 24 * 60 * 60 * 1000
y <- economics$pce
txt <- with(economics, paste0("PCE: ", pce, "<br>", "Date: ", date))

ggplotly(g) %>% add_trace(x = x, y = y, text = txt, hoverinfo = "text")
```
