### ISSUE TITLE
Autosize =F not working

### ISSUE THREAD

**Issue by ahsanshah** [ropensci/plotly#504]
It seems AUTOSIZE=F or "FALSE" does not work when I am using a ggplot conversion to plotly and adding a trace.  I tried setting AUTOSIZE in both the layout and the add_trace.  When I resize my browser window it is changing and rearranging my plots.

Note that I am plotting this on a Shiny Dashboard.  

Any idea how I can force it NOT to autosize when browser window is resized?

**Comment by cpsievert** [comment]
Duplicate of #403
