### ISSUE TITLE
geom_hline does not work in Shiny with log scale

### ISSUE THREAD

**Issue by NicholasClark** [ropensci/plotly#511]
My shiny code is a bit too much to include here, but when I use ggplotly in Shiny with geom_hline, the line disappears if I use type = 'log' in the x-axis or y-axis options in "layout". The same happens for geom_vline and geom_abline. 

Here is some toy code without the shiny app:
p <- ggplot(mtcars, aes(x = wt, y=mpg)) + geom_point()
p <- p + geom_hline(yintercept = 20, size = .25)
ggplotly(p)
layout(p, yaxis = list(type = 'log') )

The line will show in R, but not in a Shiny application.

**Comment by NicholasClark** [comment]
Note: When geom_hline does work, it does not extend indefinitely in both directions (in the way that a darkened x- or y-axis does), but shows up as a line segment instead. It would be nice if it extended so that it doesn't appear as a line segment when you zoom out.

**Comment by cpsievert** [comment]
Since you're using `ggplotly()`, why not use `scale_y_log10()`?

```r
p <- ggplot(mtcars, aes(x = wt, y=mpg)) + geom_point()
p <- p + geom_hline(yintercept = 20, size = .25) + scale_y_log10()
ggplotly(p)
```


If you change the axis type on a `ggplotly()` plot, you'll have to scale the data as well, which isn't super straightforward currently.

**Comment by NicholasClark** [comment]
This still doesn't have the desired effect.
Here is with scale_x_log10() (on my data):
![screen shot 2016-03-15 at 8 58 57 pm](https://cloud.githubusercontent.com/assets/7820491/13798922/1ecd850c-eaf1-11e5-9273-5760b38d7021.png)
Here is with layout(p, yaxis = list(type = 'log') ):
![screen shot 2016-03-15 at 8 59 52 pm](https://cloud.githubusercontent.com/assets/7820491/13798928/35556ca4-eaf1-11e5-8d87-db8d59fe09d3.png)

Notice the difference in the x-axis numbers. I would like the second scaling (between .0001 and 10) instead of the log values.
