### ISSUE TITLE
Too many active WebGL contexts. Oldest context will be lost

### ISSUE THREAD

**Issue by xzmagic** [ropensci/plotly#517]
I hava a proplem while use plot_ly 10times to create  10 surface plots. I get waring:Too many active WebGL contexts. Oldest context will be lost, so  plot not show but the first 9 plot can show normally.
warning details：
plotly-latest.min.js:19 WARNING: Too many active WebGL contexts. Oldest context will be lost.
plotly-latest.min.js:36 lost context

Is there a way workaround this proplem?

**Comment by cpsievert** [comment]
Hmm, this is probably a plotly.js limitation, right @etpinard?

**Comment by cpsievert** [comment]
Official response here -- https://github.com/plotly/plotly.js/issues/337
