### ISSUE TITLE
Possible to highlight Plotly Marker with a DT::table selection?

### ISSUE THREAD

**Issue by ahsanshah** [ropensci/plotly#528]
I am trying to use the following example to highlight specific markers on a plotly plot based on a row selection on a DT::table:  https://yihui.shinyapps.io/DT-rows/

It seems this does not work as intended for PLOTLY (I get either a "subscript out of bounds" or a "need finite xlim values" error).  Do you know if we can indeed use this functionality in PLOTLY or if I need a plotly equivalent to pass the Row selection to the plotly graph.   I presume this is possible and I am doing something wrong but want to confirm if Plotly does not allow this type of highlight of a marker based on a Table row selection.

**Comment by cpsievert** [comment]
Yes, it is possible, see here -- https://gist.github.com/cpsievert/2b291f20e5c90ac6ba6e

For future reference, please follow our [guidelines for opening issues](https://github.com/ropensci/plotly/blob/master/CONTRIBUTING.md#opening-issues)
