### ISSUE TITLE
update to plotly v1.7.0

### ISSUE THREAD

**Issue by timelyportfolio** [ropensci/plotly#529]
I am guessing you have a workflow for updating when new plotly.js releases hit like [`v1.7.0`](https://github.com/plotly/plotly.js/releases/tag/v1.7.0) this morning, so I wanted to file this issue to understand the workflow and potentially communicate to the broader user base.  I see the [script](https://github.com/ropensci/plotly/blob/master/inst/plotlyjs.R), so I assume that is the automated method of getting the newest `plotly.js`.

**Comment by cpsievert** [comment]
Yea, I should probably have a Makefile or something setup...I usually run that script interactively and manually edit the yaml...feel free to automate it if you want

**Comment by cpsievert** [comment]
Also, feel free to do the update yourself :)
