### ISSUE TITLE
'surface' not plotting in plotly 3.4.8

### ISSUE THREAD

**Issue by McClellandKemp** [ropensci/plotly#531]
Session info -------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.4 (2016-03-10)
 system   x86_64, mingw32             
 ui       RStudio (0.99.879)          
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Chicago             
 date     2016-03-24                  

Packages -----------------------------------------------------------------------------------------------------------------------
 package     * version date       source                            
 assertthat    0.1     2013-12-06 CRAN (R 3.2.2)                    
 base64enc     0.1-3   2015-07-28 CRAN (R 3.2.2)                    
 colorspace    1.2-6   2015-03-11 CRAN (R 3.1.3)                    
 curl          0.9.6   2016-02-17 CRAN (R 3.2.3)                    
 DBI           0.3.1   2014-09-24 CRAN (R 3.2.2)                    
 devtools    * 1.10.0  2016-01-23 CRAN (R 3.2.4)                    
 digest        0.6.9   2016-01-08 CRAN (R 3.2.4)                    
 dplyr         0.4.3   2015-09-01 CRAN (R 3.2.2)                    
 ggplot2     * 2.1.0   2016-03-01 CRAN (R 3.2.4)                    
 git2r         0.14.0  2016-03-13 CRAN (R 3.2.4)                    
 gridExtra     2.2.1   2016-02-29 CRAN (R 3.2.4)                    
 gtable        0.2.0   2016-02-26 CRAN (R 3.2.4)                    
 htmltools     0.3.5   2016-03-21 CRAN (R 3.2.4)                    
 htmlwidgets   0.6     2016-02-25 CRAN (R 3.2.4)                    
 httr          1.1.0   2016-01-28 CRAN (R 3.2.3)                    
 jsonlite      0.9.19  2015-11-28 CRAN (R 3.2.3)                    
 knitr         1.11    2015-08-14 CRAN (R 3.2.2)                    
 magrittr      1.5     2014-11-22 CRAN (R 3.1.3)                    
 memoise       1.0.0   2016-01-29 CRAN (R 3.2.4)                    
 munsell       0.4.3   2016-02-13 CRAN (R 3.2.4)                    
 plotly      * 3.4.8   2016-03-24 Github (ropensci/plotly@0f05881)  
 plyr          1.8.3   2015-06-12 CRAN (R 3.2.3)                    
 R6            2.1.2   2016-01-26 CRAN (R 3.2.3)                    
 Rcpp          0.12.3  2016-01-10 CRAN (R 3.2.3)                    
 rsconnect     0.3.79  2015-11-12 Github (rstudio/rsconnect@79f5016)
 rstudioapi    0.3.1   2015-04-07 CRAN (R 3.2.2)                    
 scales        0.4.0   2016-02-26 CRAN (R 3.2.4)                    
 tidyr         0.4.1   2016-02-05 CRAN (R 3.2.3)                    
 viridis       0.3.4   2016-03-12 CRAN (R 3.2.4)                    
 withr         1.0.1   2016-02-04 CRAN (R 3.2.3)                    
 yaml          2.1.13  2014-06-12 CRAN (R 3.2.2)

**Example**

> test <- structure(list(price = c(0.66, 0.89, 1.26, 1.35, 1.49, 1.58, 1.63, 1.81, 1.95, 2.15, 2.27, 2.3, 2.69, 2.73, 2.8, 2.87, 2.96, 3, 3.19, 3.24, 3.33, 3.39, 3.42, 3.47, 3.65, 3.79, 3.84, 3.88, 3.98, 4.11, 4.2, 4.25, 4.34, 4.39, 4.48, 4.57, 4.6, 4.71, 4.94, 4.99, 5.03, 5.1, 5.26, 5.49, 5.54, 5.63, 5.72, 5.86, 5.95, 6.09 ), quantity = c(1L, 1L, 2L, 1L, 2L, 1L, 3L, 1L, 2L, 10L, 1L, 1L, 4L, 1L, 3L, 2L, 1L, 1L, 1L, 3L, 2L, 9L, 1L, 3L, 1L, 2L, 4L, 1L, 5L, 1L, 4L, 2L, 1L, 3L, 2L, 1L, 1L, 2L, 2L, 4L, 1L, 3L, 1L, 1L, 3L, 2L, 1L, 2L, 1L, 2L), frequency = c(3L, 4L, 1L, 2L, 7L, 1L, 2L, 2L, 1L, 1L, 3L, 1L, 1L, 11L, 1L, 4L, 32L, 55L, 36L, 2L, 1L, 1L, 6L, 1L, 13L, 2L, 2L, 150L, 1L, 6L, 1L, 1L, 3L, 1L, 7L, 8L, 5L, 1L, 2L, 7L, 5L, 1L, 7L, 151L, 1L, 1L, 15L, 1L, 113L, 6L)), .Names = c("price", "quantity", "frequency"), row.names = c(NA, 50L), class = c("data.table", "data.frame")) 
> library(plotly)
> plot_ly(test, x = price, y = quantity, z = frequency, type = "surface")

![surface](https://cloud.githubusercontent.com/assets/5316929/14019118/295af3c4-f19f-11e5-87f7-9d606d48fdc5.PNG)

**Comment by cpsievert** [comment]
This is similar to #329, in the sense that you have to provide a numeric matrix to `z` and vectors to `x` and `y`
