### ISSUE TITLE
Garbled geom_tile plots

### ISSUE THREAD

**Issue by hardwhack** [ropensci/plotly#541]
Just getting started with plotly for R. Most of the plots look great and the ggplotly command makes it easy. I am having a problem with geom_tile plots however. Tried the demos at http://plot.ly/ggplot2/geom_tile/

The plot looks fine in R using ggplot2, i.e. when I type 'p' and hit return in R. When I use ggplotly(p), however, the plot is garbled. The axis, labeling, scale bars are fine but the actual values and image are garbled. Moving the cursor around shows that the colors correspond to what it thinks the data values should be, however the values are wrong.

I have tried this on two different Mac computers in both R and RStudio. Same behavior. Attaching pictures:
![untitled1](https://cloud.githubusercontent.com/assets/1630119/14368322/e20af684-fcd1-11e5-95b4-63ebafc5e6c7.png)
![untitled 2](https://cloud.githubusercontent.com/assets/1630119/14368324/e53eca9c-fcd1-11e5-988b-0869f674e5fe.png)

It looks like there is some patterning to the imported data. A stride or orientation problem?

**Comment by cpsievert** [comment]
You need the dev version

**Comment by hardwhack** [comment]
Thanks, that fixed the problem. To save anyone from trying to find out how to install dev version,

remove.packages('plotly')          # remove old version
devtools::install_github("ropensci/plotly")       #install dev version
