### ISSUE TITLE
Possible to default the legend and line selection?

### ISSUE THREAD

**Issue by ahsanshah** [ropensci/plotly#543]
This is more of a question than an issue but I have not been able to find an answer.  How do we default a selection of specific legend items. For instance if I have a list if ggplot geoms converted to plotly for various years and other cetagories...but I only want the current year trace to be auto selected...how would we code that? Is that possible?

**Comment by timelyportfolio** [comment]
As with the other issues, please provide some reproducible code, and I'll be happy to try to help.

**Comment by ahsanshah** [comment]
I attached an R script and some sample RDS files.  This should illustrate better.  Also, as I said, its more of a question on HOtW we can DEFAULT the trace versus an actual issue per se.  

Here is the screenshot and what I am intending to do.  There will be a lot of traces and I would like to default the traces to a specific set (e.g CURRENT YEAR) versus showing the user all of them at once.  

![image](https://cloud.githubusercontent.com/assets/14385814/14404766/2b2c792a-fe4c-11e5-9ddd-817b3208ec5f.png)

[Support.zip](https://github.com/ropensci/plotly/files/211339/Support.zip)

**Comment by ahsanshah** [comment]
In general, can we somehow dynamically modify the legend selections?  For example, if I wanted to uncheck all the selections versus clicking on each one or use a Shiny reactive to control what gets selected/unselected?  Trying to do this on the R side as a reactive with subsets will get messy so i am hoping that Plotly can allow me to adjust the legend selections dynamically or via a reactive in Shiny.

**Comment by cpsievert** [comment]
@ahsanshah feel free to file a feature request to https://github.com/plotly/plotly.js
