### ISSUE TITLE
Issue with hover value on stacked barplot

### ISSUE THREAD

**Issue by Pauline6010** [ropensci/plotly#557]
I am having troubles getting the good value rendered in the hover text with stacked barplot.
Here is a reproducible example : 

```
 #data
dataf = data.frame(Espece = c("A","A","B","B","C","C"),
                   Type = c("A","B","A","B","A","B"),
                   Value = c(2,2,5,1,6,0))
#ggplot
gg = ggplot(dataf, aes(x = Espece, y = Value, fill = Type)) + 
  geom_bar(stat = "identity") +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

#plotly
p <- ggplotly(gg)
p
```

The value for Espece A, type B is 4 whereas it should be 2. It renders stacked values instead of individual values. Is there a way to fix this ?

Thank you very much,
Pauline

**Comment by yankev** [comment]
Just another example of the possible issue, while running this example: https://plot.ly/ggplot2/geom_bar/#using-geom_bar-for-variable-comparison

```R
library(plotly)

DF <- read.table(text="Rank F1     F2     F3
1    500    250    50
2    400    100    30
3    300    155    100
4    200    90     10", header=TRUE)

library(reshape2)
DF1 <- melt(DF, id.var="Rank")

p <- ggplot(DF1, aes(x = Rank, y = value, fill = variable)) +
  geom_bar(stat = "identity")

ggplotly(p)
```

The hover option no longer displays the values of the different fills (at the same time), but displays each individually and with the cumulative sum, rather than just its own value.

![screen shot 2016-04-20 at 11 22 56 am](https://cloud.githubusercontent.com/assets/12302455/14680156/42e1b49e-06ea-11e6-97fa-188824d3e755.png)

Before: 
![screen shot 2016-04-20 at 11 24 55 am](https://cloud.githubusercontent.com/assets/12302455/14680332/ee8745de-06ea-11e6-939c-fba84efc641c.png)

```R
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.9.4 (Mavericks)

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reshape2_1.4.1  jsonlite_0.9.19 httr_1.1.0      plotly_3.4.13   ggplot2_2.1.0  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.4        magrittr_1.5       munsell_0.4.3      colorspace_1.2-6  
 [5] R6_2.1.2           stringr_1.0.0      plyr_1.8.3         dplyr_0.4.3       
 [9] tools_3.2.3        parallel_3.2.3     grid_3.2.3         gtable_0.2.0      
[13] DBI_0.3.1          htmltools_0.3.5    yaml_2.1.13        digest_0.6.9      
[17] assertthat_0.1     gridExtra_2.2.1    RColorBrewer_1.1-2 tidyr_0.4.1       
[21] base64enc_0.1-3    htmlwidgets_0.6    viridis_0.3.4      curl_0.9.7        
[25] labeling_0.3       stringi_1.0-1      scales_0.4.0    
```

**Comment by Pauline6010** [comment]
Any idea ?

**Comment by Evizero** [comment]
I am observing the same issue

**Comment by cpsievert** [comment]
> The hover option no longer displays the values of the different fills (at the same time)

Use the "compare data on hover" button in the mode bar and/or `layout(..., hovermode = "x")` if you want to ensure all the values are displayed
