### ISSUE TITLE
Hyperlink in Annotation

### ISSUE THREAD

**Issue by romario076** [ropensci/plotly#558]
If set "text" in annotations Layout as: 
layout(annotations=list(text=https://www.google.com.ua/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=plotly+ ))

It wouldnt work. If make link without question mark - it would work. I think, problem is in question mark.
How fix it?
Pllease, help.

**Comment by cpsievert** [comment]
You need `<a>` tags. This page has an example -- https://plot.ly/r/choropleth-maps/

**Comment by romario076** [comment]
Yes, i've made it with <a>. It works when link is without "?". When link contains "?" it didnt work.

**Comment by timelyportfolio** [comment]
@romario076 The `&` actually appears to be causing the problem.  Not an answer, but will you let me know if this works?

```
#issue https://github.com/ropensci/plotly/issues/558#issuecomment-213320496

library(plotly)

plot_ly(
  cars,
  x=speed,
  y=dist,
  type='scatter'
) %>%
  layout(
    title = '<a href="https://www.google.com.ua/search?q=plotly">link</a>'
  )
```

**Comment by cpsievert** [comment]
For a more general solution, use something like `curl::curl_escape()`

```r
library(plotly)

plot_ly(
  cars,
  x=speed,
  y=dist,
  type='scatter'
) %>%
  layout(
    title = sprintf(
      '<a href="%s">link</a>',
      curl::curl_escape(
        "https://www.google.com.ua/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=plotly+"
      )
    )
  )
```
