### ISSUE TITLE
geom_bar(stat='identity') has problems with negative values 

### ISSUE THREAD

**Issue by cpsievert** [ropensci/plotly#560]
http://community.plot.ly/t/inversion-negative-values-in-ggplotly/875

``` r
d <- data.frame(
    x = LETTERS[1:10], 
    y = -5:4, 
    g = rep(c('A','B'), each = 5)
)

p <- ggplot(data = d, aes(x = x, y = y, fill = g)) +
    geom_bar(stat='identity')
ggplotly(p)
```

**Comment by timelyportfolio** [comment]
Any clues here?  Happy to work on this.

**Comment by cpsievert** [comment]
[This](https://github.com/ropensci/plotly/blob/master/R/layers2traces.R#L430) is the source of the problem (that subtraction is essentially assuming positive ymin/ymax values)

**Comment by cpsievert** [comment]
We'll probably need to switch from `barmode='stacked'` to `'relative'` to fix this issue -- https://github.com/plotly/plotly.js/pull/517

**Comment by timelyportfolio** [comment]
Just in case somebody needs this before we fix, we can accomplish with `plot_ly`.

```
plot_ly(
  data = d,
  x = x,
  y = y,
  color = g,
  type = "bar"
) %>%
  layout(
    xaxis = list(type="category", categoryorder="category ascending")
  )
```

**Comment by fabiangehring** [comment]
+1, already an idea when this one will be fixed?

**Comment by taylorturneriv** [comment]
Looks like I'm not the only one who has issue with this . . . Any update on the fix? Thanks!

**Comment by fabiangehring** [comment]
Unfortunately @timelyportfolio 's fix does not work for orientation = 'h'

**Comment by cortinah** [comment]
Any updates regarding a fix for the negative bars turning positive? thank you very much

**Comment by lwasser** [comment]
hello! i am having the same issue. curious about whether a fix may be in the works. I use this with my class!

**Comment by zhdanchik** [comment]
Hello, I'm have the same problem... UP this issue
