### ISSUE TITLE
Want convert renderGvis(gvischart to plotly

### ISSUE THREAD

**Issue by thotaanil** [ropensci/plotly#575]
Hi,

I am using the below code in shiny APP,
output$chart18 <- renderGvis({
 
    gvisLineChart(as.data.frame(datasetInput()[[18]]),xvar=colnames(as.data.frame(datasetInput()[[18]]))[1], yvar=c(colnames(as.data.frame(datasetInput()[[18]]))[2],colnames(as.data.frame(datasetInput()[[18]]))[3])
)}

Now I want to change and use Plotly "Basic Time Series Plot" ,

Please let me know, how can I do that.

I have tried it, but getting below warning with no output.

Warning in geom2trace.default(dots[[1L]][[7L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
  geom_GeomDotplot() has yet to be implemented in plotly.
  If you'd like to see this geom implemented,
  Please open an issue with your example code at
  https://github.com/ropensci/plotly/issues

**Comment by cpsievert** [comment]
Please [read the guidelines](https://github.com/ropensci/plotly/blob/master/CONTRIBUTING.md#opening-issues) for opening issues.
