### ISSUE TITLE
Smart axis type defaults

### ISSUE THREAD

**Issue by royr2** [ropensci/plotly#578]
@cpsievert @timelyportfolio I was trying to answer [this question](http://stackoverflow.com/questions/37122216/plotly-r-converts-numeric-factor-levels-to-numeric-values) on SO and came across this: 

```
library(plotly)

df <- data.frame(x = c(1, 2, 4, 8, 16, 32), y = 1:6)
df$x <- as.factor(df$x)
```

```
# Works fine
p <- ggplot(df, aes(x = x, y = y)) + geom_point()
p
```
![image](https://cloud.githubusercontent.com/assets/6601579/15136076/43dc8c8c-169b-11e6-9fc2-ee027713343b.png)
```
# Looks wrong
pp <- plot_ly(df, x = x, y = y, mode = "markers")
pp
```
![image](https://cloud.githubusercontent.com/assets/6601579/15136082/4eee08bc-169b-11e6-8d87-4e5b17a0c8d1.png)
```
# works fine
ggplotly(p)
```
![image](https://cloud.githubusercontent.com/assets/6601579/15136087/5862cffe-169b-11e6-98e8-f83a7209a5ba.png)

**Comment by royr2** [comment]
I am not sure if this is by design? In which please close the issue...

**Comment by cpsievert** [comment]
Currently you need to manually specify that you have a categorical axis.

```r
plot_ly(df, x = x, y = y, mode = "markers") %>% layout(xaxis = list(type = "category"))
```

Right now we just sent the factor levels as a string to plotly.js

```r
plotly_build(plot_ly(df, x = x, y = y, mode = "markers"))$data[[1]]$x
#> [1] 1000  2000  4000  8000  16000 32000
#> Levels: 1000 2000 4000 8000 16000 32000
```

Based on those strings, plotly.js (correctly) thinks that you want a numeric axis. In the future, we should set smarter axis type defaults based on the variable mappings.

**Comment by royr2** [comment]
Ah okay got it. I haven't used `list(type = "category")` before. Good to know. Thanks ~

**Comment by gorgitko** [comment]
Hello, I am still having problem and even `layout(xaxis = list(type = "category"))` didn't help. My data:

```
> nrow(neg_summary)
305
> head(neg_summary)

Sentrix_Name Sentrix_ID max      third_quartile median    mean      first_quartile min     
4569632047_A 4569632047 258.6660 104.0361       92.18008  95.01825  82.17424       58.23933
4569632047_B 4569632047 268.4030 110.9371       98.80281  102.25254 88.49149       61.55940
4569632047_C 4569632047 241.0056 107.2028       95.66486  98.47206  85.11318       53.73413
4569632047_D 4569632047 266.8456 111.0126       99.76010  102.21811 88.52625       60.53619
4569632047_E 4569632047 265.3769 109.5106       96.99408  100.01776 85.60737       57.35104
4569632047_F 4569632047 273.5587 118.1988       103.79723 107.54025 91.06809       62.88250
```

Plotting:

```
plot_ly(neg_summary, y = ~Sentrix_Name, x = ~max, name = "maximum",
        type = "scatter", mode = "lines+markers") %>%
       layout(yaxis = list(type = "category")) %>%
       add_trace(x = ~third_quartile, name = "third quartile", mode = "lines+markers") %>%
       add_trace(x = ~median, name = "median", mode = "lines+markers") %>%
       add_trace(x = ~first_quartile, name = "first quartile", mode = "lines+markers") %>%
       add_trace(x = ~min, name = "minimum", mode = "lines+markers")
```

Result:

![plotly](https://user-images.githubusercontent.com/15315342/32616639-1b0a3a1a-c573-11e7-98f6-fd2765688ba6.png)

Categorical variables at y-axe aren't in the same order as `neg_summary$Sentrix_Name` and even there aren't all. This should be the order:

```
> neg_summary$Sentrix_Name
[1] 4569632047_A 4569632047_B 4569632047_C 4569632047_D 4569632047_E 4569632047_F 4569632048_A 4569632048_B 4569632048_C 4569632048_D 4569632048_E
...
305 Levels: 4569632047_A 4569632047_B 4569632047_C 4569632047_D 4569632047_E 4569632047_F 4569632048_A 4569632048_B 4569632048_C ... 5226121006_F
```
