### ISSUE TITLE
Updating rendered plot in shiny

### ISSUE THREAD

**Issue by TonyDIRL** [ropensci/plotly#580]
Hi,

Is it possible to update a plotly graph which has already rendered (in shiny) without rerendering the entire plot? An example usage would be initially plotting a large time series and then wishing to add various annotations without rerendering the entire plot. 

Looking online it seems it might be possible with the restyle functionality.
https://plot.ly/javascript/plotlyjs-function-reference/

Was wondering if such a feature is available in R.

Cheers

**Comment by cpsievert** [comment]
In theory this is possible with clever use of `htmlwidgets::onRender()`, but I'll definitely think about a better way to achieve this without having to write JavaScript.

**Comment by TonyDIRL** [comment]
Thank you - I will investigate htmlwidgets

**Comment by timelyportfolio** [comment]
Perhaps, we could look into a `proxy` pattern similar to leaflet.

**Comment by hherrada** [comment]
DT also provides this functionality through a `proxy` variable. It'be great to have the same functionality for plotly.

http://rstudio.github.io/DT/shiny.html (example at the bottom of the page)
