### ISSUE TITLE
plotly_POST not embedding plot as expected

### ISSUE THREAD

**Issue by chepec** [ropensci/plotly#581]
So this is a little weird, and I haven't been able to figure it out after reading the documentation ([1](https://plot.ly/r/), [2](https://plot.ly/r/file-options/), [3](https://plot.ly/rest/), [4](https://plot.ly/ggplot2/)).

I generated a plot using ggplot2, which I then embed in a R Markdown document published as HTML on the web (Jekyll blog, but that's beside the point).

```
```{r lnb-160411-quality-fits, echo=FALSE, results="asis"}
p <- ggplot() + ...
plotly_POST(p, filename = "lnb-160411-poor-fits", fileopt = "overwrite", sharing = "public")
```
This produces the following HTML:

```
<iframe src="https://plot.ly/~chepec/151" width="800" height="600" id="igraph" scrolling="no" seamless="seamless" frameBorder="0">
</iframe>
```
Which *does not* produce the expected result, i.e., an embedded plot, but instead **embeds the entire Plotly page** (see below).
![google chrome](https://cloud.githubusercontent.com/assets/979546/15198443/a643a1e8-17d7-11e6-8072-68d92bfa6773.png)

I confirmed that the URL in the iframe above is in fact the output of `plotly_POST`, 

```
> x <- plotly_POST(p, filename = "lnb-160411-poor-fits", fileopt = "overwrite", sharing = "public")
No encoding supplied: defaulting to UTF-8.
Success! Modified your plotly here -> https://plot.ly/~chepec/151
> str(x)
List of 5
 $ url     : chr "https://plot.ly/~chepec/151"
 $ message : chr ""
 $ warning : chr ""
 $ filename: chr "lnb-160411-poor-fits"
 $ error   : chr ""
 - attr(*, "class")= chr "figure"
```
and I think I can confirm that Plotly shows the embed *only* when appending `.embed` to the URL (the HTML below produces the expected embedded plot):

```
<iframe src="https://plot.ly/~chepec/151.embed" width="800" height="600" id="igraph" scrolling="no" seamless="seamless" frameBorder="0">
</iframe>
```

I think this must be an issue with `plotly_POST`? It should return the URL of an embed plot, not the whole page. By the way, this behaviour must have changed quite recently because the very same `plotly_POST(...)` call produced a properly embedded plot just a month ago.

**Comment by cpsievert** [comment]
Thanks!!
