### ISSUE TITLE
ggplotly with aes out of ggpot or geom.

### ISSUE THREAD

**Issue by jpuigde** [ropensci/plotly#589]
```{r}
require(ggplot2)
require(plotly)

gg           <- ggplot(diamonds[1:10,])
works        <- gg + geom_point( aes( x, y, colour = z) )
doesnt_works <- gg + aes( x, y, colour = z) + geom_point ()

works                  # ok
doesnt_works           # ok
ggplotly(works)        # ok
ggplotly(doesnt_works) # NOT ok

#Error in if (aesName %in% c("x", "y")) { : argumento tiene longitud cero
```
I think in plotly::gg2list on line 130

_argumento tiene longitud cero_ means _argument has zero length_

> devtools::session_info()
Session info -----------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.1 (2015-06-18)
 system   x86_64, linux-gnu           
 ui       RStudio (0.99.893)          
 language es_ES                       
 collate  es_ES.UTF-8                 
 tz       <NA>                        
 date     2016-05-19                  

>Packages ---------------------------------------------------------------------------------------------------------------------------------------------------------------
 package     * version date       source        
 assertthat    0.1     2013-12-06 CRAN (R 3.2.1)
 base64enc     0.1-3   2015-07-28 CRAN (R 3.2.1)
 chron         2.3-47  2015-06-24 CRAN (R 3.2.1)
 colorspace    1.2-6   2015-03-11 CRAN (R 3.2.0)
 DBI           0.4-1   2016-05-08 CRAN (R 3.2.1)
 devtools      1.11.1  2016-04-21 CRAN (R 3.2.1)
 digest        0.6.9   2016-01-08 CRAN (R 3.2.1)
 dplyr         0.4.3   2015-09-01 CRAN (R 3.2.1)
 DT            0.1.45  2016-03-10 local         
 ggplot2     * 2.1.0   2016-03-01 CRAN (R 3.2.1)
 ggthemes      3.0.3   2016-04-09 CRAN (R 3.2.1)
 gridExtra     2.2.1   2016-02-29 CRAN (R 3.2.1)
 gtable        0.2.0   2016-02-26 CRAN (R 3.2.1)
 htmltools     0.3.5   2016-03-21 CRAN (R 3.2.1)
 htmlwidgets   0.6     2016-02-25 CRAN (R 3.2.1)
 httr          1.1.0   2016-01-28 CRAN (R 3.2.1)
 jsonlite      0.9.20  2016-05-10 CRAN (R 3.2.1)
 knitr         1.13    2016-05-09 CRAN (R 3.2.1)
 labeling      0.3     2014-08-23 CRAN (R 3.2.0)
 lattice       0.20-33 2015-07-14 CRAN (R 3.2.1)
 magrittr      1.5     2014-11-22 CRAN (R 3.2.0)
 MASS          7.3-42  2015-07-02 CRAN (R 3.2.1)
 Matrix        1.2-2   2015-07-08 CRAN (R 3.2.1)
 memoise       1.0.0   2016-01-29 CRAN (R 3.2.1)
 munsell       0.4.3   2016-02-13 CRAN (R 3.2.1)
 plotly      * 3.4.13  2016-04-12 CRAN (R 3.2.1)
 plyr          1.8.3   2015-06-12 CRAN (R 3.2.1)
 R6            2.1.2   2016-01-26 CRAN (R 3.2.1)
 Rcpp          0.12.4  2016-03-26 CRAN (R 3.2.1)
 rmarkdown     0.9.6   2016-05-01 CRAN (R 3.2.1)
 rpart         4.1-10  2015-06-29 CRAN (R 3.2.1)
 rsconnect     0.4.3   2016-05-02 CRAN (R 3.2.1)
 rstudioapi    0.5     2016-01-24 CRAN (R 3.2.1)
 scales        0.4.0   2016-02-26 CRAN (R 3.2.1)
 tidyr         0.4.1   2016-02-05 CRAN (R 3.2.1)
 viridis       0.3.4   2016-03-12 CRAN (R 3.2.1)
 withr         1.0.1   2016-02-04 CRAN (R 3.2.1)
 yaml          2.1.13  2014-06-12 CRAN (R 3.2.0)

**Comment by cpsievert** [comment]
Change 

```r
doesnt_works <- gg + aes( x, y, colour = z) + geom_point ()
```

to 

```r
doesnt_works <- gg + geom_point(aes( x, y, colour = z))
```

**Comment by jpuigde** [comment]
Yes, I already knew that. 

>`works        <- gg + geom_point( aes( x, y, colour = z) )` 

was to show that

It is still a improve to build if you want that ggplotly does what it says to.

> Create plotly graphs using ggplot2 syntax.

ggplot2 rely does not do it completely... yet. That's all.

srry, I miss my point :P
Is a rely cool feature ^^ (integrate ggplot on plotly) I love it.
