### ISSUE TITLE
Converting R plotly object to JSON. 

### ISSUE THREAD

**Issue by contactlp** [ropensci/plotly#590]
Hi , I have tried to search, but I was not able to find how I can R plotly object to json. It will be very helpful if you can help me with this one. 

Thanks
Lav

**Comment by cpsievert** [comment]
I'd use something like this:

```r
plotly_json <- function(p, ...) {
  plotly:::to_JSON(plotly_build(p), ...)
}

plotly_json(plotly_empty(), pretty = TRUE)
```

For future reference, please read the [contributing guidelines](https://github.com/ropensci/plotly/blob/master/CONTRIBUTING.md) before opening issues.

**Comment by Alchemyst2802** [comment]
can we reverse the process, convert from json to R plotly object

**Comment by cpsievert** [comment]
Yes, use `jsonlite::fromJSON` to read in the JSON as an R list, then `plotly::as_widget()` to convert the list to a plotly (widget) object.

**Comment by err0w** [comment]
I am trying to use jsonlite::fromJSON and then plotly::as_widget() but the final plot comes out to be emplty. It has both the axes but no data points.

**Comment by cpsievert** [comment]
This advice is quite old, try using `plotly:::from_JSON()` to convert the JSON to a list
