### ISSUE TITLE
Warning: replacing previous import 'ggplot2::last_plot' by 'plotly::last_plot' when loading 'heatmaply'

### ISSUE THREAD

**Issue by talgalili** [ropensci/plotly#598]
It seems that since both ggplot2 and plotly use last_plot that this triggers a warning when importing from both packages, see:
https://travis-ci.org/talgalili/heatmaply/builds/132391290

I am not sure how to solve this.

**Comment by cpsievert** [comment]
This happens because you have 

```
import(ggplot2)
import(plotly)
```

in your DESCRIPTION. I hope to have a more general solution down the road, but for now you could use `importFrom` to import just the plotly functions you need internally, as this post describes -- http://stackoverflow.com/questions/10325231/when-writing-my-own-r-package-i-cant-seem-to-get-other-packages-to-import-corr

**Comment by talgalili** [comment]
Thanks @cpsievert 
I've now made this change so I won't have this conflict.

A longer term solution (especially as more package will likely import from both plotly and ggplot), is to rename `last_plot` to something like `last_plotly`.

What do you think?

**Comment by cpsievert** [comment]
We might not even need `plotly::last_plot()` going forward...it really only exists because of the way non-standard evaluation currently works which will hopefully change for the better within the next couple months

**Comment by cpsievert** [comment]
`last_plot` is now deprecated as of version 4.0

**Comment by Shicheng-Guo** [comment]
data.table and dply have similar problem. R should have a best solution to avoid these issues. 
```
Warning messages:
1: replacing previous import ‘data.table::last’ by ‘dplyr::last’ when loading ‘pameta’
2: replacing previous import ‘data.table::first’ by ‘dplyr::first’ when loading ‘pameta’
3: replacing previous import ‘data.table::between’ by ‘dplyr::between’ when loading ‘pameta’
4: replacing previous import ‘readr::guess_encoding’ by ‘rvest::guess_encoding’ when loading ‘pameta’
```
