### ISSUE TITLE
Missing labels when using subplot with geom_tile

### ISSUE THREAD

**Issue by talgalili** [ropensci/plotly#599]
Self contained example:
```r
library(ggplot2)
# If you want to draw arbitrary rectangles, use geom_tile() or geom_rect()
df <- data.frame(
  x = rep(c(2, 5, 7, 9, 12), 2),
  y = rep(c(1, 2), each = 5),
  z = factor(rep(1:5, each = 2)),
  w = rep(diff(c(0, 4, 6, 8, 10, 14)), 2)
)
p <- ggplot(df, aes(x, y)) +
  geom_tile(aes(fill = z))
```

Using ggplotly works fine:
```r
library(plotly)
ggplotly(p)
```

![image](https://cloud.githubusercontent.com/assets/976006/15491793/f2922070-217c-11e6-94d7-9b3d5019dadf.png)

But using subplot makes the left labels disappear:

```r
library(plotly)
subplot(plotly_empty(), p, nrows = 1, widths = c(.2,.8), margin = 0,
        shareX = TRUE, shareY = TRUE, titleX = FALSE, titleY = FALSE)
```

![image](https://cloud.githubusercontent.com/assets/976006/15491808/1586fe02-217d-11e6-99c5-46104c2ec06e.png)

This bug is important for heatmaply, since we get truncated labels, for example:

```r
devtools::install_github("ropensci/plotly")
devtools::install_github('talgalili/heatmaply')
library(heatmaply)
heatmaply(mtcars, k_row = 3, k_col = 2)
```

![image](https://cloud.githubusercontent.com/assets/976006/15491838/4ea404fa-217d-11e6-8c2b-87172af60f52.png)

**Comment by cpsievert** [comment]
In your minimal example, the labels disappear because you have specified `shareY = TRUE`. Unfortunately, it isn't possible to both draw interior tick labels and coordinate zoom/pan.

Fortunately, this isn't really a problem for the truncated labels you're getting in `heatmaply()`. You can just add to the plot margin:

```r
heatmaply(mtcars, k_row = 3, k_col = 2) %>% layout(margin = list(l = 130, b = 20))
```

**Comment by talgalili** [comment]
Hi @cpsievert 
Is there a way to know the needed margin values without forcing the user to supply them?
If so, I would rather calculate the needed values automatically for the user.

Thanks!

**Comment by cpsievert** [comment]
We could be doing a better job of this in `ggplotly()` (or really, anytime `layout.axisid.ticktext` is supplied). Feel free to post another issue with a minimal example to remind me to revisit :)

**Comment by talgalili** [comment]
Hi @cpsievert 
I don't know exactly when `layout.axisid.ticktext` is supplied, but I found another example of the text not showing properly and opened an issue for it (#600).
I hope this demonstrates the same problem.

Thanks for the help, fixing this would be very valuable for heatmaply.

Cheers,
Tal
