### ISSUE TITLE
Make ggplotly() work better anytime layout.axisid.ticktext is supplied

### ISSUE THREAD

**Issue by talgalili** [ropensci/plotly#600]
This affects issue #599 .

Minimal example:

``` r
library(ggplot2)
data(diamonds)
diamonds$cut <- paste("Super Dee-Duper extra long",as.character(diamonds$cut))
p <- qplot(cut,carat,data=diamonds,geom="boxplot") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
p
```

![image](https://cloud.githubusercontent.com/assets/976006/15492522/c7b935c0-2184-11e6-86a1-acecd0cd2d7c.png)

``` r
library(plotly)
ggplotly(p) # right most label is cut
```

![image](https://cloud.githubusercontent.com/assets/976006/15492532/dd42c712-2184-11e6-9e78-6a6e6a16436f.png)

**Comment by cpsievert** [comment]
I believe the new-ish auto-margin support fixed this issue.
