### ISSUE TITLE
Calling print on ggplotly acts differently to print on ggplot

### ISSUE THREAD

**Issue by Henry-E** [ropensci/plotly#602]
When knitting together an rmarkdown document with multiple graphs created in a loop and using the _results = "asis"_ chunk option, it is necessary to print plots to get them to appear. This functionality does not appear to be implemented for ggplotly?

```
---
title: "Untitled"
output: html_document
---

```{r, results='asis'}
library(ggplot2)
library(plotly)
Values = names(mtcars)[1:4]
mtcars$gear <- as.factor(mtcars$gear)
for(v in Values){
  # prints the graph as expected
  print(ggplot(mtcars, aes(x=carb, y = v, shape=gear)) + geom_point())
  # nothing comes out the other end for ggplotly
  print(ggplotly(ggplot(mtcars, aes(x=carb, y = v, shape=gear)) + geom_point()))
}
```(delete this comment, only here because code chunks in github have the same (```) shortcut as r chunks)
```

**Comment by cpsievert** [comment]
See https://github.com/ropensci/plotly/issues/273#issuecomment-195611009

**Comment by Henry-E** [comment]
For anyone else who comes across this, it works but requires print() to be used on the output if used inside of another for loop. Thanks for the help.
