### ISSUE TITLE
Selectively turn shareX/shareY off for a plot in subplot

### ISSUE THREAD

**Issue by talgalili** [ropensci/plotly#605]
I want to add a histogram in the corner of heatmaply, but it always comes out with distorted proportions because of shareX/shareY are set to TRUE.

It would be great if there would be a "dontshare" function (or some other name), that would allow to do something like:

``` r
p1 <- plot_ly(economics, x = date, y = uempmed, showlegend = F)
p2 <- plot_ly(economics, x = date, y = unemploy, showlegend = F)
subplot(p1, p2, dontshare(p1), p2, nrows = 2, shareY = TRUE)
```

And that when dontshare is used - it won't be synced to the other plots.

Thanks.

**Comment by cpsievert** [comment]
Can you use the recursive quality of `subplot()` to acheive the same effect?

```r
p1 <- plot_ly(economics, x = ~date, y = ~uempmed, showlegend = F)
p2 <- plot_ly(economics, x = ~date, y = ~unemploy, showlegend = F)
s1 <- subplot(p1, p2, shareY = TRUE)
s2 <- subplot(p1, p2)
subplot(s1, s2, nrows = 2)
```
