### ISSUE TITLE
knit2html not producing plotly graphs in RStudio

### ISSUE THREAD

**Issue by jandocastro** [ropensci/plotly#609]
If I have a .Rmd file and use the "Knit HTML" button in RStudio, the resulting html will render appropriately. However, if I use knit2html (before was using knitr::knit, then markdown::markdownToHTML), the resulting html is fine, but the plotly graphs are not rendered. There is a reference to PhantomJS not found?

Thanks for any and all assistance!

**Comment by cpsievert** [comment]
Hmm, if you really are using `knit2html`, and not something like `knit2pdf`, its probably a knitr problem and you should open an issue there.

PS. If you try to render an htmlwidget in anything other than an html doc, knitr uses webshot to grab a static image to place in the final output. webshot relies on [phantomjs](http://phantomjs.org/)

**Comment by jandocastro** [comment]
Thanks for the quick response! Good information. So probably not a plotly problem. It's interesting that it works through RStudio, but not when using the knit2html function.  

Thanks again for your help!

**Comment by jandocastro** [comment]
Just wanted to follow up with maybe some useful info:

It turns out I should have been using markdown::render() instead of
knit2html(). Now everything seems to be working fine.

Thanks again!
Alejandro
