### ISSUE TITLE
Subplot function resulting in incorrect layout

### ISSUE THREAD

**Issue by yankev** [ropensci/plotly#610]
Example code (https://plot.ly/r/contour-plots/#2d-density-contour-plot):

``` R
library(plotly)

x <- rnorm(200)
y <- rnorm(200)
p1 <- plot_ly(x = x, type = "histogram")
p2 <- plot_ly(x = x, y = y, type = "histogram2dcontour")
p3 <- plot_ly(y = y, type = "histogram")
a1 <- list(domain = c(0, .85))
a2 <- list(domain = c(.85, 1))
subplot(
  layout(p1, xaxis = a1, yaxis = a2),
  layout(p2, xaxis = a1, yaxis = a1),
  layout(p3, xaxis = a2, yaxis = a1)
)
```

What we get: 
![screen shot 2016-05-26 at 5 18 12 pm](https://cloud.githubusercontent.com/assets/12302455/15590553/66f4bd34-2366-11e6-82e9-0998a0a898df.png)

How it should be: 
![screen shot 2016-05-26 at 5 22 33 pm](https://cloud.githubusercontent.com/assets/12302455/15590570/76f7edb4-2366-11e6-99c2-98424245ae3f.png)

```
sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.9.4 (Mavericks)

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tidyr_0.4.1    dplyr_0.4.3    plotly_3.6.0   ggthemes_3.0.3 ggplot2_2.1.0 

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.5        magrittr_1.5       munsell_0.4.3      colorspace_1.2-6   R6_2.1.2          
 [6] httr_1.1.0         plyr_1.8.3         tools_3.2.3        parallel_3.2.3     grid_3.2.3        
[11] gtable_0.2.0       DBI_0.4-1          htmltools_0.3.5    yaml_2.1.13        lazyeval_0.1.10   
[16] digest_0.6.9       assertthat_0.1     gridExtra_2.2.1    RColorBrewer_1.1-2 base64enc_0.1-3   
[21] htmlwidgets_0.6    viridis_0.3.4      labeling_0.3       scales_0.4.0       mvtnorm_1.0-5     
[26] jsonlite_0.9.20  
```

**Comment by cpsievert** [comment]
With the new `widths` and `heights` arguments in `subplot()`, we no longer need to pre-populate axis domains. @yankev could you modify that page to use this (or something similar) to the example in the [subplot vignette](http://ropensci.github.io/plotly/vignettes/subplot.html)?

I'll keep this open since we should probably be throwing a warning message if pre-existing domains are found (and clobbering them).

**Comment by yankev** [comment]
@cpsievert Do you know of way to get the axes to show up for the histograms? 
![screen shot 2016-06-10 at 11 42 12 am](https://cloud.githubusercontent.com/assets/12302455/15969984/70666322-2f00-11e6-9d7a-4e763d6d8afd.png)

Basically uses the setup you had in the subplot vignette.

```r
x <- rnorm(200)
y <- rnorm(200)
s<-subplot(
  plot_ly(x = x, type = "histogram"),
  plotly_empty(),
  plot_ly(x = x, y = y, type = "histogram2dcontour"),
  plot_ly(y = y, type = "histogram"),
  nrows = 2, heights = c(0.2, 0.8), widths = c(0.8, 0.2), 
  shareX = TRUE, shareY = TRUE, titleX = FALSE, titleY = FALSE
)
layout(s, showlegend = FALSE)
```

**Comment by cpsievert** [comment]
IMO, in this plot you should share axes, but you can set `shareX`/`shareY` to `FALSE`

**Comment by yankev** [comment]
Right yeah, I was only hoping I could get the heights values of the histograms. Though because of their orientations (one vertical and the other horizontal), I agree that shareX and shareY should be `TRUE`

**Comment by cpsievert** [comment]
If anyone is interested, you can get axes for the histograms by replacing `plotly_empty()` with `plot_ly()`
