### ISSUE TITLE
Ggplotly time series examples not showing date

### ISSUE THREAD

**Issue by arkansasred** [ropensci/plotly#611]
None of the examples demonstrated on https://plot.ly/ggplot2/time-series/ are working on my machine

Specifically, the Month + Year of the date does not show along x axis on hover, and the POSIXct/Date classes on hover are not converted to a Month + Year string

The axis ticks are also not dynamically updating on zoom

I'm using the up to date versions of ggplot2 and plotly from CRAN (ggplot2: 2.1.0, plotly: 3.6.0)

If these features were removed in the most recent versions, perhaps this example site should be updated?

**Comment by RoyalTS** [comment]
I can confirm this, see screenshot:

![screen shot 2016-07-27 at 2 33 12 pm](https://cloud.githubusercontent.com/assets/702580/17175308/2163379c-5407-11e6-95f0-c582c2a8bfa5.png)

    > sessionInfo()
    R version 3.3.0 (2016-05-03)
    Platform: x86_64-apple-darwin13.4.0 (64-bit)
    Running under: OS X 10.11.5 (El Capitan)
    
    locale:
    [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
    [1] plotly_3.6.0  ggplot2_2.1.0
    
    loaded via a namespace (and not attached):
     [1] Rcpp_0.12.5      tidyr_0.5.1      assertthat_0.1   digest_0.6.9     grid_3.3.0       plyr_1.8.4       R6_2.1.2         jsonlite_1.0     gtable_0.2.0     magrittr_1.5    
    [11] scales_0.4.0     httr_1.2.1       viridis_0.3.4    labeling_0.3     tools_3.3.0      htmlwidgets_0.6  munsell_0.4.3    yaml_2.1.13      base64enc_0.1-3  colorspace_1.2-6
    [21] htmltools_0.3.5  gridExtra_2.2.1  tibble_1.1

**Comment by RoyalTS** [comment]
In fact, it seems to be a general issue that when using `ggplotly()` the behavior of the hover following the x-axis by default is broken.

**Comment by cpsievert** [comment]
> The axis ticks are also not dynamically updating on zoom

See a61b605 for new dynamicTicks argument

> The behavior of the hover following the x-axis by default is broken.

I wouldn't say it's broken, it's just that I decided `layout.hovermode="closest"` was a better default for many scenarios. You can click the "Compare the data on hover" button in the modebar to get the old behavior back or do `layout(..., hovermode = "x")`
