### ISSUE TITLE
Scatterplot Example's Fitted Value is Not Shown on Mouse Hover

### ISSUE THREAD

**Issue by DarioS** [ropensci/plotly#614]
As [seen in the documentation](https://plot.ly/ggplot2/geom_point/#no-shading-with-geom_smooth-scatter), the fitted value data label is missing for most points (e.g. Panel B), except the left-most (Panel A) and right-most ones. It should be present for all of them. I selected the "Compare data on hover" option from the top-right plotting tools menu. If I download the latest release of [plotly from CRAN](https://cran.r-project.org/web/packages/plotly/index.html), I notice that the x-axis values don't exactly match (Panel C), except for the largest x-axis value.

![hover](https://cloud.githubusercontent.com/assets/631218/15666816/2f8ab4a4-2756-11e6-96c7-3e81311003fe.png)

**Comment by cpsievert** [comment]
I think this is fixed (other than the "compare" being the default), which you can set as the default via:

```r
ggplotly(p) %>% layout(hovermode = "x")
```
