### ISSUE TITLE
does plotly respect the timezone?

### ISSUE THREAD

**Issue by tdhock** [ropensci/plotly#62]
I just got this email:

Hi there Toby,

How are you? I've just stumbled across the greatness of Plotly and in particular, your ggplotly code (really cool!).

I've managed to plot a ggplot time series, but I've noticed that the timezone of the time series seems to have changed… 

Is there a way to either 1) tell ggplotly what timezone to use, or 2) tell ggplotly not to convert the timezone?

Thanks in advance for you response.

Cheers,
Matt.

Dr Matthew J Burns
email: matthew.burns@unimelb.edu.au

**Comment by cpsievert** [comment]
It seems like the problem here derives from a misunderstanding of what `heath$lubri_date <- ymd_hms(heath$date, tz = "EST")` does, and thus isn't a plotly problem.
