### ISSUE TITLE
Bug: function returning a list of plotly graphs

### ISSUE THREAD

**Issue by SelimRaboudi** [ropensci/plotly#629]
I wrote a function that, given a list of dataframes, returns a list of plotly graphs:

```{r}
my_plot <- function(listtbl, line = NULL, x = "levels", title = "")
{
  res <- list()

  for(var in names(listtbl))
  {
    tbl <- listtbl[[var]]
    plt <- plotly::plot_ly()

    ## layout
    ttl <- ""
    if(nchar(var) > 0)
      ttl <- var
    if(nchar(title) > 0)
      ttl <- paste0(title, " - ", ttl)

    xAxis <- list(title = x, type = "category")
    yAxis <- list(title = "line")
    plt <- plt %>% plotly::layout(xaxis = xAxis, yaxis = yAxis,
                                  title = ttl, showlegend = T)

    ## line plot
    if(length(line) > 0)
    {
      for(l in line)
        plt <- plt %>% plotly::add_trace(x = tbl[[x]], y = tbl[[l]], name = l)
    }

    res[[var]] <- plt
  }

  return(res)
}

```

When testing the function with the following toy dataset:

```{r}
library(magrittr)
library(plotly)
d1 <- data.frame(levels = letters[1:3], val1 = 1:3, val2 = 4:6)
d2 <- data.frame(levels = letters[4:6], val1 = c(4,2,7), val2 = c(2,7,1))

listd <- list(d1 = d1, d2 = d2)
pp <- my_plot(listtbl = listd, x = "levels", line = c("val1", "val2"))
```

I get strange results:

1/ the second trace "erases" the first one. In the legend 2 traces appear but with the same values:
<img width="298" alt="screen shot 2016-06-19 at 14 12 36" src="https://cloud.githubusercontent.com/assets/2227272/16177367/d01fd358-362a-11e6-88cc-76863903cbbb.png">

2/ The second graph overwrites the first one (pp$d1 and pp$d2 are identical):
![pppp](https://cloud.githubusercontent.com/assets/2227272/16177384/73fdbefe-362b-11e6-979f-412260e5f6ca.png)

--------------------

Using a more 'ggplot' syntax (tidying the dataset and using data = ..., x = ..., y = ..., group = ... in the 'add_trace' call), I manage to overcome 1/, but still I don't understand why the syntax outlined above doesn't work.
Couldn't find a workaround for 2/ though.

Output of devtools::session_info():

```{r}
Session info ---------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.0 (2016-05-03)
 system   x86_64, darwin13.4.0        
 ui       RStudio (0.99.878)          
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Europe/Paris                
 date     2016-06-19   
```

**Comment by cpsievert** [comment]
You can give the list of graphs to `subplot()`
