### ISSUE TITLE
'Bar Charts in R: Bar Chart with Relative Barmode' not working

### ISSUE THREAD

**Issue by sarunasmerkliopas** [ropensci/plotly#631]
I was trying to do the following [example](https://plot.ly/r/bar-charts/#bar-chart-with-relative-barmode) but it doesn't work, i.e. the output is the same as it would be if instead of `layout(p3, barmode = 'relative')` I did `layout(p3)` - that is, the output is bar chart with dodged bars instead of stacked

My sessionInfo() output

> R version 3.3.0 (2016-05-03)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1
> 
> locale:
> [1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
> [4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] plotly_3.6.5  ggplot2_2.1.0
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.5      tidyr_0.5.1      assertthat_0.1   digest_0.6.9     grid_3.3.0       plyr_1.8.4       R6_2.1.2         jsonlite_0.9.22 
>  [9] gtable_0.2.0     magrittr_1.5     scales_0.4.0     httr_1.2.0       viridis_0.3.4    tools_3.3.0      htmlwidgets_0.6  munsell_0.4.3   
> [17] yaml_2.1.13      base64enc_0.1-3  colorspace_1.2-6 htmltools_0.3.5  gridExtra_2.2.1  tibble_1.0

**Comment by timelyportfolio** [comment]
I can confirm this bug.  In the pending major release `v4.0`, this is fixed.

**Comment by cpsievert** [comment]
Closed via d2bf2a1eb56d824a091e2cc9afea09a5968dd050. Let us know if you're still having problems, thanks!
