### ISSUE TITLE
crowded labels 

### ISSUE THREAD

**Issue by contactlp** [ropensci/plotly#632]
Hi ,
I have labels which are very large and crowded in certain part of the figure. I want to develop something which similar to good maps, if there are overlapping labels, it will show only when I zoom in enough.

Thanks
Lav

**Comment by cpsievert** [comment]
Thanks!

As per our [contributing guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), github issues are reserved for bug reports and feature requests only. So I'll have to close your ticket.

Please use our community forums at [community.plot.ly](http://community.plot.ly/) for posts of the likes.
