### ISSUE TITLE
legend is cut on scatter plot plotly / ggplot2 / shiny

### ISSUE THREAD

**Issue by poijqwef** [ropensci/plotly#635]
The legend is cut when plotly is applied to ggplot2 within shiny.
Any suggestion?

<img width="661" alt="legend-cut" src="https://cloud.githubusercontent.com/assets/14263948/16357000/1725516a-3ab8-11e6-9b28-269951dd0a27.PNG">

Here is the code I am using:

server:

`
  output$timeSeries <- renderPlotly({
   df <- timeSeriesPriceData()
   gplot <- ggplot() + geom_line(data=df,aes(x=datetime,y=price,colour="price")) +
     scale_colour_manual(values=c("blue")) + theme(legend.position="left")
   g <- ggplotly(p=gplot,showlegend=TRUE)
  })
`
ui:

`
plotlyOutput("timeSeries"),
`

**Comment by karthikg0703** [comment]
Is this fixed ? I'm still facing the same issue (I have plotly 3.6.0)
