### ISSUE TITLE
Documentation of event_data Outdated

### ISSUE THREAD

**Issue by DarioS** [ropensci/plotly#637]
There is no example named *events*. The command

    shiny::runApp(system.file("examples", "events", package = "plotly"))

should be changed to

    shiny::runApp(system.file("examples", "plotlyEvents", package = "plotly"))

Also, the parameter `source` should also mention `ggplotly`. It only refers to `plot_ly`, although both are currently possible.

**Comment by cpsievert** [comment]
I'm not sure where you see `shiny::runApp(system.file("examples", "events", package = "plotly"))`?

**Comment by DarioS** [comment]
The outdated example command is present in the version in CRAN, but not in the development branch in GitHub. Still, the description of `source` lacks any mention of `ggplotly`.
