### ISSUE TITLE
Rangeselector when using multiple y-axis

### ISSUE THREAD

**Issue by royr2** [ropensci/plotly#638]
@cpsievert @timelyportfolio I am using `rangeselector` with multiple y-axis. Nothing shows up. I am using the `fix/nse` branch. What am I doing wrong? Or is it by design? 

```r
# Works
df <- data.frame(x = seq.Date(as.Date("2016-01-01"), by = 1, length.out = 180),
                 y1 = rnorm(180),
                 y2 = rnorm(180, sd = 1.5))

plot_ly(data = df, x = ~x) %>% 
  add_lines(y = ~y1) %>% 
  add_lines(y = ~y2) %>% 
  layout(
    xaxis = list(rangeselector = list(
      buttons = list(
        list(step = "all")
      )
    ))
  )

# No plot
df <- data.frame(x = seq.Date(as.Date("2016-01-01"), by = 1, length.out = 180),
                 y1 = rnorm(180),
                 y2 = rnorm(180, sd = 1.5))

plot_ly(data = df, x = ~x) %>% 
  add_lines(y = ~y1) %>% 
  add_lines(y = ~y2, yaxis = "y2") %>% 
  layout(
    xaxis = list(rangeselector = list(
      buttons = list(
        list(step = "all")
      )
    )),
    
    yaxis2 = list(overlaying = "y")
  )
```

**Comment by cpsievert** [comment]
@royr2 I have a feeling plotly.js won't support this...have you gotten it to work in any other context?

**Comment by royr2** [comment]
@cpsievert I hadn't tried it. I was trying to replicate [this](http://www.frbsf.org/education/teacher-resources/chair-federal-reserve-economy-simulation-game). I was adding a second layer for the recession indicators (0/1) with a separate y - axis. That's when I realized I couldn't add the range selector buttons. Any idea how I could replicate those charts without adding a second layer? Jack wanted a post on them

**Comment by royr2** [comment]
Actually nvm I'll just workaround it for now. Thanks @cpsievert

**Comment by ahsanshah** [comment]
is it confirmed that Plotly will not support the range selector on multiple y axes?  Is this something which can may be supported in the future?

**Comment by franzbischoff** [comment]
Same happens here, I'm using it in a R project.

**Comment by andrelx** [comment]
Same behaviour here.  That really is a problem for me ... Any plans to correct this ?

André
