### ISSUE TITLE
Embeding Html extract into a different html doesn't work

### ISSUE THREAD

**Issue by kranthikandi** [ropensci/plotly#656]
I have created a boxplot graph using plotly and did html extract using this
`htmlwidgets::saveWidget(as.widget(ggp), "working/directory/index.html")`.
this created a index.html and a directory called index_files.

Now I'm trying to embed this in `home.html` using `<div><embed src="index.html"></div>` it's showing a blank page.
It works only if redirect to a new page using `<a href="index.html">index</a>`.

**Comment by timelyportfolio** [comment]
Is there a reason you are not using <iframe src = "index.html"></iframe>?  I don't think this is an issue with `plotly`.

**Comment by kranthikandi** [comment]
I am developing a single page application. so i don't want to navigate to a different page. 
I have tried all different ways to embed in a `div` all result in same blank. 
I tried this
`<div id="htmlwidget_container">
      <h1>Heelloo</h1>
      <div id="htmlwidget-6956" style="width: 100%; height: 400px;" class="plotly html-widget"></div>
</div>`
I can see the `H1` but not the `div`.

**Comment by cpsievert** [comment]
Have you tried doing this with any other htmlwidgets? If you can't get it to work for other htmlwidgets, I would post an issue here -- https://github.com/ramnathv/htmlwidgets

**Comment by kranthikandi** [comment]
`<iframe src = "index.html"></iframe>` is working thank you @timelyportfolio
