### ISSUE TITLE
axref and ayref not working

### ISSUE THREAD

**Issue by justinfinkle** [ropensci/plotly#657]
Trying to add some annotation arrows that scale, but the `axref` and `ayref` arguments don't seem to work.  `ax` and `ay` still seem to be in pixels.

Here's a simple toy example:
`plot_ly(x=1:10, y=1:10) %>% layout(annotations=list(x=1, y=1, ax=10, ay=0, xref='x', yref='y', axref='x', ayref='y', showarrow=TRUE))`
![image](https://cloud.githubusercontent.com/assets/9001591/17160528/6815ec3c-535a-11e6-8ddf-2043e40d1efa.png)

versus

` plot_ly(x=1:10, y=1:10) %>% layout(annotations=list(x=1, y=1, ax=100, ay=0, xref='x', yref='y', axref='x', ayref='y', showarrow=TRUE))`
![image](https://cloud.githubusercontent.com/assets/9001591/17160525/5fb28848-535a-11e6-934e-168f96055a7d.png)

**Comment by cpsievert** [comment]
Looks like you have an extra `xref`/`yref` in there. I think this is what you want:

```r
plot_ly(x=1:10, y=1:10) %>% 
  layout(annotations=list(x=1, y=1, ax=5, ay=5, ayref='y', axref='x', showarrow=TRUE))
```

**Comment by justinfinkle** [comment]
My interpretation from the [API](https://plot.ly/r/reference/#layout-annotations) `xref`/`yref` are for the annotation coordinate axis whereas `axref`/`ayref` are for the arrow tail. Is that incorrect?

Basically I'd like to draw an arbitrary arrow that is on the data axes and will scale accordingly.

**Comment by justinfinkle** [comment]
The development version appears to work as expected (plotly_4.0.2). All arguments in the api can be specified
