### ISSUE TITLE
ggplotly ignores \n in breaks axes label

### ISSUE THREAD

**Issue by brolin** [ropensci/plotly#661]
I use in ggplot str_wrap() to wraps texts for the names of my breaks as show in the next figure

![ggplot](https://cloud.githubusercontent.com/assets/45384/17200778/b8822a98-544d-11e6-88ae-0ea57258310d.png)

str_wrap() adds \n characters each fixed number of characters, but when i render the graphic with ggplotly the texts are overlapped as you can see in the next figure.

![ggplotly](https://cloud.githubusercontent.com/assets/45384/17200779/b885c41e-544d-11e6-8aa3-b1f84d9f17d3.png)

¿Any hint of how can i solve this?

Thanks in advance.

**Comment by fabiangehring** [comment]
Cannot rest right now, but have you tries <br> instead of \n?

**Comment by fabiangehring** [comment]
Hmm, I'meant using "< br >" (no spaces) instead of \n

**Comment by cpsievert** [comment]
This is fixed in the dev version
