### ISSUE TITLE
event_data (Shiny) does not work with subplots

### ISSUE THREAD

**Issue by alexwu2400** [ropensci/plotly#663]
When using plotly with shiny, receiving event data such as "plotly_hover" does not work with when plotly objects are within a subplot

Example below. Thanks!

```
library(plotly)
library(shiny)

server <- function(input, output) {
  output$plot <- renderPlotly({
    p1 <- plot_ly(data = iris, x = Sepal.Length, y = Petal.Length, mode = "markers", source = "s1")
    p2 <- plot_ly(data = iris, x = Sepal.Length, y = Petal.Length, mode = "markers", source = "s2")
    subplot(p1,p2)
    #p1
  })
  
  output$text1 <- renderText({
    evtdata <- event_data("plotly_hover", source = "s1")
    evtdata$x
  })
}

ui <- fluidPage(
  mainPanel(
    plotlyOutput("plot"),
    textOutput("text1")
  )
)

shinyApp(ui = ui, server = server)
```

Session info --------------------------------------------------
 setting  value                       
 version  R version 3.3.0 (2016-05-03)
 system   x86_64, mingw32             
 ui       RStudio (0.99.902)          
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2016-07-29                  

Packages ------------------------------------------------------
 package     * version date       source        
 assertthat    0.1     2013-12-06 CRAN (R 3.3.0)
 base64enc     0.1-3   2015-07-28 CRAN (R 3.3.0)
 chron         2.3-47  2015-06-24 CRAN (R 3.3.1)
 codetools     0.2-14  2015-07-15 CRAN (R 3.3.0)
 colorspace    1.2-6   2015-03-11 CRAN (R 3.3.0)
 data.table  * 1.9.6   2015-09-19 CRAN (R 3.3.1)
 DBI           0.4-1   2016-05-08 CRAN (R 3.3.0)
 devtools      1.12.0  2016-06-24 CRAN (R 3.3.1)
 digest        0.6.9   2016-01-08 CRAN (R 3.3.0)
 dplyr       * 0.4.3   2015-09-01 CRAN (R 3.3.0)
 DT          * 0.1     2015-06-09 CRAN (R 3.3.1)
 ggplot2     * 2.1.0   2016-03-01 CRAN (R 3.3.0)
 gridExtra     2.2.1   2016-02-29 CRAN (R 3.3.0)
 gtable        0.2.0   2016-02-26 CRAN (R 3.3.0)
 htmltools     0.3.5   2016-03-21 CRAN (R 3.3.0)
 htmlwidgets   0.6     2016-02-25 CRAN (R 3.3.0)
 httpuv        1.3.3   2015-08-04 CRAN (R 3.3.1)
 httr          1.2.0   2016-06-15 CRAN (R 3.3.0)
 jsonlite      0.9.22  2016-06-15 CRAN (R 3.3.0)
 labeling      0.3     2014-08-23 CRAN (R 3.3.0)
 lazyeval      0.2.0   2016-06-12 CRAN (R 3.3.0)
 magrittr      1.5     2014-11-22 CRAN (R 3.3.0)
 memoise       1.0.0   2016-01-29 CRAN (R 3.3.1)
 mime          0.4     2015-09-03 CRAN (R 3.3.0)
 munsell       0.4.3   2016-02-13 CRAN (R 3.3.0)
 numbers     * 0.6-1   2015-07-14 CRAN (R 3.3.1)
 plotly      * 3.6.0   2016-05-18 CRAN (R 3.3.0)
 plyr        * 1.8.4   2016-06-08 CRAN (R 3.3.0)
 pryr        * 0.1.2   2015-06-20 CRAN (R 3.3.1)
 R6            2.1.2   2016-01-26 CRAN (R 3.3.0)
 Rcpp          0.12.5  2016-05-14 CRAN (R 3.3.0)
 scales        0.4.0   2016-02-26 CRAN (R 3.3.0)
 shiny       * 0.13.2  2016-03-28 CRAN (R 3.3.1)
 stringi       1.1.1   2016-05-27 CRAN (R 3.3.0)
 stringr       1.0.0   2015-04-30 CRAN (R 3.3.0)
 tibble        1.0     2016-03-23 CRAN (R 3.3.0)
 tidyr         0.5.1   2016-06-14 CRAN (R 3.3.0)
 viridis       0.3.4   2016-03-12 CRAN (R 3.3.0)
 withr         1.0.2   2016-06-20 CRAN (R 3.3.1)
 xtable        1.8-2   2016-02-05 CRAN (R 3.3.1)
 yaml          2.1.13  2014-06-12 CRAN (R 3.3.0)

**Comment by xtYao** [comment]
Waiting for resolution to this. It'd be very nice if subplot could listen to events. Right now the work-around as I learned from https://github.com/ropensci/plotly/blob/master/inst/examples/plotlyLinkedBrush/app.R
is to use Shiny to make separate areas, which is clumsy and not good looking.
