### ISSUE TITLE
ggplotly() time series example X axis zoom and labels not working

### ISSUE THREAD

**Issue by ahsanshah** [ropensci/plotly#665]
Not sure if there is specific to my environment but the following code does not show the same on my machine. I have tested this on Windows and Linux with the same results.

https://plot.ly/ggplot2/time-series/#facet_grid-time-series-by-year

If you can see, the Labels for YEAR are duplicated and the X Axis Zoom does not zoom to specific Dates/Times.  

![image](https://cloud.githubusercontent.com/assets/14385814/17279611/89c5bd72-5746-11e6-9375-be72d67192f2.png)

It seems to work fine in the Online Example. Can this be due to a code change made recently?

**Comment by ahsanshah** [comment]
Here is a even simpler example:  https://plot.ly/ggplot2/time-series/#time-series-with-facet_grid

Any reason why these do not seem to ZOOM to the Date in the XAxis?  I tried updating to latest dev branch and the issue persist.

**Comment by ahsanshah** [comment]
Any update here?  Is it the same as https://github.com/ropensci/plotly/issues/646?  If so, feel free to combine.

**Comment by royr2** [comment]
@ahsanshah here's an example:
```r
ggplot(economics, aes(x = date, y = pce))+ 
  geom_line()

p <- ggplotly()
p$x$layout$xaxis$ticktext
p$x$layout$xaxis$tickvals
```
![image](https://cloud.githubusercontent.com/assets/6601579/17542475/b8105da2-5ee6-11e6-9606-5c364c3beb58.png)

You'll note that the tick labels are not granular enough. Hence, even when you zoom in like so:
![image](https://cloud.githubusercontent.com/assets/6601579/17542497/dab88352-5ee6-11e6-8fd0-b813cabb1571.png)

It only shows 1990 and not the dates. I don't think its so much a bug, rather a future feature? 

For now you could workaround this like so:
```r
library(plotly)

ggplot(economics, aes(x = date, y = pce))+ 
  geom_line()

p <- ggplotly()
p$x$data[[1]]$x <- as.POSIXct((p$x$data[[1]]$x + 0.1)/1000, origin = "1970-01-01", tz = "GMT")

p$x$layout$xaxis$type = "-"
p
```

**Comment by ahsanshah** [comment]
Hi. I tried this and it still does not zoom into the Date lower than the YEAR grain.  I am on the latest code base.    Am I suppose to see the Year -> Month -> Date on zoom for the X axis?  If so, it still does not seem to work

**Comment by cpsievert** [comment]
No, this was a conscious decision to ensure axis labels are translated correctly. You can still see the date in the tooltip.

**Comment by ahsanshah** [comment]
OK understood but I was trying to understand the proposed workaround...is that still an option?  This is a key feature and understand its a conscious decision but would be a big win to allow this for users.  If not possible, is there some other alternative..possibly a event/hover based option to display a vertical like like this in nvd3

![image](https://cloud.githubusercontent.com/assets/14385814/17566026/bf777eec-5f07-11e6-9124-603de8c4e973.png)
