### ISSUE TITLE
North and South Korea visualization are inverted

### ISSUE THREAD

**Issue by bjoyce3** [ropensci/plotly#666]
Numbers input for South Korea are visualized as North Korea on the Plotly R choropleth world map code, and numbers input for North Korea are visualized for South Korea. This could lead to a lot of embarrassing visualizations!

**Comment by bjoyce3** [comment]
Digging into the code, it looks like like a problem with the country codes. KOR is South Korea, and PRK is the People's Republic of Korea (North Korea). It seems to be an error here: https://github.com/plotly/plotly.js/blob/master/test/image/mocks/geo_choropleth-text.json

**Comment by bjoyce3** [comment]
Pull request submitted for fix.

**Comment by asherkhb** [comment]
this appears to be an issue in example data:
https://github.com/plotly/datasets/pull/15
