### ISSUE TITLE
Make missing attribute warnings trace specific

### ISSUE THREAD

**Issue by fabiangehring** [ropensci/plotly#667]
hi,
When combining a barplot with a scatterplot the plot is painted as expected, but gives a warning about not existing attributes. 

Issue 1: When using barmode = 'relative' , not only a warning is shown, but also barmode seems to be set back to 'group'. Interestingly markers are still painted corrrectly.

Issue 2: When combining the above plots in subplots. Markers disappear.

Both issues can be shown in the following rme:

```
data <- data.frame(x = c(20, 14, 23, -10, -18, -29, 3, -3, 7),
                   y = rep(c("a", "b", "c"), 3), 
                   z = rep(c("x", "y", "z"), each = 3), 
                   stringsAsFactors = FALSE)

# barplot ssems to be ok
p <- plot_ly(data,
             y = ~y,
             x = ~x,
             color = ~z,
             orientation = 'h',
             type = 'bar') 
layout(p, barmode = "relative")

# issue 1: when adding scatter -> warning and barmode = 'relative' broken, 
# markers plotted
add_trace(p, x = c(10, 11, -5),
          y = c("a", "b", "c"),
          type = 'scatter',
          orientation = 'h',
          marker = list(color = 'red'))

# issue 2: barmode = 'relative' still broken, markers diappear
subplot(p, p, nrows = 2)
```

**Comment by elcombato** [comment]
To elaborate on this bug:
I described it inititally in [this stackoverflow question](http://stackoverflow.com/questions/38722165/plotly-bar-and-line-chart), where you can see that it's critical in which order you define the `scatter` and the `bar` plot.

@fabiangehring's  problem with `barmode='relative'` only occurs if `orientation = 'h'`. With `orientation = 'v'` the `barmode` makes no difference:

```R
p <- plot_ly(
  x = c(1,2,3,4,5),
  y = c(1,2,1.5,3,2),
  type='scatter',
  mode='lines',
  line = list(color = 'black')
)
p <- add_trace(
  p,
  x = c(1,2,3,4,5),
  y = c(0.5,0.7,0.6,0.9,0.8),
  type='bar',
  marker = list(color = 'red')
)
p <- add_trace(
  p,
  x = c(1,2,3,4,5),
  y = c(0.2,0.3,0.2,0.4,0.3),
  type='bar',
  marker = list(color = 'orange')
)
layout(p, barmode = 'relative')
```
Produces the same warning as in the linked stackoverflow question:
> Warning messages:
> 1: The following attributes don't exist:
> 'mode', 'line'
> Valid options include:
> 'type', 'visible', 'showlegend', 'legendgroup', 'opacity', 'name', 'uid', 'hoverinfo', 'stream', 'x', 'x0', 'dx', 'y', 'y0', 'dy', 'text', 'orientation', 'marker', 'r', 't', 'error_y', 'error_x', '_deprecated', 'xaxis', 'yaxis', 'xsrc', 'ysrc', 'textsrc', 'rsrc', 'tsrc', 'key'
>  
> 2: The following attributes don't exist:
> 'mode', 'line'
> Valid options include:
> 'type', 'visible', 'showlegend', 'legendgroup', 'opacity', 'name', 'uid', 'hoverinfo', 'stream', 'x', 'x0', 'dx', 'y', 'y0', 'dy', 'text', 'orientation', 'marker', 'r', 't', 'error_y', 'error_x', '_deprecated', 'xaxis', 'yaxis', 'xsrc', 'ysrc', 'textsrc', 'rsrc', 'tsrc', 'key'

**Comment by cpsievert** [comment]
The warning messages appear because any attributes you define in `plot_ly()` are carried to any downstream `add_trace()`-like calls. 

So, in the first case, you're getting the warning because scatter traces don't have an orientation attribute. Simliarly, in the second case, the bar trace doesn't have mode or line attributes.

I'm fairly sure we could modify the warning message to be trace specific, so changing the title here to reflect that.

The other issues referenced here should be addressed in the plotly.js repo

**Comment by cpsievert** [comment]
To be more clear, I believe all your problems go away if you remove the `orientation = "h"` attribute in the scatter trace:

```r
p <- data %>%
  plot_ly(y = ~y, x = ~x, color = ~z) %>%
  add_bars(orientation = 'h') %>%
  add_markers() %>%
  layout(barmode = "relative") 
  
subplot(p, p, nrows = 2)
```

**Comment by fabiangehring** [comment]
perfect, thx
