### ISSUE TITLE
ggplotly displays differently deployed to shinyapps.io than locally

### ISSUE THREAD

**Issue by martinjhnhadley** [ropensci/plotly#669]
I have a gantt chart I've built with `ggplotly` as detailed here: https://gist.github.com/martinjhnhadley/bea1b693fb88ce79677833a1ea82b793

Locally on my machine the chart renders nicely:

![image](https://cloud.githubusercontent.com/assets/9363263/17368692/0686a84c-598d-11e6-98c4-8551f8d1da80.png)

But if I deploy the app to shinyapps.io (https://livedataoxford.shinyapps.io/broken/) and zoom in on the chart the geom_segments expand outside of the `svg-container` they're meant to live inside of:

![image](https://cloud.githubusercontent.com/assets/9363263/17368722/2960343c-598d-11e6-84fa-5b66d9c45f74.png)

I cannot replicate this error for a local version of the chart, and if I deploy the same visualisation to RPubs it does work - http://rpubs.com/martinjhnhadley/200160. Code for the .Rmd file is available in the Gist https://gist.github.com/martinjhnhadley/bea1b693fb88ce79677833a1ea82b793.

Copying shiny app code here to prevent having to click on links

``` R
## ui.R

library(shiny)
library(plotly)

shinyUI(
  fluidPage(
    wellPanel("some stuff"),
      plotlyOutput("timeline")
  )
)
```

``` R
## server.R
library(shiny)
library(plotly)

timeline_data <- read.csv("https://gist.githubusercontent.com/martinjhnhadley/2cd4bb8ded9d69e32311fd26be9290b7/raw/3ba100dc0415c8e9222e1901a68cf0e8e164f329/dump.csv", stringsAsFactors = F)
timeline_data$Valid.from..b. <- as.Date(timeline_data$Valid.from..b.)
timeline_data$Valid.until..c... <- as.Date(timeline_data$Valid.until..c...)

shinyServer(
  function(input, output){
    output$timeline <- renderPlotly({
      ggplotly(ggplot(
        timeline_data,
        aes(
          x = Valid.from..b.,
          xend = Valid.until..c...,
          y = Name.Policy,
          yend = Name.Policy,
          colour = Type.of.policy
        )
      ) +
        geom_segment(size = 4) +
        geom_segment(
          aes(
            x = Valid.from..b. - 25,
            xend = Valid.from..b.,
            y = Name.Policy,
            yend = Name.Policy
          ),
          colour = "black",
          size = 4,
          arrow=arrow(type = "closed")
        ) +
        xlab("Date") + ylab(""), tooltip = "text")
    })
  }
)
```

**Comment by cpsievert** [comment]
Huh, I just tried zooming on the graphic [here](https://livedataoxford.shinyapps.io/broken/), and appears to be working fine in Chrome. Feel free to reopen if you think there is still a problem
