### ISSUE TITLE
Download plot as png button doesn't work in some contexts

### ISSUE THREAD

**Issue by methodds** [ropensci/plotly#672]
Hi,

I used `ggplotly()` in a shiny app to create a bar graph and want user to be able to download the graph as an image file. Pressing the download button in the top menu of the graph however does not work and raises an `Sorry there was a problem downloading your png` error. Can this be fixed somehow?
An example is available [here](http://pathways.polsys.uni-bamberg.de:443/stmInsights/).

Thanks and Cheers,
Carsten

**Comment by cpsievert** [comment]
FWIW, you can use the `export()` function now to (locally) export to png programmatically

**Comment by komalsrathi** [comment]
I had the same problem but installing the devel version solved the problem. 

```
devtools::install_github("ropensci/plotly")
```

**Comment by cpsievert** [comment]
For posterity, this still seems to be a problem when clicking the download button in RStudio, but you have two other options:

(1) Open the plot in another web browser (e.g., Chrome, Firefox).
(2) Use the `export()` function.
