### ISSUE TITLE
Creating Click and hover events

### ISSUE THREAD

**Issue by kranthikandi** [ropensci/plotly#674]
I am trying to mimic the click event and hover event on the graph. 
I have a Html extract of the bar graph which i have developed in R. I'm using `iframe `to embed it in a different web app. 
Now I'm sending ping to the server but not getting the same response `message/e Object` from the server as shown in [Demo.](https://plot.ly/r/click-events/)

do I have to right any server side script to handle this. 
the webapp is and the Html extract both on the same tomcat server.

**Comment by cpsievert** [comment]
Thanks!

As per our [contributing guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), github issues are reserved for bug reports and feature requests only. So I'll have to close your ticket.

Please use our community forums at [community.plot.ly](http://community.plot.ly/) for posts of the likes.
