### ISSUE TITLE
subplot doesn't merge legend entries

### ISSUE THREAD

**Issue by cpsievert** [ropensci/plotly#675]
``` r
m <- split(mtcars, mtcars$vs)
subplot(lapply(m, function(x) plot_ly(x, x = ~mpg, y = ~wt, color = ~factor(cyl))))
```

**Comment by ramay** [comment]
Hi ,
I am having the same problem. Have you found a solution to this?

Interestingly for my data, in one case it is merging legends and in another case it is not.  I had added legendgroup and used showlegend to show legend for one of the two plots.

 I am attaching my data and code used in the two plots so you can see what is happening.

Thanks!
Hena
[subplot_Merge_Issue.zip](https://github.com/ropensci/plotly/files/790992/subplot_Merge_Issue.zip)

**Comment by cpsievert** [comment]
@ramay see [this test](https://github.com/ropensci/plotly/blob/d62d8eaeb7b60b5741a89d4b8bcdbc2180509c4d/tests/testthat/test-plotly-subplot.R#L178-L208)
