### ISSUE TITLE
additional trace in mesh3d group data

### ISSUE THREAD

**Issue by BoyaoZhang** [ropensci/plotly#685]
Why there is an additional trace in mesh3d plots? That is the blue area in the following plot. And how can I remove it?

```
d <- iris[1:100,]
plot_ly(d, x = Sepal.Length, y = Sepal.Width, z = Petal.Length,
type = "mesh3d", group = Species)
```

![rplot](https://cloud.githubusercontent.com/assets/17792013/17682946/7a78f306-634f-11e6-875c-8ed59b3c36d1.png)

**Comment by cpsievert** [comment]
If you read the NEWS, you'll see the group argument has been deprecated in the dev version. I think you want this?

```r
d <- iris[1:100,]
plot_ly(
  d, x = ~Sepal.Length, y = ~Sepal.Width, z = ~Petal.Length,
        type = "mesh3d", color = ~factor(Species))
```

**Comment by BoyaoZhang** [comment]
That is just what I want! Thank you for your reply.
