### ISSUE TITLE
Example code of stacked fill area 

### ISSUE THREAD

**Issue by ThoDuyNguyen** [ropensci/plotly#686]
Is there any direct support for stacked fill area plot?

This link below does not provide example. 
https://plot.ly/r/filled-area-plots/

Stacked fill area in ggplot2: 

http://chrisalbon.com/r-stats/stacked-area-graph.html

Thank you in advance

**Comment by cpsievert** [comment]
As per our [contributing guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), github issues are reserved for bug reports and feature requests only. So I'll have to close your ticket.

Please use our community forums at [community.plot.ly](http://community.plot.ly/) for posts of the likes.
