### ISSUE TITLE
Color of border pad

### ISSUE THREAD

**Issue by Tmv3v** [ropensci/plotly#692]
http://stackoverflow.com/questions/38986899/r-plotly-how-to-change-the-color-of-the-outer-border

This issue appeared when I tried to create a plot with grey background., and I am unable to find a way to change the color of the border pad

**Comment by oyvindholmstad** [comment]
I am having the same issue. Does anyone know if this is something generated in the R portion of plotly or plotly.js?

**Comment by cpsievert** [comment]
Sounds like you want a different default in htmlwidget sizing policy. Try something like this:

```r
p1$sizingPolicy$padding <- 0
```
