### ISSUE TITLE
Placeholder Plot Fails to Render

### ISSUE THREAD

**Issue by DarioS** [ropensci/plotly#694]
A plot, which is shown until the user makes a selection, draws with `ggplot2` but is completely blank once rendered by `plotly`.

```
  blankPlot <- ggplot() + labs(x = "A Variable", y = "Another Variable") + ggtitle("Placeholder")
  blankPlot  # Works as expected
  ggplotly() # Nothing shown at all - axes labels and title expected.
```

I think that this is a simple base case which should work.

**Comment by cpsievert** [comment]
This works now
