### ISSUE TITLE
Grouping based on color variable?

### ISSUE THREAD

**Issue by pgensler** [ropensci/plotly#695]
Hello,

As I have been starting to use plotly, I have seen two different approaches to making a grouped bar chart, and was wondering if the approach I am taking is even legal/advised :
Option 1: Create a plotly object, but color and group based on the same variable(code below). There really isen't much documentation on this feature, so I'm not even sure if I'm doing it right, or how this is supposed to behave.
```
sample <- data.frame(
  Category <- c("Furniture","Furniture","Furniture","Furniture",
                "Office Supplies","Office Supplies", "Office Supplies", "Office Supplies",
                "Office Supplies", "Office Supplies", "Office Supplies", "Office Supplies",
                "Office Supplies", "Technology","Technology","Technology","Technology"),
  SubCategory <- c("Bookcases","Chairs","Furnishings","Tables","Appliances","Art","Binders","Envelopes", 
                   "Fasteners","Labels","Paper","Storage",  "Supplies", "Accessories","Copiers","Machines",
                   "Phones"),
  sales <- c(889222.51,920892.65,239840.16,445823.93,614737.91,225594.68,281494.68,104903.88,50156.06,44269.30,
             150113.36,692903.08,152196.19,463383.33,965899.78,458655.43,1005525.38)
  )

sample %>%
  plot_ly(
    x = SubCategory,
    y = sales,
    type = "bar",
    group = Category,
    color = Category
  )
```

or:

Option2: Create a plotly object, and then add the 16 layers of bars individually with add_trace (or now add_bars). Attached is a screenshot of what I'm trying to achieve.
the code would be similar to the modern data post here:
http://moderndata.plot.ly/time-series-charts-by-the-economist-in-r-using-plotly/
![grouped-barchart](https://cloud.githubusercontent.com/assets/7308115/17954062/f7e976f4-6a3d-11e6-8946-70bf3614ae5f.png)

I am able to render my barchart just fine, but when I start to use grouping is when it seems like it just adds a layer onto the plot, rather than actually trying to group. Not really sure if this happens in the dev version, but would appreciate your thoughts on this. Thanks so much.

**Comment by cpsievert** [comment]
I would use the `subplot()` function (where you have one plot per category), here is the vignette -- http://ropensci.github.io/plotly/vignettes/subplot.html

As per our [contributing guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), github issues are reserved for bug reports and feature requests only. So I'll have to close your ticket.

Please use our community forums at [community.plot.ly](http://community.plot.ly/) for posts of the likes.

**Comment by pgensler** [comment]
Carson,
Thanks for the help,  but the subplot did not keep all the bars for the given categories. I have updated my post in the community page if you want to look at it in more detail.
