### ISSUE TITLE
None of the examples in the documentation works

### ISSUE THREAD

**Issue by lucacerone** [ropensci/plotly#708]
I recently updated to ropensci/plotly v ‘4.3.5’.

After that none of the plots I created before works, and none of the example in the "Getting Started" guide works: https://plot.ly/r/getting-started/

For example if I do something like: 

```{R}
p <- plot_ly(iris, x = Petal.Length, y = Petal.Width,
             color = Species, mode = "markers")
```

Plotly complains about the object "Petal.Length" not being found.

Has the interface changed? How are we supposed to create plots now?

Thanks a lot for the help!

Cheers,
Luca

**Comment by cpsievert** [comment]
Hi Luca, 

There are a number of breaking changes, and we're in the midst of updating all the documentation. 

In the meantime, here is a draft of blog post we intend on publishing in the coming weeks. It should help you understand why changes were made and how to fix them. -- http://rpubs.com/cpsievert/206885

**Comment by gtumuluri** [comment]
Whew! This helps. Thank you. BTW - if you suggest using dev version for a fix, it will be extremely useful to mention this post / link as well. I was banging my head for a while not knowing. You guys do excellent work. Keep up.

**Comment by lucacerone** [comment]
thanks @cpsievert sorry for the delay!
