### ISSUE TITLE
Error in map_size: could not find function "lengths"

### ISSUE THREAD

**Issue by hayneswa** [ropensci/plotly#715]
The function "lengths" was first introduced in R version 3.2.0 and is called by map_size (and several other functions). Running with an earlier version of R results in the error message:
Error in map_size: could not find function "lengths"

One possible resolution is to make the dependency in the DESCRIPTION file R (>= 3.2.0).

**Comment by hayneswa** [comment]
Replacing lengths() with lapply(X, length) was able to resolve this issue for me on R 3.1.2

The changes can be seen here:
https://github.com/hayneswa/plotly/commit/eb1c0a89cbb1acd3a537d11cf508a997cd16629a

**Comment by cpsievert** [comment]
Thanks!
