### ISSUE TITLE
Syntax changed

### ISSUE THREAD

**Issue by Nikolai-Hlubek** [ropensci/plotly#719]
Hi guys

We currently tried version 4.3.4 (due to an annoying bug with plotly.js) of R plotly and I noticed that almost all of our plots, which were done in 3.6.1 don't work anymore, because the syntax was changed. 
Additionally the R examples on the plotly homepage don't work anymore and the API documentation is out of sync.

I found a solution for us by changing the package name to plotly4 in the DESCRIPTION and installing both plotly versions.

Maybe for other users it might be feasible to provide some backward compatibility option if plotly 4 is released or have an old package called plotly3 or call the new package plotly4?

**Comment by cpsievert** [comment]
Please see #708
