### ISSUE TITLE
Retrain color defaults in subplot

### ISSUE THREAD

**Issue by gtumuluri** [ropensci/plotly#724]
I have this piece of code that works fine in 3.x but not in the 4.x dev version. In fact, subplot in 3.x actually changes the colors of the plots, which is also broken in 4.x.

```
p1 <- plot_ly(filter(mtcars, am == 1), x = mpg, type = 'histogram', histnorm = 'probability',
              xbins = list(start = 0, end = max(mtcars$mpg) + 5,
                           size = 3),
              autobinx = FALSE, showlegend = FALSE)
p2 <- plot_ly(filter(mtcars, am == 0), x = mpg, type = 'histogram', histnorm = 'probability',
              xbins = list(start = 0, end = max(mtcars$mpg) + 5,
                           size = 3),
              autobinx = FALSE, showlegend = FALSE)

p <- plotly::subplot(p1, p2, nrows = 2, shareY = TRUE, shareX = TRUE)
p %>% layout(annotations = list(
  list(x = 0.5 , y = 1.05, text = 'Automatic', showarrow = F,
       xref = 'paper', yref = 'paper'),
  list(x = 0.5, y = 0.45, text = 'Manual', showarrow = F,
       xref = 'paper', yref = 'paper')))
```

Any idea on how to get annotations to work with subplot?

**Comment by gtumuluri** [comment]
As for the color not being used in subplot, you can execute this piece of code and try:

```
m <- split(mtcars, mtcars$vs)
subplot(lapply(m, function(x) plot_ly(x, x = ~mpg, type = 'histogram')))
```

This same piece of code produces subplots with different colors in the prior version.

**Comment by cpsievert** [comment]
There are a few issues here -- one of which required a bug fix (your 2nd comment) -- so I've changed the title to reflect that.

If you use new formula mappings, as you do in your second comment, your first example should no longer be "broken".

Also, as long as you use "paper" references in your annotations, `subplot()` should be able to reposition them.
