### ISSUE TITLE
Query - access to low level widgets

### ISSUE THREAD

**Issue by richardbeare** [ropensci/plotly#734]
Hi,
Apologies if this is an obvious or stupid question. I'd like to be able to use something along the lines of ipywidgets in jupyter notebooks from R. We're trying to provide similar notebooks for both python and R for SimpleITK. I'm wondering if it is feasible to access any of the components that plotly uses, for example sliders, checkboxes etc, and use them in a more general way - i.e connect them to something that isn't a plot. Are you aware of other packages that might offer that kind of facility?

Thanks

**Comment by cpsievert** [comment]
Thanks!

As per our [contributing guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), github issues are reserved for bug reports and feature requests only. So I'll have to close your ticket.

Please use our community forums at [community.plot.ly](http://community.plot.ly/) for posts of the likes.
