### ISSUE TITLE
error when using "color" when only 1 datapoint is present

### ISSUE THREAD

**Issue by shosaco** [ropensci/plotly#735]
See http://stackoverflow.com/questions/39752432/colors-in-plotly-4-x-for-r

This bug is visible in generation subplot or plots when a subplot or plot has only one datapoint.

Prerequisites:

- the data has only one row,
- and a color = argument is passed to plot_ly or add_trace.
- and the column used for color has factor levels that are not present

      plot_ly(head(iris, 1), x = ~Sepal.Length, y = ~Sepal.Width, color=~Species, type = "scatter", mode = "markers")

    Error in if (has_attr(x$type, "colorscale")) x[["z"]] else NULL : argument is of length zero`

The following workaround works fine:
       plot_ly(pdata, x = ~Sepal.Length, y = ~Sepal.Width, color = factor(pdata$Species), type = "scatter", mode = "markers")

**Comment by cpsievert** [comment]
fixed via 724b440578f954593e9d6ce555bca8b143fc9e6d
