### ISSUE TITLE
ggplotly: Incorrect display of x-axis with geom_bar in the case of one axis label

### ISSUE THREAD

**Issue by Safstat** [ropensci/plotly#740]
Hello,
I installed the new version of plotly (4.5.2) and I have found these problems:
1- The display of x-axis is incorrect with geom_bar when we have only one axis label
whereas it works fine when I just run the ggplot() 
2- informations do not appear on hover for the last panel.
3- Warning messages: "In is.na(e1) : is.na() applied to non-(list or vector) of type 'NULL'"
Here's my code:

DF <- read.table(text="Rank   P_Rank    value_Rank     P2_Rank
                                 AC      1        250             1
                                 AN      1        100             1
                                 AT      1        155             1
                                 CA      1        90              1
                                 AC      2        630             1
                                 AN      2        150             1
                                 AT      2        384             1
                                 CA      2        485             1
                                 AC      3        94              1 
                                 AN      3        75              1
                                 AT      3        163             1
                                 CA      3        97              1
                                 AC      4        63              2
                                 AN      4        16              2
                                 AT      4        140             2
                                 CA      4        610             2
                                 AC      5        46              2
                                 AN      5        330             2
                                 AT      5        150             2
                                 CA      5        67              2 
                                 AC      6        130             2
                                 AN      6        250             2
                                 AT      6        484             2
                                 CA      6        185             2
                                 AC      7        130             3
                                 AN      7       250             3
                                 AT      7        484             3
                                 CA      7        185             3", header=TRUE)  

g <- with(DF,
                   ggplot(data=DF)+
                  geom_bar( aes(x = factor(P_Rank), y = value_Rank, fill = Rank), stat = "identity") +
            facet_wrap(~ P2_Rank, switch = "x", scales = "free_x") )
ggplotly(g)

![ggplot](https://cloud.githubusercontent.com/assets/7080429/18985396/f2ee306e-86f7-11e6-891e-b31e2181a6d3.png)

**Comment by cpsievert** [comment]
I think this is fixed now
