### ISSUE TITLE
Country code that are unknown shifts event_data selection in Plotly choropleth (R/Shiny)

### ISSUE THREAD

**Issue by HLeviel** [ropensci/plotly#748]
I'm trying to determine clicked country in a choropleth map displayed in shiny.

I used [this example for click event](https://plot.ly/r/shinyapp-map-click/) and [this one for display](https://plot.ly/r/choropleth-maps/) and this code works:

```
library(shiny)
library(plotly)
library(countrycode)

df <- countrycode_data[,c("iso3c", "country.name")]
df <- df[complete.cases(df),]
df$random <- rnorm(dim(df)[1])

shinyApp(
  ui = shinyUI(fluidPage(plotlyOutput("plot"), textOutput("text"))), 

  server = shinyServer(function(input, output) {
    output$text <- renderPrint({
      d <- event_data("plotly_click")
      ifelse(is.null(d), "No selection", as.character(df[as.numeric(d[2])+1,"country.name"])) 
      })

    output$plot <- renderPlotly({plot_ly(df, z=~random, locations = ~iso3c, text = ~country.name, type="choropleth")})
  }))
```

When I click on **Afghanistan** which is the first country of the dataset, it correctly selects it
but if I click on **Albania** which is the third one, it returns **Aland Islands** which is the second, and which is not displayed by Plotly:

So I'm guessing that the selection is calculated on a list of displayed entries which I project on the original dataset (which includes all countries)

I unsuccessfully tried to find the country list used in Plotly, which I could use to remove unknown countries.

**Comment by cpsievert** [comment]
This code gives me an error:

```r
Error: object 'countrycode_data' not found
```

Feel free to fix and reopen.

**Comment by HLeviel** [comment]
It's been fixed!
