### ISSUE TITLE
event_data: attempt to apply non-function

### ISSUE THREAD

**Issue by ashleyfarrugia89** [ropensci/plotly#751]
Hello,

I am trying to get events working for plotly in a r shiny module, I managed to get it working previously but it appears that a recent update of the r plotly code has broken this. I have even tried the example in https://cran.r-project.org/web/packages/plotly/plotly.pdf for event_data, and this returns exactly the same error that I am receiving which suggests to me that this is clearly a bug in the latest release. The error I am getting is Error in event_data: attempt to apply non-function. Is there any light you can shine on why I am getting this error?

Thanks,

Ashley

**Comment by cpsievert** [comment]
Please see https://github.com/hadley/ggplot2/issues/1806

**Comment by ashleyfarrugia89** [comment]
Hello cpsievert, I tried the changes you suggest in the article where both ggplot2 and plotly are the CRAN versions, but I still get the same error. This error occurs even when I try to run the example "shiny::runApp(system.file("examples", "plotlyEvents", package = "plotly"))". Just to confirm the version of ggplot is 2.1.0 and plotly is 4.5.2 which are the CRAN versions. I am not sure what is going on here but it is not the same issue are presented in the ggplot ticket.

Thanks,

Ashley
