### ISSUE TITLE
In a bubble chart where points have different sizes, the size in the legend should be consistent

### ISSUE THREAD

**Issue by daattali** [ropensci/plotly#755]
The following line works nicely 

```
plot_ly(iris, x = ~Sepal.Length, y = ~Sepal.Width, color = ~factor(Species), size = ~Petal.Length)
```

![image](https://cloud.githubusercontent.com/assets/952340/19209257/5ae42cdc-8cbb-11e6-9c7c-930b5018c14a.png)

However, the following code results in the legend sizes being weird huge markers, and it's a reason enough to just suppress the legend altogether

```
myiris <- iris[!duplicated(iris$Species), ]
plot_ly(myiris, x = ~Sepal.Length, y = ~Sepal.Width, color = ~factor(Species), size = ~Petal.Length)
```

![image](https://cloud.githubusercontent.com/assets/952340/19209267/857a8374-8cbb-11e6-870f-57593dba4008.png)

@cpsievert told me previously on Twitter that this might be a plotly.js bug. I don't know how to translate this into a JS issue, so if it's indeed a plotly.js bug could you please open the corresponding issue on their repo?

Potentially related to #705

**Comment by cpsievert** [comment]
Pretty sure this was fixed in b48d360badd226d5869eb5283687a17464c6e5dd
