### ISSUE TITLE
3D plot surfaces with distinct x and y coordinates in plotly >= 4.5.2

### ISSUE THREAD

**Issue by nevrome** [ropensci/plotly#756]
I created a vignette with plotly 3.6.? - now I have difficulties to get my code to work with plotly 4.5.2.

The vignette with the old working code can be found [here](https://cran.r-project.org/web/packages/recexcavAAR/vignettes/recexcavAAR-vignette-2.html). I can't reproduce the 3D surface plot with distinct coordinates: 

```{r}
vis %>% 
  add_trace(
    x = surf[[1]]$x, y = surf[[1]]$y, z = surf[[1]]$z, type = "surface", 
    showscale = FALSE, opacity = 0.9, hoverinfo = "none"
  )
```
previously worked. Now I get an Error: 

```{r}
Error: Variables must be length 1 or 19.
Problem variables: 'x'
```
What's the correct syntax to reproduce my old plot with plotly 4.5.2?

**Comment by cpsievert** [comment]
Works for me with the latest GitHub version

**Comment by nevrome** [comment]
Ok - thanks. With the github version it works. Do you have an ETA for this fix in the CRAN version?
