### ISSUE TITLE
geom_smooth not working for ggplotly

### ISSUE THREAD

**Issue by vinhdizzo** [ropensci/plotly#759]
Hi,

Currently on dev version of ggplot2 and plotly in R.  `geom_smooth` seems to not work.  Here's an example:
```r
library(ggplot2)
library(plotly)
library(dplyr)
df <- data.frame(x=rnorm(1000), y=rnorm(1000), text='hello')
df %>%
  ggplot(aes(x=x, y=y, text='hello')) +
  geom_point(alpha=1/3) +
  geom_smooth()
ggplotly(g, tooltip='text')
```

Error:
```
> df <- data.frame(x=rnorm(1000), y=rnorm(1000), text='hello')
> df %>%
+     ggplot(aes(x=x, y=y, text='hello')) +
+     geom_point(alpha=1/3) +
+     geom_smooth()
`geom_smooth()` using method = 'gam'
> ggplotly(g, tooltip='text')
`geom_smooth()` using method = 'loess'
Error in `$<-.data.frame`(`*tmp*`, "alpha", value = 1) : 
  replacement has 1 row, data has 0
```

If I remove the `geom_smooth` line, then things work.  Thanks!

**Comment by cpsievert** [comment]
Looks like you're referencing another object, try this instead:

```r
library(ggplot2)
library(plotly)
library(dplyr)
df <- data.frame(x=rnorm(1000), y=rnorm(1000), text='hello')
g <- df %>%
  ggplot(aes(x=x, y=y, text='hello')) +
  geom_point(alpha=1/3) +
  geom_smooth()
ggplotly(g, tooltip='text')
```

**Comment by vinhdizzo** [comment]
Thanks for catching that error.  Here's a better reproducible example:

```r
library(dplyr)
library(ggplot2)
library(plotly)
g <- data.frame(x=c(23.2,22.8),y=c(17.7,16.3),company=c('a','b')) %>%
    ggplot(aes(x=x,y=y,text=company)) +
    geom_point() +
    geom_smooth()
ggplotly(g, tooltip='text')
```
Error:
```
`geom_smooth()` using method = 'loess'
Error in `$<-.data.frame`(`*tmp*`, "alpha", value = 1) : 
  replacement has 1 row, data has 0
```

If I remove the `geom_smooth` line, then plotly plots it OK.

Can you re-open the issue?  Again this is on dev plotly and dev ggplot2.  Thanks so much for your help.

**Comment by avnerkantor** [comment]
I have the same error.

**Comment by irJERAD** [comment]
same error as well. I've gone through permutations of methods and arrangements. Something with ggplotly and ggplot2. The Docs to mention something about being over 1000 observations and I'm above the 10k mark on this

**Comment by dkgaraujo** [comment]
I haven't investigated much, but for the sake of an empirical help to other ggplotly users, what I noted is that when I pass the "text" aesthetic to the base `ggplot()` function, then of course under the hood it gets passed on to `geom_smooth()` and it then fails to appear on ggplotly. Whereas if I first add the geom_smooth layer *and only then add the geom_point layer passing the text aesthetic only in the geom_point layer*, then everything appears as it should in the ggplotly.
