### ISSUE TITLE
`group_by` not resulting in grouped visual markings

### ISSUE THREAD

**Issue by martinjhnhadley** [ropensci/plotly#761]
The documentation for `plotly_data` provides the following example:

```r
p <- txhousing %>%
  group_by(city) %>%
  plot_ly(x = ~date, y = ~sales)
p
```

This is meant to "# use group_by() to define groups of visual markings" - which I assume to mean that a legend is generated and a colour supplied to each grouping in `city`. However, the following output is generared instead:

```
No trace type specified:
  Based on info supplied, a 'scatter' trace seems appropriate.
  Read more about this trace type -> https://plot.ly/r/reference/#scatter
No scatter mode specifed:
  Setting the mode to markers
  Read more about this attribute -> https://plot.ly/r/reference/#scatter-mode
Warning message:
Ignoring 568 observations 
```

However `groups(p)` correctly reports that the group is `city`. Unfortunately, the old syntax has been deprecated:

```r
txhousing %>%
  plot_ly(x = ~date, y = ~sales, group = ~city)
```
```
Warning messages:
1: In plot_ly(., x = ~date, y = ~sales, group = ~city) :
  The group argument has been deprecated. Use `group_by()` or split instead.
```

**Comment by cpsievert** [comment]
> which I assume to mean that a legend is generated and a colour supplied to each grouping in city

I suggest reading this -- https://cpsievert.github.io/plotly_book/scatter-traces.html#line-plots

> Unfortunately, the old syntax has been deprecated:

As the warning suggests, if u want the old behavior, change `group` to `split`

**Comment by martinjhnhadley** [comment]
@cpsievert thanks, I need to go through the new book properly. Clearly!

**Comment by DonZhi** [comment]
The code below may work:
p <- txhousing %>%
  plot_ly(x = ~date, y = ~sales, split = ~city)
p
