### ISSUE TITLE
plotly surface plot incorrect behavior

### ISSUE THREAD

**Issue by nlhuong** [ropensci/plotly#764]
When plotting a rectangular matrix as a surface in 3D I get very weird errors.
Here is an example of the yield curve surface plot producing errors.

library(ustyc); library(plotly)
yield_data <- getYieldCurve()
yield_df <- yield_data$df
yield_df$BC_30YEARDISPLAY <- NULL

dim(yield_df)
[1] 6705   11

str(yield_df)
'data.frame':   6705 obs. of  11 variables:
 $ BC_1MONTH: num  NA NA NA NA NA NA NA NA NA NA ...
 $ BC_3MONTH: num  7.83 7.89 7.84 7.79 7.79 ...
 $ BC_6MONTH: num  7.89 7.94 7.9 7.85 7.88 ...
 $ BC_1YEAR : num  7.81 7.85 7.82 7.79 7.81 ...
 $ BC_2YEAR : num  7.87 7.94 7.92 7.9 7.9 ...
 $ BC_3YEAR : num  7.9 7.96 7.93 7.94 7.95 ...
 $ BC_5YEAR : num  7.87 7.92 7.91 7.92 7.92 ...
 $ BC_7YEAR : num  7.98 8.04 8.02 8.03 8.05 ...
 $ BC_10YEAR: num  7.94 7.99 7.98 7.99 8.02 ...
 $ BC_20YEAR: num  NA NA NA NA NA NA NA NA NA NA ...
 $ BC_30YEAR: num  8 8.04 8.04 8.06 8.09 ...

plot_ly(
  x = as.Date(rownames(yield_df)),
  y = colnames(yield_df),
  z = data.matrix(yield_df)) %>% add_surface()

> Error: Variables must be length 1 or 6705. Problem variables: 'y'

plot_ly(
  x = colnames(yield_df),
  y = as.Date(rownames(yield_df)),
  z = data.matrix(yield_df)) %>% add_surface()

> Error: Variables must be length 1 or 6705. Problem variables: 'x'

plot_ly(
  y = as.Date(rownames(yield_df)),
  z = data.matrix(yield_df)) %>% add_surface()

produces the correct plot however the x indices are indices and I would like to label
the x tick-marks with the values in the colnames(yield_df) which are:

colnames(yield_df)
 [1] "BC_1MONTH" "BC_3MONTH" "BC_6MONTH" "BC_1YEAR"  "BC_2YEAR"  "BC_3YEAR"  "BC_5YEAR" 
 [8] "BC_7YEAR"  "BC_10YEAR" "BC_20YEAR" "BC_30YEAR"

Please let me know what might be the issue. I am running:
R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)
packageVersion("plotly")
[1] ‘4.5.2’

Thanks!

**Comment by cpsievert** [comment]
I believe this is now fixed

**Comment by shashj199** [comment]
Can you explain how this is fixed? I am facing a similar problem
packageVersion("plotly")
[1] ‘4.5.6’
