### ISSUE TITLE
basic plotting naming convention (non-tilde ~) broken?

### ISSUE THREAD

**Issue by khufkens** [ropensci/plotly#765]
From the plotly reference:

plot_ly(economics, type = "scatter", x = date, y = uempmed, name = "unemployment", marker = list(color="rgb(16, 32, 77)" ,marker-color))

results in this error:

Error in plot_ly(economics, type = "scatter", x = date, y = uempmed, name = "unemployment",  : 
  object 'uempmed' not found

plot_ly(economics, type = "scatter",  x = ~date, y = ~uempmed, name = "unemployment", marker = list(color="rgb(16, 32, 77)" ,marker-color))

Note the tilde in front of the x and y variable!!!
This plots normally!!

This small difference breaks most of my plotting routines (if not all).

--- version
platform       x86_64-apple-darwin13.4.0  
arch           x86_64  
os             darwin13.4.0  
system         x86_64, darwin13.4.0  
status  
major          3  
minor          3.1  
year           2016  
month          06  
day            21  
svn rev        70800  
language       R  
version.string R version 3.3.1 (2016-06-21)
nickname       Bug in Your Hair

**Comment by cldougl** [comment]
Hi there,
Thanks for mentioning the reference page, that's now been updated (to match the rest of our documentation on plot.ly/r ). 
The examples are now updated to run with version 4.x.x (now on CRAN & our dev version). 
For more information on version 4 of our package you can check out this post: http://moderndata.plot.ly/upgrading-to-plotly-4-0-and-above/
