### ISSUE TITLE
Missing data when scales="free_y"

### ISSUE THREAD

**Issue by viniciusvgp** [ropensci/plotly#766]
There is a problem in the new  plotly version  (4.5.2).
With the following example, plotly draws only the last chart of the facet.
library(plotly)
ggplotly(
    ggplot(data.frame(Value = c(2,4, 56,70, 9,4, 23,30 ), Type=c('A', 'A', 'B', 'B', 'C', 'C', 'D', 'D'), Origin= c('XX', 'YY', 'XX', 'YY', 'XX', 'YY', 'XX', 'YY'))) + geom_bar(aes(x=Origin, y=Value, fill=Type), position="stack", stat="identity") + facet_wrap(~Type, nrow=1, scales="free_y")
)
Result (plotly 4.5.2):
![currentplotly](https://s16.postimg.org/n6y0y2b4j/newplot.png)

Expected result (old plotly 3.6.2):
![oldplotly](https://s16.postimg.org/5i6a6fzdf/newplot_1.png)

Even with simple facet, one of the charts is not drawn.
![withoutfacet](https://s16.postimg.org/hc3bxowlh/newplot_2.png)

**Comment by cpsievert** [comment]
A more minimal example of the problem:

```r
mtcars$x <- with(mtcars, paste(vs, am))
ggplot(mtcars, aes(x = mpg, y = wt)) + geom_point() + facet_wrap(~x, scales = "free_y")
ggplotly()
```

I believe the problem is restricted to the "free_y" case, so for now, you could "workaround" that by using "free" instead.

**Comment by titaniumtroop** [comment]
#1132 also references this issue, which apparently has been fixed. I had this issue as well a couple of weeks ago. Updating to the latest plotly version resolved the issue: Try upgrading to the lastest version from github:

``` r
devtools::install_github("ropensci/plotly")
```
