### ISSUE TITLE
Adding layer makes tool tips disappear

### ISSUE THREAD

**Issue by biologicaldynamics** [ropensci/plotly#770]
Using ggplot2 and plotly, I can easily create a US county choropleth and set custom tool tips. However, when I add state boundaries, tool tips fail to render in _some_ situations. The problem seems to be linked to proximity to the state boundary. I believe this may be a bug.

Note that switching to "compare data on hover" solves the problem. As a temporary solution, is there a way to set this to be true by default?

First, an example where adding the second layer completely breaks tool tips.

```
library(plotly)
library(tidyverse)

### One layer -- works fine
a <- data.frame(group = seq(3085), val = rnorm(3085)) %>%
  left_join(ggplot2::map_data("county"), by = "group")

p <- ggplot(a, aes(long, lat, group = group)) +
  geom_polygon(aes(fill = val, text = subregion))

ggplotly(p, tooltip="text")

### Two layers -- no tool tips
b <- ggplot2::map_data("state")

p <- ggplot(a, aes(long, lat, group = group)) +
  geom_polygon(aes(fill = val, text = subregion)) +
  geom_path(data = b, color = "black")

ggplotly(p, tooltip="text")
```

When I use a much smaller choropleth (one state), the tool tips display normally even with two layers.

```
### Just Delaware: shows tool tips
b <- ggplot2::map_data("state") %>%
  filter(region == "delaware")

a <- data.frame(group = seq(3085), val = rnorm(3085)) %>%
  left_join(ggplot2::map_data("county"), by = "group") %>%
  filter(region == "delaware")

p <- ggplot(a, aes(long, lat, group = group)) +
  geom_polygon(aes(fill = val, text = subregion)) +
  geom_path(data = b, color = "black")

ggplotly(p, tooltip="text")
```

A medium-size choropleth with two layers displays tool tips far from the state boundary, but not close to it.

```
### New England: *sometimes* shows tool tips
new_england <- c("maine", "new hampshire", "vermont", "massachusetts", "connecticut", "rhode island")
b <- ggplot2::map_data("state") %>%
  filter(region %in% new_england)

a <- data.frame(group = seq(3085), val = rnorm(3085)) %>%
  left_join(ggplot2::map_data("county"), by = "group") %>%
  filter(region %in% new_england)

p <- ggplot(a, aes(long, lat, group = group)) +
  geom_polygon(aes(fill = val, text = subregion)) +
  geom_path(data = b, color = "black")

ggplotly(p, tooltip="text")
```

**Comment by cpsievert** [comment]
> Note that switching to "compare data on hover" solves the problem. As a temporary solution, is there a way to set this to be true by default?

```r
ggplotly(p, tooltip="text") %>% layout(hovermode = "x")
```

**Comment by cpsievert** [comment]
> I believe this may be a bug.

I wouldn't consider it a bug, but perhaps the hover behavior could be improved.

Anyway, this is something that will have to be resolved at the plotly.js level. I'd recommend posting this figure to a plotly account and filing an issue here -- https://github.com/plotly/plotly.js/issues

**Comment by Nova-Scotia** [comment]
@borenstein did you ever come up with an alternative solution? @MountainCedar this is the issue we are having with ggplotly graphs in our app. The "compare on hover" solution doesn't work for me.
