### ISSUE TITLE
`ggplotly` does not respect the `plotly_domain` environment variable

### ISSUE THREAD

**Issue by rasmusab** [ropensci/plotly#771]
Say I work at a company with sensitive information, and I want the "edit" button to point to our custom plotly domain so that people don't leak data by mistake. In the current version of plotly for R (4.5.2) the `plot_ly` command respects a custom domain but `ggplotly` does not.

Example: 

```
> Sys.setenv("plotly_domain"="https://plotly.myplotlydomain.com/")
>
> a <- plot_ly(economics, x = ~pop)
> a$x$base_url
[1] "https://plotly.myplotlydomain.com/"
> 
> b <- ggplotly(ggplot(economics, aes(pop)) + geom_histogram(), )
> b$x$base_url
NULL
```

This is also reflected in that the "save and edit plot in cloud"-button does not point to the custom domain. This issue might be related to this issue: https://github.com/ropensci/plotly/issues/444

**Comment by lucacerone** [comment]
Yes it is the same issue. It was fixed at some point though.

**Comment by cpsievert** [comment]
This appears to be fixed in the dev version which we'll be submitting to CRAN in the next couple weeks (right after ggplot2 submits)

**Comment by sudburyrob** [comment]
@rasmusab  -- hi I got a note from Chris about this earlier today .. does Carson's note address his concern?

**Comment by rasmusab** [comment]
@sudburyrob Yes it does, thanks! :)
