### ISSUE TITLE
Linking views with plotly_hover

### ISSUE THREAD

**Issue by avnerkantor** [ropensci/plotly#775]
I want to show simultantly the tooltips of all the plots when I hovering one of them. Is that possible?

library(plotly)
vars <- setdiff(names(economics), "date")
plots <- lapply(vars, function(var) {
  plot_ly(economics, x = ~date, y = as.formula(paste0("~", var)), name = var) %>%
    add_lines()
})
subplot(plots, nrows = length(plots), shareX = TRUE, titleX = FALSE)

**Comment by cpsievert** [comment]
No. Please file a feature request at https://github.com/plotly/plotly.js
