### ISSUE TITLE
Zeppelin 0.6 fail to use plotly in R

### ISSUE THREAD

**Issue by harryprince** [ropensci/plotly#779]
http://stackoverflow.com/questions/40079899/how-to-configure-apache-zeppelin-to-display-graph-created-by-plotly-from-r-inter

the find the same unsolved problem on stackoverflow[`Zeppelin`](http://stackoverflow.com/questions/40079899/how-to-configure-apache-zeppelin-to-display-graph-created-by-plotly-from-r-inter)

**Comment by cpsievert** [comment]
Have you tried using `embed_notebook()` with the latest (dev) version?
