### ISSUE TITLE
a warning I don't understand

### ISSUE THREAD

**Issue by stla** [ropensci/plotly#783]
Hello,
I'm using plotly `4.5.2`.
First, I do a heatmap:
```
library(plotly)
x <- 0:10
y <- 0:10
dd <- transform(expand.grid(x=x, y=y), z=x+y)
pp <- plot_ly() %>% 
  add_trace(data=dd, x=~x, y=~y, z=~z, type="heatmap")
```
It works fine.
Then, I add a line to the graphic:
```
dd1 <- data.frame(x=0:10, y=0:10) 
pp <- pp %>%
  add_trace(data=dd1, x=~x, y=~y, type="scatter", mode="lines", showlegend=FALSE)
```
Now, I add a second line:
```
dd2 <- data.frame(x=0:10, y=10:0)
pp <- pp %>%
  add_trace(data=dd2, x=~x, y=~y, type="scatter", mode="lines", showlegend=FALSE)
```
This generates this warning:
```
Warning message:
'heatmap' objects don't have these attributes: 'marker'
Valid attributes include:
'type', 'visible', 'showlegend', 'legendgroup', 'opacity', 'name', 'uid', 'hoverinfo', 'stream', 'z', 'x', 'x0', 'dx', 'y', 'y0', 'dy', 'text', 'transpose', 'xtype', 'ytype', 'zsmooth', 'connectgaps', 'colorbar', 'zauto', 'zmin', 'zmax', 'colorscale', 'autocolorscale', 'reversescale', 'showscale', 'xaxis', 'yaxis', 'zsrc', 'xsrc', 'ysrc', 'textsrc', 'key'
```
I don't understand this warning. This is not important because the output is nice. But I would prefer if there were no warning.

**Comment by cpsievert** [comment]
Thanks!

As per our [contributing guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), github issues are reserved for bug reports and feature requests only. So I'll have to close your ticket.

Please use our community forums at [community.plot.ly](http://community.plot.ly/) for posts of the likes.

**Comment by geotheory** [comment]
Looked like a bug to me
