### ISSUE TITLE
bottom padding on subplot interferes with tooltip

### ISSUE THREAD

**Issue by Alanocallaghan** [ropensci/plotly#786]
In some cases, using bottom padding causes tooltips to not be usable within a lower plot of the subplot. In the example below, the padding is set to zero within heatmaply to avoid this. I then manually change the (similar to what `layout(h, margin=list(b=50))` would do) and the issue can be seen. Cheers

	library(devtools)
	library(htmlwidgets)
	install_github("Alanocallaghan/heatmaply")
	x  <- as.matrix(datasets::mtcars)

	library(heatmaply)

	h <- heatmaply(x[,-c(8,9)], seriate = "mean",
	          col_side_colors = t(data.frame(
	          	a=c(rep(0,5), rep(1,4)), b=c(rep(0,5), rep(1,4))
	          	)),
	          row_side_colors = x[,8:9]
	          # ,
	          # return_ppxpy=TRUE
	          )
	saveWidget(h, "test.html")

	h$x$layoutAttrs[[2]]$margin$b <- 50
	saveWidget(h, "test.html")

**Comment by cpsievert** [comment]
This heatmaply call gives me an error, feel free to fix and reopen

**Comment by Alanocallaghan** [comment]
Sorry about that, the example is fixed now, though in this instance the bug doesn't seem to occur, though I observed it recently in another instance. If I reproduce I'll re-open.
