### ISSUE TITLE
plotly_IMAGE() results in 500 error

### ISSUE THREAD

**Issue by cldougl** [ropensci/plotly#789]
`plotly_IMAGE()` is consistently resulting in the following error:
```
Error in process.image(append_class(resp, "image")) : 
  Internal Server Error (HTTP 500).
```

example:
```
library(plotly)
set.seed(100)
d <- diamonds[sample(nrow(diamonds), 1000), ]
p <- plot_ly(d, x = ~carat, y = ~price, color = ~carat,
             size = ~carat, text = ~paste("Clarity: ", clarity))
plotly_IMAGE(p)
```

**Comment by jrjhealey** [comment]
I'm having the same problem. I can't see any information elsewhere on the web, and the Plotly forums pointed me to this open issue.

Is there a known solution yet?

**Comment by elisebell** [comment]
This issue is affecting me as well - any idea when it will be resolved?

**Comment by cldougl** [comment]
@jrjhealey it won't be in the CRAN version just yet, but you could use the latest development version by installing via devtools: `devtools::install_github("ropensci/plotly")`. More installation instructions can be found here: https://plot.ly/r/getting-started/#installation

**Comment by flop71** [comment]
The 500 error appears to be fixed using the latest drop of ploty (I tried it yesterday) however from the command line when i run Error in process.image(append_class(resp, "image")) : 
  Payment Required (HTTP 402).

I realise this is a diffident issue.

Regards
Jonathan

**Comment by hack-r** [comment]
I have this problem using the latest R plot.ly package... would suggest to reopen this issue
