### ISSUE TITLE
Using layout within R-notebook

### ISSUE THREAD

**Issue by geponce** [ropensci/plotly#791]
Using the R-notebook setup and the example plot/data from th plotly github: 

title: "R Notebook"
output:
  html_notebook: default
  html_document: default
  always_allow_html: default
  pdf_document: default

```{r}
var.themes1 <- theme_bw() + theme(plot.title=element_text(family="Arial", face="bold", size=20)) + theme(axis.text.x = element_text(hjust = 0.1, size=14,color="grey40")) + theme(axis.text.y = element_text(hjust = 0.1, size=14,color="grey40")) + theme(axis.title.x=element_text(family="Arial",  size=16)) + theme(axis.title.y=element_text(family="Arial",  size=16)) + theme(legend.title=element_text(family="Arial",  size=16)) + theme(legend.text=element_text(family="Arial",  size=14))

library(plotly)
g <- ggplot(faithful, aes(x = eruptions*100, y = waiting*100)) +
  stat_density_2d(aes(fill = ..level..), geom = "polygon") + 
  #xlim(1, 6) + ylim(40, 100) +
  xlab ("Eruptions") + ylab ("Waiting (sec)") +
  var.themes1

m = list( l = 200, r = 200, b = 70, t = 50, pad = 0 )
 f <- list( 
   family = "Open Sans", 
   size = 14, 
   color = "#000" 
 ) 
 l <- list( 
  font = f, 
   x=1, 
   y=1 
 ) 
 
b <- ggplotly(g) %>%
  layout(legend= l,margin = m, font = list(family = 'Open Sans', size = 14))
build <- plotly_build(b)
build 
````

I'm trying to change the margin between the axis titles and the axis text using the margin option within layout and I keep getting this error:

_**Error in lengths(x$annotations) : 'x' must be a list**_

Guillermo

**Comment by vancelopez** [comment]
@geponce Did you ever find a solution to this?

**Comment by geponce** [comment]
@vancelopez Not yet.

**Comment by vancelopez** [comment]
Okay, the error code is from the base `lengths()` function. The error is induced when calling `layout()`. I was able to get around this by declaring an empty `annotations` attribute.  Including session info and reproducible example. Recommend renaming the issue to indicate a bug.

```
library(plotly)
library(dplyr)

d <- sample_frac(diamonds, 0.1)

# working plot
plot_ly(d, y = ~price, type = "box")

# not working
plot_ly(d, y = ~price, type = "box") %>%
  layout(xaxis = list(title = "all diamonds"))
#Error in lengths(x$annotations) : 'x' must be a list

# workaround
plot_ly(d, y = ~price, type = "box") %>%
  layout(xaxis = list(title = "all diamonds"),
         annotations = list()) 
```

Session info -------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.0 (2015-04-16)
 system   i386, mingw32               
 ui       RStudio (1.0.44)            
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Los_Angeles         
 date     2016-11-30                  

Packages -----------------------------------------------------------------------------------------------------------------------------------------------------
 package     * version date       source        
 assertthat    0.1     2013-12-06 CRAN (R 3.2.0)
 base64enc     0.1-3   2015-07-28 CRAN (R 3.2.2)
 colorspace    1.3-1   2016-11-18 CRAN (R 3.2.5)
 DBI           0.5-1   2016-09-10 CRAN (R 3.2.5)
 devtools      1.12.0  2016-06-24 CRAN (R 3.2.5)
 digest        0.6.10  2016-08-02 CRAN (R 3.2.5)
 dplyr       * 0.5.0   2016-06-24 CRAN (R 3.2.5)
 ggplot2     * 2.2.0   2016-11-11 CRAN (R 3.2.5)
 gtable        0.2.0   2016-02-26 CRAN (R 3.2.0)
 htmltools     0.3.5   2016-03-21 CRAN (R 3.2.4)
 htmlwidgets   0.8     2016-11-09 CRAN (R 3.2.5)
 httr          1.2.1   2016-07-03 CRAN (R 3.2.0)
 jsonlite      1.1     2016-09-14 CRAN (R 3.2.5)
 lazyeval      0.2.0   2016-06-12 CRAN (R 3.2.5)
 magrittr      1.5     2014-11-22 CRAN (R 3.2.0)
 memoise       1.0.0   2016-01-29 CRAN (R 3.2.3)
 munsell       0.4.3   2016-02-13 CRAN (R 3.2.3)
 plotly      * 4.5.6   2016-11-12 CRAN (R 3.2.5)
 plyr          1.8.4   2016-06-08 CRAN (R 3.2.5)
 purrr         0.2.2   2016-06-18 CRAN (R 3.2.5)
 R6            2.2.0   2016-10-05 CRAN (R 3.2.5)
 Rcpp          0.12.8  2016-11-17 CRAN (R 3.2.5)
 scales        0.4.1   2016-11-09 CRAN (R 3.2.5)
 tibble        1.2     2016-08-26 CRAN (R 3.2.5)
 tidyr         0.6.0   2016-08-12 CRAN (R 3.2.5)
 viridisLite   0.1.3   2016-03-12 CRAN (R 3.2.4)
 withr         1.0.2   2016-06-20 CRAN (R 3.2.5)
 yaml          2.1.14  2016-11-12 CRAN (R 3.2.5)

**Comment by cpsievert** [comment]
All these examples seem to work for me

**Comment by geponce** [comment]
@cpsievert It looks like the latest update for some of the packages related to R-notebook and plotly dependencies fixed the issue  **_Error in lengths(x$annotations) : 'x' must be a list_** 
@vancelopez Since I did a recent update to the packages plotly, knitr and rmarkdown.  I hadn't tested lately and I actually don't get the error anymore. 

However, couple of issues with labels on the axes and legend overlaping the plot when try to use layout() with facet_grid. Is this something that still not supported?  See this example from the plotly-R website:
[Facet_grid Timeseries](https://plot.ly/ggplot2/facet_grid/)
```
library(plotly)
library(plyr)

date <- rep(as.Date(1:365,origin='2011-1-1'),7)
location <- factor(rep(1:7,365))
product <- rep(letters[1:7], each=365)
value <- c(sample(1:10, size=365, replace=T),sample(1:3, size=365, replace=T),
           sample(10:100, size=365, replace=T), sample(1:50, size=365, replace=T),
           sample(1:20, size=365, replace=T),sample(50:100, size=365, replace=T),
           sample(1:100, size=365, replace=T))
dat<-data.frame(date,location,product,value)


corr_dat<-ddply(dat, .(product), summarise, value=value)
corr.df<-unstack(corr_dat, value~product)

corr_plot <- data.frame(date=max(dat$date),
                        label=paste0("rho==",round(cor(corr.df)[,1], 2)),
                        ddply(dat, .(product), summarise,
                              value=(min(value)+max(value))/2))

d<-ggplot(dat, aes(x=date, y=value, color=location, group=location)) +
    geom_line()+
    facet_grid(product ~ ., scale = "free_y")
  g <- ggplotly(d, source = 'source') %>% 
        layout(yaxis=list(title = 'PRICE $'))
g
```
![image](https://cloud.githubusercontent.com/assets/5420072/20774987/04b75516-b716-11e6-9f87-1dc6f4ae4b17.png)
![image](https://cloud.githubusercontent.com/assets/5420072/20775071/66129fd2-b716-11e6-95bc-f12e29c87495.png)

**Comment by cpsievert** [comment]
@geponce you could use the usual `ggplot2::ylab()`, but here is a more general solution for modifying annotations from the built object:

```r
g <- plotly_build(ggplotly(d, source = 'source'))
g$x$layout$annotations[[which(sapply(g$x$layout$annotations, "[[", "text") == "value")]]$text <- "PRICE $"
g
```
