### ISSUE TITLE
Color of text box 

### ISSUE THREAD

**Issue by caleblareau** [ropensci/plotly#792]
Direct from the plotly site, under some plotting conditions, the color of the text box does not change in conjunction with the point being hovered over. 

For example, see the graph associated with "3D Scatter Plot with Color Scaling" on this link: https://plot.ly/r/3d-scatter-plots/

**Comment by cpsievert** [comment]
I think this is a plotly.js issue. Please file a reproducible example -- https://github.com/plotly/plotly.js
