### ISSUE TITLE
multiline category labels not centered

### ISSUE THREAD

**Issue by salim-b** [ropensci/plotly#793]
When creating a plot with multiline labels (using HTML `<br>` tags in the strings), the lables are aligned as if they would consist of only one line, i. e. they aren't centered. See example below or [on plot.ly](https://plot.ly/~slim-b/221/wenn-es-um-politische-informationen-geht-wie-stark-vertrauen-sie-folgenden-infor/):

![example](https://i.imgur.com/5cYRiFA.png)

Regardless of whether you gonna fix this or not, is there any workaround to get correctly aligned multiline labels with the current plotly for R?

**Comment by cpsievert** [comment]
Thanks!

As per our [contributing guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), github issues are reserved for bug reports and feature requests only. So I'll have to close your ticket.

Please use our community forums at [community.plot.ly](http://community.plot.ly/) for posts of the likes.

**Comment by salim-b** [comment]
@cpsievert Thanks, I've actually read those guidelines and thought I should report this as a bug. But I guess you disagree. Can I change this into a _feature request_ then?

**Comment by cpsievert** [comment]
Sorry, I misread the problem -- this would be better reported/solved over at https://github.com/plotly/plotly.js

**Comment by salim-b** [comment]
ok, [reported](https://github.com/plotly/plotly.js/issues/1137).
