### ISSUE TITLE
ggplotly no longer works with ggplot2 version 2.2.0

### ISSUE THREAD

**Issue by bschneidr** [ropensci/plotly#794]
With the latest update of ggplot2, the `ggplotly()` function no longer seems to work.

Please see the example below:

```
library(ggplot2)
library(plotly)

ggiris <- qplot(Petal.Width, Sepal.Length, data = iris, color = Species)
ggplotly(ggiris)
```

When I call `ggplotly()` in this example, I receive the following error:

```
Error in gg2list(p, width = width, height = height, tooltip = tooltip,  : 
  attempt to apply non-function
```

**Comment by talgalili** [comment]
The version of plotly on github does work with ggplot2.

@cpsievert - could you please upload the current github version of plotly to CRAN?

Thanks.

**Comment by cpsievert** [comment]
4.5.6 was just accepted

**Comment by talgalili** [comment]
Thanks :)
