### ISSUE TITLE
plotly#554: crosstalk highlighting/linking works selectively 

### ISSUE THREAD

**Issue by slavaua87** [ropensci/plotly#796]
![image](https://cloud.githubusercontent.com/assets/9389560/20327728/5cca9efe-ab5c-11e6-90a6-c4b3ded4fe7a.png)

The plotly piece is `ggplotly(p) %>% highlight(off = "plotly_unhover", color = "yellow")`. 

I cannot give a reproducible example because the data is proprietary, and I do not really understand the issue to reproduce it with open data. The image has as much as I have. Little tinkering in a debugger shows that the issue seems to come up when hay.every is not an array when it should be one. 

The issue emerges only for some number of data points. For sample size of 8, chart shows highlighting and brushed linking works across multiple charts, but with 9 points, neither work. Other combinations of points also work or do not work without an obvious pattern. This somehow has to be related to the for loop inside which hay.every is evaluated.

There also may be a connection to what R type determines the color of points. For the sample sizes that give an error, the issue goes away, at least for the number of points I tried, if I change from character to integer type.

**Comment by cpsievert** [comment]
Interesting. Can you provide the output of `console.log(haystack);`?

**Comment by slavaua87** [comment]
The issue seems to be with findNestedMatches function. There is a type mismatch, sometimes the `haystack` argument is a string when it should be an array. The existing code only checks elements for being arrays - the for loop under the comment - but the whole container should be an array, too. So a simple fix, which I haven't tested a ton, is to add a type-checking statement like this:

```
function findNestedMatches(haystack, needleSet) {  
  var matches = [];  
  if(!Array.isArray(haystack)){  
	haystack = [haystack]; 
// ensure both haystack and needleset are an array of an arrays
  for (var i = 0; i < haystack.length; i++) {
    if (!Array.isArray(haystack[i])) {
      haystack[i] = [haystack[i]];
    }
  }
...
 } 
```
Note that I am only showing the initial lines of the function. I could do a pull request, but I am not sure about the branch.

**Comment by cpsievert** [comment]
@slavaua87 does this fix it? ^^^

**Comment by slavaua87** [comment]
No, same problem.

**Comment by cpsievert** [comment]
whoops, I made a silly mistake in 	f79cea9 -- does 2ec5bcc46fe203d049aca30d4dc1b6584f9e2f05 fix it?

**Comment by slavaua87** [comment]
Yes. Thanks!
