### ISSUE TITLE
Reseting click-events

### ISSUE THREAD

**Issue by paulcbauer** [ropensci/plotly#797]
Hi Plotly Team, hi Carson,

I am building a rather advanced shiny app. The idea is that users can draw curves by clicking on one plotly plot. Then their input is added to a global data set which in turn is visualized in another plot. 

I have a problem with event_data. I need to be able to reset/delete the event_data after I added it's contents to global object. Is there any possibility to do that? I found [this](http://stackoverflow.com/questions/39858767/clear-plotly-click-event) and [this](https://community.plot.ly/t/coupled-events-with-shiny-and-plotly-in-r-resetting-click-event-data-once-new-plot-is-rendered/1805) but no easy solutions (also I don't know javascript).

Thank you!

Paul

**Comment by cpsievert** [comment]
Thanks!

As per our [contributing guidelines](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), github issues are reserved for bug reports and feature requests only. So I'll have to close your ticket.

Please use our community forums at [community.plot.ly](http://community.plot.ly/) for posts of the likes.
