### ISSUE TITLE
Customising Hover Text No Longer Possible With ggplot 2.2.0

### ISSUE THREAD

**Issue by DarioS** [ropensci/plotly#800]
Since the new ggplot2 is released, `geom_point` doesn't have a `text` aesthetic.

In ggplot2 version 2.1:

    geom_point(aes(text = "Name"))

In ggplot2 version 2.2:

    geom_point(aes(text = "Name"))
    Warning: Ignoring unknown aesthetics: text

How can users modify the hover text if they have installed ggplot2 2.2 ? Also, the [online examples](https://plot.ly/r/) are out of date.

**Comment by cpsievert** [comment]
**ggplot2** _never_ supported a `text` aesthetic, but now it warns about unsupported aesthetics.

You can ignore the warning...it still works via `ggplotly()` as it did before
