### ISSUE TITLE
scale_y_log10() alters tooltip values in ggplotly

### ISSUE THREAD

**Issue by kurtosis** [ropensci/plotly#804]
If I transform an axis to log scale this alters the values that show up in the tooltip. For example, I get 
'val=0.95' (i.e. log10(9)), rather than 'val=9'

library(plotly)
test=data.frame(index=c(1,2,3), val=c(9,14,2))
ggplotly(
  ggplot(test, aes(x=index, y=val)) + geom_point() + scale_y_log10()
)

**Comment by titaniumtroop** [comment]
Same goes for scale_[xy]_sqrt()

```
library(plotly)
test=data.frame(index=c(1,2,3), val=c(9,14,2))
ggplotly(
ggplot(test, aes(x=index, y=val)) + geom_point() + scale_y_sqrt()
)
```

![screen shot 2017-03-21 at 12 08 37](https://cloud.githubusercontent.com/assets/13068310/24160217/33d8376e-0e2f-11e7-966f-5951b3ad76df.png)
