### ISSUE TITLE
`barnorm` removed from `layout` attributes but still in plotly.js and works

### ISSUE THREAD

**Issue by martinjhnhadley** [ropensci/plotly#806]
Using example:

```r
# number of diamonds by cut and clarity (n)
cc <- count(diamonds, cut, clarity)
# number of diamonds by cut (nn)
cc2 <- left_join(cc, count(cc, cut, wt = n))
p <- cc2 %>%
  mutate(prop = n^2 / nn) %>%
  plot_ly(x = ~cut, y = ~prop, color = ~clarity) %>%
  add_bars()
p %>% layout(barmode = "stack")
```

In previous versions of your R/Python documentation and APIs there was the attribute for `layout` called `barnorm` that allowed stacking to be controlled. It currently continues to work but provides an error:

```r
p %>% layout(barmode = "stack", barnorm = "percent")
p %>% layout(barmode = "stack", barnorm = "fraction")
# Warning message:
# 'layout' objects don't have these attributes: 'barnorm'
```

I note that the interactive plotly2 builder no longer includes this option either, or in your [excellent!] new book https://cpsievert.github.io/plotly_book/bars-histograms.html

![image](https://cloud.githubusercontent.com/assets/9363263/20520569/3b8150e2-b09f-11e6-8f9c-60efeb544adf.png)

However, it is still supported in the plotly.js library extensively: https://github.com/plotly/plotly.js/search?utf8=%E2%9C%93&q=barnorm

Could you advise on my dependence on this attribute? I could easily manage this in my data processing, but there are obvious benefits to using a well thought out stacking system in your JS library.

Understand this isn't a "bug" as requested by your default text in issues - very happy for this to be closed.

**Comment by cpsievert** [comment]
Thanks. Just to be clear, it's a warning (and appears to be a false-positive one), not an error.
