### ISSUE TITLE
Axis are duplicated when using scattergl type and color

### ISSUE THREAD

**Issue by federicou** [ropensci/plotly#809]
I'm using Plotly package version 4.5.6.
Trying to plot a scatter chart with scattergl and linking the color to a variable in my dataset I see that the axis and label are drawn twice
`p <- plot_ly(x=~runif(100),y=~runif(100),color=runif(100),mode="markers",type="scattergl")`
while this doesn't occur when setting the type to "scatter" or removing the property "color

**Comment by cpsievert** [comment]
Huh, interesting, in the meantime, you can do this:

```r
plot_ly(x=~runif(100),y=~runif(100),color=~runif(100)) %>% 
  add_markers() %>% 
  toWebGL()
```
