### ISSUE TITLE
add _real_ stacked area charts [feature request]

### ISSUE THREAD

**Issue by salim-b** [ropensci/plotly#810]
I'm filing this issue as a gathering point for the feature request of **_real_ stacked area charts**.

The current solution to create stacked area charts is [to plot cumulative variables](https://plot.ly/r/filled-area-plots/) which has multiple drawbacks:
- correct (i.&nbsp;e. non-cumulative) hover values have to be set manually by using `text = ...`
- the resulting chart [is incorrect if some traces are shown and others hidden (by clicking on legend items)](https://github.com/plotly/plotly.js/issues/344)

A real solution would be to have an argument like `layout(linemode = "stack"`), [same as there is for bar charts](https://plot.ly/r/bar-charts/). Of course this would need some under-the-hood work in `plotly.js` first I guess.

Some more information:
- relevant bug reports:
  - `plotly.js`: <https://github.com/plotly/plotly.js/issues/344>
  - `plotly` for `R`: <https://github.com/ropensci/plotly/issues/686>
- [Generating a stacked area chart in `ggplot2`](http://chrisalbon.com/r-stats/stacked-area-graph.html) and then converting it to plotly using `ggplotly` doesn't work as supposed either (the plot doesn't get rescaled correctly if traces in between are unselected, there will just be space left).
- workaround (in `JS`): <https://codepen.io/etpinard/pen/yOgdOb>

**Comment by cpsievert** [comment]
This is more of a feature request of plotly.js, rather than R package. Please file an issue there -- https://github.com/plotly/plotly.js

**Comment by salim-b** [comment]
ok, [reported](https://github.com/plotly/plotly.js/issues/1217).
