### ISSUE TITLE
add an option for title positioning and/or alignment [feature request]

### ISSUE THREAD

**Issue by salim-b** [ropensci/plotly#812]
Right now there's no proper way to set the spacing between the title and the plot area.

It is possible to set a top margin via `margin = list(t = ...)`. But there's no way to set the title position _between that top margin and the plot area_, it just gets auto-positioned in a way far from perfect.

 If you wanna add more space, currently the only way to do that is to increase that top margin which actually increases the space between the title and the plot area – but only by a fraction of the additional top margin value. This results in ridiculously large spacings between the top of the frame and the title. This is especially true for multiline titles (using `<br>` tags) where the the top margin needs to be quite large for all of the title lines to be visible.

**Comment by cpsievert** [comment]
This, as well as #812, seems better suited for issues over at https://github.com/plotly/plotly.js

**Comment by salim-b** [comment]
> This, as well as #812 ...

_This_ actually is #812 so I guess you mean another issue?

> This (...) seems better suited for issues over at https://github.com/plotly/plotly.js

Ok, I see. What [@etpinard proposes](https://github.com/plotly/plotly.js/issues/882#issuecomment-244198133) in https://github.com/plotly/plotly.js/issues/882 seems to include what I've requested above :+1:

**Comment by cpsievert** [comment]
Whoops, yea, I meant #811

**Comment by salim-b** [comment]
ok, also reported over at plotly.js
