### ISSUE TITLE
Don't work on Microsoft R Open

### ISSUE THREAD

**Issue by h0tc0d3** [ropensci/plotly#814]
```
library(plotly)
p <- plot_ly(midwest, x = ~percollege, color = ~state, type = "box")
p
```
Show error
> Error in unique.default(x) : unique() applies only to vectors

**Comment by bcdunbar** [comment]
from recollection that's because when you install.packages("plotly") in MRAN it installs 3.6

**Comment by cpsievert** [comment]
I can't do anything to help, sorry.
