### ISSUE TITLE
TypeError: 'undefined' is not a function (evaluating 'i.bind(void 0,t)')

### ISSUE THREAD

**Issue by khaledwj90** [ropensci/plotly#815]
i'm trying to execute my first example but i got below error in the console.

**TypeError: 'undefined' is not a function (evaluating 'i.bind(void 0,t)')**

i'm using CDN to get JS.

<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

**Comment by cpsievert** [comment]
Please reopen if you can provide a reproducible R example
