### ISSUE TITLE
Iframe can't be embedded in R notebooks

### ISSUE THREAD

**Issue by NicolasWoloszko** [ropensci/plotly#820]
Iframes embedded in R notebooks return errors. 
It is all the more anniying that the figures produced with embed_notebook(p) do not survive when the R notebook is downloaded in html. 
Thanks in advance.

**Comment by Nikolai-Hlubek** [comment]
As a workaround you can do the following:
> embed_notebook(p, file="yourfile.html")
Then embed_notebook does not create a temp file but will always use "yourfile.html". If you download the notebook in html you must distribute yourfile.html as well and you will get the proper output.

**Comment by cpsievert** [comment]
I'm guessing RStudio won't allow u to embed iframes for security reasons. I can't do about that, sorry

**Comment by NicolasWoloszko** [comment]
I am using Jupyter notebook, not R studio
