### ISSUE TITLE
No output with scattergl and add_trace

### ISSUE THREAD

**Issue by Nikolai-Hlubek** [ropensci/plotly#821]
The following slight deviation of the recommended example for scattergl results in an empty plot.

```
n <- 750
x <- rnorm(n)
y <- 2*x + rnorm(n, sd = 5)

p <- plot_ly(type = "scattergl", mode = "lines")
p <- add_trace(p, x = x, y = y)
embed_notebook(p, file="data.html")
```

This is not jupyter specific. The same error happens with `print(p)` instead of `embed_notebook ` in RStudio.

**Comment by cpsievert** [comment]
Since you've specified `type` in `plot_ly()` it will create a trace, but you haven't supplied any data for this trace...

I suppose `plot_ly()` could do a better job of at least warning about "empty" traces.

In the meantime, this will give you the desired result:

```r
n <- 750
x <- rnorm(n)
y <- 2*x + rnorm(n, sd = 5)

plot_ly(x = x, y = y) %>%
    add_paths() %>%
    toWebGL()
```

**Comment by cpsievert** [comment]
This appears to work now
