### ISSUE TITLE
Save as html -> Pandoc out of memory

### ISSUE THREAD

**Issue by Nikolai-Hlubek** [ropensci/plotly#822]
Hi guys

I have the following minimal example of plotly

```
library(plotly)

n <- 300000
x <- rnorm(n)
y <- 2*x + rnorm(n, sd = 5)

p <- plot_ly(type = "scatter", mode = "markers")
p <- add_trace(p, x = x, y = y)
print(p)
```

Up until this point everything works fine. Plotting in RStudio can be done without any issue. 
As a next step I would like to save the result into a html file and do the following:

htmlwidgets::saveWidget(as.widget(p), "index.html")

```
pandoc.exe: out of memory
Error: pandoc document conversion failed with error 1
```

This leads to a Pandoc out of memory error. The html file is only ~10MB so I do not consider this a _data to big to handle_ issue. Although this ultimately is a htmlwidgets error I'm posting this issue here as well, because I would like to get plotly html output to perform properly.

**Comment by cpsievert** [comment]
Your example works for me, and there isn't much I can do here....
