### ISSUE TITLE
plotly::export generates blank files 

### ISSUE THREAD

**Issue by augustoamerico** [ropensci/plotly#825]
I've notice this behaviour in the following scenarios:

- Plotly object with the plot type = "box"
- Plotly object with the plot type = "scatter" and marker colors with continuous values

A minimal example where I can find the stated behaviour:

```
dfs <- data.frame(
  x = rnorm(10),
  y = rnorm(10),
  z = rnorm(10)
)

case1 <- plotly::plot_ly(dfs, y = ~y, type="box")
plotly::export(case1)
case2 <- plotly::plot_ly(dfs, x = ~x, y = ~y, type="scatter", mode="markers", marker=list(color = ~z)) 
plotly::export(case2)
```

**Comment by cpsievert** [comment]
This seems to be working now. I think the recent addition of a TypedArray polyfill by default fixed the problem
