### ISSUE TITLE
ggplotly: Some tooltips missing in stacked barplot

### ISSUE THREAD

**Issue by luke-a** [ropensci/plotly#831]
_(Crossposted [from Stackoverflow.com](http://stackoverflow.com/questions/41184959/plotly-ggplot2-some-tooltips-missing-in-stacked-barplot): )_ Given for example
```
library(ggplot2)
library(plotly)
df <- data.frame(V1=gl(6,20), V2=gl(40,3))
p <- ggplot(df, aes(x=V1, fill=V2)) + geom_bar(color="white")
ggplotly(p)
```
![ggplotly](https://cloud.githubusercontent.com/assets/4359307/21287012/db2cc082-c462-11e6-9eb5-9a8c1afc5512.gif)

some bar segments show no tooltip/hover information, whereas the legend displays the huge number of factor levels nicely (=scroll bar). How can I fix this?

I'm using
```
packageVersion("ggplot2")
# [1] ‘2.2.0’
packageVersion("plotly")
# [1] ‘4.5.6’
```

**Comment by EmanuelContreras** [comment]
adding some code. We can fix it:
```
library(ggplot2)
library(plotly)
df <- data.frame(V1=gl(6,20), V2=gl(40,3))
p <- ggplot(df, aes(x=V1, fill=V2)) + geom_bar(color="white")
fixed<-ggplotly(p)

for (i in 1:length(levels(df$V2))){
  fixed$x$data[[i]]$text[length(fixed$x$data[[i]]$text)+1] <- c("")
}
fixed
```
![captura de pantalla de 2016-12-26 14-22-03](https://cloud.githubusercontent.com/assets/22753863/21485830/608a7c40-cb77-11e6-8e08-0e1eb5dacb00.png)

**Comment by cpsievert** [comment]
This appears to be fixed now
