### ISSUE TITLE
plot_ly() in R console (3.2.3) produces different viridis scheme to plot_ly() in Rstudio 

### ISSUE THREAD

**Issue by bcdunbar** [ropensci/plotly#837]
In Rstudio the following code works as expected, whereas in the R console (3.2.3) the viridis scheme doesn't correctly display (bottom left of image). However, when plotly_POST is called the colors are displayed as expected (bottom right).

plot_ly(x=seq(1,5), y=rep(2,5), type="scatter", mode="markers", marker=list(color=viridis(5), size=20))

![viridis plot-plot_ly-post](https://cloud.githubusercontent.com/assets/8393928/21556174/769969a2-cdec-11e6-86b7-cbaa79759a17.png)

**Comment by cpsievert** [comment]
Hmmm, I can't seem to replicate the problem...
