### ISSUE TITLE
Missing label colors in barplot when not using add_trace

### ISSUE THREAD

**Issue by fabiangehring** [ropensci/plotly#838]
When creating a colored barplot without using add_trace, some label colors remain black:

```
colors <- c("blue","grey", "red", "yellow")
  data <- data.frame(time = factor(c("2010", "2011", "2010", "2011", "2010", "2011")),
                     value = c(10, 20, 30, 40, 50, 60),
                     type = c("A", "B", "C", "A", "B", "C"))
 
  data %>%
    plot_ly(
      type = "bar",
      x = ~time,
      y = ~value,
      color =  ~type,
      colors = colors) %>%
    layout(barmode = "relative")
```
The same issue can be discovered when using "marker = list(color = colors)" option instead of colors option directly. When using add_trace instead, everything seems to work fine. But since the number of color levels is not known in advance all the time, a solution which used add_trace (within a loop) feels unconvenient.

**Comment by cpsievert** [comment]
This was fixed recently
