### ISSUE TITLE
`export()` doesn't work properly with choropleth maps

### ISSUE THREAD

**Issue by salim-b** [ropensci/plotly#840]
If I try to export any choropleth map using plotly's `export()` function, the map itself is missing in the resulting PNG file. For example feeding the map produced by the following [code from plotl.ly](https://plot.ly/r/choropleth-maps/)
```
library(plotly)
df <- read.csv("https://raw.githubusercontent.com/plotly/datasets/master/2011_us_ag_exports.csv")
df$hover <- with(df, paste(state, '<br>', "Beef", beef, "Dairy", dairy, "<br>",
                           "Fruits", total.fruits, "Veggies", total.veggies,
                           "<br>", "Wheat", wheat, "Corn", corn))
# give state boundaries a white border
l <- list(color = toRGB("white"), width = 2)
# specify some map projection/options
g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)

p <- plot_geo(df, locationmode = 'USA-states') %>%
  add_trace(
    z = ~total.exports, text = ~hover, locations = ~code,
    color = ~total.exports, colors = 'Purples'
  ) %>%
  colorbar(title = "Millions USD") %>%
  layout(
    title = '2011 US Agriculture Exports by State<br>(Hover for breakdown)',
    geo = g
  )
```
to the `export()` function produces this raster image:
![p](https://cloud.githubusercontent.com/assets/20040931/21593464/ae663e72-d117-11e6-88e9-4b6a607a29e7.png)

I don't know if this problem is related to the [current need of an internet connection to produce maps](https://github.com/ropensci/plotly/issues/356) (I mean somewhere internally; of course I have an active internet connection when exporting the map). At least with `scatter` and `bar` plots the export works as supposed.

I'm using `plotly 4.5.6` with `R 3.3.2` on `Ubuntu Linux 16.04 LTS`.

**Comment by cpsievert** [comment]
It appears that giving it some time to load the external resources fixes the problem. To do so, use the `delay` argument (from `webshot()`)

```
export(p, delay = 2)
```

**Comment by salim-b** [comment]
> It appears that giving it some time to load the external resources fixes the problem. To do so, use the delay argument (from webshot())

Thanks for the hint, this works indeed! I guess it would make sense to have this mentioned in the [corresponding tutorial](https://plot.ly/r/static-image-export/#export-locally).
