### ISSUE TITLE
ggplotly produces legend even if suppressed in ggplot

### ISSUE THREAD

**Issue by romunov** [ropensci/plotly#842]
[User on Stackoverflow reported](http://stackoverflow.com/q/41445123/322912) that legends/guides are not suppressed even when explicitly told so when constructing the `ggplot` object. For completeness, here's an excerpt from the question

 ```r
library(ggplot2)
library(plotly)

dat <- data.frame(
time = factor(c("Lunch","Dinner"), levels=c("Lunch","Dinner")),
total_bill = c(14.89, 17.23))

# No legend, since the information is redundant
ggplot(data=dat, aes(x=time, y=total_bill, fill=time)) +
geom_bar(colour="black", stat="identity") +
guides(fill=FALSE)

ggplotly()
```

with `plotly` package version 4.5.6.

**Comment by supersambo** [comment]
Here is a dirty solution to get rid of the legend by by disabling it in the ggplotly object:

``` r
library(ggplot2)
library(plotly)

dat <- data.frame( time = factor(c("Lunch","Dinner"), levels=c("Lunch","Dinner")), total_bill = c(14.89, 17.23))

# No legend, since the information is redundant
p <- ggplot(data=dat, aes(x=time, y=total_bill, fill=time)) + geom_bar(colour="black", stat="identity") + guides(fill=FALSE)
p <- ggplotly(p)


for (i in 1:nrow(dat)){
    p$x$data[[i]]$text <- c(p$x$data[[i]]$text, "") 
    p$x$data[[i]]$showlegend <- FALSE
}
p
```

**Comment by bcdunbar** [comment]
you can use `theme(legend.position='none')` which translates with `ggplotly()`

**Comment by romunov** [comment]
This is more than satisfactory, thank you.

**Comment by jonmcalder** [comment]
Thanks for suggesting that "dirty hack" @supersambo

Surely there must be a more elegant way to do this though?

**Comment by maxheld83** [comment]
any chance this can be re-opened @romunov? I ran into the same problem, and would love a cleaner solution long-term.

**Comment by romunov** [comment]
Here you go, @maxheld83.

**Comment by dralmostright** [comment]
Hi, have you guys tired [hide_legend](https://rdrr.io/cran/plotly/man/hide_legend.html). I have tried and it worked for me.

**Comment by cpsievert** [comment]
Please use `hide_legend()` for cases like this. And `plotly_json()`/`style()` if you want to hide specific legend entries

**Comment by OGuggenbuehl** [comment]
> Please use `hide_legend()` for cases like this. And `plotly_json()`/`style()` if you want to hide specific legend entries

Any chance I could get an example on how to hide specific legend entries with `style()`?
