### ISSUE TITLE
scatter mode default inconsistencies

### ISSUE THREAD

**Issue by cldougl** [ropensci/plotly#843]
scatter `mode` typically defaults to `"lines+markers"` if there are less than 20 points, or `"lines"` if there are 20+ points: https://plot.ly/r/reference/#scatter-mode . In the current version it looks like this default is overridden to `"markers"`:
```
No scatter mode specifed:
  Setting the mode to markers
  Read more about this attribute -> https://plot.ly/r/reference/#scatter-mode
```
This may cause [inconsistencies with the code translator](https://github.com/plotly/streambed/issues/8883#issuecomment-268859935):

**Comment by cpsievert** [comment]
Is there anyway the translator could supply defaults via plotly.js (maybe via `Plotly.Plots.supplyTraceDefaults`)? I think this would generally solve any default inconsistencies.

**Comment by cldougl** [comment]
cc @tarzzz
