### ISSUE TITLE
event_data doesn't work with scatterplot (type = "scattergl")

### ISSUE THREAD

**Issue by uncle-m** [ropensci/plotly#845]
New to this system - apologies for adding this as a new issue.
It was previously reported here: https://github.com/ropensci/plotly/issues/624
and is supposed to have been completed here: plotly/plotly.js#994
but it is still not working in R plot.ly/ shiny.

I added example code in #624 above. Can it be reopened please.

**Comment by cpsievert** [comment]
It you can provide a reproducible example, I'll reopen

**Comment by uncle-m** [comment]
Hi, thanks for the quick reply. I posted some code in #624.

**Comment by cpsievert** [comment]
Oh thanks, sorry, can you file a new issue with the example included?
