### ISSUE TITLE
changes to ggplotly graph only made to first facet in multi-facetted plot

### ISSUE THREAD

**Issue by corinne-riddell** [ropensci/plotly#847]
Hi! I've noticed that when I try to apply changes to a multi-facetted ggplotly graph the change will only be applied to the first facet instead of across all facets. 

Simple example:
`ggplotly(ggplot(data = iris, aes(x = Sepal.Length, y = Sepal.Width)) + geom_point() + facet_grid(. ~ Species)) %>% 
  layout(xaxis = list(tickangle = -45))
`

I would expect the `tickangle` to change the angle for all facets, but it only affects the first one:

![image](https://cloud.githubusercontent.com/assets/12090129/21743372/c6c66b08-d4ce-11e6-91ac-494569989150.png)

Thanks :)

**Comment by cpsievert** [comment]
Hi @corinne-riddell, `theme(axis.text.x = element_text(angle = 45))` does what you're expecting, and the changes you're requesting would be backwards-incompatible, so I don't think it would be worthwhile.
