### ISSUE TITLE
wrapping of labels not supported in ggplotly

### ISSUE THREAD

**Issue by earowang** [ropensci/plotly#851]
Hi Carson,

`ggplot2` works fine for the wrapping of long labels, while `ggplotly` doesn't support yet. A little example is as follows:

```r
library(plotly)
library(stringr)

df_x <- data.frame(
  x = "this is very loooooooooooong text to illustrate",
  y = 100
)

p <- ggplot(aes(x = x, y = y), data = df_x) +
  geom_bar(stat = "identity") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10))
p
ggplotly(p)
```

Cheers,
Earo

**Comment by cpsievert** [comment]
Thanks @earowang. f85a9dd adds support for translating R linebreaks to HTML

For now, you'll need to manually adjust margins to account for the multiple lines of text (`ggplotly()`isn't that smart, yet)

```r
ggplotly(p) %>% layout(margin = list(b = 100))
```

**Comment by earowang** [comment]
Awesome! Thanks Carson.
