### ISSUE TITLE
fill Interaction not working with ggplot2 and plotly

### ISSUE THREAD

**Issue by robertowiest** [ropensci/plotly#853]
Hello, I want to add an interaction in my figure as described below:
`estagios <- c("ninfas", "adultos", "alados", "totais")
    valores <- c(4,4, 2, 10)
    df <- data.frame(estagios,valores)
   ggplot(data=df, aes(x=estagios,y=valores,fill=estagios)) +
      geom_bar(stat="identity")
    ggplotly()
`
However, the picture is displayed correctly but the interaction does not. Verifying, if the fill parameter is removed the interaction is displayed correctly.

`estagios <- c("ninfas", "adultos", "alados", "totais")
    valores <- c(4,4, 2, 10)
    df <- data.frame(estagios,valores)
   ggplot(data=df, aes(x=estagios,y=valores)) +
      geom_bar(stat="identity")
    ggplotly()
`
Regards

**Comment by cpsievert** [comment]
Could you be more specific? The result looks ok to me...try using the latest version
