### ISSUE TITLE
github version doesn't work with github ggplot2

### ISSUE THREAD

**Issue by stanstrup** [ropensci/plotly#858]
plotly v4.5.6.9000
ggplot2 v2.2.1.9000

```r
ggiris <- qplot(Petal.Width, Sepal.Length, data = iris, color = Species)
ggplotly(ggiris)
```

Gives an empty output. Works with cran ggplot2.

**Comment by cpsievert** [comment]
Hmm, works fine for me. Maybe open the developer console of your viewer/browser and see if there are errors?

**Comment by stanstrup** [comment]
That was an interesting question. It turns out that it works in chrome but not in the rstudio viewer. So some kind of incompatibility was introduced somewhere I guess.

**Comment by stanstrup** [comment]
OK it seems more obscure than that. It seems to usually work on the first plot. Then stops working in rstudio and I get the blank plot. An R restart solves it temporarily. So probably nothing to do with versions in the end.
Ideas?

**Comment by cpsievert** [comment]
A reproducible example would help

**Comment by stanstrup** [comment]
The example in the first post is reproducible for me (I had another plot I was working on that seems to work some times) in that I cannot get it to display in Rstudio at all.

**Comment by cpsievert** [comment]
What do you see if you: 

right-click -> "Inspect Element" -> Click on "Console" tab

?

(also, see if updating fixes it...it sounds like a problem that should have been solved recently...)

**Comment by stanstrup** [comment]
Sorry. Didn't realize the Rstudio browser had that too. -->

> Invaliding tabset config (Presentation index) 127.0.0.1/:136
> Pane config is not valid 127.0.0.1/:136
> TypeError: undefined is not a constructor (evaluating 'ArrayBuffer.isView(t)') plotly-latest.min.js:48

Hmmm dang. I reinstalled plotly and now I cannot reproduce :( Sorry about wasting time. Dunno if I had an older version (but same version number as current github) or something got broken some other way.

The 2 first lines from above is still in the console though. But the 3. is gone.

**Comment by cpsievert** [comment]
No worries, that's what I expected, I'm pretty sure you just needed to update
