### ISSUE TITLE
custom hoverinfo with "text" does not work if a variable is mapped to color

### ISSUE THREAD

**Issue by ateucher** [ropensci/plotly#864]
If you map `color` to a variable, the color mapping works but tooltips do not appear when setting `text` and `hoverinfo="text"`:

```r
df <- data.frame(a = rnorm(5, 50, 1), 
                 b = letters[1:5], 
                 stringsAsFactors = FALSE)

p <- plot_ly(df, x = ~a, y = ~b,
             type = "bar", color = ~b, 
             text = ~paste("Value: ", round(a, 1)),
             hoverinfo = "text")
p
```

If  you set `color` to a constant, the correct hoverinfo (specified via `text`) is displayed in a tooltip as expected: 

``` r
library(plotly)
df <- data.frame(a = rnorm(5, 50, 1), 
                 b = letters[1:5], 
                 stringsAsFactors = FALSE)

p <- plot_ly(df, x = ~a, y = ~b,
             type = "bar", color = I("red"), 
             text = ~paste("Value: ", round(a, 1)),
             hoverinfo = "text")
p
```

Setting `hoverinfo` to `"x"`, `"y"`, `"x+y"` etc does work as expected when `text` is set and `hoverinfo="text"`:
```r
df <- data.frame(a = rnorm(5, 50, 1), 
                 b = letters[1:5], 
                 stringsAsFactors = FALSE)

p <- plot_ly(df, x = ~a, y = ~b,
             type = "bar", color = ~b, 
             hoverinfo = "y+x")
p
```

Thanks!

**Comment by cpsievert** [comment]
This is a special

**Comment by cpsievert** [comment]
Appears to be fixed now

**Comment by andret6** [comment]
Having this issue as of 2/23/2021, using R 4.0.2, Rstudio 1.3.959, cran package for plotly version 4.9.2.1.

Exact same issue as above, hover text does not display with color mapping.

**Comment by Duque-de-Sealand** [comment]
Same issue here, for plotly version 4.9.4.1 I am using:
R version 4.1.0 (2021-05-18)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 8

color attribute does not map to hoverinfo.

**Comment by khughitt** [comment]
Bug still present in plotly 4.10.0 / R.

Seems to arise whenever there is only a single data point that would be colored. When multiple points are present in the group, the colors / hover text are handled without issue.
