### ISSUE TITLE
Stacked bar chart - compare on hover shwoing incorrect values

### ISSUE THREAD

**Issue by nirmalpatel** [ropensci/plotly#867]
Hi,

Stacked bar chart is showing incorrect values when hovering.

Here's a shiny app:

```r
library(plotly)
library(shiny)
library(tibble)
library(ggplot2)

df1 <- tribble(
  ~x, ~y, ~z,
  1, 1, "A",
  1, 3, "B",
  2, 4, "A",
  2, 2, "B",
  3, 5, "A",
  3, 3, "B"
)

ui <- fluidPage(
  plotly::plotlyOutput("plot1")
)

server <- function(input, output) {
  
  output$plot1 <- plotly::renderPlotly({
    p <- ggplot(df1, aes(x, y)) +
      geom_bar(stat = "identity", aes(fill = z))
    
    plotly::ggplotly(p)
  })
}

shinyApp(ui, server)
```

When I do compare on hover, this is what I see:

![Image bug](http://i.imgur.com/wX9NIPu.png)

In the bottom box, I should see values:

Z: A
x: 1
y: 1

But instead, I see:

z: A
x: 1
y: 4

So it seems that total is being printed for bottom fill instead of individual number associated with it.

**Comment by cpsievert** [comment]
I believe this is fixed in the lastest (dev) version
