### ISSUE TITLE
Customize Cursor Shape?

### ISSUE THREAD

**Issue by iankloo** [ropensci/plotly#871]
The cursor shape (the cross shape) that occurs whenever you mouse over any part of the plotly chart is a little chunky and big for my taste.  It would be much more clean if the mouse cursor stayed the same shape (like it does in highcharts).  Is there a way to disable the cursor shape change entirely?

Thanks.

**Comment by cpsievert** [comment]
This is something that needs to be asked/requested here -- 

http://community.plot.ly/
https://github.com/plotly/plotly.js
