### ISSUE TITLE
black entry legend for barchart

### ISSUE THREAD

**Issue by kiezuz** [ropensci/plotly#872]
The legend for some barcharts has black entries. I could not figure out when this happens.

Reproducible example:
```
dd <- data.frame(quarter = c(1, 1, 2, 2, 3, 3),
                 type = c('Motor', 'Travel', 'Travel','Motor','Motor', 'Travel'),
                 V1 = c(10, 20, 15, 25, 5, 8)
)

```

```
p <- plot_ly(
  data = dd,
  x = ~ quarter,
  y = ~ V1,
  type = 'bar',
  color = ~ type
) 
```

![image](https://cloud.githubusercontent.com/assets/13571472/22653655/62b12c60-ec8a-11e6-9fc3-34a8f840dc7b.png)

**Comment by cpsievert** [comment]
This is fixed now
