### ISSUE TITLE
Error in ggfun("create_layout")

### ISSUE THREAD

**Issue by zhitkovk** [ropensci/plotly#875]
Hi, 

I've came across a strange error when using `ggplotly()` function.

My example code is following:

```
 p <- ggplot(data = mtcars, aes(x = mpg)) +
      geom_histogram(bins = 8)
    
 ggplotly(p)
```

Then I get the error:

```
Error in ggfun("create_layout")(plot$facet, plot$coordinates) :
unused argument (plot$coordinates)
```

My R version is 3.3.1 and I run the development version of `plotly` from github. Other packages versions are the following: `htmlwidgets_0.8     plotly_4.5.6.9000   ggplot2_2.2.1`.

**Comment by cpsievert** [comment]
If u want to use the dev version of plotly you currently have to use the dev version of ggplot2
