### ISSUE TITLE
hiding collaborate button not working

### ISSUE THREAD

**Issue by shosaco** [ropensci/plotly#876]
Dear team,

first of all, thanks for you great work. I want to remove the modebar button "Collaborate" using

    plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length) %>% config(modeBarButtonsToRemove = "collaborate")

However, it is not disappearing. The other buttons are removable. I also can't find the Collaborate handling in https://github.com/plotly/plotly.js/blob/master/src/components/modebar/buttons.js

**Comment by cpsievert** [comment]
Try this

```
plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length) %>% config(collaborate = FALSE)
```

**Comment by shosaco** [comment]
Thanks a lot. It's indeed correctly documented in PDF, but wrong in NEWS (https://cran.r-project.org/web/packages/plotly/news.html).
