### ISSUE TITLE
[R] Warning message: 'layout' objects don't have these attributes: 'sliders' 

### ISSUE THREAD

**Issue by zhang675** [ropensci/plotly#880]
I tried to add a slider bar to my analysis. However, I kept getting the warning messages
Warning message:
'layout' objects don't have these attributes: 'sliders'
Valid attributes include:
'font', 'title', 'titlefont', 'autosize', 'width', 'height', 'margin', 'paper_bgcolor', 'plot_bgcolor', 'separators', 'hidesources', 'smith', 'showlegend', 'dragmode', 'hovermode', 'xaxis', 'yaxis', 'scene', 'geo', 'legend', 'annotations', 'shapes', 'images', 'updatemenus', 'ternary', 'mapbox', 'radialaxis', 'angularaxis', 'direction', 'orientation', 'barmode', 'bargap', 'mapType'

I tried every example on page https://plot.ly/r/sliders/ on my local Rstudio ver. 1.0.136
The chart is showing, but there is no slider to manipulate.

Thanks in advance

**Comment by cpsievert** [comment]
You probably need the dev version of plotly
