### ISSUE TITLE
facet_wrap() causing display error inside ggplotly()

### ISSUE THREAD

**Issue by corinne-riddell** [ropensci/plotly#881]
Hi,

I'm stumbling into a display issue when I add the ggplotly wrapper around a ggplot that uses facet_wrap.

The data: [testdata.txt](https://github.com/ropensci/plotly/files/775192/testdata.txt)

This works:
`test.data <- read.table("/your_directory/testdata.txt")`

`ggplot(test.data, 
       aes(y=outcome, x = year)) + 
  geom_line(aes(col = place, lty = factor(strata))) +
  facet_wrap( ~ place, ncol = 5) +
  ylab("Outcome") +
  xlab("Year")`

This doesn't:
`ggplotly(ggplot(test.data, aes(y=outcome, x = year)) + 
           geom_line(aes(col = place, lty = factor(strata))) +
           facet_wrap( ~ place, ncol = 5) +
           ylab("Outcome") +
           xlab("Year")
)`

(but note that if you remove `facet_wrap` it displays as expected. 

Anything I can do to fix this in the version that uses facet_wrap? Thank you!

**Comment by Elizemiku** [comment]
Use the parameter scales = "free" 
`ggplotly(ggplot(test.data, aes(y=outcome, x = year)) + geom_line(aes(col = place, lty = factor(strata))) + facet_wrap(~place,ncol=5, scales = "free") + ylab("Outcome") + xlab("Year") )`
See if it works

**Comment by corinne-riddell** [comment]
Thanks, @Elizemiku :). This solves the weird display issue, although ideally I'd like a fixed y-axis range across the facets.

**Comment by Elizemiku** [comment]
In this case use "free_x" instead of just scale = "free"

**Comment by corinne-riddell** [comment]
Okay -- I can accept that trade-off. Curious that the `ncol` argument throws things off, but this is already much better than where I started. 🙏 thanks!
