### ISSUE TITLE
Allow Annotation of Boxplot Outliers

### ISSUE THREAD

**Issue by DarioS** [ropensci/plotly#887]
The dots away from the whiskers seem not to be able to be labelled with text such as sample ID. Can this be fixed? I'm using `ggplotly` on a `ggplot2` boxplot. Labelling points in a scatterplot is easy in comparison. Also, when I hover on an outlying dot, the hover text of the box and for the minimum and maximum dots appears, but **not** the text of the dot I hovered on. Can other dots than minimum and maximum have hover text and the hovering only appear on the box when the user's cursor is hovered on the box, not the dots?

**Comment by cpsievert** [comment]
> Can this be fixed?

Automatic annotations are hard. Try adding them manually -- https://plot.ly/r/text-and-annotations/

**Comment by schultzdre** [comment]
You can overlay the outliers with a scatterplot after idetifying them. Something like this:
```
#Set seed
set.seed(9)

#Generate random dataset>`
x <- data.frame(values = rnorm(100,sd=2),labels = paste("point",as.character(1:100)))

#Get outliersdata
vals <- boxplot(x[,"values"],plot = FALSE)

#Make outliars dataset
y <- x[x[,"values"] > vals$stats[5,1] | x[,"values"] < vals$stats[1,1],]

#Make plot
plot_ly(x,y = ~values,x = 1,type = "box") %>%
  add_markers(data = y, text = y[,'labels'])
```
