### ISSUE TITLE
Does plotly has radar chart?

### ISSUE THREAD

**Issue by ryanlin1986** [ropensci/plotly#890]
![image](https://cloud.githubusercontent.com/assets/11850439/23543839/10ac513e-002f-11e7-8d48-59d1916b24b2.png)

I'm looking for something like this, it is one of the basic chart I believe, but I can not found an example in plotly.
So does plotly support radar chart or have a plan to support?

**Comment by kickbox** [comment]
Have a look at this: http://jkunst.com/highcharter/highcharts.html

**Comment by bcdunbar** [comment]
see http://moderndata.plot.ly/radar-charts-in-r-using-plotly/,

similarly https://plot.ly/r/polar-chart/

**Comment by jackparmer** [comment]
See also this approach using an azimuthal map projection:
https://stackoverflow.com/questions/37670412/can-i-recreate-this-polar-coordinate-spider-chart-in-plotly

![image](https://user-images.githubusercontent.com/1865834/32187875-a1578626-bd7c-11e7-834f-47c2afc7d7cd.png)
