### ISSUE TITLE
Plotly plot-container is not removed on Shiny Input Error

### ISSUE THREAD

**Issue by cannin** [ropensci/plotly#893]
In the case of an input error Plotly does not remove the plot-container (see screenshot), and the Shiny error div is a sibling of the parent div (i.e. trendPlot in this example) rather than replacing the plot-container as is done with other Shiny plotting libraries like highcharts using rCharts.

Is this a bug? Is there a workaround to make plot-container disappear on a Shiny input error?

Online App: https://plotly.shinyapps.io/UN-Simple/
App code: https://plot.ly/r/shinyapp-UN-simple/
StackOverflow: http://stackoverflow.com/questions/42654169/plotly-plot-container-is-not-removed-on-shiny-input-error/42654390#42654390

![screen shot 2017-03-07 at 11 58 01 am](https://cloud.githubusercontent.com/assets/790284/23678757/6ea222e2-0353-11e7-9008-5ffbdb93513a.png)

**Comment by cpsievert** [comment]
Does `devtools::install_github("ropensci/plotly#894")` fix the problem?

**Comment by cannin** [comment]
Yes, it does appear to fix the problem. Thanks for the quick response.

**Comment by cpsievert** [comment]
6ca4cf87da614ee60d97c69b40db1b7a7609d4ee should officially fix the problem. Try reinstalling from master and let me know if you run into any issues!
