### ISSUE TITLE
ggplotly() fails 

### ISSUE THREAD

**Issue by ramay** [ropensci/plotly#899]
Hi,
I am getting the following error when calling ggplotly()
`Error in ggfun("create_layout")(plot$facet, plot$coordinates) : 
  unused argument (plot$coordinates)`

My test code is:
`
x=1:10
y=1:10
ggplotly(ggplot(,aes(x=x,y=y)) + geom_point())`

Thanks for your help!
Hena

**Comment by ramay** [comment]
Forgot to mention that I am using the development version plotly_4.5.6.9000  & ggplot2_2.2.1

**Comment by cpsievert** [comment]
The dev version of plotly [requires the dev version of ggplot2](https://github.com/ropensci/plotly/blob/master/DESCRIPTION#L65-L66)

```
devtools::install_github("ropensci/plotly")
```

should do the trick

**Comment by ramay** [comment]
Nope it is not for me. I installed this version  already and tested it.

**Comment by ramay** [comment]
Thank you! It works. Probably this will also solve a legend group problem I have been having with subplot.
