### ISSUE TITLE
Stacked bar gives total for first factor

### ISSUE THREAD

**Issue by geoffreylarnold** [ropensci/plotly#902]
When creating a stacked bar chart with geom_bar Plotly returns the total in the first factor of the fill.

Example:
`ggplotly(ggplot(foo, aes(x=name, fill = state)) + 
             geom_bar() +         
             scale_fill_manual(values=cbPalette) +
           tooltip = c("x", "count", "state")) `

**Comment by cpsievert** [comment]
Thanks!

As per the [issue template](https://github.com/ropensci/plotly/blob/master/.github/ISSUE_TEMPLATE.md), bug reports must be accompanied by a *reproducible* example, so I'll have to close your ticket.

I'm happy to reopen your issue once you've provided a reproducible example.
