### ISSUE TITLE
Can I save a plotly file in pdf? if so, how can I do it. 

### ISSUE THREAD

**Issue by elcansaito** [ropensci/plotly#903]
Trying to save a subplot in pdf.

p1 <- ggplotly(HEIGHT_1)
p2 <- ggplotly(HEIGHT_2)
p3 <- ggplotly(HEIGHT_3)
p4 <- ggplotly(HEIGHT_4)

a <- subplot(p1,p2,p3,p4, nrows = 2, widths = NULL, heights = NULL, margin = 0.04,
        shareX = TRUE, shareY = FALSE)

plotly_IMAGE(a, format = "pdf", out_file = "output.pdf")

1: You need a plotly username. See help(signup, package = 'plotly') 
2: Couldn't find username 
3: You need an api_key. See help(signup, package = 'plotly') 
4: Couldn't find api_key 

I also did this.
signup("jisidro", "jisidro@gmail.com", save = TRUE)
Error in process.signup(append_class(resp, "signup")) : 
  Bad Request (HTTP 400).

Not sure what else to do. 

THANKS

**Comment by cpsievert** [comment]
Hmm, try signing up using the plotly website -- http://help.plot.ly/how-to-sign-up-to-plotly/

**Comment by elcansaito** [comment]
I actually did that too. I´ll try to do it in another R session. Thanks for your fast answer

**Comment by cpsievert** [comment]
Ahh, maybe you need to store your credentials? https://plot.ly/r/getting-started/

**Comment by elcansaito** [comment]
Ok, this is what I did. 

In another computer, I installed plotly. 

if (!require(devtools)) install.packages("devtools")
devtools::install_github("cpsievert/plotcon17")
library(plotly)

#### Then I regenerate the API key

Sys.setenv("plotly_username"="jisidro")
Sys.setenv("plotly_api_key"="*****************")

### and then I wanted to save on pdf.

p1 <- ggplotly(HEIGHT_1)
p2 <- ggplotly(HEIGHT_2)
p3 <- ggplotly(HEIGHT_3)
p4 <- ggplotly(HEIGHT_4)

a <- subplot(p1,p2,p3,p4, nrows = 2, widths = NULL, heights = NULL, margin = 0.04,
        shareX = TRUE, shareY = FALSE)

plotly_IMAGE(a, format = "pdf", out_file = "output.pdf")

Error in process.image(append_class(resp, "image")) : 
  Payment Required (HTTP 402).

# It seems I need to pay to be able to save on pdf?

I also tried this code from here 
https://plot.ly/settings/subscription/?modal=true&utm_source=plotly-py&utm_medium=folder-limit

plotly_POST(p, filename = "r-docs/midwest-boxplots")

No encoding supplied: defaulting to UTF-8.
Error: Hi there! Free users cannot create folders.
To save this file on Plotly, please remove the folder in your filename path.
If you would like to create folders and save files in them, please upgrade your account at: https://goo.gl/NrPpg6 

###Am I missing something?

THANKS CARSON!!!
J

**Comment by cpsievert** [comment]
> It seems I need to pay to be able to save on pdf?

Ah, yes, I didn't realize that. That is more clear on our pricing page -- https://plot.ly/products/cloud/

Try using `export()` instead

**Comment by elcansaito** [comment]
Thanks Carson. I wish I could pay that a year. :) Plotly is more than excellent, but I can´t.

I tried Export and it works, also I install install.packages("webshot") and now plotly_IMAGE seems to work. 
The only thing I am trying to get is to have jpeg or png with a high quality in resolution. Do you know how to do that?

Thanks again for your patient and help.
J





Error in webshot::webshot(f, file, delay = delay, ...) : 
  unused arguments (format = "jpeg", out_file = "output.jpeg")
