### ISSUE TITLE
Multiple issues when using frames in the dev version

### ISSUE THREAD

**Issue by klydd** [ropensci/plotly#905]
Hi,

I just downloaded the dev version of plotly and found some odd behavior when toying around with the new frame option. Forgive me if this has already been posted about or fixed.

Short story: plotly does not seem to like it when columns supplied to the `frame` option and columns supplied to `color` or `split` have identical values.

Here's an example. Consider the following data:

```R
library(plotly)
library(dplyr)

example_data <- data.frame(
  y = rnorm(20),
  score = c(1,1,1,1,2,2,2,2,3,3,3,3, 1,1,1,1,2,2,2,2),
  population = c(rep(1, 12), rep(2,8))
  ) 

```

I'd like to visualize the variable `y` in a boxplot that groups the `y` values by `score` and uses the `frame` option to let the user compare how `y` varies for each `score` in two populations.

The scores range from 1 to 3, and score 3 is only represented in population 1.

This is the code I use to plot the boxplot:

```R
example_data %>% 
  plot_ly(y= ~y, split = ~score, frame = ~population, type ='box')
```

The result looks like this:

![Plot 1](https://i.imgur.com/eUga6nI.png)

The box plots should be hovering above 1,2,3 on the x axis, instead it is 0,1 and 3,

Furthermore, if I move the slider from population 1 to 2 and back, the colors will change in between the frames, and score 3 will remain in the chart even though it is not present in population 2:

![Slider set to pop2](https://i.imgur.com/QId8pFf.png)

![Slider moved back to pop1](https://i.imgur.com/WdfjdA1.png)

If I create a new dummy column in my data, where I increment the scores by 3 so that they do not share any values with the population column, and replot the boxplot grouping by the new score, the chart will look normal again:

```R
example_data$score2 <- example_data$score + 3

example_data %>%
  plot_ly(y= ~y, split = ~score2, frame = ~population, type ='box')
```

![X axis looks normal again](https://i.imgur.com/k0lMkCN.png)

However, the colors will still change in between the frames, and score 3 (now score 6) will still continue to show up when switching over to population 2:

![](https://i.imgur.com/07ovER6.png)

![](https://i.imgur.com/wottO1g.png)

## More observations

The axis problem and the issue with the third score showing up in population 2 persists when I use the `color` option instead of `split`  and recode the `score` vars as a factor.  Though the colors no longer change when switching between the frames:

```R
example_data %>% 
  plot_ly(y= ~y, color = ~as.factor(score), frame = ~population, type ='box')

example_data %>% 
  plot_ly(y= ~y, color = ~as.factor(score2), frame = ~population, type ='box')

```

The third score will vanish properly when plotting the boxplot the following way:

```
example_data %>% plot_ly(x= ~score, y = ~y, frame = ~population, type ='box')
```

Unfortunately parts of the plot will render outside the plot margins (at least in RStudio):

![](https://i.imgur.com/5eXkgIg.png)
![](https://i.imgur.com/ALaj2ji.png)

The problems also persist when using characters instead of integers:
```R
spell_out_ints <- function(ints) {
  int_names <- c("one", "two", "three")
  sapply(ints, function(i) int_names[i]) %>% as.character()
}

example_data$score3 <- spell_out_ints(example_data$score)
example_data$population1 <- spell_out_ints(example_data$population)

example_data %>%
  plot_ly(y= ~y, split = ~score3, frame = ~population1, type ='box')
```

And a final observation: the problem isn't limited to boxplots. I discovered this when trying to plot a line  plot much the same way as the boxplot above, i.e. grouping by two integer columns.

I am running plotly version `plotly_4.5.6.9000` Here is the output of my `sessionInfo()`:

```
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Swedish_Sweden.1252  LC_CTYPE=Swedish_Sweden.1252    LC_MONETARY=Swedish_Sweden.1252 LC_NUMERIC=C                   
[5] LC_TIME=Swedish_Sweden.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.5.0        plotly_4.5.6.9000  ggplot2_2.2.1.9000

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.8        magrittr_1.5       munsell_0.4.3      xtable_1.8-2       colorspace_1.3-2   viridisLite_0.1.3  R6_2.2.0          
 [8] httr_1.2.1         plyr_1.8.4         tools_3.3.2        grid_3.3.2         gtable_0.2.0       DBI_0.5-1          htmltools_0.3.5   
[15] crosstalk_1.0.0    yaml_2.1.14        lazyeval_0.2.0     assertthat_0.1     digest_0.6.12      tibble_1.2         shiny_0.14.2      
[22] RColorBrewer_1.1-2 purrr_0.2.2        tidyr_0.6.1        base64enc_0.1-3    htmlwidgets_0.8    mime_0.5           scales_0.4.1      
[29] jsonlite_1.3       httpuv_1.3.3 
```

**Comment by cpsievert** [comment]
Interesting. Thanks for the detailed report. Could you clarify how you created `score2`?

**Comment by klydd** [comment]
Apologies, forgot to include it in the post. I've updated my post with the missing code. 

In short, I just added 3 to each value in the original `score` column, to remove any overlap with the values in the `population` column:

```R
example_data$score2 <- example_data$score + 3

example_data %>%
  plot_ly(y= ~y, split = ~score2, frame = ~population, type ='box')
```

**Comment by cpsievert** [comment]
Thanks, a few things were going awry here, in short:

1. I hadn't accounted for cases where a "splitting variable" (e.g., `split`, `color` if discrete) and the "frame variable" had similar values, which was causing the weird axis placement problem.   77f3a23bd2ccf988963f748b3c0825152eec6bd9 fixes that.

2. I wasn't properly retraining color defaults after registering frames which caused the weird change in trace colors (when they weren't specified). ce16ab121d1f9e62773ca00a7a2bd212ed6e1b7e fixes that.

3. I hadn't accounted for "missing" traces across frames.   12364faae3ead455f316d3320c1f7d8da4340719 should fix that.
