### ISSUE TITLE
RMarkdown and Pie Charts:  Warning in arrange_impl(.data, dots): '.Random.seed' is not an integer

### ISSUE THREAD

**Issue by mikebesso** [ropensci/plotly#921]
When knitting the RMarkdown (a single chunk rmd file) to HTML, 

```
library(plotly, warn.conflicts = FALSE, quietly = TRUE);

PieData <- data.frame(
  labels = c("a", "b", "c"), 
  values = c(2, 3, 4)
);

plot_ly(
  PieData,
  labels = ~labels,
  values = ~values,
  type = 'pie'
) %>%
layout(
  xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
  yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE)
)
```

I get the following warning

```
## Warning in arrange_impl(.data, dots): '.Random.seed' is not an integer
## vector but of type 'NULL', so ignored
```

So far, I only get this warning when knitting.

When googling this warning, I see several examples that also have this warning as part of the output, including:

https://rpubs.com/danfrett/222491

http://rstudio-pubs-static.s3.amazonaws.com/229222_bad34e39a61f44ae80468710c2d58dc6.html

http://rstudio-pubs-static.s3.amazonaws.com/256976_cf7b4f46cc06450fb31d6074ea5e3318.html

Any idea as to how I can knit without this warning?

THANKS

**Comment by cpsievert** [comment]
Put `warning = FALSE` in your [chunk options](https://yihui.name/knitr/options/)

Closing as I don't think this is something plotly can/should fix.

**Comment by mikebesso** [comment]
Thank you for the quick reply.  You made me dig deeper... much deeper.  And I agree, the issue is not plotly.  But, the fix is a bit more involved than ignoring warnings.  Though, ignoring warnings does get rid of the warning in the output html, it still shows up in the console.  I'm a bit OCD on not ignoring warnings.  

From what I now understand, the issue is with the knitr caching logic.  And, at least on MacOS, the knitr cache and plotly seem to throw this warning.  The warning is triggered by the knitr caching logic when it does not find a random seed.  So, I am able to get rid of the warning by calling set.seed() in my first setup chunk.

Thanks again.
