### ISSUE TITLE
geom_spoke plotly implementation

### ISSUE THREAD

**Issue by sctyner** [ropensci/plotly#923]
From [`ggplot2`](https://github.com/tidyverse/ggplot2/blob/master/R/geom-spoke.r) example:

```
df <- expand.grid(x = 1:10, y=1:10)
df$angle <- runif(100, 0, 2*pi)
df$speed <- runif(100, 0, sqrt(0.1 * df$x))
p <- ggplot(df, aes(x, y)) +
     geom_point() +
     geom_(aes(angle = angle), radius = .5)
```

Output: 
```
Warning message:
In geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
  geom_GeomSpoke() has yet to be implemented in plotly.
```

Just thought I'd ping you about it. Seems like it be fairly easy to implement, and I might even do it and submit a pull request after I'm done tweaking `to_basic.GeomNet`. 😝

**Comment by sctyner** [comment]
#348

**Comment by cpsievert** [comment]
Seems like it be fairly easy to implement, and I might even do it and submit a pull request after I'm done tweaking `to_basic.GeomNet`.

Awesome, please do! 👍 🎉
