### ISSUE TITLE
No label and unable to click and drag in Parcoords

### ISSUE THREAD

**Issue by bcdunbar** [ropensci/plotly#945]
This works in [python](https://plot.ly/python/parallel-coordinates-plot/) and [JS](https://plot.ly/javascript/parallel-coordinates-plot/) parcoord examples.

![parcoords](https://cloud.githubusercontent.com/assets/8393928/24978354/5c1b58ca-1f9e-11e7-8e78-8c9ce742e4bf.gif)

But in [R](https://plot.ly/r/parallel-coordinates-plot/), no label seems to be generated for each dimension nor can you click and drag. 

```
p <- plot_ly(type = 'parcoords', line = list(color = 'blue'),
             dimensions = list(
               list(range = c(1,5),
                    constraintrange = c(1,2),
                    label = 'A', values = c(1,4)),
               list(range = c(1,5),
                    tickvals = c(1.5,3,4.5),
                    label = 'B', values = c(3,1.5)),
               list(range = c(1,5),
                    tickvals = c(1,2,4,5),
                    label = 'C', values = c(2,4),
                    ticktext = c('text 1', 'text 2', 'text 3', 'text 4')),
               list(range = c(1,5),
                    label = 'D', values = c(4,2))
               )
             )
```

**Comment by cpsievert** [comment]
Interesting. The R package sets some layout default, and it appears `layout.margin` is the problem here. I think this is a plotly.js bug https://github.com/plotly/plotly.js/issues/1592

```r
> l <- plotly_build(p)$x
> str(l$layout)
List of 3
 $ margin    :List of 4
  ..$ b: num 40
  ..$ l: num 60
  ..$ t: num 25
  ..$ r: num 10
 $ dragmode  : chr "zoom"
 $ showlegend:Class 'plotly_default'  logi FALSE
> l$layout$margin <- NULL
> as_widget(l)
```

**Comment by cpsievert** [comment]
@bcdunbar afabd7d provides a workaround so this should *just work*, but this really should be addressed in plotly.js

**Comment by monfera** [comment]
`layout` can be set but if `layout.t` is low enough it'll cut off what's above the axis tops.
