### ISSUE TITLE
ggplotly doesn't handle explicit linetype in geom_*line

### ISSUE THREAD

**Issue by kent37** [ropensci/plotly#949]
Line types specified explicitly (vs as an aesthetic) in `geom_hline`, `geom_vline` and `geom_abline` render in ggplotly as solid lines. For example,

    library(ggplot2)
    library(plotly)
    
    x <- seq(0, 3.5, by = 0.5)
    y <- x * 0.95
    df <- data.frame(x, y)
    gg <- ggplot(df, aes(x, y)) + geom_point() +
      geom_vline(xintercept=c(2.5, 3, 3.5), linetype=1:3) +
      geom_hline(yintercept=c(2.5, 3, 3.5), linetype=1:3) +
      geom_abline(slope=-1, intercept=c(2.5, 3, 3.5), linetype=1:3)

    gg # Three lines in each direction, one solid, one dashed, one dotted
    ggplotly(gg) # All lines are solid

![image](https://cloud.githubusercontent.com/assets/187033/25051842/b2111a4c-211c-11e7-9973-453028cb8371.png)

![image](https://cloud.githubusercontent.com/assets/187033/25051854/bff5c5a4-211c-11e7-96ab-b49d484f83f7.png)

**Comment by cpsievert** [comment]
Thanks!
