### ISSUE TITLE
Marker sizes are not meaningful in a dot plot

### ISSUE THREAD

**Issue by nielsenmarkus11** [ropensci/plotly#965]
When I produce the following dot plot markers of size=1 in the first group are not equal to the size of the second group.  Thus, comparisons between groups is meaningless.  The same problem occurs when I use a different data set. Size=1 in all three scenarios appears to be a different size of marker. Is it possible to turn off auto resizing of markers and allow the user to specify the size of the diameter in pixels explicitly?

```
dat <- data.frame(y=factor(c(1,1,2,2),levels=c(1,2),labels=c("GRP1","GRP2")),
                   x=c(1,2,3,4),
                   n=c(1,1,1,1),
                   grp=c("GRP1","GRP1","GRP2","GRP2"))

plot_ly(dat) %>%
  add_markers(x = ~x, 
              y = ~y, color = ~grp, 
              size = ~n, 
              opacity = .7) %>%
  layout(showlegend=F)
```

![capture2](https://cloud.githubusercontent.com/assets/9438047/25292769/d435af20-2694-11e7-849c-d13a8ef76334.PNG)

```
dat2 <- data.frame(y=factor(c(1,1,2,2),levels=c(1,2),labels=c("GRP1","GRP2")),
                   x=c(1,2,3,4),
                   n=c(1,2,1,1),
                   grp=c("GRP1","GRP1","GRP2","GRP2"))

plot_ly(dat2) %>%
  add_markers(x = ~x, 
              y = ~y,  color = ~grp, 
              size = ~n, 
              opacity = .7) %>%
  layout(showlegend=F)
```
![capture3](https://cloud.githubusercontent.com/assets/9438047/25292799/02c4d050-2695-11e7-9fd4-dbced90c8414.PNG)

**Comment by cpsievert** [comment]
Think of the "special" top-level arguments `size`, `color`, `alpha`, `symbol`, etc. as a convenient short-hand for setting their more explicit counterparts. You should _always_ be able to override their behavior using the official [figure reference](https://plot.ly/r/reference/#scatter-marker-size) directly

```r
plot_ly(x = 1:4, y = 1:4, size = 1:4, marker = list(size = 4:1 * 10, sizemode = "diameter"))
```

![screen shot 2017-04-21 at 2 27 04 pm](https://cloud.githubusercontent.com/assets/1365941/25293064/a1bedd64-269e-11e7-9a39-5029bacfc579.png)
