### ISSUE TITLE
Problem when using coord_flip() in bar chart

### ISSUE THREAD

**Issue by pepe-enriquez** [ropensci/plotly#968]
Hi,
When trying to make an horizontal bar chart I have faced a problem. I am using the dev version for ggplotly (ggplot2 2.2.1.9000 and plotly 4.5.6.9000)

Building the standard vertical plot it works as expected:

``` R
dat <- data.frame(
  time = factor(c("Lunch","Dinner"), levels=c("Lunch","Dinner")),
  total_bill = c(14.89, 17.23)
)

# Without coord_flip() - as expected:
p1 <- ggplot(data=dat, aes(x=time, y=total_bill)) +
  geom_bar(stat="identity")

ggplotly(p1)
``` 
![pantallazo](https://cloud.githubusercontent.com/assets/7224614/25313059/45b287fc-2827-11e7-9d46-9829116dfa09.png)

But if I use the coord_flip option, it seems there is something strange:

``` R

# With coord_flip() - not right
p2 <- ggplot(data=dat, aes(x=time, y=total_bill)) +
  geom_bar(stat="identity") + coord_flip()

```
Output of ggplot2: 
![imagen](https://cloud.githubusercontent.com/assets/7224614/25313102/09bd8e08-2828-11e7-92af-10bb8534be44.png)
But when converting to plotly object:
``` R
ggplotly(p2)
``` 

![imagen](https://cloud.githubusercontent.com/assets/7224614/25313049/299acc8c-2827-11e7-9d2b-136a8934a5b7.png)

Thanks for the help.

**Comment by cpsievert** [comment]
Thanks! Should be fixed now...

**Comment by pepe-enriquez** [comment]
Wonderful!. Many thanks.

**Comment by matthiassandra** [comment]
Where can I find the solution? I have the same problem. I'm using plotly package 4.6.0. 
Thanks!

**Comment by cpsievert** [comment]
Please update to 4.6.0.9000

**Comment by matthiassandra** [comment]
OK, thanks! But where can I find this version? My Rstudio can't find it.

**Comment by pepe-enriquez** [comment]
I think you need to install the development package, as explained in the plotly for R page:

if (!require("devtools")) install.packages("devtools")
devtools::install_github("ropensci/plotly")

You need to ensure that the loaded version in your session is 4.6.0.9000. Check that in the "packages" tab in Rstudio.

Cheers.

**Comment by matthiassandra** [comment]
Yes, thanks! Problem solved!
