### ISSUE TITLE
Select multiple groups in a single box select when using "plotly_selected"

### ISSUE THREAD

**Issue by talgalili** [ropensci/plotly#974]
Example code:

```r
library(plotly)
library(crosstalk)
D <- SharedData$new(iris, key = ~Species) 
scatter <- ggplot(data=D, aes(x = Sepal.Length, y = Sepal.Width)) 
p <- scatter + geom_point(aes(color=Species, shape=Species)) +
  xlab("Sepal Length") +  ylab("Sepal Width") +
  ggtitle("Sepal Length-Width")
highlight(ggplotly(p), on = "plotly_selected")

```

Now I wish to select two species in one stroke. But when trying to do so, only the first group is selected:

The selection

![image](https://cloud.githubusercontent.com/assets/976006/25422360/571c2270-2a69-11e7-8539-7fec45bc8479.png)

What got selected:

![image](https://cloud.githubusercontent.com/assets/976006/25422374/60c1011a-2a69-11e7-8e48-71e602f05c46.png)

Trying to use persistent=TRUE did not help.
Is it possible to add the option for the selection to work on several groups at the same time?

Thanks.

**Comment by cpsievert** [comment]
Thanks!
