### ISSUE TITLE
Provide an explicit argument in api_create() to overwrite file

### ISSUE THREAD

**Issue by likso** [ropensci/plotly#976]
```
p <- plot_ly(z = ~volcano) %>% add_surface()
api_create(p, filename = "file/volcano", sharing = "private")
```

A random number named of public grid is created home when posting a private graph.

**Comment by cpsievert** [comment]
Hmm, seems to work for me, what happens if you run `plotly:::verify("username")` and `plotly:::verify("api_key")`? Don't post you api key here, but please email me if these are properly configured and you have a paid account.

**Comment by likso** [comment]
It shows my username and my api key correctly. And yes, I have a paid account.

**Comment by likso** [comment]
It happened on both R 3.3.3 windows and R 3.4.0 linux platform.

**Comment by cpsievert** [comment]
Ok, thanks, could you also provide the output of `devtools::session_info()`, `api("files/lookup?path=file/volcano")`, and a link to the file it created?

**Comment by likso** [comment]
https://plot.ly/~nickso/7121

> devtools::session_info()
Session info ------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.3 (2017-03-06)
 system   x86_64, mingw32             
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  English_United States.1252  
 tz       Asia/Taipei                 
 date     2017-04-27                  

Packages ----------------------------------------------------------------------------------------------------------------------
 package     * version date       source        
 assertthat    0.2.0   2017-04-11 CRAN (R 3.3.3)
 colorspace    1.3-2   2016-12-14 CRAN (R 3.3.3)
 crosstalk     1.0.0   2016-12-21 CRAN (R 3.3.3)
 curl          2.5     2017-04-14 CRAN (R 3.3.3)
 DBI           0.6-1   2017-04-01 CRAN (R 3.3.3)
 devtools      1.12.0  2016-06-24 CRAN (R 3.3.3)
 digest        0.6.12  2017-01-27 CRAN (R 3.3.3)
 dplyr         0.5.0   2016-06-24 CRAN (R 3.3.3)
 ggplot2     * 2.2.1   2016-12-30 CRAN (R 3.3.3)
 gtable        0.2.0   2016-02-26 CRAN (R 3.3.3)
 htmltools     0.3.5   2016-03-21 CRAN (R 3.3.3)
 htmlwidgets   0.8     2016-11-09 CRAN (R 3.3.3)
 httpuv        1.3.3   2015-08-04 CRAN (R 3.3.3)
 httr          1.2.1   2016-07-03 CRAN (R 3.3.3)
 jsonlite      1.4     2017-04-08 CRAN (R 3.3.3)
 lazyeval      0.2.0   2016-06-12 CRAN (R 3.3.3)
 magrittr      1.5     2014-11-22 CRAN (R 3.3.3)
 memoise       1.1.0   2017-04-21 CRAN (R 3.3.3)
 mime          0.5     2016-07-07 CRAN (R 3.3.2)
 munsell       0.4.3   2016-02-13 CRAN (R 3.3.3)
 plotly      * 4.6.0   2017-04-25 CRAN (R 3.3.3)
 plyr          1.8.4   2016-06-08 CRAN (R 3.3.3)
 purrr         0.2.2   2016-06-18 CRAN (R 3.3.3)
 R6            2.2.0   2016-10-05 CRAN (R 3.3.3)
 Rcpp          0.12.10 2017-03-19 CRAN (R 3.3.3)
 scales        0.4.1   2016-11-09 CRAN (R 3.3.3)
 shiny         1.0.2   2017-04-18 CRAN (R 3.3.3)
 tibble        1.3.0   2017-04-01 CRAN (R 3.3.3)
 tidyr         0.6.1   2017-01-10 CRAN (R 3.3.3)
 viridisLite   0.2.0   2017-03-24 CRAN (R 3.3.3)
 withr         1.0.2   2016-06-20 CRAN (R 3.3.3)
 xtable        1.8-2   2016-02-05 CRAN (R 3.3.3)

> api("files/lookup?path=file/volcano")
<Response from plot.ly>
List of 27
 $ creation_time    : chr "2017-04-26T21:48:08.886946Z"
 $ comments         :List of 2
  ..$ count  : int 0
  ..$ results: list()
 $ deleted          : logi FALSE
 $ parented         : logi TRUE
 $ embed_url        : chr "https://plot.ly/~nickso/7122.embed"
 $ fid              : chr "nickso:7122"
 $ filename         : chr "volcano"
 $ filetype         : chr "plot"
 $ img_url          : chr ""
 $ image_urls       :List of 3
  ..$ default    : chr "https://api.plot.ly/v2/files/nickso:7122/image?image_name=default"
  ..$ list-thumb : chr "https://api.plot.ly/v2/files/nickso:7122/image?image_name=list-thumb"
  ..$ block-thumb: chr "https://api.plot.ly/v2/files/nickso:7122/image?image_name=block-thumb"
 $ api_urls         :List of 3
  ..$ files : chr "https://api.plot.ly/v2/files/nickso:7122"
  ..$ plots : chr "https://api.plot.ly/v2/plots/nickso:7122"
  ..$ parent: chr "https://api.plot.ly/v2/folders/nickso:7120"
 $ owner            : chr "nickso"
 $ parent           : int 7120
 $ preview          : chr ""
 $ referencers      : list()
 $ references       : list()
 $ share_key        : chr "56JMSkVO2Hf6NN6VrlY008"
 $ share_key_enabled: logi FALSE
 $ title            : chr ""
 $ views            : int 0
 $ web_url          : chr "https://plot.ly/~nickso/7122/"
 $ world_readable   : logi FALSE
 $ date_modified    : chr "2017-04-26T21:48:08.973Z"
 $ stars            :List of 2
  ..$ count  : int 0
  ..$ results: list()
 $ collaborators    :List of 2
  ..$ count  : int 0
  ..$ results: list()
 $ subfolder_count  : NULL
 $ refresh_interval : NULL
 - attr(*, "class")= chr "api"

**Comment by cpsievert** [comment]
Ah, I think I see the problem. 

The new version of the API creates a "grid" backing each plot, which is located here -- https://plot.ly/~nickso/7121/

The actual plot is located at -- https://plot.ly/~nickso/7122/

I can see the grid, but not the plot. In other words, the plot is private, but the grid is not.

**Comment by cpsievert** [comment]
Thanks! Installing the dev version of the package should fix the problem (let me know if not)

```
devtools::install_github("ropensci/plotly")
```

**Comment by likso** [comment]
Tested and the grid created is private. However the location of the grid is now at HOME and the filename of the grid is random generated. The original behavior of plotly_POST is the put the grid with appending " GRID" to the graph filename which located in the same folder of the graph.

And do you have any idea to put in back the argument fileopt = "overwrite" in api_create()? Since I would like to skip any interactive confirmation to overwrite existing files.

**Comment by cpsievert** [comment]
`fileopt` was deprecated in the new version of the API, but I could add a similar argument to `api_create()`

**Comment by dolomitejunkie** [comment]
Thank you for adding this to v3.6.1, it is a very useful capability we have lost.

**Comment by cpsievert** [comment]
> The original behavior of plotly_POST is th put the grid with appending " Grid" to the graph filename which located in the same folder of the graph.

This behavior has been restored with 3d9c0a5b3643388952d6238cb3b27f2ae1f9a2da. Note that `filename` can now also be of length 2, specifying both plot/grid filenames.

> And do you have any idea to put in back the argument fileopt = "overwrite" in api_create()? 

Added in 74d9e8da886a19b761d1fac69ca629c27037a53d

**Comment by dolomitejunkie** [comment]
tested and I think this only partially works? Yes it overwrites the file of the same name which is great to have back.  But unfortunately it also changes the embedded share URL name which never used to happen.  This means that although the overwrite functionality is fixed, all links to the charts get updated every time a chart is updated.  This is extremely painful as all links then have to be refreshed manually with the new URL. Happy to supply further information is required?

**Comment by cpsievert** [comment]
Thanks a0bef6c should fix that. Let me know if you run into anything else that needs fixing!

**Comment by dolomitejunkie** [comment]
many thanks, tested and works.  Updates are now 'back to normal'!

**Comment by dolomitejunkie** [comment]
sorry to raise another issue.  When updating data sets this morning the following error occured and the new file name error on rewrite is occurring again.

> Error: package or namespace load failed for ‘plotly’ in get(Info[i, 1], envir = env):
 lazy-load database '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/plotly/R/plotly.rdb' is corrupt
In addition: Warning message:
In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1

**Comment by dolomitejunkie** [comment]
seems to be behaving again following some more testing.  I will monitor and report further performance if there are more issues.

**Comment by miniget** [comment]
I need your help please
My interactive plot loses its property when I run the code in r presentation mode. Do you have any idea?

My code is:
```{r, }
library(plotly)
plot_ly(iris, x = ~Sepal.Length, y = ~Petal.Length, color = ~Species)
```
