### ISSUE TITLE
Help Request: Is there a way to add a png/jpg image to a 3D plotly graph (in R)

### ISSUE THREAD

**Issue by renegademonkey** [ropensci/plotly#988]
Hi there,

This is more of a help/enhancement request than an issue.

I am plotting a 3D surface image (similar to your volcano data example):

`plot_ly(z = ~volcano) %>% add_surface()`

The only difference is that my data is related to geographical coordinates (on the x and y axes). What I would like to now do is overlay/underlay a real map onto this graph as an additional surface.

I've downloaded a detailed map image png with the exact same co-ordinates/dimensions as my plot. I've already spent many hours trying to figure out how to add an image as a flat surface layer to the 3D plot, but have not yet succeeded.

I can see how to add additional plotted surfaces (as per [here](https://plot.ly/r/3d-surface-plots/#multiple-surfaces)) by adding:

`%>% add_surface(z = z_matrix)`

but specifying an image here doesn't work (needs a matrix).

I've also looked into trying to add it as a background image, [as you would in a 2D plot](https://plot.ly/r/logos/), but this doesn't work in 3D plots.

Any other ideas?

**Comment by cpsievert** [comment]
> What I would like to now do is overlay/underlay a real map onto this graph as an additional surface.

This would be better asked as a feature request in plotly.js https://github.com/plotly/plotly.js/issues/new
