### ISSUE TITLE
HTML axes labels do not work with type="surface"

### ISSUE THREAD

**Issue by stla** [ropensci/plotly#990]
Hello, 
The axes labels do not appear:
```
plot_ly(type="surface", z=~volcano) %>%
  layout(scene =
           list(xaxis = list(title="&#963;"),
                yaxis = list(title="<i>Y</i>"))
  )
```

```
> packageVersion("plotly")
[1] ‘4.6.0’
```

**Comment by stla** [comment]
I get the same issue with JS plotly. This is not an issue with R plotly.

**Comment by cpsievert** [comment]
> I get the same issue with JS plotly. This is not an issue with R plotly.

Mind opening an issue here? https://github.com/plotly/plotly.js/issues/new
