### ISSUE TITLE
Parcoords not rendering in RStudio

### ISSUE THREAD

**Issue by sipemu** [ropensci/plotly#997]
When I try to plot a parallel plot in RStudio, the plot is not rendered correctly (see screenshot below). There is already a closed issue on this, but it do not work for me. 

```
df <- read.csv("https://raw.githubusercontent.com/bcdunbar/datasets/master/iris.csv")
df %>%
  plot_ly(type = 'parcoords',
          line = list(color = ~species_id,
                      colorscale = list(c(0,'red'),c(0.5,'green'),c(1,'blue'))),
          dimensions = list(
            list(range = c(2,4.5),
                 label = 'Sepal Width', values = ~sepal_width),
            list(range = c(4,8),
                 label = 'Sepal Length', values = ~sepal_length),
            list(range = c(0,2.5),
                 label = 'Petal Width', values = ~petal_width),
            list(range = c(1,7),
                 label = 'Petal Length', values = ~petal_length)
          )
)
```

![image](https://cloud.githubusercontent.com/assets/1296999/25899815/99e6b628-3591-11e7-9bff-d088755519e2.png)

My SessionInfo:
```
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] htmlwidgets_0.9   plotly_4.6.0.9000 ggplot2_2.2.1     shiny_1.0.0      

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9       magrittr_1.5      munsell_0.4.3     viridisLite_0.1.3
 [5] colorspace_1.3-2  xtable_1.8-2      R6_2.2.0          httr_1.2.1       
 [9] plyr_1.8.4        dplyr_0.5.0       tools_3.3.2       grid_3.3.2       
[13] gtable_0.2.0      DBI_0.5-1         crosstalk_1.0.0   htmltools_0.3.5  
[17] yaml_2.1.14       lazyeval_0.2.0    digest_0.6.12     assertthat_0.1   
[21] tibble_1.2        purrr_0.2.2       tidyr_0.6.1       mime_0.5         
[25] scales_0.4.1      jsonlite_1.2      httpuv_1.3.3     
```

**Comment by cpsievert** [comment]
Hmmm, does it render ok for you in a web browser? This is what I see:
![screen shot 2017-05-10 at 10 07 45 am](https://cloud.githubusercontent.com/assets/1365941/25905785/84b09edc-3568-11e7-9073-7de060535c66.png)

**Comment by sipemu** [comment]
Yes, in the web browser it works fine. Just in the RStudio viewer it looks like as in my screenshot above.

**Comment by cpsievert** [comment]
What do u see if u right-click -> inspect element -> console? Any errors? Also, what version of RStudio?

**Comment by sipemu** [comment]
I got this error

![image](https://cloud.githubusercontent.com/assets/1296999/25937969/fd3a7998-362d-11e7-8096-a0e35bfa9301.png)

The RStudio version is: 1.0.143

**Comment by cpsievert** [comment]
Interesting, thanks. Can you provide the call stack as well?

**Comment by sipemu** [comment]
The call stack is empty. May I do something wrong?

**Comment by cpsievert** [comment]
@sipemu would you mind upgrading plotly and trying again?

**Comment by sipemu** [comment]
@cpsievert I installed plotly and all dependent package new (github versions). The error message in the console disappear, but the plot is still not functional.

**Comment by cpsievert** [comment]
@monfera bringing this to your attention while your squashing RStudio issues ;)

**Comment by cpsievert** [comment]
This is probably fixed now, let me know if it isn't

**Comment by JasonAizkalns** [comment]
I do not believe this is fixed. Everything looks good and is functional in the web browser, but not in the RStudio Viewer pane. `RStudio Version 1.2.1335`

```
- Session info --------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.3 (2019-03-11)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio   

plotly      * 4.9.0      2019-05-23 [1] Github (ropensci/plotly@9b5c4f6)
```

Here are the errors from the console:

![image](https://user-images.githubusercontent.com/5184911/58282494-eea4ce80-7d73-11e9-82cf-cd32a8ce21e3.png)
