### ISSUE TITLE
Bug: empty plot when dates on x-axis

### ISSUE THREAD

**Issue by thibautjombart** [ropensci/plotly#998]
On current R 3.4.0 with all packages up-to-date, I find the following bug:
```
library(ggplot2)
library(plotly)

x <- data.frame(dates = as.Date("2001-01-01") + 1:10)
x
        dates
1  2001-01-02
2  2001-01-03
3  2001-01-04
4  2001-01-05
5  2001-01-06
6  2001-01-07
7  2001-01-08
8  2001-01-09
9  2001-01-10
10 2001-01-11
p <- ggplot(x) + geom_histogram(aes(x = dates))
p
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
ggplotly(p)
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
Warning message:
We recommend that you use the dev version of ggplot2 with `ggplotly()`
Install it with: `devtools::install_github('hadley/ggplot2')` 
```
The instruction `ggplotly(p)` produces an empty graph. It works otherwise without dates. 

Installing the devel version of *ggplot2* as suggested in the warning fixes the issue, but then other changes in *ggplot2* devel break compatibility with the package I work on. Also I'm not sure how to handle the dependency of a stable package on a development one. Advice welcome ;)

**Comment by cpsievert** [comment]
You can always count on the dev (GitHub) version of ggplot2 and plotly *always* working nicely together. It's a shame that this case is broken using CRAN versions, but IMO it's not worth the effort to support legacy versions of ggplot2.

I would suggest either using a package manager (e.g. packrat or checkr), or better yet, taking the plunge, and making the dev version of your package work with the dev version of ggplot2

**Comment by thibautjombart** [comment]
The problem is, as it currently stands the bit I need to change to work with ggplot2 devel will not work with the CRAN version - change in internal data structure, it seems.

**Comment by cpsievert** [comment]
yep, that is exactly why I've given up trying to fully support both versions 😉

**Comment by thibautjombart** [comment]
I understand, and I suspect I might end up doing the same in your shoes. It remains a serious problem though: ggplot2 takes a very liberal approach to development and regularly breaks backward compatibility. So having to rely on the devel version for something to work is a real problem, especially when developing tools meant to be used in crisis situations (most of what I do at [RECON](http://www.repidemicsconsortium.org/)). 

Don't get me wrong: I highly appreciate ggplot2 and plotly, they're amazing tools. This is just me waving my hand and pleading for more devel conservatism ;)

**Comment by infiniotbv** [comment]
Hi there, while issues above where some time ago, i have the same problem as above: showing an empty plot with dates on the x-axis. 

Some info:
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          4.2                         
year           2017                        
month          09                          
day            28                          
svn rev        73368                       
language       R                           
version.string R version 3.4.2 (2017-09-28)

I also experienced the same trouble when i tried the dev versions. Is there any solution?

**Comment by pvbokhoven** [comment]
Hi there, while issues above where some time ago, i have the same problem as above: showing an empty plot with dates on the x-axis.

Some info:
platform x86_64-apple-darwin15.6.0
arch x86_64
os darwin15.6.0
system x86_64, darwin15.6.0
status
major 3
minor 4.2
year 2017
month 09
day 28
svn rev 73368
language R
version.string R version 3.4.2 (2017-09-28)

I also experienced the same trouble when i tried the dev versions. Is there any solution?

**Comment by viking** [comment]
Please consider supporting the CRAN version of ggplot2. I understand that it's annoying, but depending on development versions makes the plotly package inherently unstable.
